### ISSUE TITLE
Creating User Manually With Jetstream Teams SQLSTATE[42S02]: Base table or view not found: 1146 Table 'myappdb.App\Models\Membership' doesn't exist

### ISSUE THREAD

**Issue by kinger251285** [laravel/jetstream#1002]
- Jetstream Version: 2.6.8
- Jetstream Stack: Inertia
- Uses Teams: yes
- Laravel Version: 8.83.5
- PHP Version: 8.1
- Database Driver & Version: MYSQL

### Description:

I am creating a new user using the non register route. I am manually adding a new user. No team is created on basic users (no team is required - this should be a feature IMO). I get an error stating - "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'myappdb.App\Models\Membership' doesn't exist". 

I can see this is caused either by the HasTeams() on the User Model or vendor files shared Inertia Data Middleware - "'user' => function () use ($request) {" this section. 

Commenting the middleware section out, the error disappears. Commenting the User Model HasTeams() out changes the errror.

I have also tried creating a team when manually creating the user. I have also manually (in the DB) tried adding a team and still get the error. 

I cannot see anywhere why it would be referencing Membership rather than teams.
 

My Code:

UserCreation:
`
        
        $Email = $request->email;
        $User = User::where('email', $Email)->first();

        if($User == null || $User == ''){

            $User = new User();
            $User->email = $Email;

        }

        if(!$User->subscribed('default')){

            $User->name = $request->first_name;
            $User->first_name = $request->first_name;
            $User->last_name = $request->last_name;
            $User->password = Hash::make($request->password);
            $User->country = $request->country;
            $User->telephone = $request->phone;
            $User->admin_role = 'something';

            $User->save();

            if($User->allTeams()->isEmpty()){

                $team = $User->ownedTeams()->create([
                    'user_id' => $User->id,
                    'name' => explode(' ', $User->first_name, 2)[0]."'s Team",
                    'personal_team' => true,
                ]);

            } 

            Auth::login($User);

            return redirect()->route('some_route');

        }`

SharedInertiaData Code Which Seems to be causing the issue:
`
              
                

                user' => function () use ($request) {
                if (! $request->user()) {
                    return;
                }
                if (Jetstream::hasTeamFeatures() && $request->user()) {
                    $request->user()->currentTeam;
                }
                return array_merge($request->user()->toArray(), array_filter([
                    'all_teams' => Jetstream::hasTeamFeatures() ? $request->user()->allTeams()->values() : null,
                ]), [
                    'two_factor_enabled' => ! is_null($request->user()->two_factor_secret),
                ]);
            },`

**Comment by kinger251285** [comment]
This line specifically is breaking this. It does not like the allTeams() function. Im not sure why. Checking an older version of jetstream it looks like the ->values() is a recent addition. 

vendor/laravel/jetstream/src/http/middleware/shareinertiadata.php

`'all_teams' => Jetstream::hasTeamFeatures() ? $request->user()->allTeams()->values() : null,`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by driesvints** [comment]
Every user requires a team. A personal team is always required.

**Comment by kinger251285** [comment]
@driesvints  

I get that. However even when the team is created and a personal team is allocated, either via the code the same way a registered user is or manually via input into the database this error occurs. 

A user created via the bog standard out of the box register form is also creating this error.

**Comment by kinger251285** [comment]
the issue seams to be with allTeams()

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
I'll reopen this once you've provided a repo.

**Comment by driesvints** [comment]
@kinger251285 it's best that you try to reproduce this in a fresh Laravel app with the command from above. If you can't, then I suspect this is something specifically for your app.

**Comment by kinger251285** [comment]
@driesvints No problem, i think you are right, ive copied the Jetstream vendor files from a working project and all is working. I cannot fathom why in this project it thinks that membership is its own table rather than act as a pivot. Its all down to the allTeams() function.

**Comment by kinger251285** [comment]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'myDBName.App\Models\Membership' doesn't exist (SQL: select `teams`.*, `App\Models\Membership`.`user_id` as `pivot_user_id`, `App\Models\Membership`.`team_id` as `pivot_team_id`, `App\Models\Membership`.`role` as `pivot_role`, `App\Models\Membership`.`created_at` as `pivot_created_at`, `App\Models\Membership`.`updated_at` as `pivot_updated_at` from `teams` inner join `App\Models\Membership` on `teams`.`id` = `App\Models\Membership`.`team_id` where `App\Models\Membership`.`user_id` = 1)

Is the full error i get.

**Comment by kinger251285** [comment]
Its anytime allTeams() is accessed not just creating a new user manually.

**Comment by kinger251285** [comment]
FIXED FIXED FIXED - After installing a new laravel install i noticed my existing project was missing the App\Models\Membership. Thinking this was being accessed via the vendor package files. It appears i may have updated Jetstream somewhere and this model had not been published correctly. Copied it across and now allTeams() works.
