### ISSUE TITLE
Jetstream, Nova + Scout - user.field_referencing_discrepency

### ISSUE THREAD

**Issue by StratMedia** [laravel/jetstream#1004]
- Jetstream Version: ^2.6
- Jetstream Stack: Inertia / Livewire
- Uses Teams: Yes
- Laravel Version:8.83.5
- PHP Version: 8.1.2
- Database Driver & Version: MySql 8.0.27

### Description:
Installed fresh Laravel 8, Jetstream and Nova, in that order.  Then installed Laravel/Scout.
All migrations up to date.  100% clean vanilla setup.  No customisations.  
So far only 1 user registered and user data is showing as expected in Nova.

Issue: Nova search of user table produces an error. 

### Steps To Reproduce:
Open Nova index page. Enter registered user name (in this case Bill) into top menu bar search field.
Throws a red overlay error message: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.profile_photo_url' in 'where clause' (SQL: select * from `users` where (`users`.`profile_photo_url` like %Bill%) order by `id` desc).

There is no 'users.profile_photo_url' field.  There is however a 'users.profile_photo_path' field.   Dug around a little and discovered a) 10 x coded references to 'profile_photo_path` in vendor/laravel/jetstream and b) another 14 x coded references in same folder: vendor/laravel/jetstream. Ran composer remove laravel/scout - immediate problem solved. However, the above conflicting references persist and likely to cause other problems around the user table.  

Any suggestions?

**Comment by driesvints** [comment]
Please post this on the Nova issue tracker: https://github.com/laravel/nova-issues

**Comment by driesvints** [comment]
Which

**Comment by StratMedia** [comment]
Yes, using the database driver.  Since last message I have re-installed Scout and issue repeats.  I've uninstalled scout again and refreshed stack.  Seems Scout doesn't play nicely with Nova@latest

**Comment by driesvints** [comment]
Closing in favor of the Scout issue
