### ISSUE TITLE
2FA Show Setup Key

### ISSUE THREAD

**Issue by ps-sean** [laravel/jetstream#1005]
Is there a way the setup key can be shown if the user is unable to scan the QR code?

Some 2fa apps (especially those that are browser plugins) don't have the ability to scan QR codes and instead need a setup key.

**Comment by driesvints** [comment]
Yes this sounds like something that could be useful. Feel free to attempt a PR 👍

**Comment by runthis** [comment]
For anyone who comes across this and wants a fast implementation, it's as easy as this line in the section showing the qrcode, such as the `$showingQrCode` if block in the two-factor...blade file.
`{{ decrypt($this->user->two_factor_secret) }}`

Maybe in a future jetstream update it will look like this, a girl can hope.

![image](https://user-images.githubusercontent.com/8216720/159142785-d78276fd-3a9b-46ed-bcb0-b348edcbb9f0.png)

**Comment by ps-sean** [comment]
@runthis I’ve submitted a pull request similar to what you suggest, obviously anything done in livewire must include an inertia setup too, which is a little more complicated as it relies on fortify.

I’ve submitted requests for both so hopefully this will get implemented soon

**Comment by runthis** [comment]
@ps-sean <3
