### ISSUE TITLE
"Browser Session", "Account Deletion", "Two Factor Authentication" not working after adding another field for authentication.

### ISSUE THREAD

**Issue by james-wong123** [laravel/jetstream#1016]
- Jetstream Version: 2.6
- Jetstream Stack: Inertia
- Uses Teams: yes
- Laravel Version: 9.5.1
- PHP Version: 8.1.2
- Database Driver & Version: Mysql 8.0.28

### Description:

When i try to do account delete, log out of all browser sessions, this pops up

![image](https://user-images.githubusercontent.com/87692325/159866582-0ca8a146-fa8e-4e75-8cea-207de6d0b695.png)

For more detailed explanations pls head over to https://stackoverflow.com/questions/71598247/jetstream-unable-to-delete-account-after-modifying-the-authentication-logic-la

For the Two Factor Authentication, i cant even submit the post to the route, not thing happened after submitting.

**Comment by james-wong123** [comment]
I have found the solution for all this, 

Inside `vendor/laravel/fortify/src/Actions/ConfirmPassword.php`, there is a function `__invoke` which Confirm that the given password is valid for the given user.

In default, `$username = config('fortify.username');` but my config('fortify.username') is set to `auth` that why it is not inside the database and return `column not found`

Is there a way to change this? cuz modifying the vendor is not a good solution.

**Comment by jjbofficial** [comment]
Change fortify.username to email. You can read the docs to find out more [https://laravel.com/docs/9.x/fortify#authentication](https://laravel.com/docs/9.x/fortify#authentication)

**Comment by james-wong123** [comment]
@jjbofficial there is one problem after changing that.

User can't be authenticate anymore.

**Comment by jjbofficial** [comment]
What is the error that you get when you try to authenticate ?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by james-wong123** [comment]
> if i change `'username' => 'email'`, 

![image](https://user-images.githubusercontent.com/87692325/160348286-1f44fad4-8bf5-4707-8003-ee56f250ae4f.png)
