### ISSUE TITLE
Priorize 'accepted' validation rule for terms checkbox in CreateNewUserWithTeams.php

### ISSUE THREAD

**Issue by jrrmcalcio** [laravel/jetstream#1018]
- Jetstream Version: 2.6.8
- Jetstream Stack: Inertia
- Uses Teams: yes
- Laravel Version: 9.5.1
- PHP Version: 8.1.2
- Database Driver & Version: Mysql 8.0.22

### Description: I notice that you updated the validation rule for terms checkbox priority to 'accepted', but when using teams it was not updated.   I think this change should apply to both, with teams and without teams right?

**Comment by driesvints** [comment]
Fixed in tomorrow's release
