### ISSUE TITLE
php artisan jetstream:install livewire did not completely scaffold Auth

### ISSUE THREAD

**Issue by jimgwhit** [laravel/jetstream#102]
- Jetstream Version: first
- Laravel Version: 8
- PHP Version: 7.4
- Database Driver & Version: mysql 8

### Description: No Login Controller is created and no trait.

Tried
 ```
php artisan jetstream:install livewire
```

Also tried
```
php artisan jetstream:install inertia
```
> A HomeController will also be generated to handle post-login requests to your application's dashboard.

Wasn't created.  Also no Login controller was created.  Where is the login controller?

I also use the authenticated method from the trait, but where is this trait now, no UI any more?

Is the UI still okay with version 8 (and future versions if I don't want jetstream), or is the UI deprecated, do you have to use jetstream.  Not anything in docs about the laravel ui for Auth.

And I thought jetstream was optional, where is the AuthenticatesUsers.php trait now located.

The docs are leaving out so much it seems.  The docs says there should be controller and trait:

> Authenticating

> Now that you have routes and views setup for the included `authentication controllers`, you are ready to register and authenticate new users for your application! You may access your application in a browser since the authentication controllers already contain the logic `(via their traits)` to authenticate existing users and store new users in the database.

**Comment by alxmtr** [comment]
Hey jimgwhit,

It seems like no controllers or traits are supposed to be created when installing Jetsteam as it used to be with Laravel UI.

For your concerns about UI being deprecated, the GitHub page of the package says it should no longer be used on new Laravel projects, we have to use Jetstream instead.

Maybe you should give us more details about what you are trying to do with the auth that requires you to use the AuthenticatesUsers trait so we can help you.

**Comment by jimgwhit** [comment]
@alxmtr v7 the UI had the mentioned trait, how in v8 do I duplicate the methods such as authenticated.

And where in v8 are the authentication traits located?

**Comment by alxmtr** [comment]
[Laravel Fortify](https://github.com/laravel/fortify) powers the auth features of Jetstream and is probably what you are looking for.

**Comment by jimgwhit** [comment]
@alxmtr in vendor folder and saw controllers but what traits is the documentation referring to I saw no traits?
Has all control over redirection been removed?

I usually pick a redirect location depending role.

Are there still traits you can override. I just can't seem to find them.

**Comment by alxmtr** [comment]
Laravel 8 has been released only 10 hours ago as I write this and the documentation is probably still referring to the auth traits and controllers from Laravel UI. It is misleading.

There are no traits like AuthenticatesUsers anymore in Jetstream and Fortify.

**Comment by jimgwhit** [comment]
I also noticed that there's only one place in config to set where to redirect to once logged in.

However shouldn't there be an option somewhere, that way if an admin, redirect to admin page, if another role, redirect to another page, etc for a few other roles.

This was easy in Prior versions, is there a workaround or a fix.

**Comment by taylorotwell** [comment]
These out of date docs have been updated.

**Comment by jimgwhit** [comment]
Also any one landing here, @snapey put a fix on the forum for redirects, see:

https://laracasts.com/discuss/channels/laravel/version-8-redirects  I included there a small example.
Either will work.
