### ISSUE TITLE
Confirming 2FA requires additional changues to an external config file

### ISSUE THREAD

**Issue by flick36** [laravel/jetstream#1025]
- Jetstream Version: 2.7.0
- Jetstream Stack: Inertia / Livewire
- Uses Teams: yes / no
- Laravel Version: 9.6.0
- PHP Version: 8.1.4
- Database Driver & Version: Postgre 14.2

### Description:
Well me again, I'm sorry. Confirming 2FA https://github.com/laravel/jetstream/pull/992 it's a nice and really appreciated edition problem is, if we do a simple `composer update` well it doesn't kind of work because we have to add `'confirm' => true` to the fortify config file. it's not a big of a problem (once you found out why the newly addition doesn't work. I'm ashame to admint it took longer than i wished to figure it out) to add a simple line it's not a big deal, the thing is when you do a `composer update` i believe you are expected to have things broke on the updates of the package you require, but we don't explicitly require 'laravel/fortify' it's required within the package and the new `'laravel/fortify'` version adds that line https://github.com/laravel/fortify/commit/0fa359a4671de51e90a3d907b174f6c7db9720c6 so, i stil thing it should bea  breaking changue update but it's here now, and for the people that don't know why this newly addition isn't working, maybe try and see if you have that line.

### Steps To Reproduce:

Install previous jetstream version (2.6.8) do a composer update, and 2FA isn't really working

**Comment by driesvints** [comment]
Yeah, you definitely have to do this manually if you want to enable 2FA confirmation. Normally nothing should break though. I can't immediately see this from your explanation but do things break when you simply run composer update? And if so: what error do you get?

**Comment by ChrisRiddell** [comment]
Thoughts on the having to edit the fortify config file or any file that needs manual edits maybe needs to be documented in the UPGRADING.md file as you should not really need to dig through the source code to upgrade between 2.x (MINOR) versions? _(I miss the recipes:update from Symfony)_

I just upgraded an old Jetstream 2.6 project and I'm unable to reproduce any errors or unexpected behaviour without the `'confirm' => true` for 2FA using the Google Authenticator App.

**Comment by driesvints** [comment]
Right. I don't think anything will break if you run a composer update. 

Listing all upgrade steps between minor versions is an impossible task as there's way too much files involved. It basically boils down to copying the changes from the stubs. Remember that Jetstream is a scaffold and there's no easy way to upgrade to newer functionality in stubs. People might have edited their stubs already so it's much more complicated than just copy/paste.
