### ISSUE TITLE
Laravel Passport Integration

### ISSUE THREAD

**Issue by tokuzou0829** [laravel/jetstream#1029]
I would like to be able to add OAuth clients for Laravel Passport from jetstream.

**Comment by joelbutcher** [comment]
@tokuzou0829 You can pull in Laravel Passport using `composer`, then it's just a case of creating / updating any files you wish to use to include the logic for creating OAuth clients. Jetstream won't do this out of the box, it's likely too much code to maintain.

```shell
composer require laravel/passport
```

Might be worth a trip to the [Laravel Passport documentation](https://laravel.com/docs/9.x/passport).

**Comment by driesvints** [comment]
Atm we're not pursuing first party support for this. You're free, however, to add this yourself.
