### ISSUE TITLE
JetConfirmsPassword on Confirming 2FA

### ISSUE THREAD

**Issue by hailwood** [laravel/jetstream#1033]
- Jetstream Version: 2.7.1
- Jetstream Stack: both
- Uses Teams: N/A but no
- Laravel Version: N/A but 9.6.0
- PHP Version: N/A but 8.1.0
- Database Driver & Version: N/A

### Description:
In the Inertia stack the `Confirm` button for 2FA is wrapped in 
```jsx
<JetConfirmsPassword @confirmed="confirmTwoFactorAuthentication">...</JetConfirmsPassword>
```
However the input on the form the button relates to triggers the same function via the enter key
```
@keyup.enter="confirmTwoFactorAuthentication"
```
Meaning the confirms password can be bypassed by simply pressing <kbd>enter</kbd> on the input.

Similary for the Livewire stack it's wrapped in
```html
<x-jet-confirms-password wire:then="confirmTwoFactorAuthentication">
```
However the input on the form the button relates to triggers the same function via the enter key
```
wire:keydown.enter="confirmTwoFactorAuthentication"
```

I believe this wrapping JetConfirmsPassword/x-jet-confirms-password probably shouldn't be there as the user would have recently confirmed their password when they clicked the `Enable` button, so unless they clicked enable and then left their device long enough for the confirm password timeout to occur (3 hours by default iirc) they'll never get prompted anyway.

### Steps To Reproduce:
Enable 2FA and 2FA Confirming

### Relevant Files
https://github.com/laravel/jetstream/blob/2.x/stubs/livewire/resources/views/profile/two-factor-authentication-form.blade.php
https://github.com/laravel/jetstream/blob/2.x/stubs/inertia/resources/js/Pages/Profile/Partials/TwoFactorAuthenticationForm.vue

**Comment by driesvints** [comment]
Thanks for reporting this. I think removing the key press listeners is the easiest solution for now. I sent in a PR for that here: https://github.com/laravel/jetstream/pull/1035

**Comment by driesvints** [comment]
@hailwood we can't seem to recreate this. Pressing enter on the field invokes the password confirmation.

**Comment by driesvints** [comment]
In livewire I seem to be getting a 403 model when entering in the code field after executing your route. Fresh Laravel app. This isn't ideal indeed.. 

<img width="1876" alt="Screenshot 2022-04-08 at 12 09 58" src="https://user-images.githubusercontent.com/594614/162415341-e58dd495-ce12-4411-92e8-82d33be9575e.png">
