### ISSUE TITLE
Auth guard [:api] is not defined in 2FA Recovery Code

### ISSUE THREAD

**Issue by eskiesirius** [laravel/jetstream#1037]
- Jetstream Version: v2.6.6
- Jetstream Stack: Inertia
- Uses Teams: no
- Laravel Version: ^8.75
- PHP Version: 7.4
- Database Driver & Version: MySQL

### Description:
After generating 2FA Recovery Code and use it when logging in, errors pops out which is "Auth guard [:api] is not defined"

### Steps To Reproduce:
Install Laravel Audit then attach it to the User Model then enable 2FA and get the recovery code then login using recovery code.

**Comment by eskiesirius** [comment]
I fixed it by removing api in audit.php
from
```
'user'      => [
        'morph_prefix' => 'user',
        'guards'       => [
            'web',
            'api'
        ],
        'resolver' => OwenIt\Auditing\Resolvers\UserResolver::class
    ],
```
to
```
'user'      => [
        'morph_prefix' => 'user',
        'guards'       => [
            'web',
        ],
        'resolver' => OwenIt\Auditing\Resolvers\UserResolver::class
    ],
```

**Comment by driesvints** [comment]
We don't support Laravel Audit sorry.

Try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
