### ISSUE TITLE
Password reset events are not fired when UpdateUserPassword action is ran.

### ISSUE THREAD

**Issue by sunscreem** [laravel/jetstream#1038]
- Jetstream Version: 2.7.3
- Jetstream Stack: Inertia
- Uses Teams:  no
- Laravel Version: 9.8.1
- PHP Version: 8.0.15

### Description:

_note: this may be a fortify issue_

As the title suggests, I'm trying to catch the `Illuminate\Auth\Events\PasswordReset` event. When using the password reset form within the profile screen the event doesn't seem to be fired.

### Steps To Reproduce:

Install laravel, install jetstream. 

Create password reset listener and listen for Illuminate\Auth\Events\PasswordReset

[Issue repo created here](https://github.com/sunscreem/jetstream-issue/blob/master/app/Listeners/PasswordResetListener.php).

**Comment by driesvints** [comment]
Can you try logging instead? Since it's an inertia app, I don't actually expect you to see a dd in your screen.

**Comment by sunscreem** [comment]
Hey @driesvints. I was using logging before, I noticed the password resets weren't getting logged. So in my demo I replaced that logging with a dd so I could see something had triggered. I can confirm it never gets to the dd (or the logging in my real app). Apologies for the confusion.

**Comment by driesvints** [comment]
With your exact repo, I'm able to receive the event and log it:

```
<?php

namespace App\Listeners;

class PasswordResetListener
{
    public function handle($event)
    {
        logger('password reset event received.');
    }
}
```

<img width="905" alt="Screenshot 2022-04-15 at 09 43 53" src="https://user-images.githubusercontent.com/594614/163541203-948fc281-42c5-46b0-abd2-6f62d923fd28.png">

**Comment by sunscreem** [comment]
@driesvints Sorry about this - but can you confirm that you reset your password using the form inside the app? The one you see when you are logged in and go to `Profile`?

Just to confirm I am able to see the event fired when the password if changed via the usual auth routes but not via the the form on the profile page.

**Comment by driesvints** [comment]
@sunscreem That's not a password reset. That's a profile update.

**Comment by sunscreem** [comment]
@driesvints thanks. So I'm guessing I'll need to find a different event to tap into the password being updated here?

**Comment by driesvints** [comment]
Right now, I don't immediately see such an event. You're free to attempt a PR if you want 👍
