### ISSUE TITLE
Livewire ProfileInformationTest, 'profile information can be updated', failing

### ISSUE THREAD

**Issue by tanthammar** [laravel/jetstream#1039]
- Jetstream Version:  2.7.2
- Jetstream Stack: Livewire 2.10.5
- Uses Teams: yes
- Laravel Version: 9.7.0
- PHP Version: 8.1.4
- Database Driver & Version: MySQL 8.0.27
- "pestphp/pest": "^1.16",
- "pestphp/pest-plugin-laravel": "^1.1",
-  "pestphp/pest-plugin-livewire": "^1.0",

### Description:
The Livewire ProfileInformationTest, 'profile information can be updated' test is failing.
But filling out the form manually, works.

The test fails when asserting that the user has been updated

```
expect($user->fresh())
        ->name->toEqual('Test Name')
```

```
Failed asserting that two strings are equal.
Expected :'Test Name'
Actual   :'Cyrus Rempel PhD'
```

**Comment by driesvints** [comment]
Seems to pass for me on a fresh install.

<img width="602" alt="Screenshot 2022-04-14 at 16 12 57" src="https://user-images.githubusercontent.com/594614/163408978-aa4009bd-794d-4df2-b49c-b3fabcbe6846.png">
