### ISSUE TITLE
Jetstream SSR error on pages within a sub folder 

### ISSUE THREAD

**Issue by DelaneyArkICT** [laravel/jetstream#1041]
- Jetstream Version: 2.7
- Jetstream Stack: Inertia vue SSR enabled
- Uses Teams: both
- Laravel Version: 8.75
- PHP Version: 7.4
- Database Driver & Version:

### Description:
When using the SSR flag with Jetstream and the inertia stack clicking the page reload button in the browser will cause the error mentioned below. I have narrowed the bug down to only be present on all pages that are in a sub folder in the pages directory. 

for example projects\resources\js\Pages\Profile\Show.vue

Pages in the projects\resources\js\Pages are not effected by this issue only if they are 1 or more folder deep.

Please note that SSR does not work on ANY pages that are in a sub folder of the 'projects\resources\js\Pages ' directory this is testable by viewing the page source.

### Steps To Reproduce:

Install the inertia stack with ssr flag compile ssr.js and vue then launch ssr.js with node and go to the profile page or a page that is a sub folder within the 'resources\js\Pages\' directory and click the reload button in the browser. Then look at the cli where you launched ssr.js from and you will see the following error.

Error in console
ReferenceError: window is not defined
    at setup (C:\xampp\htdocs\project\public\js\ssr.js:1:35396)
    at callWithErrorHandling (C:\xampp\htdocs\project\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:157:22)
    at setupStatefulComponent (C:\xampp\htdocs\project\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7027:29)
    at setupComponent (C:\xampp\htdocs\project\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:6982:11)
    at renderComponentVNode (C:\xampp\htdocs\project\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:198:17)
    at ssrRenderComponent (C:\xampp\htdocs\project\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:629:12)
    at C:\xampp\htdocs\project\public\js\ssr.js:1:42344
    at renderComponentSubTree (C:\xampp\htdocs\project\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:269:13)
    at renderComponentVNode (C:\xampp\htdocs\project\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:214:16)
    at ssrRenderComponent (C:\xampp\htdocs\project\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:629:12)
[Vue warn]: Unhandled error during execution of setup function
  at <Anonymous>

**Comment by DelaneyArkICT** [comment]
### Further information (IMPORTANT)

After additional testing, server side rendering  **ONLY** stops working after the user has been successfully authenticated.

**Comment by driesvints** [comment]
Ping @xiCO2k

**Comment by xiCO2k** [comment]
Hey @DelaneyArkICT, can you share the code of the ssr.js file?

Thanks

**Comment by DelaneyArkICT** [comment]
Hello @xiCO2k no problem.

`import { createSSRApp, h } from 'vue';
import { renderToString } from '@vue/server-renderer';
import { createInertiaApp } from '@inertiajs/inertia-vue3';
import createServer from '@inertiajs/server';
import route from 'ziggy';

const appName = 'Laravel';

createServer((page) =>
    createInertiaApp({
        page,
        render: renderToString,
        title: (title) => `${title} - ${appName}`,
        resolve: (name) => require(`./Pages/${name}.vue`),
        setup({ app, props, plugin }) {
            return createSSRApp({ render: () => h(app, props) })
                .use(plugin)
                .mixin({
                    methods: {
                        route: (name, params, absolute) => {
                            return route(name, params, absolute, {
                                ...page.props.ziggy,
                                location: new URL(page.props.ziggy.url),
                            });
                        },
                    },
                });
        },
    })
);
`

**Comment by xiCO2k** [comment]
One thing that you need to be aware on your pages/components. is to not have the `window` being used on server. 

That is not related with our scaffolding, is related with the way you use it.

There is a check that I use all the time, on my pages/components:

```js
const isServer = typeof window === 'undefined';
```

This way you can make sure the `window` is being used on the SSR runtime.

@driesvints, from what I checked here, looks like that is not an issue on our side.

@DelaneyArkICT if you need any help feel free to send me a DM on Twitter.

**Comment by driesvints** [comment]
Thanks @xiCO2k
