### ISSUE TITLE
How to redirect conditionally after switching teams ?

### ISSUE THREAD

**Issue by james-wong123** [laravel/jetstream#1047]
- Jetstream Version: 2.6
- Jetstream Stack: Inertia 
- Uses Teams: yes
- Laravel Version: 9.11.0
- PHP Version: 8.1
- Database Driver & Version: Mysql - 8.0.29

### Description:
I have added roles and permissions to my application, 

When switching the teams

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
