### ISSUE TITLE
Profile page not loading with email verification disabled

### ISSUE THREAD

**Issue by JoelBeerDe** [laravel/jetstream#1052]
- Jetstream Version: 2.8.0
- Jetstream Stack: Inertia
- Uses Teams: no
- Laravel Version: 9.12.2
- PHP Version: 8.1.4
- Database Driver & Version: MySQL - 8.0.28-arm64

### Description:
After a fresh installation of Jetstream you get the error `Uncaught (in promise) Error: Ziggy error: route 'verification.send' is not in the route list.` when you try to open the profile. 

### Steps To Reproduce:
Install a new project and try to go to profile view

### Fix
You can fix the error by enabling `Features::emailVerification()` in config/forty.php or simply removing the "Click here to re-send the verification email." link on the profile page.

A better approach would be to check if `Features::emailVerification()` is enabled and display the resend link according to that.

**Comment by driesvints** [comment]
Thanks, this is indeed an oversight.

**Comment by driesvints** [comment]
@JoelBeerDe would you be able to try out my fix from https://github.com/laravel/jetstream/pull/1053 to see if that works for you?

**Comment by JoelBeerDe** [comment]
@driesvints Works for me again now, thanks!
