### ISSUE TITLE
Jetstream without team option still creates team related code

### ISSUE THREAD

**Issue by NicoHood** [laravel/jetstream#1058]
- Jetstream Version: v2.8.2
- Jetstream Stack: Livewire
- Uses Teams: no
- Laravel Version: v9.14.1
- PHP Version: 8.1.x
- Database Driver & Version:

### Description:
I've just installed jetstream and tracked all changes via git. It turns out, that there are some changes related to the teams feature, which I do not use. I'd expect that this code would not be used.

I can only do pictures for now, as it is a private repository.
![image](https://user-images.githubusercontent.com/6888294/170886124-e42e6d34-1687-45bb-85a8-1b53d156a1bc.png)
![image](https://user-images.githubusercontent.com/6888294/170886128-8d8ffed1-3fa0-4fb2-8c6e-d31f3cef92d9.png)
![image](https://user-images.githubusercontent.com/6888294/170886162-ca6e6570-7a42-42f6-9071-9da58907a857.png)

### Steps To Reproduce:
* Create a new laravel project
* Install fortify
* Now track that in git
* Install jetstream
* Checkout the difference of the files, especially the modified files

**Comment by driesvints** [comment]
Yes that's intentional. To give you the option to switch to teams later on if you want to.
