### ISSUE TITLE
Fresh install of laravel new app with jetstream not building with Vite

### ISSUE THREAD

**Issue by ianyxtan** [laravel/jetstream#1083]
- Jetstream Version: 2.9.0
- Jetstream Stack: Inertia
- Uses Teams: no
- Laravel Version: 9.19
- PHP Version: 8.1.7
- Database Driver & Version: sqlite3

### Description:
Fresh install of laravel new app with jetstream not building with Vite

### Steps To Reproduce:
1. Create new laravel app using laravel/installer:
```
cd ~/sites
laravel new signin

```

2. Install jetstream:
```
cd signin
composer require laravel/jetstream
```

3. Install Inertia stack:
```
php artisan jetstream:install inertia
npm install 
```

4. Add database:
```
touch database/database.sqlite
```

5. Update .env file:
```
- DB_CONNECTION=mysql
+DB_CONNECTION=sqlite
...
DB_DATABASE=/home/*username*/sites/signin/database/database.sqlite
 
```

6. Run Vite:
```
npm run dev
```

7. Visit http://localhost:3000 but throws 404 error

Repo: https://github.com/ianyxtan/signin

**Comment by jessarcher** [comment]
Hi @ianyxtan, `http://localhost:3000` is Vite's development server that provides hot module replacement for your application. You will still need to run a local development server for your application, using `php artisan serve`, [Laravel Sail](https://laravel.com/docs/9.x/sail), or [Laravel Valet](https://laravel.com/docs/9.x/valet).

We have a [PR](https://github.com/laravel/vite-plugin/pull/57) for the Laravel plugin that should make the clearer in the future.
