### ISSUE TITLE
Duplicate sessions table migration

### ISSUE THREAD

**Issue by kristencolquhoun** [laravel/jetstream#1088]
- Laravel Version: 8.37 onwards
- PHP Version: ^8

### Description:
Due to Laravel now using anonymous migrations, the install command unsuccessfully checks if the sessions migration already exists, this results in duplicate migrations for the sessions table, this occurs if either the sessions migration is created before the jetstream install command, or if the install command is ran more than once.

https://github.com/laravel/jetstream/blob/ee23dac932fa3344d3a7939b7a2a8fda10e57a53/src/Console/InstallCommand.php#L105

### Steps To Reproduce:
php artisan sessions:table
php artisan jetstream:install

**Comment by driesvints** [comment]
You should not run the sessions table command when also installing jetstream. Jetstream is meant to be the first thing you run when installing a new Laravel app. The check you mentioned above indeed is obsolete now.
