### ISSUE TITLE
Incompatibilities/confusion with Sail

### ISSUE THREAD

**Issue by leonardchallis** [laravel/jetstream#1092]
- Jetstream Version: 2.10.0
- Jetstream Stack: Livewire
- Uses Teams: no
- Laravel Version: 9.20.0
- PHP Version: 8.1.8
- vite version: 2.9.14
- Database Driver & Version: N/A

### Description:

After a default Sail installation, following the installation instructions from the Jetstream documentation causes confusion. You're instructed to run `npm run dev` - before this would compile and drop you back to a shell. Now using vite, it outputs the following and stays there:

```
  vite v2.9.14 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 202ms.


  Laravel v9.20.0

  > APP_URL: http://example-app.test
```

_Note: also the port is wrong here._

The documentation says:

> After installing Jetstream, you should install and build your NPM dependencies and migrate your database:
> 
> ```
> npm install
> npm run dev
> php artisan migrate
> ```
> 

I haven't used vite much yet so I'm not familiar, but I presume it's meant to do that (and acts like `watch` used to?) but it's not clear it's worked properly for people expecting to be able to then run their migrate command.

### Steps To Reproduce:

```
curl -s "https://laravel.build/example-app" | bash
sail up -d
composer require laravel/jetstream
sail artisan jetstream:install livewire
npm install
npm run dev
```

As a side note, it would be great to be able to install Jetstream alongside Laravel (in the same way `laravel new example-app --jet` would.

**Comment by driesvints** [comment]
Thanks for reporting this. I've sent in a PR with the correct non-blocking command: https://github.com/laravel/jetstream-docs/pull/66

> Note: also the port is wrong here.

The `Local:` shouldn't be used and should be ignored.
