### ISSUE TITLE
How i can customize jetstream livewire component

### ISSUE THREAD

**Issue by mr-chetan** [laravel/jetstream#1094]
Please make livewire components customizable or make them publishable.
So we can change or add the functionality to them.

**Comment by mr-chetan** [comment]
I also make the pull request regarding that 
[https://github.com/laravel/jetstream/pull/1091](https://github.com/laravel/jetstream/pull/1091)

**Comment by driesvints** [comment]
Right now, we don't offer this, sorry.

**Comment by mr-chetan** [comment]
@driesvints It's ok you don't offer this.
But closing the issue is not the solution to the problems
