### ISSUE TITLE
Jetstream 2 with Larastan

### ISSUE THREAD

**Issue by eskiesirius** [laravel/jetstream#1096]
- Jetstream Version: v2.10.1
- Jetstream Stack: Inertia
- Uses Teams: yes
- Laravel Version: v9.21.3
- PHP Version: 8.1
- Database Driver & Version:

### Description:
![Screenshot_14](https://user-images.githubusercontent.com/7463362/180213870-e4ba2f6b-a0ed-49c1-b9ac-93d8214b0b18.png)

**Comment by driesvints** [comment]
Hi, we don't optimize for tools like Larastan. If you want to fix something feel free to send in a PR. Thanks
