### ISSUE TITLE
double escaping string in components views

### ISSUE THREAD

**Issue by Ronan-Lenor** [laravel/jetstream#1105]
- Jetstream Version: 2.10.2
- Jetstream Stack: Livewire
- Uses Teams: yes
- Laravel Version: 9.x

### Description:
some part of jetstream views are double escaping strings, resulting in gibberish characters in html page rendering.

### Steps To Reproduce:

in [.\stubs\livewire\resources\views\teams\create-team-form.blade.php](https://github.com/laravel/jetstream/blob/2.x/stubs/livewire/resources/views/teams/create-team-form.blade.php) `<x-jet-label value="{{ __('Team Owner') }}" />` is used with `{{ ... }}` which escape single quotes like so `&#039;`.

BUT in [.\resources\views\components\label.blade.php](https://github.com/laravel/jetstream/blob/2.x/resources/views/components/label.blade.php) the `$value` is escaped a second time, creating `&amp;#039;`

### Possible Solution
i haven't check everywhere this problem occure, but using `{!! ... !!}` instead of `{{ ... }}` could resolve the problem:
`<x-jet-... attribute="{!! __('translated text') !!}" />`

P.S.: of course don't use `{!! ... !!}` in the label component, which would result in a security issue.

**Comment by driesvints** [comment]
For me, on a fresh Jetstream install, everything seems fine:

<img width="336" alt="Screenshot 2022-08-01 at 17 00 38" src="https://user-images.githubusercontent.com/594614/182179276-66120188-ef8d-4cc0-aa0f-6caac2b1421f.png">
<img width="207" alt="Screenshot 2022-08-01 at 17 00 41" src="https://user-images.githubusercontent.com/594614/182179283-143d8029-8865-49a2-b5a7-0184f31be3c7.png">

**Comment by Ronan-Lenor** [comment]
there is no quotes in english, try french
