### ISSUE TITLE
Code style preset for Jetstream's Vue components

### ISSUE THREAD

**Issue by eta-orionis** [laravel/jetstream#1124]
I believe it is necessary to provide or document a code style preset for the Vue components included with Jetstream. Otherwise the developer experience suffers upon upgrades.

Actual problem scenario:
- Laravel 8 App using Jetstream components; a few components had been customized a little (e.g. colors, margins, etc.)
- the old components were autoformatted by eslint/prettier to whatever settings eslint/prettier had at that time
- upgrading to Laravel 9, developer wants to upgrade the Vue components too, porting over the few changes done back then
- Due to the mismatched formatting between old and new components, every line has a change and it is impossible to distinguish actual code changes from formatting changes

How a code style preset resolves this:
- existing codebases can be reformatted to the preset and merged easily with the updated components from Jetstream
- the formatting of the provided components remains consistent over future versions, allowing easy upgrades to future versions of Jetstream

It does not matter for which tool the preset is, as long as it exists for at least one tool (just enough to bring existing codebases to the preset)

Simplest way to resolve: publish or document the settings that @taylorotwell, @jessarcher, and/or the other developers of Jetstream's Vue components use.

**Comment by driesvints** [comment]
It's not really meant to upgrade the components. Jetstream is a scaffold tool that publishes components into your app. Any upgrades you want to perform really fall on yourself. Right now we don't have a plan for a separate code style preset.
