### ISSUE TITLE
Terms and conditions should be required by default

### ISSUE THREAD

**Issue by JoshSalway** [laravel/jetstream#1126]
https://github.com/laravel/jetstream/blob/04a68c0294b9e04a8109497ff05987268a12610f/stubs/inertia/resources/js/Pages/Auth/Register.vue#L90

**Comment by jessarcher** [comment]
Thanks for fixing this in #1127!

**Comment by JoshSalway** [comment]
> Thanks for fixing this in #1127!

Thanks, No worries @jessarcher
