### ISSUE TITLE
Inertia cannot authenticate(even with correct credentials) when hosted in cPanel

### ISSUE THREAD

**Issue by CleoCTech** [laravel/jetstream#1128]
- Jetstream Version: 2.9
- Jetstream Stack: Inertia 
- Uses Teams: no
- Laravel Version: 9.19
- PHP Version: 8.0.2
- Database Driver & Version: Mysql 8

When trying to login I am returned to the login page again. I can get the user being returned from the console then back to login page.  If I enter a wrong email or password, it returns with an error.
However, the application logs in well in my local machine, the problem is expereinced in cPanel host space.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
