### ISSUE TITLE
Deleting a team that's the current_team for a User causes issues

### ISSUE THREAD

**Issue by Illizian** [laravel/jetstream#1129]
- Jetstream Version: 2.3.6
- Jetstream Stack: Livewire
- Uses Teams: yes
- Laravel Version: 8.42.1
- PHP Version: 8.0.22
- Database Driver & Version: mysql:8.0 (from laravel/sail)

### Description:

There's an issue with deleting a Team assigned as a User's current team.

The method `currentTeam` within the `HasTeams` trait has a check to switch to a User's personal team if their `current_team_id` is null. Unfortunately, with no cascades, this ID doesn't get updated.

```php
if (is_null($this->current_team_id) && $this->id) {
    $this->switchTeam($this->personalTeam());
}
// [...]
```
Which can be found [here](https://github.com/laravel/jetstream/blob/2.x/src/HasTeams.php#L28-L30).

### Steps To Reproduce:

_I'm sorry, I have provided a tinker routine here as it seems most relevant because this involves "logic"._

```php
// 1. Create a Team, with an owner and a team member
$team = Team::factory()
  ->state([ 'approved' => true, 'personal_team' => false ])
  ->hasOwner(
    User::factory()->withPersonalTeam()
  )
  ->hasUsers(
    User::factory()->withPersonalTeam()
  )
  ->create()
/*
=> App\Models\Team {
  id: 7,
  // [...]
}
*/

// [debug] print the User we added as a member for the context on this issue
$team->users->first();
/*
=> App\Models\User {
  id: 9,
  // [...]
}
*/

// 2. Switch the user above onto that team
$team->users->first()->switchTeam($team);
/*
=> true
*/

// [debug] print the User's current team
$team->users->first()->currentTeam
/*
=> App\Models\Team {
  // [...]
  id: 7,
}
*/

// 3. Delete the team
$team->delete()
/*
=> true
*/

// 4. Try and get the user's current team
$team->users->first()->currentTeam
/*
=> null
*/
```

Thanks and please forgive lack of info. I'm happy to provide any additional info you require and I'm happy to submit a PR with a fix to that method. I just wanted to get your opinions and expertise first... An additional check on the method mentioned could be used to check if the `current_team_id` points to an existing team.

**Comment by driesvints** [comment]
You cannot delete the current team of a user. A user always needs a team record.

**Comment by Illizian** [comment]
> You cannot delete the current team of a user. A user always needs a team record.

You cannot, or you should not. Because you definitely can...
