### ISSUE TITLE
Explode deprecated on null - src/HasProfilePhoto.php

### ISSUE THREAD

**Issue by Cjleto** [laravel/jetstream#1130]
- Jetstream Version: 2.12
- Jetstream Stack: Livewire
- Uses Teams: no
- Laravel Version: ^9
- PHP Version: 8.1
- Database Driver & Version: mysql

### Description:
Hi guys,
in src/HasProfilePhoto.php:74 i have a php warning for deprecated explode on null. 

`$name = trim(collect(explode(' ', $this->name))->map(function ($segment) {
            return mb_substr($segment, 0, 1);
        })->join(' '));`

> resolved adding `?? ''` after `$this->name` param

**Comment by driesvints** [comment]
https://github.com/laravel/jetstream/blob/2.x/database/migrations/2014_10_12_000000_create_users_table.php#L18

`name` cannot ever be `null`.
