### ISSUE TITLE
This test just do Nothing

### ISSUE THREAD

**Issue by AliGh1** [laravel/jetstream#1134]
- Jetstream Version: 2.12.0
- Jetstream Stack: Livewire
- Uses Teams: no
- Laravel Version: 9.28.0
- PHP Version: 8.1.6
- Database Driver & Version:

### Description:
Hello, I'm just wondering what kind of test it do
[livewire/BrowserSessionsTest.php](https://github.com/laravel/jetstream/blob/2.x/stubs/tests/livewire/BrowserSessionsTest.php).

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
