### ISSUE TITLE
Running Pint Permission Denied

### ISSUE THREAD

**Issue by eskiesirius** [laravel/jetstream#1136]
- Jetstream Version: v2.12.0
- Jetstream Stack: Inertia
- Uses Teams: no
- Laravel Version: v9.29.0
- PHP Version: 8
- Database Driver & Version:

### Description:
Running pint command returns permission denied

### Steps To Reproduce:
![Screenshot_1](https://user-images.githubusercontent.com/7463362/189905575-3bbdc41b-68a9-4a8d-b920-278000cdec97.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
