### ISSUE TITLE
BrowserSessionTest has started reporting as `risky`

### ISSUE THREAD

**Issue by da-mask** [laravel/jetstream#1137]
- Jetstream Version: 2.12.0
- Jetstream Stack: Livewire
- Uses Teams:  no
- Laravel Version: 9.29.0 
- PHP Version: 8.1.8
- Database Driver & Version:   8.0.23 - MySQL 

### Description:
On my app, when running BrowserSessionTest from the Livewire stack, the `test_other_browser_sessions_can_be_logged_out` is now reporting that `This test did not perform any assertions`, which, on the surface of it, is true. I'm not sure how this test "tests" this feature, because it does not have any assertions, nor ever did. 

### Steps To Reproduce:

1.  run `php artisan test --filter test_other_browser_sessions_can_be_logged_out`
2. View test result to risky (I hope this is the same for others!)

**Comment by da-mask** [comment]
Looks related to this question, but no answer there. #1134

**Comment by driesvints** [comment]
Heya, thanks! I sent in a PR for this.

**Comment by da-mask** [comment]
Sweet! Thanks for all your work!
