### ISSUE TITLE
The removed season returns again

### ISSUE THREAD

**Issue by AliGh1** [laravel/jetstream#1139]
- Jetstream Version: 2.12.0
- Jetstream Stack: Inertia
- Uses Teams: no
- Laravel Version: 9.29.0
- PHP Version: 8.1.6
- Database Driver & Version: MySQL

### Description:
Hello, I think there is a bug, It **_may be risky_**
When you log out the other sessions or change the account password, the killed sessions can come back.

### Steps To Reproduce:

1. I log into an account in a browser like Chrome
2. I log in to the same account in another browser such as firefox and **_check the remember me option_**
3. In the Firefox browser (remember me checked), I go to the `/` root
4. In the Chrome browser, I go to the `/user/profile` root, and  Log Out Other Browser Sessions.
5. Check the Database and yes, I only have one session.
6. In the Firefox browser, refresh the `/` page and **_Booom!_**; I'm back
7. I check the database and yes, I have access to the account, without entering the password, because I have two sessions now.

This scenario even works for changing passwords.

**Comment by driesvints** [comment]
There's an extensive explanation for why this happens here: https://github.com/laravel/jetstream/issues/277

**Comment by AliGh1** [comment]
Thanks, It was really helpful, But I didn't understand the correct answer, that was just the reason.

**Anyway, I found a solution that I think is good**.
You can add `\Laravel\Jetstream\Http\Middleware\AuthenticateSession::class` Middleware to `web` middlewareGroups in `App\Http\Kernel.php`.
You can find this middle in `config('jetstream.auth_session')`
I didn't see any problem with **remember me**.
And now, you can delete other sessions, _even if remember me checked_, with **Log Out Other Browser Sessions** button and if the malicious user tries to refresh the page, it will be redirected to the login page.
@driesvints If this method doesn't cause a problem, it may be a PR or at least it is mentioned in the document.

Thank you for reading and taking the time.

**Comment by driesvints** [comment]
Feel free to attempt a PR to the docs 👍
