### ISSUE TITLE
TeamInvitationController.php uses `Laravel\Jetstream\TeamInvitation` instead of `App\Models\TeamInvitation` created by stubs

### ISSUE THREAD

**Issue by sicaboy** [laravel/jetstream#1141]
- Jetstream Version: 2.11.2
- Jetstream Stack: Inertia & Livewire
- Uses Teams: yes & no
- Laravel Version: 9.27.0
- PHP Version: 8.1
- Database Driver & Version:

### Description:

The `TeamInvitationController.php` uses `Laravel\Jetstream\TeamInvitation` as injection in `accept(...,TeamInvitation $invitation) and `destroy(...,TeamInvitation $invitation)` instead of `App\Models\TeamInvitation` created by stubs.

**This makes the custom Model classes useless.**

### Steps To Reproduce:

**Example:**
- Change the DB connection for the model App\Models\TeamInvitation
- When adding invitations & removing invitations, it ignores the custom DB connection, because the DI uses the `Laravel\Jetstream\TeamInvitation` instead.

**Comment by sicaboy** [comment]
I saw this issue had been addressed here https://github.com/laravel/jetstream/issues/890 but in the latest release, the fix wasn't merged.

**Comment by sicaboy** [comment]
I saw the fix was reverted here https://github.com/laravel/jetstream/commit/220787a48ff97f1cc125b34ad19716f4edfe71d4

**Comment by driesvints** [comment]
Right now, we have no plans for this. Anyone can attempt a new PR to master.

**Comment by sicaboy** [comment]
I have done a workaround by copying the controller and overwriting the route.
