### ISSUE TITLE
Not using custom jetstream-routes

### ISSUE THREAD

**Issue by sicaboy** [laravel/jetstream#1142]
- Jetstream Version: 2.11.2
- Jetstream Stack: Inertia / Livewire
- Uses Teams: yes / no
- Laravel Version: 9.27.0
- PHP Version: 8.1
- Database Driver & Version:

### Description:
Not using custom `jetstream-routes` even there is one. See the steps to reproduce below.

### Steps To Reproduce:

- Publish jetstream-routes  `php artisan vendor:publish --tag="jetstream-routes"`
- It doesn't actually matter what the custom route content is, even if we published the routes. This line code doesn't read the `routes/jetstream.php` https://github.com/laravel/jetstream/blob/2.x/src/JetstreamServiceProvider.php#L204

I'd like to do the fix if the members think it is a bug.

**Comment by driesvints** [comment]
You still need to use `Jetstream::ignoreRoutes()` and include the `jetstream.php` route file here: https://github.com/laravel/laravel/blob/9.x/app/Providers/RouteServiceProvider.php#L31

This is rarely done and recommended against which is why we don't document this.
