### ISSUE TITLE
Support for React

### ISSUE THREAD

**Issue by jezzdk** [laravel/jetstream#1144]
It's awesome that we get a bunch of Vue components for Inertia, when scaffolding a new Jetstream project. However, at my company it has been decided long ago that React is the frontend tech of choice. It would be extra awesome if Jetstream could provide an option between Vue and React components when installing.

The GitHub user [ozziexsh](https://github.com/ozziexsh/) has already done a helluva job [porting the Vue components to React](https://github.com/ozziexsh/laravel-jetstream-react), so you might be able to get a head start there.

**Comment by driesvints** [comment]
We have no plans for this sorry.
