### ISSUE TITLE
support for svelte

### ISSUE THREAD

**Issue by ramabie** [laravel/jetstream#1145]
i am a jetstream livewire user.
jetstream with live is a great work.

when i saw the svelte i got interested in it.
will there be a svelte version of jetstream in the future?

**Comment by driesvints** [comment]
We have no plans for this right now, sorry.

**Comment by ramabie** [comment]
ok master
thankyou for the response

**Comment by n4j1Br4ch1D** [comment]
it will be great to have svelte supported
