### ISSUE TITLE
trait ConfirmsTwoFactorAuthentication fires Scout make Searchable Job on every 'user/profile' visit

### ISSUE THREAD

**Issue by hopkins385** [laravel/jetstream#1146]
- Jetstream Version: v2.12.2
- Jetstream Stack: Inertia 
- Uses Teams: no
- Laravel Version: 9.31.0
- PHP Version: 8.1.10
- Database Driver & Version:
  Broadcasting ................................................................................................................................. log  
  Cache ...................................................................................................................................... redis  
  Database ................................................................................................................................... mysql  
  Queue ...................................................................................................................................... redis  
  Scout ................................................................................................................................... database  
  Session .................................................................................................................................... redis 

### Description:

Hi guys, I was wondering why the "Scout: make Searchable Job" is fired every time I visit or refresh the route /user/profile.
I'm using Laravel Scout on the user-model with the standard trait that comes with Scout "use Searchable;".
I'm also using redis for the Queue with SCOUT_QUEUE = true. 

I was able to trace it down to the 'ConfirmsTwoFactorAuthentication' trait that comes with Jetstream. 
The method 'neverFinishedConfirmingTwoFactorAuthentication' returns always true (if the user has not enabled two-factor) which causes always a model update and that results in a Job for Scout to re-index the "updated" user model. 

But, the intention of this method is to check if the user has started confirming two factor but aborted somehow (if I understand this correctly). See source code comment: "_// If the profile is reloaded and is not confirmed but was previously in confirming state, disable..._"

### Steps To Reproduce:

Use Laravel-Scout on the user model, enable queue for scout with redis.
Enable two factor auth feature if not already enabled.
Log-in and visit route or refresh /user/profile. 

Result: On every visit a new Job "make searchable" is fired. 

### Proposed update:

```
protected function neverFinishedConfirmingTwoFactorAuthentication(Request $request, $currentTime)
    {
        return !array_key_exists('code', $request->session()->getOldInput()) &&
            is_null($request->user()->two_factor_confirmed_at) &&
            $request->session()->has('two_factor_confirming_at') && //<- add this line to ensure the user has started two factor auth 
            $request->session()->get('two_factor_confirming_at', 0) != $currentTime;
    }
```

**Comment by driesvints** [comment]
Heya yeah that update sounds good. Can you PR?

**Comment by hopkins385** [comment]
Hi, I'd love to give smth back to the community. But it would be my first PR. Is there anywhere a documentation about the PR workflow? e.g. do I need to branch and then what is next?

**Comment by driesvints** [comment]
Here you go https://laravel.com/docs/9.x/contributions#which-branch
