### ISSUE TITLE
2FA form not getting correct errors - Inertia stack

### ISSUE THREAD

**Issue by likeadeckofcards** [laravel/jetstream#1152]
- Jetstream Version: 2.12.3
- Jetstream Stack: Inertia
- Uses Teams: Does not matter
- Laravel Version: 9.32.0 (Does not matter)
- PHP Version: 8.1.10 (Does not matter)
- Database Driver & Version: mysql 8.0.30 (Does not matter)

### Description:
When using the Inertia stack with Jetstream, there is a bug when submitting the two factor challenge form. Since the form is initialized with both code and recovery_code, it will always submit both values to the server. In the Fortify response class, `Laravel\Fortify\Http\Responses\FailedTwoFactorLoginResponse.php` there is a check that the request has the recovery_code key and does not check if it has a value. It then is setting the invalid field and message accordingly. Because of this check, the inertia stack causes fortify to think that we are using the recovery code to login instead of the standard code.

Other Note:
Livewire stack submits this correctly. 

### Steps To Reproduce:

1. `Laravel new jetstream-test --jet --stack=inertia`
2. Finish install
3. Setup a user with 2FA enabled
4. Log out
5. Log back in
6. Enter an invalid 2FA code
7. No message will display

**Comment by driesvints** [comment]
Thanks. Seems like you sent in a PR so let's see how that goes 👍
