### ISSUE TITLE
Default tests fail with strict mode enabled

### ISSUE THREAD

**Issue by heychazza** [laravel/jetstream#1161]
- Jetstream Version: 2.12.3
- Jetstream Stack: Inertia
- Uses Teams: yes
- Laravel Version: 9.35.1
- PHP Version: 8.1.10
- Database Driver & Version: MySQL 8

### Description:
With Laravels new `Model::shouldBeStrict();` mode, it seems it has caused the default tests to fail with the following error:
```
The attribute [current_team_id] either does not exist or was not retrieved for model [App\Models\User].
```

This issue only applies when it's enabled, and I have a feeling this may be a bug with the new strict mode in general.

### Steps To Reproduce:

1. Create a fresh Jetstream application.
2. Add `Model::shouldBeStrict();` to the `AppServiceProvider`.
3. Run `php artisan test`

**Comment by driesvints** [comment]
We'd welcome a PR for this, thanks.

**Comment by heychazza** [comment]
> We'd welcome a PR for this, thanks.

I think this is a bug more so with Laravel but aren't sure, seemingly `current_team_id` exists with strict mode off but not on.

**Comment by ash-jc-allen** [comment]
I've made a PR that may (or may not) fix these tests 🙂

PR: https://github.com/laravel/jetstream/pull/1162
