### ISSUE TITLE
Teams related feature tests fails when Teams feature is disabled but has been done at jetstream installation

### ISSUE THREAD

**Issue by loicm** [laravel/jetstream#1165]
- Jetstream Version: 2.12.3
- Jetstream Stack: Livewire
- Uses Teams: no
- Laravel Version: 9.35.1
- PHP Version: 8.1.7
- Database Driver & Version: MySQL

### Description:

When Teams support has been made at Jetstream installation then disabled in config/jetstream.php, Feature tests for teams fail.

### Steps To Reproduce:

- install jetstream with `--teams`
- in `config/jetstream.php` comment the teams feature: ` Features::teams(['invitations' => true]),`
- run tests : `php artisan test`
- see that "team" tests fails

List of test files:

- `CreateTeamTest.php`
- `DeleteTeamTest.php`
- `LeaveTeamTest.php`
- `RemoveTeamMemberTest.php`
- `UpdateTeamMemberRoleTest.php`
- `UpdateTeamNameTest.php`

I added team feature verification in the tests like it already exists for API support tests.
Example in `CreateTeamTest.php`

```php
    public function test_teams_can_be_created()
    {
        if (! Features::hasTeamFeatures()) {
            return $this->markTestSkipped('Teams support is not enabled.');
        }
        
        // here untouched existing test
    }
```

Do you think a PR is needed?

**Comment by calvertyang** [comment]
I've made a PR #1167 that fix these tests.

**Comment by driesvints** [comment]
Delete these tests if you don't need them.
