### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by mbnoimi** [laravel/jetstream#1166]
Typescript became very popular these days. It used in so many huge projects.

**I suggest to support typescript version of Jetstream.**
### NOTE:
There is [a fine clone supports TS](https://github.com/iDevelopThings/vue3-jetstream-inertia-typescript) but it's one man show.

**Comment by driesvints** [comment]
Right now, we have no plans for this sorry.

**Comment by saleh-mir** [comment]
+1
