### ISSUE TITLE
Support for Passkey

### ISSUE THREAD

**Issue by kaiserkiwi** [laravel/jetstream#1172]
Hi there, i use Jetstream in pretty much all of my projects and after the release of iOS 16 I wondered if Jetstream could work with Passkey. If you're not familiar with the term, it's a new standard from Apple. https://developer.apple.com/passkeys/

But it's not exclusive to the Apple ecosystem. Microsoft and Google are working on this too, so it could be pretty soon that this will be a new thing everyone wants to have (hopefully).

So are there any plans to add Passkey to Jetstream or an additional package that plugs into Jetstream?

**Comment by driesvints** [comment]
Heya, thanks. Right now, we don't have any plans to implement this ourselves, sorry. Please see https://github.com/asbiin/laravel-webauthn if you need this.

**Comment by kaiserkiwi** [comment]
I know this was closed two years ago, but time has passed and PassKeys get more and more "normal". And still we have to manually implement it for every project. 

Do you still have no plans for this?

**Comment by renky** [comment]
I also know this is closed, but now that laravel has a first-party-webauthn package -> is it planned to integrate it into jetstream?
