### ISSUE TITLE
Password reset or Forgot Password

### ISSUE THREAD

**Issue by NewAdventure00777** [laravel/jetstream#1173]
- Jetstream Version: #.#.#
- Jetstream Stack: Inertia / Livewire
- Uses Teams: yes 
- Laravel Version: 9
- Database Driver & Version: MYSQL

### Description:
Hello, I need help with this:
How come I this error:
"Attempt to read property "currentTeam" on null" every time I click the forgot password link?"
 
This is what the server is showing:

**[C:\laravel\express\storage\framework\views\48591c79291c5a599253e4a9a3357cec814d7fdb.php : 65](phpstorm://open?file=C%3A%5Claravel%5Cexpress%5Cstorage%5Cframework%5Cviews%5C48591c79291c5a599253e4a9a3357cec814d7fdb.php&line=65)

line #65 shows:
                                        <?php echo e(Auth::user()->currentTeam->name); ?>

and all these other issues:
--Illuminate \ Foundation \ Bootstrap \ HandleExceptions : 65
handleError
--Illuminate \ Foundation \ Bootstrap \ HandleExceptions : 259
--Illuminate\Foundation\Bootstrap\{closure}
C:\laravel\express\storage\framework\views\48591c79291c5a599253e4a9a3357cec814d7fdb.php : 65
include
Laravel \ Jetstream \ Http \ Livewire \ NavigationMenu : 83
Livewire\ComponentConcerns\{closure}
Livewire \ LivewireViewCompilerEngine : 84
evaluatePath
Livewire \ LivewireViewCompilerEngine : 59
get**
-----------------------------------------------------------------

I would definitely appreciate any quick help.

Thank you guys!

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
