### ISSUE TITLE
Tailwind not detecting any classes

### ISSUE THREAD

**Issue by json39** [laravel/jetstream#1176]
- Jetstream Version: 2.12.5
- Jetstream Stack: Inertia
- Uses Teams: no
- Laravel Version: 9.38.0
- PHP Version: 8.1.5
- Database Driver & Version: MySQL 8.0.23
- OS: Windows 10

### Steps To Reproduce:
```
laravel new temp
cd temp
composer require laravel/jetstream
php artisan jetstream:install inertia
npm install
npm run dev
php artisan serve
```
[Screenshot of the welcome page after build](https://user-images.githubusercontent.com/117255287/199409725-5b2fa4cf-b244-4a59-9c51-2ee14e67763b.png)

npm run build output:

![image](https://user-images.githubusercontent.com/117255287/199409525-c1e17486-d102-46f6-9eb7-adfc06045df3.png)

**Comment by driesvints** [comment]
<img width="912" alt="Screenshot 2022-11-02 at 17 44 56" src="https://user-images.githubusercontent.com/594614/199550205-ddd46587-4a60-4a1b-9621-31dcacc32ebd.png">

**Comment by driesvints** [comment]
Seems to work fine for me.

**Comment by json39** [comment]
> Seems to work fine for me.

Oh well this definitely makes the problem go away for me. Thanks!
