### ISSUE TITLE
Tailwind not detecting any classes

### ISSUE THREAD

**Issue by json39** [laravel/jetstream#1177]
- Jetstream Version: 2.12.5
- Jetstream Stack: Inertia
- Uses Teams: no
- Laravel Version: 9.38.0
- PHP Version: 8.1.5
- Database Driver & Version: MySQL 8.0.23
- OS: Windows 10

### Description: On a brand new install of inertia, without modifying a single file after install, tailwind is not detecting *any* classes *at all*

Reopening because "works for me" does not help at all when a completely clean install with zero modifications does not work out of the box.

### Steps To Reproduce:
```
laravel new temp
cd temp
composer require laravel/jetstream
php artisan jetstream:install inertia
npm install
npm run dev
php artisan serve
```
[Screenshot of the welcome page after build](https://user-images.githubusercontent.com/117255287/199409725-5b2fa4cf-b244-4a59-9c51-2ee14e67763b.png)

npm run build output:

![image](https://user-images.githubusercontent.com/117255287/199409525-c1e17486-d102-46f6-9eb7-adfc06045df3.png)

npm run dev output:

![image](https://user-images.githubusercontent.com/117255287/199567526-525db809-e874-44c7-996f-eaff796400cd.png)

**Comment by driesvints** [comment]
I think closed an issue earlier similar to this one? If you need further help please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
