### ISSUE TITLE
JETSTREAM Livewire Fresh Install

### ISSUE THREAD

**Issue by soubverified** [laravel/jetstream#1178]
Jetstream Version: ^2.*
Jetstream Stack: Livewire
Uses Teams: no
Laravel Version: ^9.*
PHP Version: 8.0.2
Database Driver & Version:
Description:  after a fresh install, the profile page throws lots of verbose messages in browser console regarding the password confirmation modal and the update password form. 

Steps To Reproduce:
1.Fresh Start Laravel Project with laravel new project --jet. 
2. Serve the project after succesfull installation.
3. Register an account and login. 
4. After login navigate to the profile page. 
5. Turn on dev tools in browser and check for console messages.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
