### ISSUE TITLE
Jetstream Inertia --ssr Fresh Install

### ISSUE THREAD

**Issue by moedayraki** [laravel/jetstream#1179]
- Jetstream Version: ^2.12
- Jetstream Stack: Inertia
- Uses Teams: no
- Laravel Version: ^9.19
- PHP Version: 8.0.2
- Database Driver & Version:

### Description:

 ErrorException 

  file_get_contents(/Users/Dayraki/Documents/local_dev/youth-platform/config/inertia.php): Failed to open stream: No such file or directory

  at vendor/laravel/jetstream/src/Console/InstallCommand.php:712
    708▕      * @return void
    709▕      */
    710▕     protected function replaceInFile($search, $replace, $path)
    711▕     {
  ➜ 712▕         file_put_contents($path, str_replace($search, $replace, file_get_contents($path)));
    713▕     }
    714▕ 
    715▕     /**
    716▕      * Get the path to the appropriate PHP binary.

### Steps To Reproduce:

- Fresh Start Laravel Project
- Composer Require Jetstream
- php artisan jetstream:install inertia --ssr

**Comment by timacdonald** [comment]
I'm unable to replicate this. The following succeeds for me as expected:

```sh
composer create-project laravel/laravel test-repo \
    && cd test-repo \
    && composer require laravel/jetstream \
    && php artisan jetstream:install inertia --ssr

**Comment by moedayraki** [comment]
I don't know what was going on. I've noticed that inertiajs/inertia-laravel was not being required automatically. I've installed it manually and restarted the process and now it's working.

Thanks!
