### ISSUE TITLE
Do not hardcore model names

### ISSUE THREAD

**Issue by supertassu** [laravel/jetstream#118]
Currently Jetstream.php has multiple hardcoded class names:

https://github.com/laravel/jetstream/blob/89d7f8b174cd2d4eac4f063492f9db64fc935554/src/Jetstream.php#L46
https://github.com/laravel/jetstream/blob/89d7f8b174cd2d4eac4f063492f9db64fc935554/src/Jetstream.php#L230
https://github.com/laravel/jetstream/blob/89d7f8b174cd2d4eac4f063492f9db64fc935554/src/Jetstream.php#L252

Could those be made configurable so the models can be located somewhere else (in a subdirectory, for example)? Thanks!

**Comment by mallardduck** [comment]
@supertassu - I think you're overlooking the easiest way to address this issue. Extend and overwrite. There's nothing forcing you to use the `Laravel\Jetstream\Jetstream` class without customizing it and adjusting the behavior.

```
<?php


namespace App;

use App\SomeOther\Folder\User;

class MyJetstream extends \Laravel\Jetstream\Jetstream
{
    public static $userModel = User::class;

    /**
     * Get the name of the team model used by the application.
     *
     * @return string
     */
    public static function teamModel()
    {
        return 'App\\SomeOther\\Folder\\Team';
    }

    /**
     * Get the name of the team model used by the application.
     *
     * @return string
     */
    public static function membershipModel()
    {
        return 'App\\SomeOther\\Folder\\Membership';
    }
}
```

This will work just fine and all you need to change from here is to adjust your Apps `JetstreamServiceProvider` to use this implementation instead of the OOTB version shipped with the package.

**Comment by mallardduck** [comment]
@supertassu - now that #121 is merged in this should all be even easier to pull off.

I overlooked that a `useUserModel` method existed earlier, so between #119 and #121 this issue should be moot and can be set solved/closed.

Now you can simply do:

```
        Jetstream::useUserModel(App\MyStuf\Models\User::class);
        Jetstream::useTeamModel(App\MyStuf\Models\Team::class);
        Jetstream::useMembershipModel(App\MyStuf\Models\Membership::class);
```

... within the `boot` method of your apps `JetstreamServiceProvider`.

**Comment by supertassu** [comment]
Thank you @mallardduck!
