### ISSUE TITLE
DeleteAccountTest fails: No query results for model [App\Models\User]

### ISSUE THREAD

**Issue by BrandonOldenhof** [laravel/jetstream#1180]
- Jetstream Version: 2.12.3
- Jetstream Stack: Livewire
- Uses Teams: yes
- Laravel Version: 9.33.0
- PHP Version: 8.1.12
- Database Driver & Version: mysql

### Description:
The `DeleteUserForm` Livewire component deletes the user before attempting to log it out throwing a `No query results for model [App\Models\User].` error in the DeleteAccountTest.

The current code is the following:
```
        $deleter->delete(Auth::user()->fresh());

        $auth->logout();
```

### Steps To Reproduce:

1 . Enable the following features in `config/jetstream.php`:
```php
    'features' => [
        // Features::termsAndPrivacyPolicy(),
        // Features::profilePhotos(),
        // Features::api(),
        Features::teams(['invitations' => true]),
        Features::accountDeletion(),
    ],
```
2. Run `php artisan test`

### Possible solution
Update the deleteUser method in `vendor/laravel/jetstream/src/Http/Livewire/DeleteUserForm.php` to the following:
```
    public function deleteUser(Request $request, DeletesUsers $deleter, StatefulGuard $auth)
    {
        $this->resetErrorBag();

        if (! Hash::check($this->password, Auth::user()->password)) {
            throw ValidationException::withMessages([
                'password' => [__('This password does not match our records.')],
            ]);
        }

        $user = Auth::user()->fresh();
        $auth->logout();

        $deleter->delete($user);

        if ($request->hasSession()) {
            $request->session()->invalidate();
            $request->session()->regenerateToken();
        }

        return redirect('/');
    }
```

**Comment by driesvints** [comment]
I can run this test just fine in my Jetstream app.
