### ISSUE TITLE
Profile photo disk maybe should not be public

### ISSUE THREAD

**Issue by mesiarm** [laravel/jetstream#1182]
Profile photo is part of  personal information and it should not be accesible by other users or not logged-in user. It should be prevented to access profile photo different from user which is logged in.

**Comment by driesvints** [comment]
It needs to be public, otherwise the photo cannot be shown to others. You can edit the disk by changing the `jetstream.profile_photo_disk` config item.

**Comment by mesiarm** [comment]
> It needs to be public, otherwise the photo cannot be shown to others. You can edit the disk by changing the `jetstream.profile_photo_disk` config item.

HasProfilePhoto trait is not prepared for using private storage disk.

getProfilePhotoUrlAttribute in HasProfilePhoto trait should check if disk is private or public and if it is private it should check, if we are receiving profile photo url of current user and serve it through response()->file() not through Storage::disk($this->profilePhotoDisk())->url().
