### ISSUE TITLE
Banners does not get reset after a new route has been accessed.

### ISSUE THREAD

**Issue by FoksVHox** [laravel/jetstream#1204]
- Jetstream Version: 2.13.1
- Jetstream Stack: Livewire
- Uses Teams: no
- Laravel Version: 9.45.0
- PHP Version: 8.1.13
- Database Driver & Version: mysql 8.0

### Description:
When using the banners, that is explained in the documentation, they are showed when you first access the route, as expected. But when you access a new route, you'll still see the banner you set on the previous route. 

### Steps To Reproduce:

1. Set a banner on the first route
2. Access another route
3. See the banner still visible.

**Comment by jessarcher** [comment]
Hi @FoksVHox, I'm unable to reproduce this with your instructions.

Are you returning a redirect after you flash the banner on the first route, or are you returning a view?

Flash data is available during the current request _and_ the next request. If you only want it available on the current request, you can use the [`now` method](https://laravel.com/docs/9.x/session#flash-data) instead.

**Comment by FoksVHox** [comment]
@jessarcher Thanks for the explanation, I understand now.
