### ISSUE TITLE
TwoFactorAuthenticationSettingsTest failed when eloquent strict mode is enabled.

### ISSUE THREAD

**Issue by Lakshan-Madushanka** [laravel/jetstream#1220]
- Jetstream Version: 2.14.1
- Jetstream Stack: Livewire
- Uses Teams: no
- Laravel Version: 9.4.0
- PHP Version: 8.1.10
- Database Driver & Version: MySQL 8.0.30

### Description:
I decided to use eloquent strict mode in our new project but surprisingly jetstream TwoFactorAuthenticationSettingsTest failed with the following message.

![Screenshot 2023-01-15 184054](https://user-images.githubusercontent.com/47297673/212544104-c76e9c8a-758b-4c30-9ba7-1bbe009a6aec.png)

### Steps To Reproduce:

1). Setup laravel jetstream project.
2). [Enable strict mode](https://laravel.com/docs/9.x/eloquent#enabling-eloquent-strict-mode).
3. Run tests `php artisan test`

**Comment by driesvints** [comment]
You've sent in a PR so let's see how it goes.
