### ISSUE TITLE
Email Verification (Inertia Vue3): VerifyEmail.vue Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by AdamDevBone** [laravel/jetstream#1222]
- Jetstream Version: 2.14.1
- Jetstream Stack: Inertia Vue3 (v1.0.0 - did the updates as prescribed on inertiajs.com)
- Uses Teams: no
- Laravel Version: 9.47.0
- PHP Version: 8.2.1
- Database Driver & Version: MySQL 8.0.31

### Description:

I am getting the following console error (and non-display) of the VerifyEmail.vue component on {localdomain.test}/email/verify

```
useForm.ts:63 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Proxy.data (useForm.ts:63:22)
    at P.watch.immediate (useForm.ts:239:36)
    at callWithErrorHandling (runtime-core.esm-bundler.js:157:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:21)
    at job (runtime-core.esm-bundler.js:1794:17)
    at doWatch (runtime-core.esm-bundler.js:1837:13)
    at watch (runtime-core.esm-bundler.js:1671:12)
    at P (useForm.ts:236:3)
    at setup (VerifyEmail.vue:12:14)
```

The email asking to verify sends ok, and verification completes successfully after clicking that link, but in the meantime VerifyEmail.vue is blank when running Vite in `npm run dev`. It will display after `npm run build` but fires the same error when I hit `Resend Verification Email` (the `Edit Profile` and `Log Out` links work fine though).

I also get the following Vue warnings while in Vite dev mode
```
[Vue warn]: Unhandled error during execution of watcher callback 
  at <VerifyEmail jetstream=
```
```
[Vue warn]: Unhandled error during execution of setup function 
  at <VerifyEmail jetstream=
```

### Steps To Reproduce:

1. Enabled email verification via config/fortify.php
2. Implemented MustVerifyEmail in Apps/Models/User
3. Register a new user via {localdomain.test}/register

**Comment by timacdonald** [comment]
This will be addressed in the following PR: https://github.com/laravel/jetstream/pull/1219
