### ISSUE TITLE
Welcome Component Is darkmode support without providing --dark on install

### ISSUE THREAD

**Issue by RhysLees** [laravel/jetstream#1223]
- Jetstream Version: ^2.15
- Jetstream Stack: Inertia & Livewire
- Uses Teams: yes & no
- Laravel Version: ^9.19
- PHP Version: 8.2
- Database Driver & Version: Mysql

### Description:

<img width="1469" alt="image" src="https://user-images.githubusercontent.com/43909932/213027316-8f7f456b-2541-4a64-aded-47460b6fff3f.png">

### Steps To Reproduce:

Fresh install laravel Jetstream without --dark. You can optionally enable Teams and choose either stack.

login and view the Welcome component

**Comment by jessarcher** [comment]
Thanks for reporting this @RhysLees! This should be fixed with #1224.

**Comment by RhysLees** [comment]
> Thanks for reporting this @RhysLees! This should be fixed with #1224.

Thanks!
