### ISSUE TITLE
Livewire-tmp not cleaning up when I finalized my avatar

### ISSUE THREAD

**Issue by rama-adi** [laravel/jetstream#123]
- Jetstream Version: 1.0.2
- Laravel Version: 8.0.1
- PHP Version: 7.3.7
- Database Driver & Version: 10.3.16-MariaDB

### Description:
Livewire-tmp is not clearing up the temp files when I clicked 'save' on my avatar

### Steps To Reproduce:
Upload photo using the Livewire stack

![image](https://user-images.githubusercontent.com/17980909/92667985-18ef1680-f340-11ea-8ae2-6acc53590637.png)
![image](https://user-images.githubusercontent.com/17980909/92668008-26a49c00-f340-11ea-9a4f-9af7639d01d6.png)

**Comment by underwood** [comment]
I think the file cleanup is once every 24 hours. Automatic for local files, there is a configure command to run for cleanup on S3.

https://laravel-livewire.com/docs/2.x/file-uploads#auto-cleanup

**Comment by driesvints** [comment]
Please see the above.

**Comment by CarmineMM** [comment]
I have the same problem and I am not using S3.
In the documentation it says that this folder "livewire-tmp" is used with S3: https://laravel-livewire.com/docs/2.x/file-uploads#upload-to-s3
