### ISSUE TITLE
Gives error while creating new Laravel app using --jet directive

### ISSUE THREAD

**Issue by iabduul7** [laravel/jetstream#124]
- Jetstream Version: 1.0
- Laravel Version: 8.x
- PHP Version: 7.4.10
- Database Driver & Version: MYSQL & 8.0

### Description:
While creating new Laravel App with `--jet` directive it automatically gets aborted after asking which stack to use. 

### Steps To Reproduce:
run command `laravel new project-name --jet`

![image](https://user-images.githubusercontent.com/24309704/92689593-b35b5400-f358-11ea-9d88-08a7d4402a75.png)

**Comment by driesvints** [comment]
Works fine for me. Make sure you upgrade to the latest installer version.

**Comment by emveeoh** [comment]
I get the same error.

**Comment by baselbj** [comment]
It seams that the issue only occurs on PowerShell and cmd it works using  git bash

**Comment by epvdevel** [comment]
Try to update laravel installer:

```
composer global remove laravel/installer
composer global require laravel/installer
```

To check the version of the installer:

`laravel -V`

next:

`laravel new yourAppName --jet --stack=inertia or livewire`

works with cmd or git or any other... good coding ;)
