### ISSUE TITLE
back to the previous page with jetstream and fortify after login

### ISSUE THREAD

**Issue by enaeim** [laravel/jetstream#1249]
- Jetstream Version: 2.4
- Jetstream Stack: jetstrap
- Uses Teams: no
- Laravel Version: 8.65
- PHP Version: 8.0

### Description:
Hi.
How to go back to the previous page with jetstream and fortify after login? I really tried many solutions. But I did not succeed.
Tanks a lot.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by driesvints** [comment]
Also please don't open issues on multiple repos.
