### ISSUE TITLE
updateProfilePhoto() expects UploadedFile, string given

### ISSUE THREAD

**Issue by Krixx1337** [laravel/jetstream#1253]
- Jetstream Version: 3.0.0
- Jetstream Stack: Livewire
- Uses Teams: no
- Laravel Version: 10.0.0
- PHP Version: 8.1
- Database Driver & Version: mysql-server:8.0

### Description:
When I run PHPStan analysis in my project, I'm getting this error:
```
 ------ --------------------------------------------------------------------- 
  Line   Actions/Fortify/UpdateUserProfileInformation.php                     
 ------ --------------------------------------------------------------------- 
  26     Parameter #1 $photo of method App\Models\User::updateProfilePhoto()  
         expects Illuminate\Http\UploadedFile, string given.                  
 ------ --------------------------------------------------------------------- 
```

### Steps To Reproduce:
Run PHPStan and see: `php vendor/bin/phpstan analyse`

**Comment by AaronLil** [comment]
I fixed this in my project by adding an "or" statement to the parameter hint for $input, pointing to \Illuminate\Http\UploadedFile.

Line 16, from this:
```
* @param  array<string, string>  $input
```

To this:
```
* @param  array<string, string|\Illuminate\Http\UploadedFile>  $input
```

I'm not sure if this function needs a string as a parameter to work correctly, but I decided to leave the instruction there so as not to break something in the system. Maybe someone can tell us if this fix needs to be incorporated into the main code.

**Comment by driesvints** [comment]
We don't consider PHPStan errors to be bugs. Feel free to send in a PR if you want to change something 👍

**Comment by lucassimines** [comment]
Same issue here.

```
Expected type 'Illuminate\Http\UploadedFile'. Found 'string'.intelephense(1006)
Argument '1' passed to updateProfilePhoto() is expected to be of type Illuminate\Http\UploadedFile, string givenPHP(PHP0406)
@param array<string, string> $input

(parameter) string[] $input
```
