### ISSUE TITLE
In Laravel 10 Livewire can not install 

### ISSUE THREAD

**Issue by BeiAduo** [laravel/jetstream#1254]
- Jetstream Version:last version
- Jetstream Stack:  Livewire
- Uses Teams:  no
- Laravel Version: 10.0
- PHP Version: 8.2.0
- Database Driver & Version:

### Description:

 php artisan jetstream:install livewire
   INFO  Migration created successfully.  

sh: line 0: exec: composer: not found

**Comment by michaelvcolianna** [comment]
Are you using MAMP or a similar app? If so, you may need to make Composer available globally. (Possible methods at https://gist.github.com/kkirsche/5710272)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by BeiAduo** [comment]
I using MAMP PHP and brew install composer 
 
composer -vvv about
Running 2.5.3 (2023-02-10 13:23:52) with PHP 8.2.0 on Darwin / 22.3.0

I using composer install laravel and nova ,Is good !

**Comment by Akalanka1337** [comment]
@BeiAduo  How?
