### ISSUE TITLE
[3.x] Can't view:cache

### ISSUE THREAD

**Issue by kawax** [laravel/jetstream#1256]
- Jetstream Version: 3.0.0
- Jetstream Stack: Livewire
- Uses Teams: yes
- Laravel Version: 9.x
- PHP Version: 8.2
- Database Driver & Version:

### Description:
Maybe this code is not needed.
https://github.com/laravel/jetstream/blob/0f5e33b7c57954c677dcd3463703e768bda1b26b/src/JetstreamServiceProvider.php#L70

### Steps To Reproduce:

```
php artisan view:cache

Symfony\Component\Finder\Exception\DirectoryNotFoundException 

".../vendor/laravel/jetstream/src/../resources/views" directory does not exist.
```

**Comment by sirikkoster** [comment]
Same problem here

**Comment by mihob** [comment]
Same problem here

Jetstream Version: 3.0.0
Jetstream Stack: Inertia
Uses Teams: no
Laravel Version: 10.x
PHP Version: 8.1

**Comment by driesvints** [comment]
Fixed and released, thanks!
