### ISSUE TITLE
[2.x] Installation of Pest on Laravel 10 broken

### ISSUE THREAD

**Issue by joelbutcher** [laravel/jetstream#1257]
- Jetstream Version: 2.16.1
- Jetstream Stack: Inertia / Livewire
- Uses Teams: yes / no
- Laravel Version: 10.0.0
- PHP Version: 8.2.2
- Database Driver & Version: N/A

### Description:
Nuno has fixed this with #1246 but as of right now, this fix hasn't been tagged or deployed, blocking users from using  pest as their testing framework for Jetstream on Laravel 10.x

### Steps To Reproduce:
1. `composer create-project laravel/laravel:10 test && cd test`
2. `composer require laravel/jetstream:^2.16`
3. `php artisan jetstream:install inertia --pest`
4. Watch for composer to fail with:

```bash
Problem 1
    - pestphp/pest v1.22.1 requires nunomaduro/collision ^5.10.0|^6.0 -> found nunomaduro/collision[v5.10.0, v5.11.0, v6.0.0, ..., v6.4.0] but it conflicts with your root composer.json require (^7.0).
    - pestphp/pest[v1.22.2, ..., v1.22.4] require nunomaduro/collision ^5.11.0|^6.3.0 -> found nunomaduro/collision[v5.11.0, v6.3.0, v6.3.1, v6.3.2, v6.4.0] but it conflicts with your root composer.json require (^7.0).
    - Root composer.json requires pestphp/pest ^1.22 -> satisfiable by pestphp/pest[v1.22.0, ..., v1.22.4].
```

**Comment by driesvints** [comment]
I tagged v2.16.2 with this. Thanks!

**Comment by joelbutcher** [comment]
@driesvints opened and closed in record speed – love it! Thanks 😁
