### ISSUE TITLE
After enabling Team Feature, it gives error

### ISSUE THREAD

**Issue by imran300** [laravel/jetstream#126]
ErrorException
Trying to get property 'id' of non-object (View: C:\xampp\htdocs\HR\resources\views\layouts\app.blade.php) (View: C:\xampp\htdocs\HR\resources\views\layouts\app.blade.php)
http://127.0.0.1:8000/dashboard

**Comment by michaelr0** [comment]
Hey Imran300,

#108 was related to this.
To overcome this for now, you'll need to check the teams table it is likely that the user doesn't have a personal team and that you will need to create one for that user (possibly all users), set user_id as the users id, choose a name for the team and then set personal_team = 1 then visit the dashboard again and it should work.

Cheers.
