### ISSUE TITLE
Jetstream components

### ISSUE THREAD

**Issue by amihailov** [laravel/jetstream#1269]
This PR https://github.com/laravel/jetstream/pull/1118 changed the way Jetstream components are handled.

They are now copied under generic names in the view components folder.

If one installs Jetstream on an existing project it overwirtes any existing components in the project having the same name whitout any warning (same for overwriting the existing User Model or the layout files).

Basically this makes Jetstream usable only on brand new projects, otherwise it could be havoc.

Since Jetstream components / resources are package specific, they should live in their own space.

**Comment by timacdonald** [comment]
Jetstream is only meant to be installed in new applications. See the [installation documentation](https://jetstream.laravel.com/3.x/installation.html).

<img width="837" alt="Screen Shot 2023-02-22 at 9 06 46 am" src="https://user-images.githubusercontent.com/24803032/220469453-bec55a1c-edeb-41cc-8f47-71a57f1c240d.png">

**Comment by amihailov** [comment]
I know that, I've read the docs. I have used Jetstream since a while. And still, (over)writing so many generic name components in the user basic components folder whitout any prompt is wrong at some many levels...
