### ISSUE TITLE
Jetstream routes file publishing wrongly.

### ISSUE THREAD

**Issue by RohitRD31** [laravel/jetstream#127]
- Jetstream Version: 1.0.2
- Laravel Version: 8.0.0
- PHP Version: 7.4.8
- Database Driver & Version: 5.7.24 (MySql)

### Description:
When publishing jetstream routes file. File get published incorrectly. (jetstream instead of jetstream.php)

### Steps To Reproduce:

1. Run command _'php artisan vendor:publish'_
2. Select tag id of jetstream accordingly (in mine case 23)
3. file get copied from [\vendor\laravel\jetstream\routes\livewire.php] To [\routes\jetstream]
4. Check route directory
5. Fine name should be jetstream.php instead on jetstream

**Comment by driesvints** [comment]
We've merged a PR for that which we hope to tag soon: https://github.com/laravel/jetstream/pull/109
