### ISSUE TITLE
Session handling Redis

### ISSUE THREAD

**Issue by hannesClown** [laravel/jetstream#1270]
Hi,

I would like to suggest to make it possible to use Redis for session handling.
Mostly the argument it, that you don't have a real persistent layer with Redis, but the fact is, that many larger project are using Redis for session handling.
Using a database like Mysql could be a performance issue.

I don't know how to post this here:
I like jetstream and it is a great help to setup a laravel app fast! Thank you for that!

**Comment by driesvints** [comment]
Thanks! Right now we don't have plans to work on this ourselves but if you can send in a PR which we can look at we could consider it maybe.
