### ISSUE TITLE
Any (logged-in) user can accept a team invitation on behalf of the invited user

### ISSUE THREAD

**Issue by bschultz** [laravel/jetstream#1279]
- Jetstream Version: 3.0.2
- Jetstream Stack: Inertia / Livewire
- Uses Teams: yes
- Laravel Version: 9.52.4
- PHP Version: 8.1.11
- Database Driver & Version: MySQL 8.0.27

### Description:

Hi,

we are using Jetstream with Teams in our project.
During some tests we discovered, that it is possible for any (logged-in) user to accept the team invitation on behalf of the invited user if one has the signed link.
This might be an edge case and no big security issue but we are wondering if you are aware of this and if this is intended?

I guess this could/should maybe improved by checking if the logged-in user (email) is the same as the invited user (email)?

### Steps To Reproduce:

1. Invite a new user to a team with an mail address you have access to
2. Log-in with an admin user or any other existing user account different from the invited user
3. Click the link in the mail to accept the team invitation for the invited user

**Comment by driesvints** [comment]
This is indeed intended. The email is personally delivered to the target user. If you share that link then anyone can click it. If you think this should be changed feel free to attempt a PR, thanks 👍
