### ISSUE TITLE
Inertia - Expired session causes the website to be displayed in a modal

### ISSUE THREAD

**Issue by RobertBoes** [laravel/jetstream#128]
- Jetstream Version: 1.0.2
- Laravel Version: 8.0.1
- PHP Version: 7.4.7
- Database Driver & Version: mysql Ver 14.14 Distrib 5.7.29, for osx10.15
- Stack: Inertia

### Description:
When the session expires the user doesn't get redirected to the login page, but instead this page is shown as a modal. After logging in within the modal the website is shown inside the modal.

### Steps To Reproduce:
- Create a new Laravel + Jetstream project using `laravel new saas --jet --stack=inertia --teams`
- Register an account
- When logged in, open your preferred devtools and delete the `laravel_session` cookie
- Click on a link, for example in the user-dropdown click on "Profile"
- A modal is now shown with the login page
- When logging in within the modal the site will be displayed inside the modal

**Comment by SeanBourke** [comment]
Is your Jetstream/Laravel environment set to Dev or Production? -- https://inertiajs.com/error-handling

**Comment by RobertBoes** [comment]
It seems to me that doesn't matter, because that's for error pages.
What happens is the following:
- I keep the webpage open after I logged in, session has expired (or delete the cookie), which means the I'm no longer logged in
- I click on a link, for example "Profile" or "Dashboard"
- Inertia fetches the page (ex. /dashboard), this page will redirect (302) to the login page
- Since the login page is not an Inertia response it will be rendered in the Inertia "error" modal

**Comment by Wiejeben** [comment]
Related https://github.com/inertiajs/inertia-laravel/issues/57

**Comment by skattabrain** [comment]
Also having this issue, opening in a modal.

**Comment by redhedded1** [comment]
Is this a good workaround? In App\Http\Middleware\Authenticate.php
```
namespace App\Http\Middleware;

use Illuminate\Support\Facades\Request;
use Illuminate\Auth\Middleware\Authenticate as Middleware;

class Authenticate extends Middleware
{
    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return string|null
     */
    protected function redirectTo($request)
    {
        if (! $request->expectsJson() && Request::inertia()) {
            abort(409, '', ['X-Inertia-Location' => url()->route('login')]);
        } else if (! $request->expectsJson()) {
            return route('login');
        }
//        if (! $request->expectsJson()) {
//            return route('login');
//        }
    }
}
```

**Comment by driesvints** [comment]
@reinink do you might know what exactly needs to be done for this? The solution from above maybe? I didn't immediately found anything in the Inertia docs but I'm also very new to Inertia so not sure if I was looking in the right places.

**Comment by reinink** [comment]
@driesvints Happy to look into this for you. Give me a couple days.

I'm actually hoping to also submit a PR to Jetstream for some recent updates to Inertia.js as well.

I'll be in touch. 👍

**Comment by driesvints** [comment]
@reinink awesome. Thanks!

**Comment by dillingham** [comment]
Maybe a hard redirect to the login with intended redirect after would fix @reinink? 🤔
Personally would prefer not opening the login with a modal.

**Comment by reinink** [comment]
Yes, we could do an `Inertia::location($url)` visit. However, to me, the better way to fix this is using all Vue page components, instead of using any Blade views for the Inertia.js stack.

@claudiodekker has already done this work, which you can find here: #298. However, I can see that it has been tagged for the 2.x release. I don't really see how this is a breaking change though (correct me if I'm wrong @driesvints), so I actually think it would be better to just merge this into 1.x.

**Comment by driesvints** [comment]
Best to check with @taylorotwell. I do think it's a breaking change because it's simply not how the auth layer works in the current stable release. People might be caught off guard when this part of the stack changes.

**Comment by reinink** [comment]
Understood buddy! Maybe I'm just misunderstanding. My understanding is that once Jetstream is installed, all the views are published to your `/resources` folder, meaning changing this in 1.x wouldn't impact anyone currently using Jetstream. Is that wrong?

**Comment by driesvints** [comment]
The way I understand that PR is that it's required to publish the new vue views to your resources directory and included them in your auth scaffold. Maybe I'm misunderstanding 🤔

**Comment by reinink** [comment]
Yeah, you're right. You would have to publish the views again, and in that sense it doesn't fix the issue for the existing users.

Okay, let me try put a fix together for this using `Inertia::location($url)`. 👍

**Comment by akc4** [comment]
I have the same issue: https://ibb.co/68b7Jf9

**Comment by RobertBoes** [comment]
I think this issue can be closed now, as this will be fixed in the 2.x release of Jetstream since #298 is now merged into master.

This issue is caused by the the auth pages which currently return a blade view. In 2.x all of Jetstreams auth pages will be Inertia responses. When a middleware then redirects to the login page it should render correctly.

**Comment by bricehartmann** [comment]
My workaround is to use `Inertia::location` if the request is over ajax, otherwise use an old fashioned redirect.

```
if ($request->ajax()) {
    return Inertia::location(route('my-route'));
}

return redirect()->route('my-route');
```

**Comment by harri4007** [comment]
I know this is closed but I've finally pushed my project into production and this became an issue where it wasn't in development.  Here's what I did to fix it.  I placed this code in the Authenticate.php middleware and removed the default and it worked perfectly:

 `        if (! $request->expectsJson() && $request->inertia()) {
            abort(409, '', ['X-Inertia-Location' => url()->route('login')]);
        } else if (! $request->expectsJson()) {
            return route('login');
        }`

I haven't upgraded inertia yet and don't plan on it until things become more stable with the entire laravel/jetstream/inertia stack so this works for now.  Hope it helps someone!

**Comment by shahzodjonweb** [comment]
> I know this is closed but I've finally pushed my project into production and this became an issue where it wasn't in development. Here's what I did to fix it. I placed this code in the Authenticate.php middleware and removed the default and it worked perfectly:
> 
> ` if (! $request->expectsJson() && $request->inertia()) { abort(409, '', ['X-Inertia-Location' => url()->route('login')]); } else if (! $request->expectsJson()) { return route('login'); }`
> 
> I haven't upgraded inertia yet and don't plan on it until things become more stable with the entire laravel/jetstream/inertia stack so this works for now. Hope it helps someone!

Thank you so much! Worked perfect on me also!

**Comment by nemesisKO** [comment]
also as the documentation said you should add custom error pages and add some code in Exeptions/Handler to avoid this misbehavior (not exactly cause this feature meant to show to the developer )
read this to solve this issue if you are have struggling with it
[https://inertiajs.com/error-handling](url)

**Comment by matthewknill** [comment]
> 2.x release of Jetstream

This didn't work for me because it seemed like the `unauthenticated` function was not being called. I had to do this instead:

```php
/**
 * Prepare exception for rendering.
 *
 * @param $request
 * @param \Throwable $e
 * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\Response|\Symfony\Component\HttpFoundation\Response
 * @throws Throwable
 */
public function render($request, Throwable $e)
{
    $response = parent::render($request, $e);

    if ($response->status() === 419) {
        $location = $e instanceof AuthenticationException ? $e->redirectTo() : route('login');
        return response('', 409)->header('X-Inertia-Location', $location);
    }

    return $response;
}
```

**Comment by johnqiuwan** [comment]
does anyone know how to solve this using laravel 11?

**Comment by kh09211** [comment]
> does anyone know how to solve this using laravel 11?

I was able to fix my particular scenario in Laravel 11 with Fortify and Inertia/Vue. My issue was that I needed to return the user to a non-inertia page that the user was redirected to after an expired session. When they logged back in, the page was shown inside a modal. I put this in the register method of FortifySerivceProvider.php. I found part of this solution in the Fortify doc and the other part in the Inertia doc under external redirects.

```
use Laravel\Fortify\Contracts\LoginResponse;
use Inertia\Inertia;

class FortifyServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        $this->app->instance(LoginResponse::class, new class implements LoginResponse {
            public function toResponse($request)
            {
                return Inertia::location(redirect()->intended()->getTargetURL());
            }
        });
    }
    
    ...
```
