### ISSUE TITLE
php artisan vendor:publish --tag=jetstread-views

### ISSUE THREAD

**Issue by hitobias** [laravel/jetstream#1282]
- Jetstream Version: ^3.0
- Jetstream Stack:  Livewire
- Uses Teams:  no
- Laravel Version: 10
- PHP Version: 8.2
- Database Driver & Version:

### Description:
php artisan vendor:publish --tag=jetstream-views

output:

 INFO  No publishable resources for tag [jetstream-views].

**Comment by pramanikriju** [comment]
I guess then that can be removed from the [Upgrade Guide](https://github.com/laravel/jetstream/blob/3.x/UPGRADE.md) for Jetstream v3
