### ISSUE TITLE
How can I use jetstream without tailwind.

### ISSUE THREAD

**Issue by alokVishu** [laravel/jetstream#1283]
Hello,

I am looking to utilize Jetstream for my Vue 3 and Vuetify 3 projects, but I do not want to use Tailwind CSS. Can you please guide me on how to achieve this, or direct me to any documentation that explains how to remove Tailwind and integrate alternative styles and components? 

Thank you.

**Comment by driesvints** [comment]
Right now, we only offer Tailwind support.
