### ISSUE TITLE
Only have 1 button to accept invitation in email

### ISSUE THREAD

**Issue by SimonJ** [laravel/jetstream#1284]
Hey,

I think the UX is really bad when you invite a user and let's say they are 40+ years old.

The flow is:
1. Get the email
2. Create a user (that also creates a team that they don't need or want to have)
3. Find the email again and accept the invitation
4. You got redirected to the page with the message "you have accepted the invitation" 
5. You are still on your own team
6. You have to go to team settings and find the team you were invited into
7. You are on the invited team

That's really confusing I would say.

Would it be better if you just let the user accept the invite and create a user that auto-switches them to the team they got invited to?
Then if the user wants to have their own team also, they can create that.

What do you guys think of that? and is it just me with this "issue"

**Comment by driesvints** [comment]
We'd appreciate a PR that improves this experience in a non-breaking way. Thanks!
