### ISSUE TITLE
A way to change the subject of TeamInvitation

### ISSUE THREAD

**Issue by SimonJ** [laravel/jetstream#1286]
Hello,

I would like to change the subject when the team invitation is sent out. But I just wanted to make sure that it's only me that can't find out how to do it before I would make a PR to make it possible 😅

It's the /vendor/laravel/jetstream/src/Mail/TeamInvitation.php file

**Comment by driesvints** [comment]
Right now there's no easy way to override this except for overwriting the `InviteTeamMember` action. You could maybe attempt a PR to make this easier?
