### ISSUE TITLE
Team owner get all access

### ISSUE THREAD

**Issue by SimonJ** [laravel/jetstream#1287]
Hey,

When you create a new user with a team, the team owner automatically gets all access. 
That is an issue because then something like this would happen. Or am I doing something wrong?

<img width="921" alt="Skærmbillede 2023-03-29 kl  00 12 36" src="https://user-images.githubusercontent.com/183790/228378264-212a645f-ba0f-42fa-95b7-532c1baa8e26.png">

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
