### ISSUE TITLE
Jetsream allowing two factor to be enabled without scanning qr code.

### ISSUE THREAD

**Issue by bretoreta** [laravel/jetstream#1306]
### Jetstream Version

^2.12

### Jetstream Stack

Inertia

### Laravel Version

^10.0

### PHP Version

^8.1

### Description

I enabled two factor authentication for a user without scanning the qr code then after refreshing the page the application says I have two factor authentication enabled. Do remember I did nit scan the qr code so is this a potential bug? Or is there a workaround for this? Please help.

### Steps To Reproduce

Enable two factor authentication for a user then refresh the page

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
