### ISSUE TITLE
New API Projects behaviour

### ISSUE THREAD

**Issue by D4RKAR117** [laravel/jetstream#131]
First of all, i think jetstream its awesome, i will use it for sure in my future projects, but its missing something related with projects that use laravel only as an API "Base". In the past "preset none¨ was the main way to build and API without frontend related tasks, next to that laravel ui gives us the posibility of build a simple auth layout to integrate our API's but now with jetstream is missing some flexibility of do that. so its missing some flexibility in the package to build only backend projects, and this is a perfect oportunnity to achieve modularity and flexibility to the frontend scaffolding.

My proposals are:

- Give the oportunity to use fast start auth features of jetstream without frontend tasks related like an api auth command
- A new and selective way to choose wich auth feature will be builded, giving the modularity and flexibility to the package (something like vue cli prests build)

I think this are the main features that will make jestream a powerful tool for laravel and a good start point for newcomers :smile:

**Comment by driesvints** [comment]
We're already looking into things like this but it could be a while before we have anything concrete. Thanks.
