### ISSUE TITLE
Failed to load PostCSS config...

### ISSUE THREAD

**Issue by chard1988** [laravel/jetstream#1314]
### Jetstream Version

3.1.3

### Jetstream Stack

Inertia

### Laravel Version

10.10.0

### PHP Version

8.1.18

### Description

Hi, I don't know if this is a bug or just me being dumb. I tried to install jetstream with inertia stack and got this error `Failed to load PostCSS config...` Can anyone please explain what is going on with the installation as this is the first time I've encountered this.

Thank you and pardon my ignorance.

![image](https://github.com/laravel/jetstream/assets/24698545/46edb3f9-657c-4915-a6d5-7c01ee1a99f5)

### Steps To Reproduce

php artisan jetstream:install inertia --ssr

**Comment by msoubofficial** [comment]
update the postcss.config.js to this

export const plugins = {
    tailwindcss: {},
    autoprefixer: {},
};

**Comment by msoubofficial** [comment]
the same without ssr with php artisan jetstream:install inertia .

**Comment by Scaletta** [comment]
Got the same error.

**Comment by Ahmed-Al-Ebrahimy** [comment]
I got the same error!

**Comment by timacdonald** [comment]
Hey folks, I'm on it.

I somehow managed to merge https://github.com/laravel/jetstream/pull/1242 into 2.x instead of the current 3.x.

Working on a fix. Sorry about the troubles.

**Comment by timacdonald** [comment]
Fix is up. Hoping to get it merged asap.

After the install failure, if you make the changes seen in that PR, you should be right to roll.

https://github.com/laravel/jetstream/pull/1315

**Comment by msoubofficial** [comment]
wish your  PR to be merged asap, still waiting , yeah earlier figured out the issue was with tailwindcss and postcss config

**Comment by msoubofficial** [comment]
thanks btw

**Comment by timacdonald** [comment]
You are welcome.

3.2 has been tagged and resolves the issue.

**Comment by msoubofficial** [comment]
working fine
