### ISSUE TITLE
Class "Inertia\Inertia" not found when specifying liveware as the stack

### ISSUE THREAD

**Issue by jlcfly** [laravel/jetstream#1334]
### Jetstream Version

3.2.3

### Jetstream Stack

Livewire

### Laravel Version

10.14.1

### PHP Version

8.2.3

### Database Driver & Version

n/a

### Description

After installing jetstream, and running "php artisan jetstream:install livewire", "npm install" and "npm run build", "php artisan migrate", then firing up the site with "php artisan serve", it errors with: Class "Inertia\Inertia" not found.

I searched online for solutions and reinstalling multiple times to see if I made a mistake somewhere. Nothing worked. Then I looked at the config folder at jetstream.php where it had the 'stack' entry set to 'inertia'. Setting it to 'livewire' and refreshing the page made the error go away, however, I found the other issues, such as missing blade templates, so I dug further.

It appears livewire is failing to install at all, other than bringing down livewire in a composer update. I determined the failure is in the laravel/jetstream/src/Console/InstallCommand.php file in the installLivewireStack() function in the very first thing that it does.

`// Install Livewire...`
`if (! $this->requireComposerPackages('livewire/livewire:^2.11')) {`
`    return false;`
`}`

This is returning false, after successfully running Composer updates, thus failing to install the rest of the stack due to the "return false". (I put a "die" command in this conditional and it did indeed stop here, even on a brand new install with running the jetstream:install livewire for the first time.) Commenting out the return false will let the stack install, and actually does change the config/jetstream.php, add the appropriate blade templates, etc.

NOTE: I'm on Windows 11. Not sure if that makes a difference in how requireComposerPackages() works.

### Steps To Reproduce

composer create-project laravel/laravel example-app
cd example-app
_configure database in .env_
composer-require laravel-jetstream
php artisan jetstream:install livewire
php artisan migrate
php artisan serve

You could probably skip the database configuration and migrations to see the issue.
Incidentally, after "fixing" the issue and re-running "php artisan jetstream:install livewire", it resets the config/jetstream.php to the inertia stack.

**Comment by driesvints** [comment]
With these exact steps, I can't reproduce the issue.
