### ISSUE TITLE
Laravel inertia jetstram. Two factor authentication

### ISSUE THREAD

**Issue by Toylycker** [laravel/jetstream#1340]
### Jetstream Version

3.1.0

### Jetstream Stack

Inertia

### Laravel Version

10.4.1

### PHP Version

8.1.4

### Description

Laravel inertia jetstram. Two factor authentication component looks for two_factor_enabled column but it just does not exist.

const twoFactorEnabled = computed(
    () => ! enabling.value && usePage().props.auth.user?.two_factor_enabled not working
);

### Steps To Reproduce

...

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
