### ISSUE TITLE
Team not found

### ISSUE THREAD

**Issue by lstables** [laravel/jetstream#1341]
### Jetstream Version

3.2.3

### Jetstream Stack

Inertia

### Laravel Version

10.14.1

### PHP Version

8.2.8

### Database Driver & Version

MySQL 8 Homebrew

### Description

The project I am working on is pretty much a fresh project as off a couple of weeks ago, however coming to a fresh install of MacOS and reinstalling everything I find that the link for the Team Settings

```
 <DropdownLink :href="route('teams.show', $page.props.auth.user.current_team)">
      Team Settings
  </DropdownLink>
  ```
  
  Doesn't work, the error on the console is: `Ziggy error: 'team' parameter is required for route 'teams.show'.` 
  
  I have done `php artisan ziggy:generate` and `php artisan optimize:clear` several times, but still to no avail.

### Steps To Reproduce

Nothing to reproduce, just wondering why this as stopped working all of a sudden when it worked a few days ago.

**Comment by lstables** [comment]
If I dump out `$page.props.auth.user` I can see everything is there, just bizarre how this as since stopped working.

**Comment by lstables** [comment]
Nevermind, I had some stuff in there trying to make routes on the fly, removing this eliminates this issue. My bad, apologies.

**Comment by driesvints** [comment]
@lstables actually, I can reproduce this on a fresh install. Let me look into it a bit more.

**Comment by driesvints** [comment]
Ah nvm. I seeded a user without a personal team which was the reason : )

**Comment by lstables** [comment]
I tried to 

```
const navItems = [
    {
        name: 'Dashboard',
        href: route('dashboard'),
        current: route().current('dashboard'),
    },
    {
        name: 'Properties',
        href: route('properties.index'),
        current: route().current('properties.index'),
    },
    {
        name: 'Tenancies',
        href: route('tenants.index'),
        current: route().current('tenants.index'),
    },

];

```

But this seems to have been causing the problem.
