### ISSUE TITLE
Issues with `on="saved"` in the `profile/...` Blade templates when using Livewire 3.x (beta)

### ISSUE THREAD

**Issue by nexxai** [laravel/jetstream#1346]
### Jetstream Version

3.2.4

### Jetstream Stack

Livewire

### Laravel Version

10.15.0

### PHP Version

8.2.6

### Description

After loading the Livewire 3.0.0beta3 package, when browsing to a logged in user's User Profile page, we get the error:

```
Livewire \ Exceptions \ MethodNotFoundException

Unable to call component method. Public method [on] not found on component
```

My best guess as to why this is happening is that in several of the published `resources/views/profile/...` Blade components, there are references to `<x-action-message class="mr-3" on="saved">` with the `resources/views/components/action-message.blade.php` having the following code at the top:

```blade
@props(['on'])

<div x-data="{ shown: false, timeout: null }"
    x-init="@this.on('{{ $on }}', () => { clearTimeout(timeout); shown = true; timeout = setTimeout(() => { shown = false }, 2000);  })"
    x-show.transition.out.opacity.duration.1500ms="shown"
    x-transition:leave.opacity.duration.1500ms
    style="display: none;"
    {{ $attributes->merge(['class' => 'text-sm text-gray-600']) }}>
    {{ $slot->isEmpty() ? 'Saved.' : $slot }}
</div>
```

I don't know enough about how Blade, Alpine, and Livewire interact with each other to really be able to troubleshoot the problem, and I also know Livewire 3 is still in beta, but I don't see any open PRs here so I just wanted to make sure someone knew that it was happening.

I know the event system has *changed* in Livewire 3, but I still don't totally understand what that code is doing to know if that code above even has anything to do with it but I thought it looked like a good place to start.

### Steps To Reproduce

1. Install Jetstream (Livewire edition(?)) into your app
2. Pull in the Livewire 3 beta: `composer require livewire/livewire:^3.0@beta`
3. Log in to the app
4. Browse to the User Profile page (`route('profile.show')`)

The error will pop up immediately, without performing any actions.

**Comment by nexxai** [comment]
Obviously, I'm very happy to provide any other details that might help with this.

**Comment by satoved** [comment]
Try changing `@this.on(...` to @this.$on(...'

See v3 docs: https://livewire.laravel.com/docs/javascript#the-wire-object
<img width="686" alt="image" src="https://github.com/laravel/jetstream/assets/14319239/bcca8161-ec18-46d0-9f2e-c18fbe9f7faf">

As far as I can see, current Jetstream is not adapted to Livewire v3 at all, and probably won't be until the first stable Livewire release. It's better to wait.

**Comment by nexxai** [comment]
Yep, it looks like this worked.  Thanks for catching that!
