### ISSUE TITLE
emit does not exist on jetstream livewire components

### ISSUE THREAD

**Issue by julesgraus** [laravel/jetstream#1348]
### Jetstream Version

3.2.5

### Jetstream Stack

Livewire

### Laravel Version

10.16.1

### PHP Version

8.2.8 

### Description

All the Livewire classes in ```src/Http/Livewire``` need to be upgraded to be compatible with Livewire version 3.

For example. I do get this error:

```
BadMethodCallException: Method Laravel\Jetstream\Http\Livewire\UpdateProfileInformationForm::emit does not exist.
/var/www/html/vendor/livewire/livewire/src/Component.php:138
/var/www/html/vendor/laravel/jetstream/src/Http/Livewire/UpdateProfileInformationForm.php:70
/var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
/var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php:41
/var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
/var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:35
/var/www/html/vendor/livewire/livewire/src/Wrapped.php:23
/var/www/html/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php:415
/var/www/html/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php:106
/var/www/html/vendor/livewire/livewire/src/LivewireManager.php:96
/var/www/html/vendor/livewire/livewire/src/Mechanisms/HandleRequests/HandleRequests.php:85
/var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:46
/var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php:259
/var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php:205
/var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:799
/var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:141
/var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:116
/var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:798
/var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:777
/var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:741
/var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:730
/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:200
/var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:141
/var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:116
/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:175
/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:144
/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:563
/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:353
/var/www/html/vendor/livewire/livewire/src/Features/SupportTesting/SubsequentRender.php:36
/var/www/html/vendor/livewire/livewire/src/Features/SupportTesting/RequestBroker.php:30
/var/www/html/vendor/livewire/livewire/src/Features/SupportTesting/SubsequentRender.php:35
/var/www/html/vendor/livewire/livewire/src/Features/SupportTesting/Render.php:24
/var/www/html/vendor/livewire/livewire/src/Features/SupportTesting/SubsequentRender.php:34
/var/www/html/vendor/livewire/livewire/src/Features/SupportTesting/SubsequentRender.php:16
/var/www/html/vendor/livewire/livewire/src/Features/SupportTesting/Testable.php:168
/var/www/html/vendor/livewire/livewire/src/Features/SupportTesting/Testable.php:152
/var/www/html/tests/ProfileInformationTest.php:35
/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:174
```

In livewire 3, ```emit()``` was renamed to ```dispatch```. See https://livewire.laravel.com/docs/upgrading#events

Is someone working on this already?

### Steps To Reproduce

Just run the ```tests/ProfileInformationTest.php``` test when you've installed Jetstream.

**Comment by julesgraus** [comment]
In the mean time, what would be the best approach for a workaround? Should I simply make extend the problematic classes and register them in a temporary controller using a command like this? But with the extended class?

```Livewire::component('profile.update-profile-information-form', UpdateProfileInformationForm::class);```

**Comment by inmanturbo** [comment]
I'd happily submit a `PR` with changes to support `Livewire v3` however it doesn't make sense to do it against a beta tag? Jetstream installer doesn't install v3 right? the only way to encounter this error is to first install jetstream, then install livewire v3 (beta)

**Comment by julesgraus** [comment]
Thanks.
What i'm asking for is if anyone is already working on it. If not, I can do a pull request to help make it compatible for version 3. If no one is working on it, we can wait forever :). Beta 3 is somewhat what the end result is going to be, so trying to make Jetstream compatible with the beta, in my vision, seems like it will then pretty much compatible for version 3 too.

**Comment by inmanturbo** [comment]
I need this too. lol. I just haven't had time to look yet and see if i can be done in a way that won't break apps using `Livewire v2`. Because otherwise I know a PR that won't work without requiring beta tag isn't going to be even considered.

Something to consider though, if you take this on is `V3` has an upgrade command. It make be useful for this.

**Comment by inmanturbo** [comment]
@julesgraus in the meantime in the case of a `emit()`, adding a macro is an option.

```php
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        \Livewire\Component::macro('emit', function ($event) {
            $this->dispatch($event);
        });
    }
```

**Comment by kirkbushell** [comment]
> I'd happily submit a `PR` with changes to support `Livewire v3` however it doesn't make sense to do it against a beta tag? Jetstream installer doesn't install v3 right? the only way to encounter this error is to first install jetstream, then install livewire v3 (beta)

You could start it now, no problems in that. Just be aware that some further changes may be required.

**Comment by driesvints** [comment]
Hi all. We're waiting until Livewire v3 is stable. Then we'll look into a new version of Jetstream with support for it. Thanks for your patience 🙏

**Comment by julesgraus** [comment]
Ok. I’ll close this issue for now. Thanks.
