### ISSUE TITLE
Livewire V3 have been released, So I'm appreciated if you guys should support V3 of livewire

### ISSUE THREAD

**Issue by Gmk0** [laravel/jetstream#1354]

**Comment by Devsome** [comment]
@Gmk0 I think it will be started when Livewire 3 is out of beta so no duplicate work is done.

**Comment by crynobone** [comment]
Duplicate of #1348

**Comment by incon** [comment]
It would be nice to have a beta version to use, just like how Filament is doing a beta version for V3.
