### ISSUE TITLE
Docs Upgrade Guide: Prologue/Changelog/Release Notes

### ISSUE THREAD

**Issue by inmanturbo** [laravel/jetstream#1357]
It would be helpful if the project published a section in the docs with each major release similar to the "Prologue" portion of the [laravel docs](https://laravel.com/docs/10.x/upgrade) to help bring an application that was originally built using an earlier version of jetstream up to date with the latest features , etc.

For example the last major release moved all the components out of a vendor folder and directly into `resources/views/components`. which is fine, of course. But an example of something that could be a bit of head scratcher if you haven't' been following the project closely.

**Comment by driesvints** [comment]
Hi there. Jetstream has no upgrade path. It's a scaffold for new apps. You can't upgrade unless you'll manually copy all of the code again.
