### ISSUE TITLE
Unable To Find Component using Livewire Volt

### ISSUE THREAD

**Issue by achmedislamic** [laravel/jetstream#1369]
### Jetstream Version

4.0

### Jetstream Stack

Livewire

### Laravel Version

10.20

### PHP Version

8.2.9

### Database Driver & Version

MySQL 8.0.30

### Description

When using Laravel Jetstream with Volt, Volt Component can't be find. But Volt Component works if you don't use Jetstream.

### Steps To Reproduce

1. `composer create-project laravel/laravel volt`
2. in the volt directory, `composer require laravel/jetstream`
3. `php artisan jetstream:install livewire`
4. `composer require livewire/volt`
5. `php artisan volt:install`
6. Make Volt Component. Example:  `php artisan make:volt counter`
7. use Livewire's tag syntax or the @livewire Blade directive in dashboard.blade.php for the counter (Example: `@livewire('counter')`)

**Comment by achmedislamic** [comment]
![image](https://github.com/laravel/jetstream/assets/25688207/d94c99a8-d47f-47fc-8131-52a6fbf1241c)

I tried again today using PHP 8.1 and the result is still the same. The volt component can't be found. Is Livewire Volt not compatible with Jetstream yet?

**Comment by nunomaduro** [comment]
Are you able to use a Volt component, in a fresh Laravel application without jetstream?

**Comment by achmedislamic** [comment]
Yes. It appears that volt doesn't work with Jetstream installed. I already tried it with other computer as well and the result is still the same.

**Comment by nunomaduro** [comment]
Can't replicate this issue - sorry, are you able debug this in your side?

**Comment by achmedislamic** [comment]
![image](https://github.com/laravel/jetstream/assets/25688207/438118f4-8f5d-4b82-bba9-89a83184aef0)

I tried again today with WSL but it's still doesn't work. I'm sorry, because this is happen in fresh installation Jetstream & Volt, I don't know where to debug because it all happen in vendor in the stack trace and I have limited knowledge about that. This is the screenshot again with WSL. Sorry again, I don't have macbook or linux machine to test.

You can close this issue if you want and wait someone has similar cases as I did, because in my case, I don't have a concrete reason to use Volt just yet.

Sorry again with my bad english...

**Comment by nunomaduro** [comment]
You were missing the `VoltServiceProvider` class in your `config/app.php` file:

```diff
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
+        App\Providers\VoltServiceProvider::class,
        App\Providers\FortifyServiceProvider::class,
        App\Providers\JetstreamServiceProvider::class,
    ])->toArray(),
```

Typically this gets added when using the `volt:install` command, not sure what happen.

**Comment by oscarnewman** [comment]
For what it's worth -- I just ran into the same issue where `artisan volt:install` didn't add the service provider to my `config/app.php` for some reason.

**Comment by MahmoudBakheett** [comment]
in latest laravel versions you have to add ` VoltServicProvider.php ` in Providers Folder 

```
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Livewire\Volt\Volt;

class VoltServiceProvider extends ServiceProvider
{
    /**
     * Register services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        Volt::mount([
            config('livewire.view_path', resource_path('views/livewire')),
            resource_path('views/pages'),
        ]);
    }
}
```


or just artisan volt:install
