### ISSUE TITLE
issue in upload or update profile image in jetstream 4

### ISSUE THREAD

**Issue by tarun-themesbrand** [laravel/jetstream#1371]
### Jetstream Version

4.0

### Jetstream Stack

Livewire

### Laravel Version

10.21.0

### PHP Version

8.1.13

### Description

 I created new laravel project using jetstream starter with Livewire. When i enabled the profile image feature and update image there was giving error 404 for image only. all other is working fine.
 
![image](https://github.com/laravel/jetstream/assets/120155381/33018a9f-9ae5-49af-a363-44ed7ee34c31)

### Steps To Reproduce

 I created new laravel project using jetstream starter with Livewire. When i enabled the profile image feature and update image there was giving error 404 for image only. all other is working fine.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by tarun-themesbrand** [comment]
Hi, 
But it's comes everytime when creating new project in jetstream 4.0, working fine with 3.0, so i think it's a bug not a question.
Thanks.
