### ISSUE TITLE
Token Creation Error After Switching to ULID as Primary Key in Laravel Jetstream

### ISSUE THREAD

**Issue by nouart** [laravel/jetstream#1372]
### Jetstream Version

4

### Jetstream Stack

Livewire

### Laravel Version

10.21.0

### PHP Version

8.1.2

### Database Driver & Version

10.4.22-MariaDB

### Description

I have installed a fresh Laravel Jetstream application, and I want to use ULID instead of the default 'id' column as the primary key. Everything works perfectly, except when I try to create an API token, I encounter the following issue:

`Illuminate\Database\QueryException
SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value
insert into `personal_access_tokens` (`name`, `token`, `abilities`, `expires_at`, `tokenable_id`, `tokenable_type`, `updated_at`, `created_at`) values (koukou, 1855b90e04d6c7ce750dcb6fac0034faf201089a733da11225155b3c6cbba6a9, ["read","create"], ?, 01h96tkc3qw3t16edhzkn05j90, App\Models\User, 2023-09-01 07:34:49, 2023-09-01 07:34:49)
`

I have modified the migration as follows:

`  public function up(): void
    {
        Schema::create('personal_access_tokens', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulidMorphs('tokenable');
            $table->string('name');
            $table->string('token', 64)->unique();
            $table->text('abilities')->nullable();
            $table->timestamp('last_used_at')->nullable();
            $table->timestamp('expires_at')->nullable();
            $table->timestamps();
        });
    }`

For your information, I have also installed another fresh Laravel Jetstream application without changing the default 'id' column, and everything works without any issues.

### Steps To Reproduce

The application worked perfectly after changing the default ID to ULID, except for the token-related functionality.
The table "personal_access_token" in the database structure is displayed in the image.

![Capture d’écran 2023-09-01 092731](https://github.com/laravel/jetstream/assets/9932874/da047b3c-9782-403a-8862-2d2d23f56ca9)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by nouart** [comment]
After conducting some tests, I believe the solution consists of not changing the 'id' to 'ulid' in the 'personal_access_tokens' migration. Perhaps Jetstream doesn't support ulid in this part.
Now my migration is as follows:
 ```
         public function up(): void
            {
                Schema::create('personal_access_tokens', function (Blueprint $table) {
                    $table->id();
                    $table->ulidMorphs('tokenable');
                    $table->string('name');
                    $table->string('token', 64)->unique();
                    $table->text('abilities')->nullable();
                    $table->timestamp('last_used_at')->nullable();
                    $table->timestamp('expires_at')->nullable();
                    $table->timestamps();
                });
            }
```

> The issue is now solved, and I can create API tokens and manage permissions.
