### ISSUE TITLE
unreachable code after return statement

### ISSUE THREAD

**Issue by morceaudebois** [laravel/jetstream#1374]
### Jetstream Version

4.0

### Jetstream Stack

Livewire

### Laravel Version

10.10

### PHP Version

8.1

### Description

After a fresh install of Jetstream, I get these two errors in the console:
<img width="629" alt="image" src="https://github.com/laravel/jetstream/assets/50768582/752c231f-df39-4d07-b6ef-b57aec7a1374">

They seem to only appear when Livewire is active and only in Firefox.

### Steps To Reproduce

1. Install Jetstream
2. Get to a page, like the dashboard, where Livewire is active

**Comment by crynobone** [comment]
See https://github.com/livewire/livewire/discussions/6434
