### ISSUE TITLE
Upgrade to v4.0 or 3.1 in laravel 9.52

### ISSUE THREAD

**Issue by fbmfbm** [laravel/jetstream#1375]
### Jetstream Version

3.02

### Jetstream Stack

Inertia

### Laravel Version

9.52

### PHP Version

8.1.2

### Description

 illuminate/support conflit from laravel 9 and jetstream > 3.1 depencies   on composer update.

 
```
 Only one of these can be installed: illuminate/support[v5.5.0, ...,
 - Root composer.json requires laravel/framework ^9.0 -> satisfiable by laravel/framework[v9.0.0-beta.1, ..., 9.x-dev].
 - Root composer.json requires laravel/jetstream ^3.1 -> satisfiable by laravel/jetstream[v3.1.0, ..., 3.x-dev].
```

### Steps To Reproduce

composer update

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by crynobone** [comment]
Both version 3 and 4 requires Laravel 10.
