### ISSUE TITLE
Failure to close parentheses, causes error when accessing "Team Settings"

### ISSUE THREAD

**Issue by doguskysilva** [laravel/jetstream#138]
- Jetstream Version: 1.1.0
- Laravel Version: 8.0.3
- PHP Version: 7.4.9

### Description:
When acess que page "Team Settings" using the Jeststream with Liveware return the error 

syntax error, unexpected ';', expecting ')' (View: /path/resources/views/teams/team-member-manager.blade.php) (View: /path/resources/views/teams/team-member-manager.blade.php)

I solved it by closing the parentheses in line 13 of file team-member-manager.blade.php

### Steps To Reproduce:

Follow installation
https://jetstream.laravel.com/1.x/installation.html

After logged try open "Team Settings"

**Comment by bonzai** [comment]
Fixed by #140.
