### ISSUE TITLE
Jetstream uses abandoned jenssegers/agent package

### ISSUE THREAD

**Issue by almazdanilov** [laravel/jetstream#1386]
### Jetstream Version

4.0.3

### Jetstream Stack

Livewire

### Laravel Version

10.4.1

### PHP Version

8.2

### Description

Jetstream uses abandoned "jenssegers/agent": "^2.6".
As a result Laravel can't detect new mobiles since 2020.
As example, phattarachai/laravel-mobile-detect is actual.
Please consider to change Agent in new releases.
Thanks.

### Steps To Reproduce

Open composer.json and watch for "require" section.

**Comment by driesvints** [comment]
> As a result Laravel can't detect new mobiles since 2020.

Can you please explain why you believe this?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.

**Comment by klasenma** [comment]
Hey, 

we experience this too since today; `$agent->isMobile()` always returns true for us. There's also a [current issue](https://github.com/jenssegers/agent/issues/207) in the agent package. But as their last commit is from January 2021, it seems like they abandoned the package.

**Comment by pengkong** [comment]
It should be noted that Jetstream has dropped usage of the jenssegers/agent package in v5.x and is now using mobiledetect/mobiledetectlib directly.
