### ISSUE TITLE
Laravel Multi tenancy

### ISSUE THREAD

**Issue by seph-eshipbpo** [laravel/jetstream#1387]
### Jetstream Version

4

### Jetstream Stack

Inertia

### Laravel Version

10

### PHP Version

8.1

### Database Driver & Version

mysql 8

### Description

previous version does not support laravel multi-tenancy. does this version support laravel multi-tenancy using tenancy for laravel?

### Steps To Reproduce

just verification if this version now support tenancy for laravel

**Comment by driesvints** [comment]
We don’t specifically support multitenancy sorry
