### ISSUE TITLE
Unable to find component: [navigation-menu]

### ISSUE THREAD

**Issue by CyberPunkCodes** [laravel/jetstream#1389]
### Jetstream Version

4.0.3

### Jetstream Stack

Livewire

### Laravel Version

10.28.0

### PHP Version

8.2.9

### Database Driver & Version

11.0.2-MariaDB - Homebrew

### Description

Following the steps on the [docs](https://jetstream.laravel.com/installation.html#install-jetstream-with-livewire), the navigation menu can't be found.

I have a version 3.3.0 app (jetstream + livewire) and it didn't do this during install. It seems to be introduced in v4.

Removing `@livewire('navigation-menu')` in the app layout removes the error and the page loads fine. However, of course, the navigation menu isn't there lol.

I took a look in the jetstream code and the `navigation-menu` view and `NavigationMenu` components are still there.

I am unaware of the code changes from 3 to 4 to be efficient at pinning down where the issue is. It's almost as if the `@livewire()` directive is not looking in the correct place(s)?

### Steps To Reproduce

```bash
composer create-project laravel/laravel laravel.test

cd laravel.test

composer require laravel/jetstream

php artisan jetstream:install livewire

npm install
npm run build
php artisan migrate
```

PS: I can confirm that I just tried again using jetstream 3.3.3 and didn't have this issue. It is something with jetstream v4 or possibly livewire v3. jetstream 3.3.3 installed livewire 2.12 but I think jetstream v4 is installing livewire v3.x (not sure exact version).

**Comment by andrewdwallo** [comment]
I just started having this issue saying all of my components could not be found (although I am using a different package)... But all the logic and code are basically the same. I'm confused. Some update in Livewire maybe?

**Comment by andrewdwallo** [comment]
@CyberPunkCodes Roll back to `livewire v3.0.8` and check and see if everything works fine. It did for me. So, I think it's the latest release (v3.0.9).

**Comment by CyberPunkCodes** [comment]
@andrewdwallo Thank you for your reply. FWIW 3.0.8 did the trick. I can't believe nobody has created an issue there for it. I of course looked over there.. and everywhere.

I lost a couple hours all on a side tangent. I wanted to add [Livewire Alerts](https://livewire-alert.jantinnerezo.com/) to my project and my alerts were formatted oddly. Doesn't look like his on his demo page. I realized my laravel app (with jetstream + livewire) was running livewire 2.12 and not 3. So I was attempted to quickly pop up a test laravel/jetstream/livewire app and see if the issue was because of livewire v2. My app uses Boostrap 5 not Tailwind, so was trying to determine if my css was causing issues. Shouldn't because he has everything prefixed, but you never know...  Turns out it wasn't so quick after all lol.

Looks like this can be closed.

**Comment by andrewdwallo** [comment]
@CyberPunkCodes I believe it is this PR that caused it: https://github.com/livewire/livewire/pull/7076

I honestly wouldn't have closed this issue though considering every single Jetstream application will now have issues if Livewire doesn't fix it. So, I wouldn't be surprised if this isn't addressed again shortly.

**Comment by CyberPunkCodes** [comment]
@andrewdwallo Fair point. I will re-open this issue for the sole purpose of making this visible to others, and preventing others from creating a duplicate issue here. So they can follow it. Hopefully the mods allow this to stay open until it's resolved on the other end.

I also have a bug discussion over there: [https://github.com/livewire/livewire/discussions/7093](https://github.com/livewire/livewire/discussions/7093)

**Comment by andrewdwallo** [comment]
Sounds good 👌🏻

**Comment by mavespiritu** [comment]
confirmed. it's the livewire 3.0.9. I tried reverting to 3.0.8 and everything worked.

**Comment by driesvints** [comment]
Seems Caleb already reverted this. Thanks all.
