### ISSUE TITLE
Form validation errors not displayed on Register.vue

### ISSUE THREAD

**Issue by zhongruige** [laravel/jetstream#1393]
### Jetstream Version

4.0

### Jetstream Stack

Inertia

### Laravel Version

10.29.0

### PHP Version

8.2.11

### Description

Hi there--

I just did a fresh install of the latest Jetstream and Laravel using the inertia stack. I noticed that the error messages aren't showing on the register form as they used to on previous versions. I was able to fix this using `defineProps({ errors: Object })` and update the fields from `form.errors` to `errors` but wanted to note this issue here, too. It seems like the email field error returns as expected, just not the password errors.

### Steps To Reproduce

On a fresh install (using the Inertia stack), register a user with any password that doesn't meet the requirements. Click to register and note that the error doesn't show:

<img width="503" alt="Screenshot 2023-10-30 at 1 31 59 PM" src="https://github.com/laravel/jetstream/assets/71906536/baf7fb20-f2c2-4e47-8279-4388b82cfbc3">

To verify the errors are being caught as expected and just not displayed, add `defineProps({ errors: Object })` and update the input errors from `form.errors` to `errors`. Try and register again and note that the password error is now showing:

<img width="537" alt="Screenshot 2023-10-30 at 1 31 31 PM" src="https://github.com/laravel/jetstream/assets/71906536/5748dc7b-9c97-4371-ae47-0af89c1126ad">

**Comment by crynobone** [comment]
The https://inertiajs.com/forms#form-helper documentation seems to suggest current usage is already correct.

**Comment by jessarcher** [comment]
This issue exists on Breeze as well.

It only happens with the latest version of Inertia because of [this change](https://github.com/inertiajs/inertia/pull/1568) and because we're calling `form.reset` to clear the password fields:

```js
    form.post(route('register'), {
        onFinish: () => form.reset('password', 'password_confirmation'),
    });
```

I will chat with @reinink to confirm whether we should fix it in Inertia or Jetstream and Breeze.

**Comment by jessarcher** [comment]
I've reverted the change in Inertia and released v1.0.14.

**Comment by zhongruige** [comment]
> I've reverted the change in Inertia and released v1.0.14.

Thanks so much for the quick turn around on this @jessarcher! Appreciate it. Fix worked great for me 🙌 

<img width="489" alt="Screenshot 2023-11-01 at 7 49 42 AM" src="https://github.com/laravel/jetstream/assets/71906536/0ff57bdd-0f26-431f-b3bc-80aed2a9ffa1">

**Comment by JackHardy** [comment]
@jessarcher I am currently having this same issue using inertiajs/ineria-laravel and laravel-precognition-vue-inertia. Should the PR above have rectified this too? (or is this a me issue)

**Comment by jessarcher** [comment]
@JackHardy It should have, yeah. Are you able to replicate the issue on a minimal clean install?

**Comment by JackHardy** [comment]
@jessarcher False alarm; apologies.
