### ISSUE TITLE
mobiledetect/mobiledetectlib 2.8.42 requires php 5.6.*

### ISSUE THREAD

**Issue by pascallieverse** [laravel/jetstream#1394]
### Jetstream Version

3.3.3

### Jetstream Stack

Inertia

### Laravel Version

10.30.0

### PHP Version

8.1.4

### Description

Jetstream requires jenssegers/agent that is not updated anymore and should be replaced.

The package jenssegers/agent requires serbanghita/Mobile-Detect wich pushed an update in v2.*.* that changed the php require from ```>=5.0.0``` to ``` "5.6.*" ```  wich breaks jetstream on newer php versions.

https://github.com/serbanghita/Mobile-Detect/commit/091c628c164f920dedd512b3100bf485b9371c6b

### Steps To Reproduce

Run a composer update

**Comment by driesvints** [comment]
Yeah we should replace it. But I'm not sure what the best way is to do so.

**Comment by driesvints** [comment]
I saw you're using Jetstream v3 which we don't support any longer. Does the same thing happen on Jetstream 4.x?

Also: I can't get mobiledetect/mobiledetectlib v2.8.42 to install at all. Composer correctly installs v2.8.41 for me so I'm not sure there's an issue at all? 

For Jetstream v5 we should definitely look into replacing jenssegers/agent but for now everything seems to work properly?

**Comment by pascallieverse** [comment]
Hi @driesvints,

Correct, because we can't upgrade to livewire 3 yet. I just created a new laravel 10 project with jetstream 4 to track it down and its also an issue there.

Because we use horizon we used --ignore-platform-reqs on a windows machine and that also causes mobiledetect/mobiledetectlib version 2.8.42 to install instead of 2.8.41.  So this should be fixable if we don't use the ingore of course. 

Still I think its better that the package get indeed replaced in V5.

**Comment by crynobone** [comment]
You should be able to ignore specific extensions: https://php.watch/articles/composer-ignore-platform-req

**Comment by pascallieverse** [comment]
Yes we are doing that now.

**Comment by serbanghita** [comment]
My bad, I've upgraded dependencies in composer.json from php 5.3 to 5.6 because I couldn't get composer 1.x to work on a [Docker image](https://github.com/serbanghita/Mobile-Detect/blob/2.8.x/docker-compose.yml) that helps me with local dev. 

Would it help if I release 2.8.43 and go back to the old way?

```
    "require": {
        "php": ">=5.0.0"
```

Also, would it help if I find out if `jenssegers/agent` can be pushed further or possibly replaced by some other library?
It seems like I already had this request in my queue https://github.com/serbanghita/Mobile-Detect/issues/940

**Comment by serbanghita** [comment]
@pascallieverse short term solution, I've fixed this in https://github.com/serbanghita/Mobile-Detect/releases/tag/2.8.43

@pascallieverse long term, what do you need exactly? Do you need to get exact versions of the operating system, browser, etc.?

**Comment by serbanghita** [comment]
@driesvints last question is for you as well

**Comment by pascallieverse** [comment]
Thank you @serbanghita, This fixes the issue about the requirement of php 5.6.

In the long term the agent package needs to be replaced inside this package, the agent package requires an old version of your package and is not updated anymore.

**Comment by driesvints** [comment]
> Because we use horizon we used --ignore-platform-reqs on a windows machine

@pascallieverse We can't account for that sorry.

> Would it help if I release 2.8.43 and go back to the old way?

@serbanghita yes that would help! Thanks for considering.

> long term, what do you need exactly? Do you need to get exact versions of the operating system, browser, etc.?

@serbanghita long term we need to replace jenssegers/agent with a viable alternative but I haven't found one yet. We might need to copy the class into Jetstream.

**Comment by driade** [comment]
Hi. As far as I discovered today jenssegers/agent is broken since > 2.8.41

https://github.com/jenssegers/agent/pull/208

Hope it helps.
