### ISSUE TITLE
Jetstream does not show the profile picture

### ISSUE THREAD

**Issue by drfcozapata** [laravel/jetstream#1395]
### Jetstream Version

4.0.5

### Jetstream Stack

Inertia

### Laravel Version

10.30.1

### PHP Version

8.1

### Database Driver & Version

MySQL 8.0.35 for Ubuntu 22.04

### Description

I I have developed a monolith with Laravel, JetStream, Inertia and Vue. Until last week everything was working fine when loading and using the profile picture in the app. 
For other reasons, I had to do an installation from scratch and migrate the components that I had already done, but now it shows the preview of the profile picture, saves it in the DB, but does not show it after saving.
I did another 2 new installations using "Laravel new" and the result is the same.
Did you change something in the scafolding that is affecting this bug?

### Steps To Reproduce

1. Create a new Laravel-Jetstream-Inertia project.
2. Uncomment line 62 in 'jetstream.php' file to allow use profile photo.
3. Try to upload an use the profile photo.

**Comment by crynobone** [comment]
![CleanShot 2023-11-02 at 10 58 57](https://github.com/laravel/jetstream/assets/172966/0614ba76-e86c-4b3f-8f7b-902da24f91db)

Unable to replicate the issue. The only think I could see is that I need to change `APP_URL=http://127.0.0.1:8000` since I'm using `artisan serve`.

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by drfcozapata** [comment]
Mior, thank you for your reply!

I had forgotten to set APP_URL=http://127.0.0.1:8000. I created a new
project from scratch and it works fine.

However, despite having made the change, it still does not work in my
project. I don't know if it has something to do with the fact that I
changed the data and no longer ask for name, but first_name and last_name
separately.

I will check it again to see what could be happening.
Thank you very much!

[image: image.png]


[image: Dr. Francisco Zapata] <https://linkedin.com/in/drfcozapata> *Francisco
Zapata*

Vue.js Fullstack Web Developer Jr
[image: https://t.me/drfcozapata] <https://t.me/drfcozapata> [image:
https://wa.me/584120918548] <https://wa.me/584120918548> [image:
https://twitter.com/drfcozapata] <https://twitter.com/drfcozapata> [image:
https://linkedin.com/in/drfcozapata]
<https://linkedin.com/in/drfcozapata> [image:
https://github.com/drfcozapata] <https://github.com/drfcozapata>
+58 412 0918548Puerto Ordaz, Bol, Venezuela

**Comment by crynobone** [comment]
Feel free to create a new issue with reproducing steps if you can recreate the issue based on the existing project.
