### ISSUE TITLE
update jetstream to 4.1 got Target class [Jenssegers\Agent\Agent] does not exist.

### ISSUE THREAD

**Issue by stephanus-tantiono** [laravel/jetstream#1402]
### Jetstream Version

4.1.0

### Jetstream Stack

Livewire

### Laravel Version

10.2.8

### PHP Version

8.2.1

### Database Driver & Version

mysql

### Description

Hai, Im trying to do composer update from 4.0 to 4.1 and got error 
 Target class [Jenssegers\Agent\Agent] does not exist.

### Steps To Reproduce

composer update jetstream to 4.1

**Comment by driesvints** [comment]
This class was removed from Jetstream. How are you calling this class?

**Comment by stephanus-tantiono** [comment]
I try search on vendor folder, and it's exist at ```vendor\laravel\jetstream\src\Http\Controllers\Inertia\UserProfileController.php``` and ```vendor\laravel\jetstream\src\Http\Livewire\LogoutOtherBrowserSessionsForm.php```

**Comment by driesvints** [comment]
Yes it was removed. If you were using this dependency directly you should add it to your composer.json file.
