### ISSUE TITLE
Ability to configure component view path

### ISSUE THREAD

**Issue by nathan-io** [laravel/jetstream#1404]
I was reviewing the 2.x-3.x upgrade guide and realize that we're blocked from upgrading until we move or rename multiple components.

Related issues have been opened before: https://github.com/laravel/jetstream/issues/1364 and https://github.com/laravel/jetstream/issues/1377

While I can appreciate @jessarcher 's argument in [#1364](https://github.com/laravel/jetstream/issues/1364), I don't believe that all scenarios are being considered.

In our case for example, we have an app which uses Nova (for admins), Jetstream (for authenticated users), and a "brochure website" for guests with our bespoke components, based on the company's brand guides and design systems.

The visual contrast between the dashboard and the frontend site is intentional, and a requirement in our case.

Something else to consider is that developers may want to organize different types of components into separate folders, rather than having modals, inputs, headings, and more in one place.

While it may not be possible or practical to separate the different types of Jetstream components, would it be a problem to offer a config option to define a custom component folder path?

**Comment by driesvints** [comment]
Hi there, unfortunately these changes were made deliberately and we're currently not considering adding such an option, sorry.
