### ISSUE TITLE
Jetstream with Inertiajs Vue banner not hide

### ISSUE THREAD

**Issue by majweb** [laravel/jetstream#1408]
### Jetstream Version

4

### Jetstream Stack

Inertia

### Laravel Version

10

### PHP Version

8.1

### Database Driver & Version

MYSQL

### Description

When I send a request
return redirect()->back()->banner('added.');

in the Banner.vue file this piece of code
onMounted(() => {
    setTimeout(() => { show.value = false; }, 2000)
}) only works when the component is being rendered, not when there is an action. The Banner component does not disappear after 2 seconds.

### Steps To Reproduce

d

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
