### ISSUE TITLE
Auth stubs from Laravel/UI

### ISSUE THREAD

**Issue by alexpritchard-sonin** [laravel/jetstream#141]
Include the Auth stubs, so can publish vendor assets for bits like the auth controllers.

**Comment by driesvints** [comment]
No plans for this.

**Comment by nerdalertdk** [comment]
Would be nice, don't need limewire, Inertia

To get an working auth controller I now have to pull Laravel 7 and copy over the old Auth controller.

**Comment by driesvints** [comment]
You can just use the livewire stack which is basically just Blade view files.
