### ISSUE TITLE
Class Name Conflicts - Actions

### ISSUE THREAD

**Issue by DerekBuntin** [laravel/jetstream#1413]
### Jetstream Version

4.0

### Jetstream Stack

Livewire

### Laravel Version

10.33

### PHP Version

8.2

### Description

The action

`DeleteUserWithTeams.php` 

Has a class name of 'DeleteUser', which conflicts with the action

`DeleteUser`

Therefore the action 'DeleteUserWithTeams.php' should have its class name changed to match the file name 'DeleteUserWithTeams'

I hope this helps.

### Steps To Reproduce

View the Jetstream Actions located at either:

`stubs/app/Actions/DeleteUser.php`
`stubs/app/Actions/DeleteUserWithTeam.php`

And review the class names.

**Comment by crynobone** [comment]
The files are only used when installing Jetstream and exported based on whether you choose installation with or without team options.
