### ISSUE TITLE
Dropdown menu doesn't work. Alpine missing.

### ISSUE THREAD

**Issue by anastis** [laravel/jetstream#1420]
### Jetstream Version

4.2

### Jetstream Stack

Livewire

### Laravel Version

10.38.0

### PHP Version

8.1.13

### Description

The dropdown menu on the dashboard page doesn't respond to clicks.
It appears that Alpinejs is not loaded. Adding `<script src="//unpkg.com/alpinejs" defer></script>` in `layouts/app.blade.php` fixes it.

### Steps To Reproduce

Install laravel per instructions.
Install jetstream with livewire with alpine, per instructions.
Run npm install & build, artisan migrations.
Register a user.
Login with user.
Menu on the top right doesn't work.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by crynobone** [comment]
Tested this on a fresh installation and everything working as expected:

![CleanShot 2023-12-20 at 20 23 52](https://github.com/laravel/jetstream/assets/172966/be4cc460-b324-4050-badb-6868da098486)
