### ISSUE TITLE
Most forms don't work

### ISSUE THREAD

**Issue by anastis** [laravel/jetstream#1421]
### Jetstream Version

4.2

### Jetstream Stack

Livewire

### Laravel Version

10.38.0

### PHP Version

8.1.13

### Description

It appears that the (logged in) dashboard forms and form elements don't work.

In the profile page:

- Name & email are not pre-populated. Entering new values and pressing Save, submits the form (triggers a refresh anyway) but the information is not stored in the database.
- Changing the password doesn't work either.
- 2FA, Browser Sessions, and Delete Account buttons do nothing.

If you also enable the API page, creating a new API token does nothing.

### Steps To Reproduce

In a clean install, after making the menu work ( #1420 ) visit the profile page.

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by crynobone** [comment]
Unable to replicate the issue on fresh installation:

![CleanShot 2023-12-20 at 20 23 52](https://github.com/laravel/jetstream/assets/172966/be4cc460-b324-4050-badb-6868da098486)
