### ISSUE TITLE
Change 'Profile Photo' to 'Profile Picture' or 'Avatar'

### ISSUE THREAD

**Issue by mho22** [laravel/jetstream#1425]
By default, using an icon as a profile picture, I was wondering if the Jetstream team would be interested in a small pull request regarding this.

Photo | Avatar | Image | Picture 

It's mainly a question, and I'd be glad to contribute if my suggestion could be useful for the team. 

What are your thoughts on this?

**Comment by driesvints** [comment]
Thanks but right now we don't have plans for this sorry.
