### ISSUE TITLE
Updating the password will log out the user if config jetstream.guard is `web`

### ISSUE THREAD

**Issue by mho22** [laravel/jetstream#1426]
### Jetstream Version

4.2

### Jetstream Stack

Inertia

### Laravel Version

10.10

### PHP Version

8.2.9

### Description

When I modify the guard in config file `jetstream` as `web` instead of `sanctum`. And modify the middleware in the route file `web.php` : 

```
Route::middleware( [ 'auth:web', config('jetstream.auth_session'), 'verified' ] )->group(function () 
{
    Route::get( '/dashboard', fn() => Inertia::render( 'Dashboard' ) } )->name( 'dashboard' );
} );
```

Everything works fine, until I decide to modify the password. When modifiying the password, Jetstream will launch an event `PasswordUpdatedViaController`. This one is handled by 'Inertia' in the `bootInertia()` method.

```       
Event::listen( function( PasswordUpdatedViaController $event ) 
{
    if( request()->hasSession() ) 
    {
        request()->session()->put( [ 'password_hash_sanctum' => Auth::user()->getAuthPassword() ] );
    }
} );
```

This hardcodes the guards password hash update into `password_hash_sanctum`. Resulting on a conflict between the new password set on `password_hash_sanctum` and the previous on `previous_hash_web`. `password_hash_sanctum` shouldn't exist in that case.

A PR could be made to replace : 

```
request()->session()->put( [ 'password_hash_sanctum' => Auth::user()->getAuthPassword() ] );
```

with 

```
request()->session()->put( [ 'password_hash_'.config('jetstream.guard') => Auth::user()->getAuthPassword() ] );
```

or

```
request()->session()->put( [ 'password_hash_'.Auth::getDefaultDriver() => Auth::user()->getAuthPassword() ] );
```

 like in `jetstream/src/Http/Livewire/UpdatePasswordForm.php` [ much cleaner ]

Should I go ahead and submit that pull request if needed?

### Steps To Reproduce

1. Create fresh Jetstream Inertia project

2. modify file `config/jetstream.php` 

```
//before

'guard' => 'sanctum',

//after

'guard' => 'web',
```

3. modify file `routes/web.php`
```
//before 

Route::middleware( [ 'auth:sanctum', config( 'jetstream.auth_session' ), 'verified' ] )->group( function()
{
    Route::get( '/dashboard', fn() => Inertia::render( 'Dashboard' ) )->name( 'dashboard' );
});

//after

Route::middleware( [ 'auth:web', config( 'jetstream.auth_session' ), 'verified' ] )->group( function()
{
    Route::get( '/dashboard', fn() => Inertia::render( 'Dashboard' ) )->name( 'dashboard' );
});
```

4. Register and modify password.

**Comment by driesvints** [comment]
Yeah, feel free to attempt a PR 👍

**Comment by mho22** [comment]
@driesvints The pull request I submitted was closed by the captain, so I'm leaving the workaround here for artisans who might encounter the same error as I did : 

`app/Providers/JetstreamServiceProvider.php`


```
use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Event;
use Laravel\Fortify\Events\PasswordUpdatedViaController;
use Illuminate\Support\Facades\Auth;

class JetstreamServiceProvider extends ServiceProvider
{
    public function boot() : void
    {
        Event::listen( function( PasswordUpdatedViaController $event )
        {
            if( request()->hasSession() ) request()->session()->put( [ 'password_hash_'.config( 'jetstream.guard' ) => Auth::user()->getAuthPassword() ] );
        });
    }
} 
```


It is, in fact, the outcome of the closed pull request, but it has been rewritten in the `JetstreamServiceProvider` overlay file.

**Comment by driesvints** [comment]
Yeah, it seems we're not making any changes here sorry.

**Comment by mho22** [comment]
Hi @driesvints, sorry to bother you with this. I thought this issue would be pointless with Laravel 11, but it seems if `sanctum` is no more added by default, should this mean `sanctum` must be used with `jetstream` ?

**Comment by driesvints** [comment]
@mho22 no bother at all. Sanctum is very much needed for Jetstream but only if you need api tokens.

**Comment by mho22** [comment]
@driesvints Thank you for your reactivity, so I suppose this issue will happen again if `jetstream` is used without `sanctum`. Should I suggest another PR or keeping the workaround above? Thank you for your hard work.

**Comment by driesvints** [comment]
I'd just never modify the guard as it's not needed. Not even with Inertia.
