### ISSUE TITLE
Stack links in documentation result in 404

### ISSUE THREAD

**Issue by tvbeek** [laravel/jetstream#1428]
### Jetstream Version

4.x

### Jetstream Stack

Livewire

### Laravel Version

-

### PHP Version

-

### Description

On the documentation site https://jetstream.laravel.com/ there are 2 links for the Stack Features in the menu on the left.

![image](https://github.com/laravel/jetstream/assets/2026498/ac0fc00f-9769-4c18-9d6e-c7adf9af3ff0)

They link to: https://jetstream.laravel.com/stacks/livewire and https://jetstream.laravel.com/stacks/inertia but both result in a 404 Not Found page from nginx.

After visiting Stacks url https://jetstream.laravel.com/stacks/ (this isn't linked but an educated guess) I see that the working links are: https://jetstream.laravel.com/stacks/livewire.html and https://jetstream.laravel.com/stacks/inertia.html

I suspect those pages need to work without the .html extension 😃 

I didn't create a PR because I don't where (and how) to fix it.

### Steps To Reproduce

1. Go to the documentation site: https://jetstream.laravel.com/
2. Click on one of the links below Stack Features in the left menu.
3. See a 404

**Comment by driesvints** [comment]
Thanks @tvbeek. We're looking into this.

**Comment by driesvints** [comment]
So it seems these work fine as long as you don't open them in a new tab. Just directly click them and all is good.

**Comment by driesvints** [comment]
Actually, we got this fixed! https://github.com/laravel/jetstream-docs/commit/fad89937ffb4e52967237a5244728895515e3c7f
