### ISSUE TITLE
[2FA] Disabling and enabling two factor authentication should require the user's password.

### ISSUE THREAD

**Issue by DarthShmev** [laravel/jetstream#143]
In order to enable or disable 2FA, a user should be required to input their password via a confirmation modal. This will prevent a user from accidentally enabling 2FA and not setting it up. Also, the user's password should be required to disable 2FA in order to prevent potential hijacking of an account. 

My proposal is to have a similar flow as to logging out other sessions. 
<img width="1439" alt="Screen Shot 2020-09-10 at 5 18 38 PM" src="https://user-images.githubusercontent.com/34663790/92808568-dc480d00-f389-11ea-9a7e-20b6e03a4201.png">

As always, feedback is welcome.

**Comment by yoeriboven** [comment]
It's probably better to actually enter the 6 digit code so we're sure 2FA is set up on the user's phone.

Also, this looks similar to #74.

**Comment by driesvints** [comment]
Duplicate for https://github.com/laravel/jetstream/issues/74
