### ISSUE TITLE
vite v5.0.11 building for production failed

### ISSUE THREAD

**Issue by tamer73** [laravel/jetstream#1430]
### Jetstream Version

4.2.1

### Jetstream Stack

Livewire

### Laravel Version

10.3.2

### PHP Version

8.3

### Database Driver & Version

MySQL 8.0.28

### Description

```rust
> build
> vite build

vite v5.0.11 building for production...
transforming (2) resources/css/app.cssthread '<unnamed>' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:416:13:
assertion `left == right` failed
  left: 2
 right: 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5

   Symfony\Component\Process\Exception\ProcessSignaledException 

  The process has been signaled with signal "6".

  at vendor/symfony/process/Process.php:434
    430▕             usleep(1000);
    431▕         }
    432▕ 
    433▕         if ($this->processInformation['signaled'] && $this->processInformation['termsig'] !== $this->latestSignal) {
  ➜ 434▕             throw new ProcessSignaledException($this);
    435▕         }
    436▕ 
    437▕         return $this->exitcode;
    438▕     }

      +16 vendor frames 

  17  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

``` 

### Steps To Reproduce

Strictly following the installation guide from:
[https://jetstream.laravel.com/installation.html](url)

until:
php artisan jetstream:install livewire --teams

produces the given issue

**Comment by jessarcher** [comment]
Hi @tamer73,

I'm afraid I can't reproduce this using the versions mentioned:

![image](https://github.com/laravel/jetstream/assets/4977161/87c32296-0071-45c8-abb0-c9bc31be52f1)

In any case, I can't see anything to indicate that it's an issue with Jetstream. The error message is coming from Rust, so it might be an issue with Rollup (the underlying tool behind `vite build`).

**Comment by tamer73** [comment]
Hi @jessarcher 

Thanks for taking your time. So would it be better to open this issue on vite-plugin? Sorry if i opened this issue on wrong place. Thought it would be the right place since this issue startet trying to install just like described on homepage of this project.
