### ISSUE TITLE
Email registration validation error

### ISSUE THREAD

**Issue by ivanmizz** [laravel/jetstream#1434]
### Jetstream Version

3.3

### Jetstream Stack

Livewire

### Laravel Version

10.10

### PHP Version

8.1.2

### Description

An incomplete email such as "johndoe@gmail" is able to register and login in to the app. The form should prompt the user to write complete email such as "johndoe@gmail.com"

## A user inputs an incomplete email address in the registration page

![Screenshot from 2024-01-17 15-02-50](https://github.com/laravel/jetstream/assets/33838790/38d49030-205d-461f-9111-8b3596620be0)

## The user is registered in successfully with the incomplete email address
![Screenshot from 2024-01-17 15-03-25](https://github.com/laravel/jetstream/assets/33838790/2dc0bb09-e825-4263-926c-e0a2b6062935)

### Steps To Reproduce

https://github.com/ivanmizz/servicehub-2/

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by ivanmizz** [comment]
Noted. Thanks for the feedback!
