### ISSUE TITLE
`current_team_id` gets added to the users table without selecting the team feature.

### ISSUE THREAD

**Issue by aminraeisi** [laravel/jetstream#1435]
### Jetstream Version

4.2.2

### Jetstream Stack

Inertia

### Laravel Version

10.41.0

### PHP Version

8.1.10

### Description

I ran a fresh Laravel installation and did not select the team feature. The team table is not added but I have the database column `current_team_id` in the users table.

### Steps To Reproduce

1. composer require laravel/jetstream
2. php artisan jetstream:install
3. ❯ inertia
4. ❯ api,dark,verification
5. ❯ 1

**Comment by driesvints** [comment]
Event without the teams feature enabled, every user has a personal team. https://jetstream.laravel.com/features/teams.html#the-current-team

**Comment by aminraeisi** [comment]
@driesvints Thanks for the response. My confusion is the part that this `current_team_id` corresponds to a `teams.id` table column which does not exists due to not including it in the installation process. I though that the column `current_team_id` should not be pasted if the user does want to go with the team option.

**Comment by aminraeisi** [comment]
Also on the page you mentioned says that:
```
If you installed Jetstream using the --teams option, your application will be scaffolded to support team creation and management.
```

I did it without that and it did not include anything about the team but the column `current_team_id` in the users table.
