### ISSUE TITLE
Missing Authentication traits V8

### ISSUE THREAD

**Issue by jimgwhit** [laravel/jetstream#144]
- Jetstream Version: first
- Laravel Version: 8.0
- PHP Version: 7.4
- Database Driver & Version: Mysql 8

Docs from version 8
> Authenticating

> Now that you have routes and views setup for the included authentication controllers, you are ready to register and authenticate new users for your application! You may access your application in a browser since the authentication controllers already contain the logic (via their traits) to authenticate existing users and store new users in the database.

Mentions "via their traits"

Where are these traits?  

Along with this issue you can only redirect to one possible place after login.  Any flexibility to the developer seems like it's been removed.

Would be nice to have an authenticated method in a trait like before.

**Comment by taylorotwell** [comment]
Just outdated docs. Will update now. The flexibility hasn't been removed. You can bind a LoginResponse implementation in the container and I can also add an easier Closure hook for it if you want.

**Comment by jimgwhit** [comment]
Can you add a short example in the documentation in the authentication chapter of LoginResponse implementation.

I know that many folks redirect depending on the role.
