### ISSUE TITLE
Unable to enable Two Factor Authentication

### ISSUE THREAD

**Issue by Schrijvers123** [laravel/jetstream#1462]
### Jetstream Version

5.0.1

### Jetstream Stack

Inertia

### Laravel Version

11.1.1

### PHP Version

8.3.4

### Description

It appears that enabling Two-Factor Authentication is currently impossible. When I am logged in and navigate to my user profile, I encounter a section where I should be able to activate Two-Factor Multi-Authentication. Unfortunately, it doesn't seem to work.

In the console, I receive the message 'Uncaught ReferenceError: axios is not defined
![afbeelding](https://github.com/laravel/jetstream/assets/3889668/8a44c991-2d68-4830-a690-0a246168f8c5)

### Steps To Reproduce

Just got to your profile and try to enable two way multifacty authentication

**Comment by driesvints** [comment]
I can enable 2fa just fine on a fresh jetstream install with inertia.

**Comment by Schrijvers123** [comment]
thanks for the update. Will debug more. Need to find wht COnfirmpassword.vue cause an axios error.

**Comment by Schrijvers123** [comment]
Found a solution. Due to the fact I am not using Bootstrap, but Tailwin. I added the following code to app.js:

import axios from 'axios';

window.axios = axios;

window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';

After this it was working.
