### ISSUE TITLE
Modal inside view

### ISSUE THREAD

**Issue by duanhdan** [laravel/jetstream#147]
Hi,
I've read document about modal with livewire at this [docs](https://jetstream.laravel.com/1.x/stacks/livewire.html#modals)
But when I paste these code into my view I got this message:

`
ErrorException
Undefined variable: _instance (View: /var/www/html/resources/views/vendor/jetstream/components/modal.blade.php) (View: /var/www/html/resources/views/vendor/jetstream/components/modal.blade.php) (View: /var/www/html/resources/views/vendor/jetstream/components/modal.blade.php)
`
The document doesn't show how to embedded the source, somebody could show me the sample?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by duanhdan** [comment]
I saw this line in the cache view

`<div id="<?php echo e($id); ?>" x-data="{ show: <?php if ((object) ($attributes->wire('model')) instanceof \Livewire\WireDirective) : ?>window.Livewire.find('<?php echo e($_instance->id); ?>').entangle('<?php echo e($attributes->wire('model')->value()); ?>')<?php echo e($attributes->wire('model')->hasModifier('defer') ? '.defer' : ''); ?> <?php else : ?> window.Livewire.find('<?php echo e($_instance->id); ?>').entangle('<?php echo e($attributes->wire('model')); ?>') <?php endif; ?> }"`

I don't know why PHP can't detect $_instance object.

**Comment by aceclarke** [comment]
I feel like I am running into a very similar issue.  I am having problems with livewire and getting a basic data variable passed from the component to render in the view. Same error but basic context. My searches in other forums have come up empty so far.
