### ISSUE TITLE
php artisan view:cache returns an error since laravel 11 : Unable to locate a class or view for component [mail::message].

### ISSUE THREAD

**Issue by Lukimer** [laravel/jetstream#1475]
### Jetstream Version

5.0

### Jetstream Stack

Inertia

### Laravel Version

11

### PHP Version

8.3.4

### Description

Since I run a composer update to get the latest laravel version (11), my deployment script crashes.

If I go back to laravel 10.48.7, the error does not occur anymore.

This bug just like the issues: https://github.com/laravel/framework/issues/44544

### Steps To Reproduce

Just run these commands:

composer dump-autoload
php artisan view:clear

**Comment by driesvints** [comment]
Please don't post multiple issues

**Comment by Lukimer** [comment]
Sorry!
