### ISSUE TITLE
Uploaded profile photo does not get stored

### ISSUE THREAD

**Issue by rabol** [laravel/jetstream#148]
- Jetstream Version: 1.1.2
- Laravel Version: 8.0.4
- PHP Version: 7.4.5
- Database Driver & Version: Mysql 5.7.29

### Description:
When uploading a photo on the profile page the photo does not show up when revisiting the profile page

### Steps To Reproduce:

install a new app:

laravel new myapp --jet --stack=livewire --teams

then open browser
register
login
go to profile page
upload photo (photo is displayed) 
go to front page
go back to profile page and observe that the profile image is missing

**Comment by rabol** [comment]
If I do a API call to the user route I get this:


```
{
    "id": 1,
    "name": "test test",
    "email": "test@laravel.test",
    "email_verified_at": null,
    "current_team_id": "1",
    "profile_photo_path": null,
    "created_at": "2020-09-11T08:23:24.000000Z",
    "updated_at": "2020-09-11T08:37:35.000000Z",
    "profile_photo_url": "https://ui-avatars.com/api/?name=test+test&color=7F9CF5&background=EBF4FF"
}
```

**Comment by rabol** [comment]
Very strange... did upload a few times and then it worked

**Comment by camiant** [comment]
maybe you missed the command `php artisan storage:link` to create the symlink between `storage` and `public` folders
