### ISSUE TITLE
Password validation can't be disabled

### ISSUE THREAD

**Issue by l-alexandrov** [laravel/jetstream#1488]
### Jetstream Version

4.0.5

### Jetstream Stack

Livewire

### Laravel Version

10.46.0

### PHP Version

8.2.16

### Description

Despite the fact I've disabled password validation, it's still required for 2FA activation. The `two-factor-authentication-form` component renders the component for password confirmation without checking if confirmation is required.

Btw, I think it's applicable to latest Jetstream version as well.

### Steps To Reproduce

1. Log in to a user without 2FA activated
2. Disable password confirmation in `config/fortify.php` via:
```php
Features::twoFactorAuthentication([
    'confirmPassword' => false
]),
```
4. Go to `/user/profile` 
5. Try to enable 2FA
6. See that you are still required to confirm your password

**Comment by crynobone** [comment]
See https://github.com/laravel/jetstream/pull/1464#issuecomment-2028975807
