### ISSUE TITLE
Layout Team Invitation email is messed up.

### ISSUE THREAD

**Issue by MGeurts** [laravel/jetstream#1498]
### Jetstream Version

5.1.1

### Jetstream Stack

Livewire

### Laravel Version

11.9.2

### PHP Version

8.3.7

### Database Driver & Version

MySQL 8.3

### Description

![JetStream Team Invitation](https://github.com/laravel/jetstream/assets/5404867/c4499233-6d3c-41ec-b85b-d8dc27970f6e)

### Steps To Reproduce

- Fresh install Laravel 11
- Fresh install Laravel Jetstream with Teams option
- Register
- Invite a member to your team
- Check the team invitation email

**Comment by MGeurts** [comment]
Upon further examination, it seems that right after the fresh Laravel Jetstream install, everything is OK.

The issue is caused after the file **\resources\views\emails\team-invitation.blade.php** is openend **AND SAVED** in Visual Studio Code (Windows machine). Even when saved without any actual changes except for the linter formatting (indenting) the code.

**Comment by crynobone** [comment]
This seems to be an issue with the IDE (linter) itself which we don't have any control over. Would welcome any improvement but will close the issue as no immediate changes are possible at the moment.

**Comment by MGeurts** [comment]
The issue is caused by the indents.
To me it's stange that a normal blade.php file gets corrupted this way simply by inserting indents.
Or could it be this file is somehow processed as markdown despite a confusing extention (blade.php instead of md)?
