### ISSUE TITLE
Delete not work validation (password) not work

### ISSUE THREAD

**Issue by majweb** [laravel/jetstream#1506]
### Jetstream Version

5

### Jetstream Stack

Inertia

### Laravel Version

11

### PHP Version

8.3

### Database Driver & Version

mysql

### Description

When you want to delete a user, it gives me an error. Validation for the password field does not work.

![chrome_mUDz0vhidN](https://github.com/laravel/jetstream/assets/22354155/ae3a3966-1c99-4e0f-a751-ffa0cf34616a)

### Steps To Reproduce

your own

**Comment by driesvints** [comment]
I can't reproduce this. On a fresh Jetstream app with inertia I was able to delete the user properly.
