### ISSUE TITLE
pragmarx/google2fa: Update to v8

### ISSUE THREAD

**Issue by blankster** [laravel/jetstream#151]
First of all, thanks a lot for your work!

At the moment you're using v7 of https://github.com/antonioribeiro/google2fa . That implicates compatibility problems with other packages (example: the great Laravel back-office package Orchid https://github.com/orchidsoftware/platform) already using v8 of pragmarx/google2fa. 

Would it be possible that you update in the near future to v8? I really would appreciate it 👍

**Comment by driesvints** [comment]
Sent in a PR here: https://github.com/laravel/fortify/pull/25
