### ISSUE TITLE
API Token

### ISSUE THREAD

**Issue by ImCharle** [laravel/jetstream#1511]
### Jetstream Version

3.1.0

### Jetstream Stack

Livewire

### Laravel Version

11

### PHP Version

8.2

### Database Driver & Version

mysql 8

### Description

Hello, if I am in 2 teams, and in one team I am the owner with full access and in the other member, I set currentTeam the team where I am the owner and create a token, based on this I can also control team 2 where I am a member , how can it be prevented, does anyone know?

### Steps To Reproduce

see description

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
