### ISSUE TITLE
Declaration of DeleteUser::delete(User $user): void must be compatible with DeletesUsers::delete(\Illuminate\Foundation\Auth\User $user)

### ISSUE THREAD

**Issue by carlosmintfan** [laravel/jetstream#1512]
### Jetstream Version

5.1

### Jetstream Stack

Livewire

### Laravel Version

11.9

### PHP Version

8.3.8

### Description

When opening app/Actions/Jetstream/DeleteUser.php in my Jetstream project, I get an error in VSCode: `Declaration of DeleteUser::delete(User $user): void must be compatible with DeletesUsers::delete(\Illuminate\Foundation\Auth\User $user)`
Although App\Models\User extends \Illuminate\Foundation\Auth\User, that's considered incompatible. Is that correct or should I report it to my PHP plugin in VSCode?
Also

### Steps To Reproduce

Install a new Jetstream project – look at the Jetstream docs.
Open app/Actions/Jetstream/DeleteUser.php with the PHP VSCode plugin installed. https://marketplace.visualstudio.com/items?itemName=DEVSENSE.phptools-vscode Observe the error.

At this stage, although it's a separate issue, I'd like to mention that when installing Jetstream with teams support, `DB::transaction` is used for deleting a user. Shouldn't that be done also in the non-team Jetstream version or is it only needed when dropping teams?

**Comment by carlosmintfan** [comment]
Same in all files except for `CreateNewUser.php` and `PasswordValidationRules.php` in app/Actions/Fortify

**Comment by crynobone** [comment]
> that's considered incompatible. Is that correct or should I report it to my PHP plugin in VSCode?

This seems to be an issue with PHP plugin in VSCode.
