### ISSUE TITLE
Fresh Installation Breaks

### ISSUE THREAD

**Issue by rjvim** [laravel/jetstream#1514]
### Jetstream Version

5.1.3

### Jetstream Stack

Livewire

### Laravel Version

11.9

### PHP Version

8.3

### Description

In dropdown.blade.php we have following widths supported:
https://github.com/laravel/jetstream/blob/5.x/stubs/livewire/resources/views/components/dropdown.blade.php#L11

```
$width = match ($width) {
    '48' => 'w-48',
};
```

In navigation-menu.blade.php, we use:

https://github.com/laravel/jetstream/blob/5.x/stubs/livewire/resources/views/navigation-menu.blade.php#L25
```
 <x-dropdown align="right" width="60">
```

I am guessing we need to `'60' => 'w-60',` to dropdown.

### Steps To Reproduce

1. Run `laravel new new-app`
2. Select following options

<img width="498" alt="Screenshot 2024-07-10 at 14 26 37" src="https://github.com/laravel/jetstream/assets/23579455/586f109c-b306-4231-b4d0-469f19b94747">

**Comment by DanielSpravtsev** [comment]
https://github.com/beyondcode/herd-community/issues/883

@driesvints I think we need to tag a new release
