### ISSUE TITLE
What about adding a license?

### ISSUE THREAD

**Issue by carlosmintfan** [laravel/jetstream#1518]
### Description

The Laravel Jetstream docs (not Jetstream itself) have no license. A license file is important, see https://choosealicense.com/no-permission. Also, MIT includes documentation as part of the Software, see https://github.com/laravel/jetstream/blob/5.x/LICENSE.md. So if you're real MIT licensors, you should also license your docs under MIT (as the docs are in a different repo that Jetstream itself, it may not be right to assume that they're automatically MIT just because MIT states that about docs..it says "associated" and well..this is a different repo...). Lastly, Laravel docs are also under MIT: https://github.com/laravel/docs/blob/11.x/license.md.
So, I did a PR: https://github.com/laravel/jetstream-docs/pull/100. And what happened? Taylor just closed it WITHOUT ANY EXPLANATION. If it's not a mistake (so he wanted to merge it but accidentally clicked on close), that's....not friendly. No.
Could you please explain to me what's up? Thanks!

### Steps To Reproduce

1. Read https://choosealicense.com/no-permission
2. Read https://github.com/laravel/jetstream/blob/5.x/LICENSE.md to see that MIT license includes documentation
3. Read https://github.com/laravel/jetstream-docs/pull/100 to see that Taylor closed without explanation...that's either a mistake or not very friendly.

**Comment by crynobone** [comment]
https://github.com/laravel/jetstream/blob/0eecfe8554e934d15c73cba5fd6c7f30ed640f3d/LICENSE.md?plain=1#L5-L6

The license in this repository should also cover the documentation.

**Comment by carlosmintfan** [comment]
> https://github.com/laravel/jetstream/blob/0eecfe8554e934d15c73cba5fd6c7f30ed640f3d/LICENSE.md?plain=1#L5-L6
> 
> The license in this repository should also cover the documentation.

I understand, thanks. However, it would be more clear if a license file would be added to the docs repo too...
