### ISSUE TITLE
API Tokens modal with 404 error

### ISSUE THREAD

**Issue by bobbyiliev** [laravel/jetstream#152]
- Jetstream Version: ^1.1
- Laravel Version: ^8.0
- PHP Version: 7.4.3
- Database Driver & Version: mysql  Ver 8.0.21

### Description:

I just noticed a minor bug after playing around with Jetstream. After making a change to the permissions of a specific token and then deleting that very same token, any other action on the API tokens page results in modal with a 404 error.

Refreshing the page fixes the problem.

### Steps To Reproduce:

* Create a new API token
* Make a change to the permissions of the newly created token
* Delete that very same API token
* Try to create a new token or any other action on the page

**Comment by calebporzio** [comment]
Thanks for posting. I can confirm this bug. Working on it stat.

**Comment by calebporzio** [comment]
Ok, I PR'd a solution to the problem: #155 

When that is merged, AND your Livewire install is updated to v2.2.0, this problem should go way.
