### ISSUE TITLE
2 Warning icons

### ISSUE THREAD

**Issue by eneadrian** [laravel/jetstream#1523]
### Jetstream Version

5

### Jetstream Stack

Livewire

### Laravel Version

10

### PHP Version

8

### Description

![Screenshot 2024-08-08 122008](https://github.com/user-attachments/assets/db887926-138d-4c9e-bcbd-daaf9bc74a6a)

If bannerStyle is warning, or anything other than succes or danger, 2 warning icons appears

### Steps To Reproduce

return redirect()->back()
			->with('flash', [
				'bannerStyle' => 'warning',
				'banner' => 'Something went wrong'
			]);

**Comment by eneadrian** [comment]
![Screenshot 2024-08-08 122750](https://github.com/user-attachments/assets/3b59ebda-ff24-4cfe-84ee-3f211a4894cf)

**Comment by driesvints** [comment]
Heya, thanks for reporting this one! Could you send in a PR for this?

**Comment by driesvints** [comment]
PR was merged thanks.
