### ISSUE TITLE
Builder IO causes page not to build

### ISSUE THREAD

**Issue by oceanapplications** [laravel/jetstream#1525]
### Jetstream Version

5.1

### Jetstream Stack

Inertia

### Laravel Version

11.9

### PHP Version

8.3

### Database Driver & Version

Herd Pro

### Description

When BuilderIO is included on a page, it won't properly build and be included in the manifest.json file. Everything works fine on npm run dev. npm run build is where the issues becomes apparent.

### Steps To Reproduce

https://github.com/oceanapplications/laravel-builderio This repo demonstrates the error. The only edited file is the Welcome.vue which will fail to include in the manifest resulting in an error when visiting the page.

**Comment by driesvints** [comment]
We unfortunately don't maintain this package so please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
