### ISSUE TITLE
Website didn’t update after docs change

### ISSUE THREAD

**Issue by carlosmintfan** [laravel/jetstream#1532]
### Jetstream Version

5

### Jetstream Stack

Livewire

### Laravel Version

N/A

### PHP Version

N/A

### Description

Although my PR to the docs has been merged (https://github.com/laravel/jetstream-docs/commit/5c08e6b46320c4ab799556bd4d516f60f18be4cb), the website still shows the old code at https://jetstream.laravel.com/features/authentication.html#customizing-the-authentication-pipeline

### Steps To Reproduce

N/A

**Comment by taylorotwell** [comment]
Done!
