### ISSUE TITLE
Prompt label not displayed in CLI when using --teams option with php artisan jetstream:install

### ISSUE THREAD

**Issue by HichemTab-tech** [laravel/jetstream#1535]
### Jetstream Version

5.2.0

### Jetstream Stack

Inertia

### Laravel Version

11.22.0

### PHP Version

8.3.11

### Description

When executing `php artisan jetstream:install insertia --teams`, the prompt label from Laravel Prompts does not display in the CLI, although the prompt is functional and accepts input. Without the `--teams` option, the prompt label displays correctly.

### Steps To Reproduce

**Steps to Reproduce:**
1. Open terminal.
2. Run `php artisan jetstream:install insertia --teams`.
3. Observe that the prompt label is missing.
4. Run `php artisan jetstream:install insertia` without the `--teams` option.
5. Observe that the prompt label is displayed correctly.

**Expected Behavior:**  
The prompt label should be visible regardless of the `--teams` option. it's weird i know :

**Actual Behavior:**  
The prompt label is missing when using the `--teams` option.

**Code Link:**  
_Link to the relevant code or repository (e.g., [GitHub Code Link](https://github.com/laravel/jetstream/blob/5.x/src/Console/InstallCommand.php#L763))_

**Additional Information:**  
_This issue seems isolated to the `--teams` option. No issues observed with other options._

**Comment by crynobone** [comment]
Prompts will only be available when argument (in this example `'stack'`) is missing.
