### ISSUE TITLE
Use routes on Inertia views

### ISSUE THREAD

**Issue by m1guelpf** [laravel/jetstream#157]
Similar to how Livewire uses named routes instead of path strings, it would be awesome to have Inertia do the same so that changes to the paths on the published routes or adding a prefix to Fortify routes doesn't require a change to the views.

To accomplish this, we could use [Tighten's Ziggy package](https://github.com/tightenco/ziggy), which I believe is already the standard practice for using routes in Vue code.

Would you welcome a PR that introduces this change? :octocat:

**Comment by taylorotwell** [comment]
I agree that Ziggy should likely be used for this.
