### ISSUE TITLE
Jetstream dashboard use system theme setting for light or dark theme

### ISSUE THREAD

**Issue by mous2890** [laravel/jetstream#159]
The main Laravel homepage has support for light/dark theme which automatically is detected and applied to the welcome view.  

As soon as you login via Jetstream, only the light theme is applied and the system theme is no longer used. I've only tested this on the Jetstream Inertia stack. 

Requesting feature for the Jetstream Dashboard to also automatically detected system theme and apply to frontend. 

Would be super sweet if there was a light/dark theme toggle at the top somewhere too.

**Comment by driesvints** [comment]
Since this is a feature request I recommend that you try to PR something. Thanks
