### ISSUE TITLE
Is this Early Access Project?

### ISSUE THREAD

**Issue by ukeloop** [laravel/jetstream#160]
Is this Early access project? This is not completely scaffold Auth. Because this is not support change routes and controllers. We need extend the base Provider and override whatever for changing routes and controllers. Because this project is hard coded. [#issue-692710688](https://github.com/laravel/jetstream/issues/44#issue-692710688)

This project should not be recommended at Laravel8 document.

**Comment by buismaarten** [comment]
Indeed, maybe it would we convenient to move some actions logic to the package so that the scaffolded stub (empty class) in userland extends the actual action from the package. With this approach customization is possible with bug fixes etc. from the package.

Some story for controllers.
