### ISSUE TITLE
Social media authentication/registration

### ISSUE THREAD

**Issue by rennokki** [laravel/jetstream#161]
A while ago I wrote Hej!, a package that helps you add social media business logic to any Laravel app just by using the built-in router/controller functionalities: https://github.com/renoki-co/hej

I see that Jetstream is promising, would you like to see the built-in social media authentication/registration within Jetstream? 🤔

**Comment by driesvints** [comment]
Thanks for the offer but I don't think we'll implement such a third party package at this time. Sorry.

**Comment by rennokki** [comment]
@driesvints Why implementing it that way when i can help porting it to jetstream?
