### ISSUE TITLE
Jetstream / Teams: Column not found: 1054 Unknown column 'current_team_id' in 'field list'

### ISSUE THREAD

**Issue by McPan** [laravel/jetstream#162]
- Jetstream Version: 1.1.2
- Jetstream Stack: Livewire
- Laravel Version: 8.1.0
- PHP Version: 7.4.10
- Database Driver & Version: mysql / mariadb 10.4.14

### Description: Exeception Error after registering a new user and redirect to dashboard

ErrorException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'current_team_id' in 'field list' (SQL: update `users` set `current_team_id` = 1, `users`.`updated_at` = 2020-09-12 09:07:10 where `id` = 1) (View: <PATH_TO_PROJECT>\resources\views\layouts\app.blade.php) (View: <PATH_TO_PROJECT>\resources\views\layouts\app.blade.php) 

Described column 'current_team_id' is missing in the 'users' table.

### Steps To Reproduce:

Create a new Laravel 8 project

```
composer create-project --prefer-dist laravel/laravel .\
```

Include 'jetstream' package

```
composer require laravel/jetstream
```

Create and run migrations

```
php artisan jetstream:install livewire --teams
npm install && npm run dev
php artisan migrate
```

Open the website of the new project and register a new user. Redirecting to the 'dashboard' will throw the exception specified above.

### (Temporary) solution

Create and run another migration

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AddCurrentTeamIdToUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('users', function (Blueprint $table) {
            $table->foreignId('current_team_id')
                    ->after('remember_token')
                    ->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('users', function (Blueprint $table) {
            $table->dropColumn('current_team_id');
        });
    }
} 
```

Try to register a new user and everything works fine.

**Comment by dotancohen** [comment]
I've got an open [pull request](https://github.com/laravel/jetstream/pull/166) to resolve this issue, but a change to the build process must be undertaken first.

**Comment by taylorotwell** [comment]
Re-migrate your database after installing Jetstream.

**Comment by DulbyMendez** [comment]
@taylorotwell Make .. migration:refresh work for me. Thanks!

**Comment by camilocaquimbo** [comment]
`php artisan migrate:refresh` works, thanks.

**Comment by PedroCaicedoDev** [comment]
Work for me, thanks @camilocaquimbo 👍🏼

**Comment by cuonghuynh** [comment]
Thanks @camilocaquimbo

**Comment by zorox-1** [comment]
if u get Error : `"Class 'Doctrine\DBAL\Driver\AbstractSQLiteDriver' not found"`

then Solution: Run `composer require doctrine/dbal`

**Comment by joakim-tldr** [comment]
> `php artisan migrate:refresh` works, thanks. You should include that in the documentation.

Still not added to the documentation in https://jetstream.laravel.com/installation.html. `php artisan migrate` doesnt do the trick, otherwise i wouldnt be here.
