### ISSUE TITLE
Disabling updateProfileInformation and updatePasswords feature without effect

### ISSUE THREAD

**Issue by schaeferalex** [laravel/jetstream#163]
- Jetstream Version: 1.1.2
- Jetstream Stack: Livewire
- Laravel Version: 8.1.0
- PHP Version: 7.4.10
- Database Driver & Version: mysql 5.7.26

### Description:

When disabling _updateProfileInformation_ and _updatePasswords_ in the fortify config the sections remain visible on the user profile page. Expected behaviour would be them not being visible or the input fields being disabled.

### Steps To Reproduce:

1. laravel new _project_ --jet
2. Remove `Features::updateProfileInformation()` and `Features::updatePasswords()` from `config('fortify.features')`
3. Cache config and go to /user/profile
4. Sections _Profile Information_ and _Update Password_ are still visible and functional

**Comment by taylorotwell** [comment]
Remove them from your Blade file.
