### ISSUE TITLE
Cant Use Email Verification in Jetstream also unable to modify login query

### ISSUE THREAD

**Issue by pawanbangar** [laravel/jetstream#169]
- Jetstream Version: 1.0
- Jetstream Stack: Livewire
- Laravel Version: 8.0.1
- PHP Version:7.3
- Database Driver & Version:

### Description:
Laravel 8 Provide Action under /app/actions
We Have Fortify folder under this which contains create user,but i cannot locate login user,
So How can I Modify login query like where status==='confirmed'

### Steps To Reproduce:
Install Laravel8 ,then Jetstream
Then boom all flexibility from laravel/ui is gone

**Comment by alxmtr** [comment]
To use email verification you have to enable the feature in your `config/fortify.php` file and your User model should implements the MustVerifyEmail interface.

**Comment by pawanbangar** [comment]
> To use email verification you have to enable the feature in your `config/fortify.php` file and your User model should implements the MustVerifyEmail interface.

Alerady done this,but unable to override actions in laravel8,also mustverifymail produce another bug

**Comment by alxmtr** [comment]
What kind of bug is produced by MustVerifyEmail ? 

If your `App\Models\User` model implements the `Illuminate\Contracts\Auth\MustVerifyEmail` contract the email verification should work perfectly.

```php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    // ...
}
```
(from the docs: https://laravel.com/docs/8.x/verification)

I you want the flexibility from laravel/ui you can use the version 3 compatible with Laravel 8.

`composer require laravel/ui:^3.0`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
