### ISSUE TITLE
Ask for password before enable/disable 2FA

### ISSUE THREAD

**Issue by zaherg** [laravel/jetstream#17]
Hey,

Since the user might login from multiple devices, it would be better to protect the ability to enable/disable (and for sure generating new recovery code) something like 

1. Just the enable/disable https://d.pr/v/itaIyQ
2. All buttons require confirmation https://d.pr/v/hrQW5R

I can submit a Draft PR with the code I added/changed to be reviewed and edited as required.

Thanks

**Comment by taylorotwell** [comment]
Closing as this is a feature request.

**Comment by zaherg** [comment]
hey @taylorotwell can I have your thoughts about this https://github.com/laravel/jetstream/pull/20
