### ISSUE TITLE
"npm run production" breaking layout 

### ISSUE THREAD

**Issue by danpalmieri** [laravel/jetstream#170]
- Jetstream Version: 1.1.2
- Jetstream Stack: Livewire
- Laravel Version: 8.1.0
- PHP Version: 7.4
- Database Driver & Version: Mysql  8

### Description:
`npm run production` is breaking css. 

### Steps To Reproduce:
In a fresh Laravel 8 with --jet install: 
`npm run production`
then visite /login

![Screen Shot 2020-09-12 at 23 39 16](https://user-images.githubusercontent.com/1392562/93008937-3515d200-f551-11ea-8f84-ae57f97af6a7.jpg)

**Comment by danpalmieri** [comment]
I found out that I have to:
`php artisan vendor:publish --tag=jetstream-views`
for purge to work.

**Comment by leon0399** [comment]
I think, this should be pointed in description or default Tailwind purge config should be tweaked
