### ISSUE TITLE
How to find this components <x-jet-authentication-card-logo /> 

### ISSUE THREAD

**Issue by murtazasultani** [laravel/jetstream#172]
- Jetstream Version: 1.0
- Jetstream Stack: Inertia
- Laravel Version: 8.1.0
- PHP Version: 7.4.8
- Database Driver & Version:

### Description:

How to find this components <x-jet-authentication-card-logo />  or any other component which start with start <x-jet-

**Comment by driesvints** [comment]
https://github.com/laravel/jetstream/tree/1.x/resources/views/components
