### ISSUE TITLE
Wrong IP Address used for sessions

### ISSUE THREAD

**Issue by faustbrian** [laravel/jetstream#174]
- Jetstream Version: 0.6.0
- Jetstream Stack: Livewire
- Laravel Version: 8.0.0
- PHP Version: 7.4.10
- Database Driver & Version: PostgreSQL 12.4

### Description:

When a site is running behind CloudFlare all session will be created with the IP Address of the CloudFlare servers. That means that all the sessions in your database will be bound to CloudFlare addresses rather than the IP addresses of the devices that your visitor is using.

Ideally, something like https://github.com/Vectorface/whip would be used to handle most scenarios in which the real IP address of the visitor could be cloaked. This could also be more a bug with the way Laravel handles session and IP addresses but it became visible while using Jetstream and looking at the browser sessions.

### Steps To Reproduce:

Deploy a page that uses CloudFlare. All session will use the IP addresses of the CloudFlare servers instead of the `cf-connecting-ip` header.

**Comment by fletch3555** [comment]
This is usually handled by the proxy passing headers to indicate the original request IP.  Laravel ships with the [TrustedProxy](https://github.com/fideloper/TrustedProxy) package to help manage this.  Configuration is noted in the docs: https://laravel.com/docs/8.x/requests#configuring-trusted-proxies
