### ISSUE TITLE
Missing "not registered" in Login Form

### ISSUE THREAD

**Issue by oschwarzenberg** [laravel/jetstream#175]
If you are not registered in Jetstream and you try to login, there ist no Link to go back to the Register Form.

**Comment by alxmtr** [comment]
You can easily add it in your `login.blade.php` file.

Like at the end of the form for example:
```html
<x-guest-layout>
  <x-jet-authentication-card>
    ...

    <form method="POST" action="{{ route('login') }}">
      ...

      <div class="py-2 mt-6 text-center border-t border-gray-200">
        <p class="mt-2 text-sm leading-5 text-center text-gray-600 max-w">
          Or
          <a href="#" class="font-medium text-blue-600 transition duration-150 ease-in-out hover:text-blue-500 focus:outline-none focus:underline">
            create a new account
          </a>
        </p>
      </div>
    </form>
  </x-jet-authentication-card>
</x-guest-layout>
```

![Capture d’écran 2020-09-13 150257](https://user-images.githubusercontent.com/1714997/93018754-4bb03d80-f5d2-11ea-8dd4-85f9976679a1.png)

**Comment by taylorotwell** [comment]
This is a feature request. You are free to edit that view as you see fit. It belongs to your application.
