### ISSUE TITLE
Can't reset password

### ISSUE THREAD

**Issue by aleemont** [laravel/jetstream#178]
- Jetstream Version: 1.1.2
- Jetstream Stack: Inertia / Livewire
- Laravel Version: 8.0.1
- PHP Version: 7.4.9
- Database Driver & Version:

### Description:
When I try to reset a password i get:

Swift_TransportException
Cannot send message without a sender address

**Comment by ReArmedHalo** [comment]
Did you configure your `.env`? Sounds like your `MAIL_FROM_ADDRESS` is blank (which is default) - I just confirmed it works fine for me with a clean install and once `MAIL_FROM_ADDRESS` is filled in. I used mailtrap.io.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by roarkmccolgan** [comment]
@ReArmedHalo Thanks, your solution was correct
