### ISSUE TITLE
Add Bootstrap support

### ISSUE THREAD

**Issue by MollyUrs** [laravel/jetstream#179]
With bootstrap still being the most popular CSS framework, I think Jetstream should have bootstrap support built-in.

**Comment by driesvints** [comment]
We have no plans for this atm. Please also try to search previously closed tickets next time. Thanks.

**Comment by MollyUrs** [comment]
Can we get an explanation why? With Jetstream becomming the main Auth package for Laravel, I think an explanation would be useful to stop repeat issues.

Also: https://github.com/laravel/jetstream/issues?q=is%3Aissue+bootstrap

**Comment by driesvints** [comment]
We don't want to maintain stacks we aren't using ourselves.

**Comment by jrd-lewis** [comment]
It would still be useful for people who don't use Tailwind.

**Comment by driesvints** [comment]
@jrd-lewis feel free to maintain a fork if you're willing to put in the work. This is open source so anyone can do that.

**Comment by MollyUrs** [comment]
Even an unstyled preset would be suitable, something running on pure blade without any CSS applied so that we don't have to remove all the Tailwind stuff to use bootstrap or something else.

**Comment by FoksVHox** [comment]
> @jrd-lewis feel free to maintain a fork if you're willing to put in the work. This is open source so anyone can do that.

Is it allowed to PR it to this repo?

**Comment by driesvints** [comment]
No, we're not planning on adding bootstrap to this repo.

**Comment by relaypilot** [comment]
For the people like me struggling in replacing the Tailwind modal by a Bootstrap one, here is a great snippet: https://www.nicesnippets.com/blog/laravel-livewire-crud-with-bootstrap-modal-example

**Comment by ycs77** [comment]
Using Bootstrap in Jetstream: https://github.com/nascent-africa/jetstrap

**Comment by JTD420** [comment]
> Using Bootstrap in Jetstream: https://github.com/nascent-africa/jetstrap

This is perfect! Exactly what I wanted. :) 
I hope that it sees enough usage to be maintained or potentially brought into this repo and provided as an alternative option in the future! Seems like the majority of the works already been done so now it would just be a matter of updating it with any future updates to the Laravel core. @driesvints 🙏 😉

**Comment by driesvints** [comment]
@JTD420 if we brought it into Jetstream we'd be responsible for maintaining it and future versions of Bootstrap. We don't have any plans for this. I'm closing this off here, sorry. Feel free to make use of the package above.
