### ISSUE TITLE
Jetstream documentation page not found

### ISSUE THREAD

**Issue by vikramparihar** [laravel/jetstream#18]
https://laravel.com/docs/7.x/jetstream

Page 404

I saw this link on 
https://github.com/laravel/jetstream

**Comment by LewisLarsen** [comment]
This has been reported **multiple** times before. It hasn't been written yet as per the response to one of the closed issues below. 

https://github.com/laravel/jetstream/issues/4
https://github.com/laravel/jetstream/issues/15

**Comment by smccoy78** [comment]
I keep seeing that the docs haven't been written yet, but i'm watching a video that was released on 11/02 and they are viewing the documentation.

**Comment by driesvints** [comment]
https://jetstream.laravel.com

**Comment by smccoy78** [comment]
@driesvints I've tried that in 3 different browsers. I get a 404 error in all of them. Is there any chance that valet is interfering? Reason I ask is because in the browser tab it says Valet - Not Found

**Comment by smccoy78** [comment]
Must be something with Valet. I can access the docs using Safari on my iPad, but not my Mac.

**Comment by jringeisen** [comment]
Does anyone know why valet interferes with accessing the jetstream documentation? I get a 404 - Not Found and in the page title it says Valet - Not Found.
