### ISSUE TITLE
Photo does not upload when using S3

### ISSUE THREAD

**Issue by iblacker** [laravel/jetstream#183]
- Jetstream Version: 1.1.3
- Jetstream Stack: Livewire
- Laravel Version: 8.0.1
- PHP Version: 7.4.9

### Description:

Photo doesn’t get upload when FILESYSTEM_DRIVER is set to s3. It works when the line is removed from .end file which is being stored in public folder.

<img width="838" alt="Screen Shot 2020-09-14 at 12 37 26 AM" src="https://user-images.githubusercontent.com/8527739/93045253-abcfcf80-f624-11ea-8e05-6c2cb27e1ac1.png">

This is the dd of $input inside UpdateUserProfileInformation, when using public.

And below when using s3:

<img width="839" alt="Screen Shot 2020-09-14 at 12 38 14 AM" src="https://user-images.githubusercontent.com/8527739/93045372-023d0e00-f625-11ea-9fa7-e50f2c7ea313.png">

It shows the preview, but after saving, it goes back to the previous photo and there is nothing on the s3 bucket. Tested on 2 separate projects, same result.

### Steps To Reproduce:

1. In User Profile, select new photo
2. Click on save
3. Refresh, photo doesn’t change.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
