### ISSUE TITLE
ADD REACT PLEASE

### ISSUE THREAD

**Issue by subadrun** [laravel/jetstream#185]
I LOVE F REACT

**Comment by stancl** [comment]
That's awesome!

If you love it, I'm sure you'll love writing a React version and contributing to open-source by publishing it on GitHub?

**Comment by FoksVHox** [comment]
> That's awesome!
> 
> If you love it, I'm sure you'll love writing a React version and contributing to open-source by publishing it on GitHub?

Are you suggesting that, if he won't write a React version, then he doesn't love React.
