### ISSUE TITLE
No routes files when "composer install"

### ISSUE THREAD

**Issue by lucaros97** [laravel/jetstream#186]
- Jetstream Version: 1.1.2
- Jetstream Stack: Inertia
- Laravel Version: 8.1.0
- PHP Version: 7.4.4
- Database Driver & Version: MySQL Maria DB 10.4.11

### Description:
When cloning a Laravel Jetstream application, and i run composer install it throw this error. Tried to delete vendor folder, update all dependencies, etc.

```
require(/mnt/c/code/projectname/vendor/laravel/jetstream/src/../routes/.php): failed to open stream: No such file or directory

  at vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:144
    140▕      */
    141▕     protected function loadRoutesFrom($path)
    142▕     {
    143▕         if (! ($this->app instanceof CachesRoutes && $this->app->routesAreCached())) {
  ➜ 144▕             require $path;
    145▕         }
    146▕     }
    147▕
    148▕     /**
```

### Steps To Reproduce:
- Clone a Laravel JetStream app
- Run `composer install`

**Comment by driesvints** [comment]
Uncache your routes and try again.

**Comment by saurabh85mahajan** [comment]
> Uncache your routes and try again.

I had a difficulty understanding this comment. Basically you need to make sure that Routes have been cached successfully and not clear the Route Cache. This could be done using the below command:

`php artisan route:cache`

**Comment by dominiced** [comment]
`vagrant@homestead:~/projects/scip$ php artisan route:cache

   ErrorException 

  require(/home/vagrant/projects/scip/vendor/laravel/jetstream/src/../routes/.php): failed to open stream: No such file or directory`

I'm trying to setup Jetstream. I used Composer to install LiveWire followed by Jetstream, but I receive the same errors. However, as you can see by the snippet above, I get the same errors when trying to carry out the suggested solution. So what do I do if I can't cache the route because of the issue?

**Comment by saurabh85mahajan** [comment]
Here is what worked for me:

1. Remove jetstream from composer
`composer remove laravel/jetstream`

2. Then you should be able to cache your routes using
`php artisan route:cache`

3. Then install jetstream
`composer require laravel/jetstream`

**Comment by keon99** [comment]
After install jetstream when i attempt to run `php artisan route:cache` the problem still persist.

**Comment by victor-ke** [comment]
I think its probably issue with cached config. Try removing bootstrap/cache/config.php. Jetstream tries to load routes from directory that is defined in Jetstream config.

Then run php artisan route:cache again  to see if the problem has been sorted
