### ISSUE TITLE
Edit Team Name error

### ISSUE THREAD

**Issue by youyi1314** [laravel/jetstream#187]
- Laravel Version: ^8.0
- PHP Version: 7.3.20
- Database Driver & Version: Mysql 5.7.31
- Install methods: Laravel Installer

### Description:
Show error popup when edit team name.
```
Illuminate\Contracts\Container\BindingResolutionException
Target [Laravel\Jetstream\Contracts\UpdatesTeamNames] is not instantiable.
http://127.0.0.1/livewire/message/teams.update-team-name-form
```
```
Illuminate\Container\Container::notInstantiable
vendor/laravel/framework/src/Illuminate/Container/Container.php:1017

```

### Steps To Reproduce:
Manually add `teams` and `team_user` and go to `http://127.0.0.1/teams/1` to edit Team Name ,
it popup with error in Description

**Comment by driesvints** [comment]
Transferred to jetstream repo.

**Comment by taylorotwell** [comment]
Manually adding teams and team_user is not enough. When you install Jetstream with teams it installs bindings into your JetstreamServiceProvider.

**Comment by youyi1314** [comment]
> Manually adding teams and team_user is not enough. When you install Jetstream with teams it installs bindings into your JetstreamServiceProvider.

I updated the JetstreamServiceProvider but how to let it reapply the data into teams and team_user?

**Comment by masterix21** [comment]
I had the same issue because I've added the team feature next.

You can solve, as suggested by Taylor, adding the follow lines to `JetstreamServiceProvider@boot`:
```php
Jetstream::createTeamsUsing(CreateTeam::class);
Jetstream::updateTeamNamesUsing(UpdateTeamName::class);
Jetstream::addTeamMembersUsing(AddTeamMember::class);
Jetstream::inviteTeamMembersUsing(InviteTeamMember::class);
Jetstream::removeTeamMembersUsing(RemoveTeamMember::class);
Jetstream::deleteTeamsUsing(DeleteTeam::class);
Jetstream::deleteUsersUsing(DeleteUser::class);
```
