### ISSUE TITLE
Jetstream installed in Laravel subdirectory does not work

### ISSUE THREAD

**Issue by dotjan37** [laravel/jetstream#189]
- Jetstream Version: 
- Jetstream Stack: LiveWire
- Laravel Version: 8
- PHP Version: 7.4.10
- Database Driver & Version: MySQL 

### Description:
Jetstream is not correctly installed when Laravel is installed in a subdirectory of  the server. For example: links contains href="/dashboard" but / references the root of the server and not where jetstream is installed (for example: domain.com/subdir1/subdir2/laravel/public/

### Steps To Reproduce:
Install Laravel and Jetstream in a subdirectory

**Comment by driesvints** [comment]
We don't support Laravel in a subdirectory: https://laravel.com/docs/8.x#directory-configuration

![Screenshot 2020-09-14 at 15 09 33](https://user-images.githubusercontent.com/594614/93089920-50412880-f69c-11ea-870f-52b4c15ca4ed.png)

**Comment by dotjan37** [comment]
But the "public" folder of a Laravel installation can be in a subdir of the root web dir.

**Comment by snapey** [comment]
As it says, this is not a recommended arrangement and you can end up with your .env and logfiles publicly browsable.

**Comment by dotjan37** [comment]
Laravel is installed outside the public web root (so .env en logfiles are not publicly browsable) but only the Laravel "public" folder can be a subdirectory of the webroot (many projects on one webserver), so Jetstream templates will not work correctly because all links are based on "root /".

**Comment by tauseefsshah** [comment]
@driesvints Why isn't the `url()` helper not being used by default for generating the jetstream links 😓
