### ISSUE TITLE
dark and light theme.

### ISSUE THREAD

**Issue by shirazsoft** [laravel/jetstream#191]
Please add dark and light themes.

**Comment by taylorotwell** [comment]
No plans. It would essentially force people to make their entire application dark mode supportable.

**Comment by eugenevdm** [comment]
I think things have changed a lot since 2020. Tailwind's dark mode directive makes it super easy to instantly activate dark styles where available. This feature request really seems useful in 2022.

**Comment by dinhngocvuong** [comment]
> 

+1 for dark mode

**Comment by marknuyens** [comment]
+1

**Comment by jonathan-brown** [comment]
+1

**Comment by Frankie813** [comment]
+1

**Comment by chrisheanan** [comment]
+1

**Comment by eazyurk** [comment]
+1

**Comment by prodelpe** [comment]
+1 one more

**Comment by mesiarm** [comment]
+1 for dark mode

**Comment by carcinocron** [comment]
> It would essentially force people to make their entire application dark mode supportable.

That would literally be a good thing.

**Comment by FinnPaes** [comment]
https://github.com/laravel/jetstream/commit/dcc3f9f1213c2a709fcb3e98314e30b513090b1f

**Comment by MCKLtech** [comment]
> [dcc3f9f](https://github.com/laravel/jetstream/commit/dcc3f9f1213c2a709fcb3e98314e30b513090b1f) 👀

This took me by surprise when I installed it last week. The default components will be in dark mode if your system has dark mode enabled. Doesn't currently apply to the entire default theme, so you get this weird half and half. 

In case anyone wants to disable dark mode or use a switcher, you can add this in tailwind.config.js

`
module.exports = {
    content: [
        //Foo
    ],
    darkMode: 'class',
    
    //Bar
};`
