### ISSUE TITLE
Prevent overwriting existing views on install

### ISSUE THREAD

**Issue by jimmitjoo** [laravel/jetstream#193]
Wouldn't it be nice to not overwrite existing views on install?

On a personal project I had Jetstream installed and then made changes in view files related to Jetstream Livewire. Since the project I am working on is of an "installable" type, I ran a reinstall of my own project, which triggered an "reinstall" of Jetstream, which made all the changes dissapear.

Maybe just an edge case not worthy caring about..

But would a PR that checks if files exists before publishing them be something the Laravel team likes?

**Comment by driesvints** [comment]
Jetstream is meant to be used on fresh Laravel installations. Otherwise upgrading would indeed involve manually work for checking existing views. You're free to PR something however if you like.
