### ISSUE TITLE
Inertia: Unused "SwitchableTeam.vue" component with blade syntax 

### ISSUE THREAD

**Issue by rasmuscnielsen** [laravel/jetstream#202]
- Jetstream Version: 1.1.2
- Jetstream Stack: Inertia
- Laravel Version: 8.1.0
- PHP Version:7.4
- Database Driver & Version: N/A

### Description:

In the auto-generated Inertia stubs there is a Jetstream/SwitchableTeam.vue file. To great confusion this contains a blade @if statement: https://github.com/laravel/jetstream/blob/1.x/stubs/inertia/resources/js/Jetstream/SwitchableTeam.vue

After digging further I found the component is never used, as the team-switcher is implement straight in AppLayout.vue.

If my assumptions are correct, I'd suggest to simply remove the file from the scaffolding.

### Steps To Reproduce:

`laravel new test --jet --teams --stack inertia`

**Comment by driesvints** [comment]
I think so too.
