### ISSUE TITLE
General error: 1364 Field 'reg_number' doesn't have a default value 

### ISSUE THREAD

**Issue by imhitt** [laravel/jetstream#208]
Hi,

Problem: 
Absolute clean jetstream laravel project. I can not register user. Also 80% of my request to register page returns me 419 error. (im tried to reload page before send request)

What i did:
i created a new Jetstream application with command `laravel new project-name --jet` and selected Livewire.
Afret build assets with `npm install && npm run dev` and run migration with `php artisan migrate`.

**Comment by imhitt** [comment]
Issue fixed by:
`app\Actions\Fortify\CreateNewUser.php line 31`
`'password' => Hash::make($input['password'])` changed to `'password' => bcrypt($input['password'])`

**Comment by snapey** [comment]
Can you explain your question title?  reg_number is not part of a vanilla install.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
