### ISSUE TITLE
Inertia scaffolding not supporting base url like http://domain/project

### ISSUE THREAD

**Issue by billygl** [laravel/jetstream#213]
- Jetstream Version: v1.2.1
- Jetstream Stack: Inertia 
- Laravel Version: v8.3.0
- PHP Version: 7.3.1
- Database Driver & Version: mysql 5.7.24 - MySQL Community Server

### Description:
Inertia scaffolding not supporting base url like http://domain/project. The urls go to absolute url in:
- resources\js\Layouts\AppLayout.vue
- resources\js\Pages\Profile\UpdatePasswordForm.vue
and others

That generates 404 pages when clicking profile and others.

### Steps To Reproduce:
- Place project in a subfolder in main domain, e.g. project, so url of project is: http://domain/project
- update .env, set APP_URL=http://domain/project/public
- run: npm run dev

**Comment by driesvints** [comment]
We don't support running Laravel in a subdirectory: https://laravel.com/docs/8.x#directory-configuration
