### ISSUE TITLE
Default team will not work if primary key for user changes from id() to uuid()

### ISSUE THREAD

**Issue by AngelinCalu** [laravel/jetstream#218]
- Jetstream Version: 1.2.1
- Jetstream Stack: Livewire
- Laravel Version: 8.4.0
- PHP Version: 7.4.6
- Database Driver & Version: Ver 15.1 Distrib 10.5.4-MariaDB, for Win64 (AMD64)

### Description:

When user registers through the form everything works perfectly. 
When I'm trying to log in with a user created with: 
```
User::factory(50)->create();
```

I'm getting an `ErrorException Trying to get property 'id' of non-object` on `currentTeam()` function from
`...\vendor\laravel\jetstream\src\HasTeams.php:28`

### Steps To Reproduce:

- Create a fresh laravel instalation with the jetstream package (livewire stack)
- Change the the primary key of the user from 'id' to 'uuid'
- Update all the relevant foreign fields to match the change.
- Create a new user through form registration -> This works normally.
- Create a new user through model factory / seeder -> This will produce the error.

**Comment by driesvints** [comment]
I think we only support regular id's but need confirmation by @taylorotwell.

/cc @crynobone

**Comment by elbaylot** [comment]
@AngelinCalu you can read this PR : #22 

[use numeric ids for users](https://github.com/laravel/jetstream/pull/22 )

**Comment by AngelinCalu** [comment]
The fact that this actually works when creating the user though the registration form, and not when creating it from the model factory, it's an alarm signal that the problem is not about using uuid's or not, but about creating a new account workflow.

From what I can see that's because in `app/Actions/Fortify/CreateNewUser.php` there is a default team created with the user, and when creating the user through the factory I would have to manually create a default team for each user to bypass the error.  

Is there something obvious that I'm maybe missing here?

```php
return DB::transaction(function () use ($input) {
            return tap(User::create([
                'name' => $input['name'],
                'email' => $input['email'],
                'password' => Hash::make($input['password']),
            ]), function (User $user) {
                $this->createTeam($user);   // <- this part here
            });
        });
```

**Comment by AngelinCalu** [comment]
For anyone else facing the same problem, my workaround was to manually create a personal team for each user created through the factory in the "seed-ing" process:

```
User::factory(50)->create();

        foreach (User::all() as $user) {
            $user->ownedTeams()->save(Team::forceCreate([
                'user_id' => $user->id,
                'name' => explode(' ', $user->name, 2)[0]."'s Team",
                'personal_team' => true,
            ]));
        }
```

The downsides remaining: 
- You have to make sure you're seeding the database before running tests that include users
- Users created inside the tests would face the same problem so only the previously created ones work

**Comment by taylorotwell** [comment]
We don't support UUIDs out of the box.

**Comment by AngelinCalu** [comment]
@driesvints, @taylorotwell any changes now that [this](https://github.com/laravel/framework/pull/44074) got merged?

**Comment by SimonMacIntyre** [comment]
This is a massive bummer. It means you cannot use `Sanctum` with `uuidMorphs` with `Jetstream`, unless many methods are overridden. I am pretty far down that path now, but not sure how painful it will be to complete or maintain.

**Comment by GringoDotDev** [comment]
For any future travelers who stumble onto this issue, here is how I solved it (I'm using nano id, but uuid should work almost the same):

1. Override Team::getRouteKeyName

```php
    public function getRouteKeyName(): string
    {
        return 'nano_id';
    }
``` 

2. Override the `teams.show` route from Jetstream (Livewire in my case, but again, similar approach applies to Inertia)

```php
use App\Models\Team;
use Illuminate\Http\Request;
use Laravel\Jetstream\Http\Controllers\Livewire\TeamController;

Route::group(['middleware' => config('jetstream.middleware', ['web'])], function () {
    $authMiddleware = config('jetstream.guard')
        ? 'auth:'.config('jetstream.guard')
        : 'auth';

    $authSessionMiddleware = config('jetstream.auth_session', false)
        ? config('jetstream.auth_session')
        : null;

    Route::group(['middleware' => array_values(array_filter([$authMiddleware, $authSessionMiddleware]))], function () {
        Route::group(['middleware' => 'verified'], function () {
            Route::get('/teams/{team}', function (Request $request, Team $team) {
                return app()->make(TeamController::class)->show($request, $team->id);
            })->name('teams.show');
        });
    });
```

All the middleware, etc. is essentially a direct copy from the vendor file included in Jetstream. Then we just override the team-id dependent route, dereference the id after dependency injection (which will be resolved how we want thanks to the `getRouteKeyName` override), and pass it to the vendor controller.

Janky? Yes. Jankier than overriding the controller? Meh, not great, but feels ok to me.

Hope it helps someone out there!
