### ISSUE TITLE
bootstrap ui

### ISSUE THREAD

**Issue by shirazsoft** [laravel/jetstream#219]
Can we use bootstrap as ui instead of TailWindCSS

**Comment by driesvints** [comment]
No plans for this sorry.

**Comment by developerewt** [comment]
I think it should be rethought. Bootstrap still is mostly used, I understand you guys want give more meaning to tailwind css, but the community mostly still use bootstrap. I read another issue that you said if someone PR that feature you guys won't accept. Sad about this, keep a branch apart with an important feature like that is useless.

**Comment by shoemoney** [comment]
Someone please fork Laravel and focus on the core.   It is so bloated now....
