### ISSUE TITLE
Invite a user to a Team

### ISSUE THREAD

**Issue by rabol** [laravel/jetstream#228]
Hi 

is there a plan for a 'Invite user to the team' functions?

As it is now, only users that is already a member of the app can become a team member.

**Comment by taylorotwell** [comment]
Yep, we may add that at some point.

**Comment by wittwerch** [comment]
@taylorotwell is there somewhere a backlog or a roadmap where you keep track of such requests? 
Not familiar how that is handled here, thx.

**Comment by driesvints** [comment]
@wittwerch we just keep track of anything internally really. We may add things in the future but are welcoming prs.

**Comment by wittwerch** [comment]
Ok, thx for the quick answer!

**Comment by kevnk** [comment]
Here's I made it happen: https://kevnk.medium.com/invite-users-to-laravel-jetstream-team-c65265b3ccbd
