### ISSUE TITLE
Sessions doesn't support User UUIDs

### ISSUE THREAD

**Issue by hlorofos** [laravel/jetstream#229]
- Jetstream Version: 1.1.2
- Jetstream Stack: Inertia
- Laravel Version: 8.2.8
- PHP Version: 7.4.9
- Database Driver & Version:

### Description:

I'm using string UUIDs for User model, jetpack create its session table regardless of User key by using
```
            $table->foreignId('user_id')->nullable()->index();
```
thus its incompatible. Have to fix by doing
```
            $table->foreignUuid('user_id')->nullable()->index();
```

### Steps To Reproduce:

Modify your User migration
```
            $table->uuid('id')->primary();
```

Modify your User model
```
    /**
     * Disable auto incremeting feature.
     * @return false
     */
    public function getIncrementing()
    {
        return false;
    }

    /**
     * Change primary key to string type.
     * @return string
     */
    public function getKeyType()
    {
        return 'string';
    }

    /**
     * Adds boot method to create UUID.
     */
    public static function bootHasUuid()
    {
        static::creating(function ($model) {
            $model->id = (string)Uuid::uuid4();
        });
    }
```

add a dependency to `composer.json`
```
        "ramsey/uuid": "^4.1",
```

Try to login to Jetpack dashboard, it wouldn't let you in.

**Comment by driesvints** [comment]
UUID's aren't supported out of the box for Jetstream.

**Comment by taylorotwell** [comment]
Sounds like you fixed it so what is the issue.

**Comment by McCaulay** [comment]
@hlorofos Thankyou for documenting this, just wasted an hour trying to figure out my problem and came across this and turned out to be my exact issue.
