### ISSUE TITLE
Failed to open stream

### ISSUE THREAD

**Issue by dominiced** [laravel/jetstream#230]
- Jetstream Version: 1.2.1
- Jetstream Stack: Livewire
- Laravel Version: 8.0.0
- PHP Version: 7.4.10

### Description:
I'm getting the same issue as in #186, however, I cannot try the suggested solution because the issue is stopping me from caching my route.

### Steps To Reproduce:
I just tried installing Jetstream into a fresh Laravel project (I installed LiveWire first).

**Comment by driesvints** [comment]
Uncache your routes before installing jetstream

```bash
php artisan route:clear
```
