### ISSUE TITLE
Add user permissions, groups and group permissions

### ISSUE THREAD

**Issue by TitusKirch** [laravel/jetstream#231]
Jetstream delivers a powerful team system as standard. However, I believe that user-generated teams are needed in fewer cases and that you are more likely to rely on user or group rights.

So I would suggest that you build in user and group rights (you should be able to assign users to multiple groups).

Important for the rights would be for me that there is the possibility to set a right to "never" and otherwise, if you are in multiple groups, the highest value is taken.

**Comment by syntafin** [comment]
This would be awesome.

**Comment by mous2890** [comment]
+1

**Comment by Hanashi** [comment]
good idea

**Comment by NanoCellWebDesign** [comment]
+1

**Comment by pschilly** [comment]
+1

**Comment by driesvints** [comment]
Please stop posting +1 comments and use the 👍 on the first comment. Thanks

**Comment by taylorotwell** [comment]
Feel free to build this into your own application.

**Comment by TitusKirch** [comment]
> Feel free to build this into your own application.

Okay, that's sad to hear, but then I will try to write an extension (open source of course).

If that is okay, I would link to it here.

**Comment by IgorDePaula** [comment]
@taylorotwell  Who is laravel without the community? Who uses forge and steam? The symfony community, laminas community, old zend? No, it is the laravel community. Look at the laminas framework, lost the community, lost the strength. Nobody forced you to build this tool and from the beginning you knew you would have suggestions. Being rude to the community just makes you hated.Please rethink your answer. This attitude made zend devs go to laravel, don't make the same mistake.
