### ISSUE TITLE
Livewire encountered corrupt data when trying to hydrate the [laravel.jetstream.http.livewire.update-profile-information-form]

### ISSUE THREAD

**Issue by NanoCellWebDesign** [laravel/jetstream#233]
- Jetstream Version: 1.2.1
- Jetstream Stack: Livewire
- Laravel Version: 8.5.0
- PHP Version: 7.4.6
- Database Driver & Version: 10.3.24-MariaDB

### Description:

Livewire\Exceptions\CorruptComponentPayloadException
Livewire encountered corrupt data when trying to hydrate the [laravel.jetstream.http.livewire.update-profile-information-form] component. Ensure that the [name, id, data] of the Livewire component wasn't tampered with between requests.

### Steps To Reproduce:

`artisan update` Use to update livewire and Jetstream to newest version

Login to user account and update photo

Press save and error happens

### Note:

I haven't changed any of the default Jetstream views or components

Seems to happen when using Valet + Webpack  BrowserSync using the Valet url as the proxy.

when running on the main valet url the error does not happen

**Comment by driesvints** [comment]
I unfortunately can't reproduce this. I'm suspecting this has something to do specifically with BrowserSync so it might be best that you ask on a support channel as we don't use that ourselves.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
