### ISSUE TITLE
allow users to have more details

### ISSUE THREAD

**Issue by eli007s** [laravel/jetstream#235]
i updated my jetstream/inertia to ask for username, first name, and last name. the only part that i can't change is the `HasProfilePhoto` to feed in the first and last name into the `ui-avatar` endpoint.

i modified it to this, but of course with any package updates this will revert giving me more headaches than i asked for.

```
    protected function defaultProfilePhotoUrl()
    {
        return 'https://ui-avatars.com/api/?name='.urlencode($this->first_name).' '.urlencode($this->last_name).'&color=7F9CF5&background=EBF4FF';
    }
```

can we get a field to pass in the data we want to pass into the `ui-avatar` endpoint?

**Comment by ahaseeb04** [comment]
I'm pretty sure changing it to `urlencode($this->first_name . ' ' . $this->last_name)` should fix the issue?

**Comment by driesvints** [comment]
This is something you can do in your own app.

**Comment by eli007s** [comment]
can you give me a small snippet on how this would be done outside the scope of jetstream while still using jetstream? i'm a newbie please be gentle.
