### ISSUE TITLE
Livewire is not defined after install

### ISSUE THREAD

**Issue by ryanmortier** [laravel/jetstream#236]
- Jetstream Version: Latest
- Jetstream Stack: Livewire
- Laravel Version: 8.5.0
- PHP Version: 7.4.3
- Database Driver & Version: mysql  Ver 8.0.21-0ubuntu0.20.04.4 for Linux on x86_64 ((Ubuntu))

### Description:
See screenshot.

### Steps To Reproduce:
1. `laravel new blog --jet`
2. Choose Livewire
3. Choose no teams
4. Edit `.env` with database name/password
5. `php artisan migrate`
6. `npm install && npm run dev`
7. `cd public`
8. `php -S localhost:8080`
9. Visit in a browser `http://localhost:8080/user/profile`

![image](https://user-images.githubusercontent.com/2053960/93691890-b45b5680-fab9-11ea-8be2-fe2aed0358c6.png)

Edit: Same issue with the composer installation into a fresh Laravel app.

**Comment by ryanmortier** [comment]
For some reason doing this makes it work:

```php
php artisan vendor:publish --tag=livewire:assets
```

**Comment by NanoCellWebDesign** [comment]
have you followed steps for installation https://jetstream.laravel.com/1.x/installation.html

`php artisan jetstream:install livewire --teams`

**Comment by taylorotwell** [comment]
Use `php artisan serve`.

**Comment by emadalslahi** [comment]
> Use `php artisan serve`.

I have same problem,  
i'm using laravel component and works fine when using php artisane serve 

but i want to run my site with no suage of artisan serve

is it mandatory to use artisane serve, 
sometimes there is some errors in some packegs that prevent artisan from running any command at all,  I face this with voyger and other pags so I need to run my site from appach server only 

I published livewire and put configutation write. 
it reach my method but return 404

**Comment by ryanmortier** [comment]
Sorry, Laravel doesn't work with the built-in PHP server now.
