### ISSUE TITLE
Updating the stubs/app/Actions/Fortify/

### ISSUE THREAD

**Issue by ClementN** [laravel/jetstream#241]
- Jetstream Version: 1.2.1
- Jetstream Stack: Inertia & Livewire
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

### Description:

Recent releases of https://github.com/laravel/fortify made several changes to the fortify stubs .

Eg ```UpdateUserProfileInformation.php```

Doesn't this require that their respective stubs from Jetstream to be updated, too ?

```jetstream/stubs/app/Actions/Fortify/```

**Comment by driesvints** [comment]
Things are a little bit different there. Feel free to send in a pr if you like
