### ISSUE TITLE
Install fails with 'file not found' error related to yargs-parser

### ISSUE THREAD

**Issue by KimPrince** [laravel/jetstream#242]
- Jetstream Version: ^1.2
- Jetstream Stack: Inertia
- Laravel Version: ^8.0
- PHP Version: ^7.3
- Laravel Installer Version: 4.0.3
- NPM version: 6.14.8

### Description:
Did a vagrant destroy a few days ago and installed the new Homestead on my Ubuntu host (20.04.1).  Trying to install Jetstream for the first time, the inertia stack, with --teams.  Tried both the 'vagrant new' method, and the composer method.  Failed both times with the following error.

```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/vagrant/code/ftmv2/node_modules/yargs/node_modules/yargs-parser/package.json.1863223755
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/vagrant/code/my_test/node_modules/yargs/node_modules/yargs-parser/package.json.1863223755'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

```
Removed the node_modules directory and retried npm_install, but outcome is the same.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by tuxd00d** [comment]
@KimPrince 

If I'm assuming correctly, you are using shared folders in VirtualBox.  There is a ongoing bug with VB shared folders.  Perhaps try a different way of sharing the directory or using a different engine such as Parallels Pro.

**Comment by KimPrince** [comment]
That makes sense.  I configured the drive as NFS (in Homestead.yaml) and it
works fine.

**Comment by dcyou** [comment]
thanks help me too, could be great to add it to the Homestead docs
