### ISSUE TITLE
Owner not attached to team like other users

### ISSUE THREAD

**Issue by mrpritchett** [laravel/jetstream#245]
When a user creates a team and is an "owner," that user is not attached to the team as a user in team_user and I don't see a way to get all users of a team in a method. This seems like an oversight, in my opinion. There are lots of methods for retrieving users and team's info, why not a way to grab ALL users associated easily and quickly?

**Comment by taylorotwell** [comment]
`$team->allUsers()`

**Comment by mrpritchett** [comment]
Much appreciated @taylorotwell and team!

**Comment by driesvints** [comment]
@mrpritchett we've also updated the docs with all the team methods: https://jetstream.laravel.com/1.x/features/teams.html#the-team-object

**Comment by mrpritchett** [comment]
Thanks, @driesvints. Y'all are rocking it. As a new-ish Laravel dev (crossed over from WP land last year), I'm extremely grateful to the quality and responsiveness of the code, the community, and the team behind Laravel. Seriously, thank you.
