### ISSUE TITLE
Make users.current_team_id an integer...?

### ISSUE THREAD

**Issue by telkins** [laravel/jetstream#252]
I just noticed that `users.current_team_id` is a string.  Is there a reason for this?  Wouldn't it be better to make it an integer...?

I might be missing something.  Admittedly, I didn't look into the code to see if it uses `teams.name` or something for that field.  My assumption is that it would use `teams.id`, which is a big integer, afaik.

So...I'm happy to put together a PR, but just wanted to get some background information in case I'm off-base on this. 🤓 

Thx...!  👍

**Comment by driesvints** [comment]
Yeah I think that's a leftover from when we were still using uuid's. Feel free to send in a PR 👍 

Thanks
