### ISSUE TITLE
Create Team Action can't disabled on JetStreamServiceProvider

### ISSUE THREAD

**Issue by IgorDePaula** [laravel/jetstream#255]
- Jetstream Version: ^1.2
- Jetstream Stack: Inertia 
- Laravel Version: ^8.0
- PHP Version: 7.4.3
- Database Driver & Version: sqlite

### Description:
Create Team Action can't disabled on JetStreamServiceProvider, I commented the code, but I yet got see the create team button

### Steps To Reproduce:

Code on JetStrreamServiceProvider
```php
/**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        $this->configurePermissions();

        Jetstream::createTeamsUsing(CreateTeam::class);
        Jetstream::updateTeamNamesUsing(UpdateTeamName::class);
        Jetstream::addTeamMembersUsing(AddTeamMember::class);
        Jetstream::deleteTeamsUsing(DeleteTeam::class);
        Jetstream::deleteUsersUsing(DeleteUser::class);
    }
```
I comment the create action for users not create a new team

```php
/**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        $this->configurePermissions();

       // Jetstream::createTeamsUsing(CreateTeam::class);
        Jetstream::updateTeamNamesUsing(UpdateTeamName::class);
        Jetstream::addTeamMembersUsing(AddTeamMember::class);
        Jetstream::deleteTeamsUsing(DeleteTeam::class);
        Jetstream::deleteUsersUsing(DeleteUser::class);
    }
```

**Comment by driesvints** [comment]
That's just the registration of the action. If you want to disable this specific action in the UI you can return `false` from the TeamPolicy: https://github.com/laravel/jetstream/blob/1.x/stubs/app/Policies/TeamPolicy.php#L44

**Comment by IgorDePaula** [comment]
@driesvints  Thank you very much, the docs not said about policies.

**Comment by driesvints** [comment]
@IgorDePaula did you uncomment `Jetstream::createTeamsUsing(CreateTeam::class);` again? You shouldn't comment it out.

**Comment by IgorDePaula** [comment]
@driesvints forget, I remember now that disabled the Create Action. Sorry.
