### ISSUE TITLE
Delete Team, user menu disappear on dashboard

### ISSUE THREAD

**Issue by IgorDePaula** [laravel/jetstream#256]
Jetstream Version: ^1.2
    Jetstream Stack: Inertia
    Laravel Version: ^8.0
    PHP Version: 7.4.3
    Database Driver & Version: sqlite

### Description:
I created 2 teams, but on delete one (not the first created) the user menu (above) disappears?
![Captura de tela de 2020-09-22 12-04-27](https://user-images.githubusercontent.com/2833993/93900488-d1677380-fccb-11ea-80f1-e0d4aca14b48.png)

### Steps To Reproduce:

create a new team, delete this team.

**Comment by driesvints** [comment]
I'm not sure what you mean. Everything looks fine?

**Comment by IgorDePaula** [comment]
@driesvints 
![output2](https://user-images.githubusercontent.com/2833993/93903066-a03c7280-fcce-11ea-8ac2-72d57c7f3289.gif)

**Comment by driesvints** [comment]
I don't get the same issue sorry

**Comment by IgorDePaula** [comment]
I'll try in another navigator, all time that I created and deleted some team, I get the same problem.

**Comment by UberEber** [comment]
It appears you can not delete the default team when teams were installed.  No matter what you renamed it to.  All the other team delete buttons work.  If you no longer need teams then Laraval documentation explains how to disable that feature.
