### ISSUE TITLE
Profile photo upload issue.

### ISSUE THREAD

**Issue by alturic** [laravel/jetstream#257]
In reference to #234, I can confirm there is definitely a delay happening between the actual user upload vs backend processing it. If you press Save too quickly it doesn't finish processing, however, if you watch DevTools and wait for the response and then hit Save everything works as expected. As @driesvints mentioned, disabling the Save button until the upload has finished is the correct approach.

**Comment by driesvints** [comment]
I'm sorry but this really seems like a very specific issue to you and the OP on a specific environment. Feel free to send in a fix if you want.
