### ISSUE TITLE
BusServiceProvider.php me da un error con paréntesis ')' inesperado

### ISSUE THREAD

**Issue by intelguasoft** [laravel/jetstream#263]
- Jetstream Version: 1.3.0
- Jetstream Stack: Livewire
- Laravel Version: 8.0.3
- PHP Version: 7.4.9
- Database Driver & Version: MySQL 8.0.0

### Description:
Después de instalar `laravel/jetstream` en mi proyecto utilizando el comando `create-project` de `Composer`, me da un error de paréntesis inesperado **syntax error, unexpected ')'** en el archivo BusServiceProvider.php (`Illuminate\Bus\BusServiceProvider`). por lo que quite la coma que aparece de ultimo en la linea 50 de dicho archivo y el error se corrige.

### Steps To Reproduce:
1. Ejecuto el comando `composer create-project --prefer-dist laravel/laravel blog``
1. Instalo el paquete `laravel/jetstream` con el comando: `composer require laravel/jetstream`
1. Luego asigno el stack que utilizare, en mi caso `Livewire` por medio del comando: `php artisan jetstream:install livewire`
1. Lanzo las migraciones con el comando: `php artisan migrate`
1. Deseo ver en el navegador el resultado y me da el error, segun la imagen adjunta.
![error jetstream](https://user-images.githubusercontent.com/6666627/94193327-75d4eb80-fe6d-11ea-8226-6a8f20f06184.png)

&#x1f1ec;&#x1f1f9; **Un abrazo desde mi bella Guatemala.** 
&#x1f1ec;&#x1f1f9;
PS: Gracias por tan excelente cambio en **Laravel**. **Laravel Jetstream** lo mejor que le pudo pasar a **Laravel**.

**Comment by jalowin** [comment]
Ok, el error esta en la linea 50, aparace el codigo asi
`config('queue.batching.table', 'job_batches'),`
y debe de estar asi
`config('queue.batching.table', 'job_batches')`
La coma del final es lo que sobra

Un saludo y good coding
