### ISSUE TITLE
content differs between browsers after clean install

### ISSUE THREAD

**Issue by Noso4eg** [laravel/jetstream#264]
**opera** - background at front page is dark, and content is center-aligned. On the login page it looks like the styles didn't apply, but on the opera network tab all files is 200 OK. Console has 2 messages: "in Startnull".
**ie** - background at front page is light and content is right-aligned, login page looks correct
**edge** - the page cannot be displayed

![2020-09-25_09-51-12](https://user-images.githubusercontent.com/11312159/94237133-07e4fe80-ff17-11ea-87d5-ae52ba00855a.png)

**Comment by driesvints** [comment]
Please re-open this with a filled out issue template, thanks.
