### ISSUE TITLE
Jetstream & Localization

### ISSUE THREAD

**Issue by schwartzmj** [laravel/jetstream#268]
Unless this already exists and I was not able to find, it would be helpful if we could apply middleware to the Jetstream/Fortify routes. I have a middleware that sets the localization for the user but I can't tap into it for any Jetstream pages/components, e.g. the profile page.

The way I'm getting the locale is a field saved in the database under the user.

Is there some other way I should be getting/setting locale?

**Comment by schwartzmj** [comment]
Hm. I could have swore that I'd tried this already, but it looks like it works as expected by adding the middleware to the 'web' middleware group in Kernel.php

**Comment by asivaneswaran** [comment]
@schwartzmj Hey, I am running into this issue. What did you add in the Kernel file?
