### ISSUE TITLE
User role after registration, either a user or administrator 

### ISSUE THREAD

**Issue by oladip** [laravel/jetstream#269]
Suggesting an implementation like the team's permission to users.
New user register with the role of a user with default permissions
Administrator register with a specific link provided or customized buy developer, like the Laratrust project, with higher permission
This would be a great support with the already implemented Terms feature.

Thanks, Jetstream.

**Comment by TitusKirch** [comment]
I think it is like #231

**Comment by driesvints** [comment]
No plans to add this to jetstream. Feel free to build this for your own app.
