### ISSUE TITLE
Invite User to Team via Signed URL | Accept/Decline Functionality | Remane Suggestion

### ISSUE THREAD

**Issue by MHassanSaqib** [laravel/jetstream#273]
When we add a new member through his email address, then there comes a scenario that the email is not existing in the users table. The application returns a form validation error saying the email is not existing.

With this validation alert to the user. We can add a button to send an invitation email to join the team. 

The email will contain a signed URL to register on the application. After successful registration, the new user will automatically be a part of the Team.

Other improvements and new features to this awesome package is the ability to accept or decline an invitation to join the team. When a user registers the first time, the team shouldn't be created automatically because might be he is not going to make any personal team, instead, he is creating an account for joining some other team so in this case, this automatic entry is redundant. 

When a user switches his team, the application should redirect back (if authorization passes) instead of going on to the dashboard? I personally think this would improve the usability of the application. 

Team should be renamed to Group. It would generalize the concept. A team is a group but the opposite can or cannot be true depending on the scenario. We can use groups in a wide range of scenarios. What do you guys think about my suggestions?

**Comment by driesvints** [comment]
Think there's a lot here that you can build into your own app.
