### ISSUE TITLE
User Navigation Menu Dropdown Styling

### ISSUE THREAD

**Issue by amayer5125** [laravel/jetstream#274]
When `Features::profilePhotos()` is disabled the styling of the user's name in the navigation bar doesn't look very good. I believe this is because the image alt text is what is being rendered. It has a gray circle around the text name that usually surrounds the profile image.
![image](https://user-images.githubusercontent.com/3212673/94353069-c77ea100-003a-11eb-9b32-e900b870b3b0.png)

When profile photos are disabled the name should be shown on one line possibly with a chevron beside it to denote that the name has a submenu.

**Comment by driesvints** [comment]
Seems like you already attempted a pr 👍
