### ISSUE TITLE
what diffrent between Gate and hasTeamPermission?

### ISSUE THREAD

**Issue by youyi1314** [laravel/jetstream#278]
- Jetstream Version: ^1.1
- Jetstream Stack: Inertia / Livewire
- Laravel Version: ^8.0
- PHP Version: 7.3
- Database Driver & Version: Mysql 5.7.31

### Description:
what diffrent between Gate::check('add_team_member', Team::find(1)) and User::find(1)->hasTeamPermission('add_team_member', Team::find(1))
because in blade i use Gate::check('add_team_member', Team::find(1)) it show **false**, but use User::find(1)->hasTeamPermission('add_team_member', Team::find(1)) it show **true**
and try inside `php artisan tinker` also

Below is my **JetstreamServiceProvider**
![image](https://user-images.githubusercontent.com/8391468/94476366-f6477380-0202-11eb-91c4-5521d5d828dd.png)

below is my teams table:
![image](https://user-images.githubusercontent.com/8391468/94476552-39094b80-0203-11eb-84e8-8b5872942079.png)

below is my users table:
![image](https://user-images.githubusercontent.com/8391468/94476619-4f170c00-0203-11eb-8292-cf99c6ce6017.png)

below is my tinker result:
![image](https://user-images.githubusercontent.com/8391468/94476774-808fd780-0203-11eb-9930-c5cca70a90a5.png)

### Steps To Reproduce:

edit JetstreamServiceProvider
![image](https://user-images.githubusercontent.com/8391468/94476366-f6477380-0202-11eb-91c4-5521d5d828dd.png)

edit **app/Actions/Fortify/CreateNewUser.php**
![image](https://user-images.githubusercontent.com/8391468/94476974-ce0c4480-0203-11eb-87c4-9bab84e1a0b6.png)

php artisan optimize
composer dumpautoload
php artisan migrate:reset (and re create new user and teams with owner)

register new user
than go to **Edit Team Settings**
and this is my Team Settings Page
![image](https://user-images.githubusercontent.com/8391468/94477121-090e7800-0204-11eb-832b-83617b2b479a.png)
cant delete, add team member there.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
