### ISSUE TITLE
Vue files as npm package

### ISSUE THREAD

**Issue by lostdesign** [laravel/jetstream#28]
Based on PR #26 i had the idea of moving the vue files for jetstream into their own npm package or build them as npm package additionally. Eventually this could be used for maintaining Laravel's UI components in a monorepo with Storybook, if there ever were plans to also create React Components when combined with Inertia. 

This enables people to use the UI+fortify to build their own jetstream? Or are there any plans of adding more "flavors" for jetstream at a later point? Tbh, I am not sure what flavors could even be added, other than "plain" which is just exposing an API using sanctum?

**Comment by LewisLarsen** [comment]
Would support a "plain" variant, more options never hurt and it would offer an alternative route other than Livewire/Inertia.

**Comment by lostdesign** [comment]
I am wondering though, if "plain" isn't just using fortify or if its better for over there then.

**Comment by driesvints** [comment]
Gonna wait a bit to see how #26 goes before deciding upon this.

**Comment by driesvints** [comment]
Tbh, I don't think we'll take this approach anyway. But the PR might help the ease in using different frameworks.
