### ISSUE TITLE
Class 'App\Models\Team' not found when change namespace of User, Team, Membership

### ISSUE THREAD

**Issue by bendo01** [laravel/jetstream#280]
- Jetstream Version: 1.3
- Jetstream Stack: Livewire
- Laravel Version: 8.6
- PHP Version: 7.4.10
- Database Driver & Version:
Postgresql 12
### Description:
it show error message: Class 'App\Models\Team' not found
### Steps To Reproduce:
- change migration file primary key using uuid instead of int
- move class Membership, Team, User from App\Models to App\Models\Authentification
- try to register a user
- i put the application on https://github.com/bendo01/laravel8fresh

thank you

**Comment by octoper** [comment]
You need to set the models in your JetstreamProvider in `boot()` method
```php
Jetstream::useUserModel('App\Models\Authentification\User');
Jetstream::useTeamModel('App\Models\Authentification\Team');
Jetstream::useMembershipModel('App\Models\Authentification\Membership');
```

**Comment by bendo01** [comment]
after try your ( @octoper ) solution, the error still occur
try to modify by using this

Jetstream::useUserModel(App\Models\Authentification\User::class);
Jetstream::useTeamModel(App\Models\Authentification\Team::class);
Jetstream::useMembershipModel(App\Models\Authentification\Membership::class);

it has same results  the error still occur

**Comment by bendo01** [comment]
Thank You so much for your suggestion, it works
