### ISSUE TITLE
Please add ability to assign/add Middleware to all auth routes

### ISSUE THREAD

**Issue by jaygaura** [laravel/jetstream#281]
I am trying to use Jetsream (livewire) for the first time while building a multi-lang app.

I can easily code a middle-ware to set locale, and I can obviously assign that to any route, except the auth routes, which I have not found a way to tap into. The best I could come up with seems like a work-around at best. Like for example I can set locale in the GuestLayout component class construct method. That works for the views, but not for validation messages on pages like reset password.

Am I failing to see an obvious easy solution here? If not, I'd hope for a better support here. Like a way to assign an additional middle-ware to all the Auth routes in the config file perhaps.

**Comment by joelbutcher** [comment]
@jaygaura this already is possible. If you add a `middleware` array to your `config/jetstream.php` config file, the routes inherit this. It currently defaults to `['web']` for both inertia and livewire.

It is a bit confusing, and perhaps requires a PR to update the config file with this already in there.

**Comment by jaygaura** [comment]
> @jaygaura this already is possible. If you add a `middleware` array to your `config/jetstream.php` config file, the routes inherit this. It currently defaults to `['web']` for both inertia and livewire.
> 
> It is a bit confusing, and perhaps requires a PR to update the config file with this already in there.

Thank you @joelbutcher ! Yes, I do see that in the code now that you mentioned it. (Sorry, should have checked) Although for some reason when I added my middleware to the config like below

`'middleware' => ['web', 'locale']; // the locale middleware is registered in Kernel`

it did not work for me. However, I simply added my custom middleware to the "web" group and that seems to work for all routes now. Beautiful!
