### ISSUE TITLE
Undefined class constant 'HOME' at trying to install jetstream livewire stack

### ISSUE THREAD

**Issue by inoprime** [laravel/jetstream#284]
- Jetstream Version: 1.3.1
- Jetstream Stack: Livewire
- Laravel Version:8.6.0
- PHP Version: 7.3.8
- Database Driver & Version: Mysql Server 5.7

### Description:
I already have an aplication and trying to install and use jetstream from now, then when I tried to install jetstream with livewire stack and gotting this erro:

```
Installation failed, reverting ./composer.json to its original content.

In fortify.php line 64:

  Undefined class constant 'HOME'
```

### Steps To Reproduce:

Run command:

`php artisan jetstream:install livewire --teams`

**Comment by driesvints** [comment]
You're probably missing this constant here: https://github.com/laravel/laravel/blob/master/app/Providers/RouteServiceProvider.php#L20
