### ISSUE TITLE
Jetstream livewire scaffolding did not work

### ISSUE THREAD

**Issue by VamshiSeshasayan** [laravel/jetstream#286]
Hi, I have installed Laravel 8 latest version on docker using this [tutorial](https://www.digitalocean.com/community/tutorials/how-to-set-up-laravel-nginx-and-mysql-with-docker-compose) today. Then for scaffolding I installed Laravel-Jetstream's livewire in dcoker using composer.
`composer require laravel/jetstream`
`php artisan jetstream:install livewire`
and
`npm install && npm run dev`

But the rendering has failed. Images attached. I am not sure what I am missing.

![image](https://user-images.githubusercontent.com/4988277/94725455-6841c900-0379-11eb-8bab-c3b8da9320db.png)

![image](https://user-images.githubusercontent.com/4988277/94725409-552ef900-0379-11eb-86a2-582769671337.png)

**Comment by octoper** [comment]
Did you run `npm install && npm run dev` after `php artisan jetstream:install livewire`?

**Comment by VamshiSeshasayan** [comment]
Yes, I did.

**Comment by octoper** [comment]
Wich browser do you use?

**Comment by VamshiSeshasayan** [comment]
Chrome

**Comment by FoksVHox** [comment]
Try CTRL + F5

**Comment by octoper** [comment]
Check your Devtools for any errors `Ctrl+Shift+I`

**Comment by VamshiSeshasayan** [comment]
No errors

**Comment by VamshiSeshasayan** [comment]
I cleared both cache and views. The same failed in first installation.  This is the second installation. Now it works!
`docker-compose exec app php artisan cache:clear`
`docker-compose exec app php artisan views:clear`

**Comment by octoper** [comment]
Try opening your devtools again, and reload the page with devtools open, and go to the Networrk tab and see if `app.css` is loaded

**Comment by VamshiSeshasayan** [comment]
@octoper Thank you very much.
