### ISSUE TITLE
Add tools to make testing involving teams simpler

### ISSUE THREAD

**Issue by cole-flexsim** [laravel/jetstream#287]
simplest solution would be to add a default factory for teams that just needs a user id

The more useful solution would be to make it so that when the UserFactory makes a new user it triggers the createTeam functionality that is present in the App\Actions\Fortify\CreateNewUser class. This way we don't have to manually create a personal team for any fake users we use in our Test Classes

**Comment by driesvints** [comment]
Feel free to PR something 👍
