### ISSUE TITLE
Jetstream update command

### ISSUE THREAD

**Issue by octoper** [laravel/jetstream#288]
## Problem
When updating to a new version of Jetstream most of the backend code is updated (except the files that were published to the app on install like the JetStreamProvider) and the Blade Components are updated too in the `resources/views/vendor/jetstream`.
The problem is that every other view files don't get updated, surely you can reinstall Jetstream and it will publish them again, but any changes that have been made will be lost.

## Solution (in my opinion)
The best solution I have found is adding a new command called `update`, this command will be almost identical to `install` but it will check the files from the package and the files that have been published to the app and merge them with Git Merge like functionality.

**Comment by driesvints** [comment]
Yeah I agree we need some sort of sync command to keep these files updated when new versions get released. Although it should still be a conscious action since some people might have adjusted these files.

> the Blade Components are updated too in the resources/views/vendor/jetstream.

This isn't true I believe? You still need to do this yourself?

**Comment by octoper** [comment]
Oh sorry the Blade components can be updated.

I have tried something but I couldn't figure how to do it properly 😕

**Comment by octoper** [comment]
I think I have found a solution but I don't think that will work nice 😕

**Comment by taylorotwell** [comment]
My take on it is the views simply can't be updated once they are published. Once Jetstream is installed and everything is published - it is your application. You may have changed the views in a way that we can not and should not overwrite them, etc.

**Comment by taylorotwell** [comment]
In other words, Jetstream is just a starting point. Once it is installed - it is your application.
