### ISSUE TITLE
Add the capability to change the uri for teams

### ISSUE THREAD

**Issue by likeadeckofcards** [laravel/jetstream#289]
At the moment, if a developer wants to change the what a team is called, this can be accomplished by using the built in translation functionality. However, there is no way to adjust the the route's URL. What are thoughts on making a config property to adjust this?

```php
'routes' => [
    'plural' => 'teams',
    'singular' => 'team'
]
```

**Comment by octoper** [comment]
Do you mind explaining why thats needed?

**Comment by driesvints** [comment]
Don't think we'll add this as previous attempts have been rejected.
