### ISSUE TITLE
Unable to access jetstream.laravel.com website

### ISSUE THREAD

**Issue by StefanoGroenland** [laravel/jetstream#291]
Hi everyone! 

Since a few days i am unable to open the documentation website related to this library. I've had a few "weird" issues when i try to navigate to jetstream.laravel.com

### With Valet running
![image](https://user-images.githubusercontent.com/6575921/94776632-5d5f5680-03c2-11eb-8da2-5bdb09f2406c.png)

### Without any local development service running
![image](https://user-images.githubusercontent.com/6575921/94780923-6f90c300-03c9-11eb-8c23-88d7f0c38da4.png)

I hope anyone else had this issue as wel, i can't seem to figure out why i can't connect to it..

Any tips or possible tricks to fix this are welcome!

Thankyou!

**Comment by driesvints** [comment]
Seems to work fine for me.

**Comment by StefanoGroenland** [comment]
I wasn't talking about the global uptime. It works on my iPhone as well.

But the fact that Valet messes with the reaching of the website i was wondering if someone had experienced this and knows a fix. Since i can't access the documentation on my Macbook now. (also without valet, which is the second screenshot)

**Comment by StefanoGroenland** [comment]
Wait a minute. It seems to get messed up when using the app tld in valet. Which is configured in the Dnsmasq configuration.

And since when pinging jetstream.laravel.com results in the following data : 

![image](https://user-images.githubusercontent.com/6575921/94803374-7d564080-03e9-11eb-8e2b-3e514bd7fe1d.png)

Changing the tld to something else fixed it.

**Comment by driesvints** [comment]
@StefanoGroenland iirc that tld was changed as the default one to .test about a year ago when .app became an actual TLD that could be purchased. You might be running an outdated valet install or maybe haven't updated the default tld yet.
