### ISSUE TITLE
Default Avatar photos are down

### ISSUE THREAD

**Issue by anthonywkchan** [laravel/jetstream#295]
https://github.com/laravel/jetstream/blob/39143d099282e8cba0e562481aa6b7d409f04266/src/HasProfilePhoto.php#L64

So it looks like https://ui-avatars.com is down right now, which breaks the default profile photo rendering. Not sure what the best course of action here is, but maybe self-generating default text avatars via Tailwind would be a safer approach as opposed to relying on an external API? 

I'd be happy to submit a PR if that's preferred.

**Comment by driesvints** [comment]
Seems to be up again
