### ISSUE TITLE
Import teams

### ISSUE THREAD

**Issue by aecy** [laravel/jetstream#299]
Hi, i tried jetstream is amazing. But i install without --teams

Can i import the flag teams for more features on my project without remove of my actual code ?

Sorry for my english, thanks you.

**Comment by joelbutcher** [comment]
@aecy Teams is readily available with or without the `--teams` flag on install. All the flag does is remove the feature from your apps `jetstream.php` config. Simply update the features like so
```php
    ...
    'features' => [
        Features::profilePhotos(),
        Features::api(),
        Features::teams(),
    ],
    ...
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by MCA332VSE** [comment]
I have been hacked by wannabes that are making profit of my intellectual and personal property ILL SPLIT ALL RECOVERED ASSETS AND BONUSES FOR THERE NAMES AND LOCATIONS!! 
   ThEY ARE NOT THE GOOD ONES YHESE ARE THE EMBODIMENT OF WHAT I THOUGHT YOU ALL FOUGHT AGAINST, BIG GROUPS TRYING TO CRUSH SMALL INDIVIDUALS, THE OFFER IS VALID PLEASE DONT LET THESE WORMS RUIN THE IDEALS YOU WHERE FOUNDED!!
