### ISSUE TITLE
Make x-jet-modal scrollable

### ISSUE THREAD

**Issue by jaapiyo** [laravel/jetstream#302]
I just found out that the standard modal component is not scrollable when it has long content on it. I have tried adding a ```overflow-y: auto; ``` to it's style tag but that doesn't work because the scrolling is happening to the page in the background.

**Comment by driesvints** [comment]
Feel free to PR something thanks.

**Comment by octoper** [comment]
@jaapiyo I have made a PR #305 that disables the scrolling is happening to the page in the background. So yu can check it with it if you can make the x-jet-modal scrollable

**Comment by andreich1980** [comment]
Resolved via #378
