### ISSUE TITLE
No way to set base url / inertia stack

### ISSUE THREAD

**Issue by gdinko** [laravel/jetstream#303]
- Jetstream Version: #.#.#
- Jetstream Stack: Inertia / Livewire
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

### Description:

No way to set the base url

### Steps To Reproduce:

Install laravel 8 in subfolder localhost/blahblah
in jetstream / intertia all request and links does not work
No way to set the base url

**Comment by rodrigopedra** [comment]
Using Laravel in a subfolder is not supported.

Reference: https://laravel.com/docs/8.x#directory-configuration

> Laravel should always be served out of the root of the "web directory" configured for your web server. You should not attempt to serve a Laravel application out of a subdirectory of the "web directory". Attempting to do so could expose sensitive files present within your application.

**Comment by gdinko** [comment]
This is just great! Thanks.
