### ISSUE TITLE
Disable auto create team at register

### ISSUE THREAD

**Issue by LenkaSoma** [laravel/jetstream#304]
Hello,

I don't think I'm in the right place to ask for this but I couldn't find any other place I could ask for a hand.

It's been a few days since i just tried to disable creating a team when registering, i modified the `CreateNewUser.php` file accordingly but it gave me an error at the `HasTeams.php` more precisely in this area :

```
public function currentTeam()
    {
        if (is_null($this->current_team_id) && $this->id) {
            $this->forceFill([
                'current_team_id' => $this->personalTeam()->id,
            ])->save();
        }

        return $this->belongsTo(Jetstream::teamModel(), 'current_team_id');
    }
```

I tried to remove it completely it gives me other errors and I tried some modifications but nothing was successful, if you have any idea what I should replace this function with I would be very grateful.

Wishing you a nice evening
Cordially

**Comment by octoper** [comment]
You might need to remove the `HasTeams` trait from your User model

**Comment by LenkaSoma** [comment]
Hello

First thank you for your answer, I tried to remove the use HasTeams from User.php but it sends me back to an error about the `navigation-dropdown.blade.php` file

`Trying to get property 'id' of non-object (View: /../../resources/views/navigation-dropdown.blade.php) (View: /../../resources/views/navigation-dropdown.blade.php) (View: /../../resources/views/navigation-dropdown.blade.php)`

in this line : `<x-jet-dropdown-link href="{{ route('teams.show', Auth::user()->currentTeam->id) }}">`

I thought about deleting this part but that would remove access to team options for people who have one ...

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
