### ISSUE TITLE
Having problem install jet stream in laravel 8 project

### ISSUE THREAD

**Issue by sheriffjimoh** [laravel/jetstream#307]
- 
### Steps To Reproduce:
  
I am facing problem installing jetstream and live wire in my laravel 8 project,
I have tried run this: 
$  laravel new Eiser-Shopper -- jet

when i run that , it prompt some few question then 

bring this error

In NewCommand.php line 73:

  The Laravel installer requires PHP 7.3.0 or greater. Please use "composer c
  reate-project laravel/laravel" instead.

i treid uninstall my composer , tried update my  composer.json file but still not work ,

please anybody know what this problem is ?

**Comment by tanyudii** [comment]
what your have php version?

**Comment by taylorotwell** [comment]
The error is the PHP version.

**Comment by sheriffjimoh** [comment]
> The error is the PHP version.

thank you for your reply , how do I upgrade my PHP version. I have tried uninstalling my composer and reinstalled new just to meet up PHP version 7.3 but still 7.2.0


please how do I upgrade my PHP version for the composer

**Comment by sheriffjimoh** [comment]
> what you have PHP version?

7.2.0

**Comment by AlexWinder** [comment]
@sheriffjimoh Composer does also install PHP. You can uninstall/reinstall it all day long and it will never update your PHP version. You need to update your PHP version of your webserver/system.
