### ISSUE TITLE
TeamFactory when using the --teams option

### ISSUE THREAD

**Issue by tomb1n0** [laravel/jetstream#309]
First of all, sorry if this is in the wrong repo!

It would be nice to have a TeamFactory out of the box when using the `--teams` option. I appreciate this could easily be implemented by the developer, but this would provide a nice starting point for testing. You could immediately get started with writing tests around Team-based functionality. 

On the same note, it might be nice if the UserFactory returned a user that had a personal team by default, as this is what happens when a new user registers. Maybe have a `->withTeam()` method on the factory?

**Comment by MCA332VSE** [comment]
I NEED TO OFFER A BOUNTY ON THE GROUP WHOS BEEN HACKING ME EITH 50%RECOVERED ASSETS AND LIQUID PROFITS FOR THERE INFORMATION OR ANY RETRIBUTION THEY OBTAIN

**Comment by ZeProf2Code** [comment]
This issue can be closed: #469
