### ISSUE TITLE
Feature: Add register link to login page

### ISSUE THREAD

**Issue by stancl** [laravel/jetstream#310]
From the perspective of a non-technical user, it would be nice to have a link that takes you to the register page here.

![Screen Shot 2020-10-05 at 22 24 36](https://user-images.githubusercontent.com/33033094/95128432-b11ec680-0759-11eb-8426-49c144f571ec.png)

The register page does have this. It has an `Already registered?` link.

One solution TW UI has is a link between the logo and the form.

![Screen Shot 2020-10-05 at 22 39 27](https://user-images.githubusercontent.com/33033094/95129707-af560280-075b-11eb-8795-18bf17e7fb29.png)

Something like that might work here.

Thoughts?

**Comment by driesvints** [comment]
Think that makes sense. Feel free to pr.
