### ISSUE TITLE
User variable passed via a controller method overrides the $page.user data.

### ISSUE THREAD

**Issue by tsommie** [laravel/jetstream#317]
- Jetstream Version: 8.8.0
- Jetstream Stack: Inertia / Livewire
- Laravel Version: 8.8.0
- PHP Version: 1.3.1
- Database Driver & Version: MySql 

### Description:

I have a controller method that passes a user data via the `user` variable, now the problem is when I visit this page every other place that references `$page.user` is overridden by the user data passed in the controller so now even the logged-in user in the navigation bar is showing the name and email of the user am currently viewing and not the authenticated user. But when I visit other pages it returns to normal, it only happens on this particular controller method.

### Steps To Reproduce:

1. install Jetstream using livewire stack.

2. In my application I have a controller that allows admins to view a user profile like so:

```php
public function show(User $user)
 {
        return Inertia::render('User/Show', [
            'user'  => $user
        ]);
}
``` 

I think it is worth mentioning that I booted IntertiaJs manually in AppServiceProvider because am using livewire as my default Jetstream stack.

3. So in my AppServiceProvider I have this:

```php
/**
     * Bootstrap any application services.
     *
     * @return void
     * @throws BindingResolutionException
     */
    public function boot()
    {
        $this->bootInertia();
    }

    /**
     * Boot any Inertia related services.
     *
     * @return void
     * @throws BindingResolutionException
     */
    protected function bootInertia()
    {
        $kernel = $this->app->make(Kernel::class);

        $kernel->appendMiddlewareToGroup('web', ShareInertiaData::class);
        $kernel->appendToMiddlewarePriority(ShareInertiaData::class);
    }
```

Not sure if that is the cause but...that's basically my setup!

**Comment by drjdr** [comment]
The example `PingCRM` app uses `auth` in the InertiaJS, with a user object in there. 
$page.auth.user is as practical as the Laravel Facade equivalent. Suggestion for [2.x] ?

**Comment by drjdr** [comment]
Seems like #323 was not accepted. 
You'll have to use another variable name for these pages:
```php
public function show(User $user)
 {
        return Inertia::render('User/Show', [
            'user_profile'  => $user
        ]);
}
```

**Comment by tsommie** [comment]
Ok...I just looked up #323. Don't see why `$page.auth.user` isn't ideal. Thanks!

**Comment by driesvints** [comment]
Closing this as the related PR wasn't accepted.
