### ISSUE TITLE
MustVerifyEmail not work

### ISSUE THREAD

**Issue by AliGh1** [laravel/jetstream#318]
- Jetstream Version: 1.3.1
- Jetstream Stack: Livewire
- Laravel Version: 8.8.0
- PHP Version: 7.3

Description:
Hi, I proceeded to enable email verification according to jetstream documentation, but it still does not work
I have removed the comment on the config / fortify.php configuration file attribute input item:
`    'features' => [
        Features::registration(),
        Features::resetPasswords(),
        Features::emailVerification(),
        Features::updateProfileInformation(),
        Features::updatePasswords(),
        Features::twoFactorAuthentication([
            'confirmPassword' => true,
        ]),
    ],`
and I implemented the App \ Models \ User class of the MustVerifyEmail interface.
`use MustVerifyEmail;`

**Comment by amayer5125** [comment]
You don't want to add `use MustVerifyEmail;` to the User class. You need to make the User class implement the `MustVerifyEmail` interface. This is done like this:
```php
class User extends Authenticatable implements MustVerifyEmail
```

**Comment by AliGh1** [comment]
Thank you, it works properly now

**Comment by hojabbr** [comment]
`Features::emailVerification()` is gone!

**Comment by amayer5125** [comment]
@hojabbr are you looking in [config/fortify.php](https://github.com/laravel/fortify/blob/1.x/config/fortify.php#L18)?
