### ISSUE TITLE
Auto resize image before uploading using JavaScript

### ISSUE THREAD

**Issue by lucyacat** [laravel/jetstream#325]
Is it possible to add this feature by default, so we can upload the avatar image without any restrictions?

Jetstream is really awesome, save me a lot of time to create my own login system.

**Comment by jeffwhansen** [comment]
This would be great - as would some built in upload progress indicator!

**Comment by bridhbinary** [comment]
Yep then would need to crop and position image so they sit within the same aspect ratio

**Comment by taylorotwell** [comment]
Probably won't be taking this on in the near future. Feel free to build into your own application. The more opinions we take on the more maintenance burden and complaints I have to deal with 😄
