### ISSUE TITLE
Using the default input component as is as a checkbox is bugged due to the default CSS classes the input component uses

### ISSUE THREAD

**Issue by IvaWonderbush** [laravel/jetstream#329]
Specifically the `form-input` class within the `jetstream/components/input.blade.php`, it causes a checkbox to be stretched and seemingly not clickable.

Versions:
![image](https://user-images.githubusercontent.com/15831172/95508747-c1ca7900-09b3-11eb-8877-9e1456ae5613.png)

**Comment by driesvints** [comment]
Please resubmit this with a filled out issue template.

**Comment by driesvints** [comment]
A new one, thanks.
