### ISSUE TITLE
Best Way to Handle Permissions/Teams in Laravel Jetstream

### ISSUE THREAD

**Issue by kydiep** [laravel/jetstream#333]
In this project there are 3 type of users: admins, teachers and students. Students can only view and insert homeworks, teachers can edit/add/modify students/classes stuff (even they anagraphic) and admins that can do everything (add/delete/update everything else).

I'm undecided between 2 ways how to handle teams and permissions:

There is only 1 team "School" with roles student, teacher, admin and each role has permissions like "add-student", "delete-student", "update-teacher", etc...
There is 1 team for each entity: "classes-team", "teachers-team", "students-team". An user to add a teacher, for example, must have "create" permission for "teachers-team" or be "admin" for "admins-team"
What logic is more correct?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
