### ISSUE TITLE
Ability to disable password input in confirmation modals

### ISSUE THREAD

**Issue by BeerGrizzly** [laravel/jetstream#334]
- Jetstream Version: 1.4.0
- Jetstream Stack: Livewire
- Laravel Version: 8.9.0
- PHP Version: 7.4.10

### Description:

First things first I really want to thank you for this awesome package(s) ❤️

I unfortunately came across one limiting thing when using Jetstream in combination with Socialite for OAuth Login. There is no way to disable the password input in the confirmation modal when for example deleting an account or logging out all sessions, without editing vendor files.
 
I can't imagine that i am the only one that will come to this point. I am allowing users to login without a password with OAuth which is all working. When the user wants to delete his profile or log out all sessions there is a confirmation modal with a password field. The underlying Livewire components check if the Password is correct but the user has no password that he can enter, so he won't be able to execute those actions. 

It would be great to be able to customise or disable the password in those confirmation modals, e.g. via a simple flag in the config file.

Would love to hear your opinions on that though.

**Example of such a password confirmation modal:**
![Screenshot of modal](https://user-images.githubusercontent.com/37215927/95690385-ac558900-0c17-11eb-91cc-314860367c5f.jpg)

**Comment by wittwerch** [comment]
Such a flag could also be interesting if people login over social providers, see #214

**Comment by driesvints** [comment]
This is already noted on #214 as well so gonna close this to prevent duplicate issues.
