### ISSUE TITLE
password.confirm Middleware missing view /stubs/resources/views/auth/confirm-password.blade.php

### ISSUE THREAD

**Issue by 382580322** [laravel/jetstream#335]
- Jetstream Version: 1.4.0
- Jetstream Stack: Livewire
- Laravel Version: 8.9.0
- PHP Version: 7.4.10
- Database Driver & Version: MySQL 8.0

### Description:

> InvalidArgumentException
> View [auth.confirm-password] not found.
> http://localhost/user/confirm-password

### Steps To Reproduce:
```
Route::get('/settings/security', function () {

})->middleware(['auth', 'password.confirm']);
```
Enter in a page URL

> http://localhost/settings/security

**Comment by driesvints** [comment]
Heya, thanks. We're working on this!

**Comment by taylorotwell** [comment]
Will be included in next major release. I have it up on a branch now.

**Comment by taylorotwell** [comment]
If you need it before then you can implement the views yourself.

**Comment by adampatterson** [comment]
I ran into this today on a fresh install using JetStream v1.6.5

**Comment by Cipfahim** [comment]
Still, this problem exists. @taylorotwell  Please update this one lots of people facing this issue every day.

Quick fix:

1. Add this on JetstreamServiceProvider.php boot method

Fortify::confirmPasswordView(function (Request $request) {
      return Inertia::render('Auth/ConfirmPassword')->toResponse($request);
});
 
2. Create ConfirmPassword.vue inside resource/js/Pages/Auth )

Note: Download the attached file as an example.
[ConfirmPassword.vue.zip](https://github.com/laravel/jetstream/files/5764596/ConfirmPassword.vue.zip)

**Comment by radenir** [comment]
I am also having problem with it, would be greatful for the fix.

**Comment by joelbutcher** [comment]
@radenir https://github.com/laravel/jetstream/issues/335#issuecomment-713838827
