### ISSUE TITLE
Best way to change validate-email text?

### ISSUE THREAD

**Issue by jaapiyo** [laravel/jetstream#337]
- Jetstream Version: 1.3
- Jetstream Stack: Livewire
- Laravel Version: 8.0
- PHP Version: 7.3
- Database Driver & Version: MySQL

### Description:
I would like to change the locale of my app but I'm having difficulty finding out where the validate-email template is located. I have looked at ```artisan vendor:publish laravel-mail``` but that publishes only the blade templates of the mail message and I want to change the text. 

laravel/fortify also doesn't seem to have a section in [their documentation](https://github.com/laravel/fortify#email-verification) describing where these can be found, so I'm guessing this is done by jetstream.

### Steps To Reproduce:
Not applicable...

**Comment by aeonelo** [comment]
I think you can override the sendEmailVerificationNotification in your `User` model

```
public function sendEmailVerificationNotification()
{
    $this->notify(new App\Notifications\CustomEmailVerification);
}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
