### ISSUE TITLE
Cannot find module schema-utils

### ISSUE THREAD

**Issue by gilvaju** [laravel/jetstream#338]
- Jetstream Version: 1.4
- Jetstream Stack: Inertia / Livewire
- Laravel Version: 8.9.0
- PHP Version: 7.4.9
- Database Driver & Version: Mysql

### Description:
* Cannot find module `schema-utils`

### Steps To Reproduce:
Just one fresh instalation with:

* laravel new project-name --jet
* yarn add 
* npm run dev

### Fixing
Just: yarn add schema-utils

### Screenshot
![image](https://user-images.githubusercontent.com/677039/95866739-ab6b4700-0d3e-11eb-8769-6ee8016ce515.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
