### ISSUE TITLE
Installing Jetstream replaces users migration

### ISSUE THREAD

**Issue by RMcLeod79** [laravel/jetstream#341]
Currently when you install Jetstream it overwrites the users migration file that comes with Laravel. I had a problem with this as I had already run migrations (wasn't sure whether I would use Jetstream or not) and when I tried to enable profile photos after installing Jetstream, the column was missing from the users table.

I'm happy to create a PR to make a migration that adds the necessary columns, rather than overwriting the users migration. I just wanted to check that this is wanted/useful as I get that Jetstream would normally be installed as part of a new Laravel installation.

**Comment by joelbutcher** [comment]
@RMcLeod79 Why can't you just write a migration to add the column?

**Comment by RMcLeod79** [comment]
@joelbutcher My solution was to `migrate:fresh` as I didn't have any data I was worried about losing.

I think the issue is that because Jetstream can be installed via composer after Laravel has been installed, should the users migration be overwritten, as we can't know whether it has already been migrated.

**Comment by joelbutcher** [comment]
@RMcLeod79 I think the problem the Laravel team will have with this, is that it's an extremely rare use case, one that few people are going to be concerned with. 

At the end of the day, Jetstream was built to be the default authentication system used for new Laravel projects. I highly doubt that established applications running on Laravel will look to switch their authentication over to Jetstream without considering all the changes first. Event then, when the developers are making the change, it won't take long for them to notice the problem and write a migration to fix it

**Comment by bonzai** [comment]
See #180

**Comment by driesvints** [comment]
Please see the issue above.
