### ISSUE TITLE
Invite by email to new team member

### ISSUE THREAD

**Issue by IgorDePaula** [laravel/jetstream#345]
I read the code and see where I can block create new user and add it to new team, but the idea here is, invite a new member by email, today only invite when is already registered on system. Send email with the role ID that he must register. Is strange for me, all new user have yout own team. Is more common for me (and in my country) the first user create your team and add more users for same team.

**Comment by bonzai** [comment]
#228

**Comment by IgorDePaula** [comment]
@bonzai Thank you, but mine is slightly different.

**Comment by MHassanSaqib** [comment]
I also think this will be a great functionality. Addressed it in:

https://github.com/laravel/jetstream/issues/273#event-3813275446

**Comment by driesvints** [comment]
We're working on this atm.

**Comment by driesvints** [comment]
This has landed on master and will be available in v2

**Comment by curtisblackwell** [comment]
Is there a published release schedule for Jetstream? Does it follow the core framework's major-release-every-six-months cycle?

**Comment by driesvints** [comment]
@curtisblackwell we don't have an ETA and no it doesn't follow any fixed release schedule. We're currently still looking into improving the Inertia side of v2.

**Comment by kevnk** [comment]
Here's my stop-gap solution until V2 releases: https://kevnk.medium.com/invite-users-to-laravel-jetstream-team-c65265b3ccbd

**Comment by driesvints** [comment]
@kevnk v2 has been released over a week ago

**Comment by kevnk** [comment]
😭🤦‍♂️

**Comment by kevnk** [comment]
For what it's worth, I prefer my implementation... I think it does a better job at new user onboarding UX. 

Here's Jetstream's userflow (quote from invite email):

> You have been invited to join the New Test team!
>
> If you do not have an account, you may create one by clicking the button below. After creating an account, you may click the invitation acceptance button in this email to accept the team invitation:
>
> Create Account: http://example.com/register
>
> If you already have an account, you may accept this invitation by clicking the button below:
>
> Accept Invitation: http://example.com/team-invitations/1?signature=5d97a2378d6c3c01a1029f52cdd0d21f44a01d2dcd834daa51c508670ea2f959

This two-step process for _new_ users (which will be the use-case a majority of the time) might have been a quick solution, but it's not ideal. Instead [my implementation](https://kevnk.medium.com/invite-users-to-laravel-jetstream-team-c65265b3ccbd) does it in just one step for a new user:

1. They register with a key to the Invitation model and auto-adds them to the team and switches to that team on registration.

**Comment by ninthspace** [comment]
Furthermore, if someone registers with a different e-mail address to the one they were invited with, they won't be able to add themselves to the team.

**Comment by ttquoccuong** [comment]
how to use a numberphone instead of email?

**Comment by kevnk** [comment]
FWIW — I've created a package with my implementation (1-step invite instead of multiple): https://github.com/truefrontier/jetstream-team-invites
