### ISSUE TITLE
Validation errors do not properly work, but get thrown into a Symfony dump in a pupup

### ISSUE THREAD

**Issue by lenvanessen** [laravel/jetstream#349]
- Jetstream Version:1.4.1
- Jetstream Stack:  Livewire
- Laravel Version: 8.10.0
- PHP Version: 7.4.7
- Database Driver & Version: Mysql 8.x

### Description:
When you save an any form, like changing a password or updating your profile name, you expect validation errors to be handled in a nice way, displaying inline under or above the form.

This is also what you expect based on what the templates dictate. However, for some reason livewire/jestreams just throws them in a big in-your-face popup.
![Schermafbeelding 2020-10-16 om 12 51 24](https://user-images.githubusercontent.com/23024452/96250153-af9d9b80-0fae-11eb-8d17-01f320b702b6.png)

**Comment by calebporzio** [comment]
I just installed a fresh version of Jetstream with Livewire and was not able to replicate this issue: 
![image](https://user-images.githubusercontent.com/3670578/96273457-6002a400-0f9d-11eb-8009-6a0b8e5a44f7.png)

Livewire handles calls to `dd()` by opening that modal.

My guess is that you have something in your app that is dumping errors.

Is it possible you have overwritten something in your app's Handler.php to dump errors when caught?

**Comment by lenvanessen** [comment]
@calebporzio I've done a clean install, and now it works. But previously, I installed it into an existing laravel app, that was migrated from 7 to 8, so maybe something there is not right.
