### ISSUE TITLE
Will jetstream handle user email verification?

### ISSUE THREAD

**Issue by MarceauKa** [laravel/jetstream#35]
Hi! I'm just playing with Jetstream and it's awesome 🙏

Unfortunatly it seems to not support users with email verification, am I right?

It is something planned? I need to dive into the codebase and learn Inertia before I can make a PR.

Thank you!

**Comment by driesvints** [comment]
Yes: https://github.com/laravel/jetstream#introduction

**Comment by MarceauKa** [comment]
Hm, so this is normal?

<img width="1252" alt="screenshot" src="https://user-images.githubusercontent.com/1665333/92144213-ae594a80-ee16-11ea-818f-44681f5d44a1.png">

**Comment by taylorotwell** [comment]
Enable email verification in your config/fortify.php file.

**Comment by driesvints** [comment]
@MarceauKa we added a note about this here: https://github.com/laravel/jetstream/commit/422a4eefbdf94700027428821bbcc3f6a4797b08

**Comment by MarceauKa** [comment]
Thank you @driesvints!

**Comment by shift14wx** [comment]
Hi, i am trying to guess where the "email reset password" template is in jetstream and how i can edit it?

**Comment by shift14wx** [comment]
i found it vendor/laravel/framework/src/Illuminate/Auth/Notifications/ResetPassword.php but how i can override it?
