### ISSUE TITLE
Inertia requires redirects from `PUT`, `PATCH`, and `DELETE` methods to have a 303 response code.

### ISSUE THREAD

**Issue by wilburpowery** [laravel/jetstream#351]
- Jetstream Version: 1.4.0
- Jetstream Stack: Inertia
- Laravel Version: 8.10.0
- PHP Version: 7.4.8

### Description:

Inertia requires any redirects from a `PUT`, `PATCH`, and `DELETE` requests to have a `303` response code. This requirement makes the `Update Password` and disabling the `Two Factor Authentication` not work since they are `PUT` and `DELETE` requests and they return a redirect with a 302 status code.

### Steps To Reproduce:

- Setup a new Laravel app with Jetstream and Inertia
- Register a user
- Try to change the password for that user.
- Enable 2-factor auth and then try to disable it.

![2020-10-16 10 23 55](https://user-images.githubusercontent.com/15817188/96283800-f634cb00-0f99-11eb-82fa-e09f639ba480.gif)

**Comment by ctwillie** [comment]
I just put an a related/same issue. #352

**Comment by Chrissi2812** [comment]
Had the same issue but only with a fresh installed Jetstream App. (Older App with `inertiajs/inertia-laravel: 0.2.1` runs perfectly fine out of the box.)

Seems since https://github.com/inertiajs/inertia-laravel/releases/tag/v0.3.0 you have to run `artisan inertia:middleware` to publish the middleware and add it to your middleware stack. 

The Middleware handles this at:
https://github.com/inertiajs/inertia-laravel/blob/947dcfd5b12d9b15114c072f2121794739c7756f/src/Middleware.php#L99-L109
```php
    public function changeRedirectCode(Request $request, Response $response)
    {
        if ($request->header('X-Inertia') &&
            $response->getStatusCode() === 302 &&
            in_array($request->method(), ['PUT', 'PATCH', 'DELETE'])
        ) {
            $response->setStatusCode(303);
        }

        return $response;
    }
```

**Comment by Chrissi2812** [comment]
Okay this seems already been fixed on master branch: https://github.com/laravel/jetstream/blob/ef770afd30e2c5e8adaf5a8f17e47e837843d3d5/src/Console/InstallCommand.php#L290-L297

So we just have to wait for a new Release and in the meantime have to create the middleware via the `artisan inertia:middleware` command.

**Comment by smecnarowski** [comment]
@Chrissi2812 running this command and adding `\App\Http\Middleware\HandleInertiaRequests::class,` into Kernel.php solves the problem. Thank you.

**Comment by driesvints** [comment]
Please update your inertia version. The latest version will fix this for you.
