### ISSUE TITLE
PUT method not registered for updating user password.

### ISSUE THREAD

**Issue by ctwillie** [laravel/jetstream#352]
- Jetstream Version: 1.4.1
- Jetstream Stack: Inertia
- Laravel Version: 8.10.0
- PHP Version: 7.4.5
- Database Driver & Version: Mysql 8.0.21

### Description:
When creating a new laravel project, (laravel new foo-project --jet --stack=inertia), then logging in and attempting to update my password, I get this error, "The PUT method is not supported for this route. Supported methods: GET, HEAD.".

### Steps To Reproduce:
1. create project - laravel new project-name --jet --stack-inertia
2. Register new user.
3. Go to profile and try to update your password.

Not sure why, because inertia does seem to have the update user password route registered as a 'put' route.

**Comment by bdsumon4u** [comment]
![put-method](https://user-images.githubusercontent.com/47099791/96348131-43af5600-10c8-11eb-8f2f-483ea42f331e.PNG)

### I'm having similar type of problem:
## laravel new project-name --jet --stack-inertia
I've installed laravel just now.

Password Updates Successfully.
But, problem occurs with 'profile' route..

**Comment by ctwillie** [comment]
My issue was resolved by running this command:

```php artisan inertia:middleware```

Then adding ```\App\Http\Middleware\HandleInertiaRequests::class``` in the ```web``` middleware group in ```\App\Http\Kernel.php```.

This issue was resolved in the current master branch apparently. See issue #351.

**Comment by marijnbent** [comment]
Can confirm the comment below solves the problem. #359 is also solved.

**Comment by gustaveco** [comment]
[InertiaJS v0.3.0](https://github.com/inertiajs/inertia-laravel/releases/tag/v0.3.0) don't manage PUT DELETE etc. Redirects automatically, you need to create a middleware.
