### ISSUE TITLE
On saving Profile Information custom profile information front-end resets to default front-end

### ISSUE THREAD

**Issue by Olat-nji** [laravel/jetstream#354]
- Jetstream Version: 1.4.1
- Jetstream Stack: Livewire
- Laravel Version: 8.10.0
- PHP Version: PHP Version: 7.4.5
- Database Driver & Version: Mysql 8.0.21

### Description
I used a custom front-end for a project i worked on but on getting to the profile area, specifically the update profile information. I replaced it with my custom front-end, it worked . 
But on editing any profile information and clicking on save , the front-end updates itself back to the initial front-end that was packaged with jetstream. Clearing my custom front-end.
When i reload my custom front-end shows up normally but on save again the issue comes up

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
