### ISSUE TITLE
How to remove teams functionallity... ?

### ISSUE THREAD

**Issue by matiazar** [laravel/jetstream#356]
Hi.
i have updated my app to laravel 8 and installed jetstream with teams option
but i now dont need it.
how can i remove it? there is any way?

i want to delete tables not used from database... 
thanks in advance !

**Comment by joelbutcher** [comment]
Hi, simply comment out the `Feature::teams()` line in `config/jetstream.php`

**Comment by seansilva** [comment]
had the same problem. saolved. Thank you!

**Comment by rinoj** [comment]
> Hi, simply comment out the `Feature::teams()` line in `config/jetstream.php`

Not working in production for some reason

rying to get property 'user_id' of non-object at /home/public_html/vendor/laravel/jetstream/src/HasTeams.php:107)

**Comment by christoferd** [comment]
> Hi, simply comment out the `Feature::teams()` line in `config/jetstream.php`

It's now ```Features::teams(['invitations' => true])``` by default
22-Oct-2022

**Comment by joelbutcher** [comment]
@rinoj That's probably because you created the project without teams support then enabled the feature. Some of the stubs Jetstream publishes (models, migrations and actions) are written differently to cater for users having a personal team.
