### ISSUE TITLE
Team Ownership Transfer

### ISSUE THREAD

**Issue by ChrisCrawford1** [laravel/jetstream#358]
I have came across a use case that might apply to others.

If a user account is removed from the system and they are the original owner of that team, the team is removed along with anything associated with it, which could result in some problems. I think having the ability to change the owner of teams upon deletion could be a good idea?

The use case I refer to is something like an employee no longer works for a company and they created one/many teams that are already in use. 

I am happy to implement this feature if others think it could be of use, if not I will just leave it in my own codebase :D

**Comment by kevyworks** [comment]
Expand that feature? My take is before deleting :

1. Count members, if not

**Comment by oliverbj** [comment]
@ChrisCrawford1 I am currently in the need of exactly this. The scenario is the same: I have a potential use case where an employee can create multiple teams (and projects belonging to each team). Having that user leave the company and having the option to transfer everything would be cool.

Any chance you can share your feature?

**Comment by joelbutcher** [comment]
I was thinking about exactly this. I have something similar set up for a Laravel Webhook demo project I have set up

**Comment by joelbutcher** [comment]
@ChrisCrawford1 What would role would the original owner have after the transfer? 'admin' or 'editor'?

**Comment by taylorotwell** [comment]
Please implement this in your own applications.
