### ISSUE TITLE
When disabling two factor authentication on an Inertia stack it throws a MethodNotAllowedHttpException

### ISSUE THREAD

**Issue by victorpfm** [laravel/jetstream#359]
- Jetstream Version: 1.4.1
- Jetstream Stack: Inertia
- Laravel Version: 8.10.0
- PHP Version: 7.4.9

### Description:
In a fresh laravel and jetstream installation running an inertia stack, when I try to disable two factor authentication it throws a MethodNotAllowedHttpException:  The DELETE method is not supported for this route. Supported methods: GET, HEAD.
http://jetstream.test/user/profile 

## Steps To Reproduce:
Register an user, enable two factor authentication, disable two factor authentication.

**Comment by driesvints** [comment]
Please see https://github.com/laravel/jetstream/issues/352
