### ISSUE TITLE
MAIL_MAILER=sendmail not respected

### ISSUE THREAD

**Issue by bilogic** [laravel/jetstream#361]
- Jetstream Version: v1.4.1
- Jetstream Stack: Livewire
- Laravel Version: v8.10.0 
- PHP Version: 7.4.11
- Database Driver & Version: mysql Ver 8.0.21

### Description:
Jetstream does not send email via `sendmail` with the following `.env` config
```PHP
MAIL_MAILER=sendmail
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"
```

### Steps To Reproduce:
It only sends via `sendmail` after I modify `.env` to be
```PHP
MAIL_MAILER=sendmail
# MAIL_HOST=smtp.mailtrap.io
# MAIL_PORT=2525
# MAIL_USERNAME=null
# MAIL_PASSWORD=null
# MAIL_ENCRYPTION=null
# MAIL_FROM_ADDRESS=null
# MAIL_FROM_NAME="${APP_NAME}"
```

I tried to XDebug but got lost from all the jumping around. I also did not identify which was the main line causing the issue in `.env`

**Comment by driesvints** [comment]
Seems like you already figured out the solution to your problem 👍

**Comment by bilogic** [comment]
@driesvints but why is `MAIL_MAILER` ignored/overridden when other `MAIL_x` keys are set? Is this by design?

**Comment by driesvints** [comment]
Not sure. The sendmail mailer doesn't uses those afaik. It uses the path setting: https://github.com/laravel/framework/blob/8.x/src/Illuminate/Mail/MailManager.php#L251

https://github.com/laravel/laravel/blob/master/config/mail.php#L62

Maybe your mail.php file isn't up to date.

**Comment by bilogic** [comment]
Mine is a fresh instance installed only a few hours before I opened this issue and I visually compared with yours, it is update to date. But let's clarify my understanding first. 

1. There are many `mailers` specified in the `config/mail.php`
2. The `default` one to use is specified by `MAIL_MAILER`
3. So if `MAIL_MAILER` is `sendmail`, others such as `smtp` should never be used. Is this assumption safe?

**Comment by bilogic** [comment]
I updated the OP for better clarity

**Comment by driesvints** [comment]
Is this also a problem on a non-jetstream install?

**Comment by bilogic** [comment]
I'm not sure how to test things out. I was on L5, L6 previously and already struggled to differentiate mailables, notifications and etc. However, I have identified the line to be `MAIL_FROM_ADDRESS=null`

**Comment by bilogic** [comment]
Ok, I think I got it, `MAIL_FROM_ADDRESS=null` might be causing my `sendmail` to fail.
I thought Jetstream was using `smtp` as XDebug took me through a lot of code which seemed that way.

Anyway, thank you.
