### ISSUE TITLE
Replace "ml-*" to "mx-*" whenever possible for better support for both LTR/RTL languages, and avoid text-align attributes

### ISSUE THREAD

**Issue by KMLX28** [laravel/jetstream#363]
- Jetstream Version: 1.4.0
- Jetstream Stack: Inertia / Livewire
- Laravel Version: 8.0.0
- PHP Version: 7.4.0
- Database Driver & Version:
mysql

### Description:
In the default views, there are many uses of "ml-*" for spacing between elements that can be replaced safely to "mx-*" which better since it has the same effect for both "direction: rtl" and "direction: ltr"

The same can be said for padding.

Also, text-align should be avoided whenever possible, since the direction style can take care of the text direction.
Example: 

![لقطة الشاشة 2020-10-19 133253](https://user-images.githubusercontent.com/41856121/96439955-ee7e5c00-120f-11eb-9108-827c176638d1.png)

* Using "text-left" caused a problem for "logout" when using "direction: rtl", although "profile" is working without text-align

### Steps To Reproduce:
Any fresh installment of Jetstream with either Inertia/Livewire.

**Comment by driesvints** [comment]
Feel free to send in a PR. I'm personally not sure this is needed.
