### ISSUE TITLE
Use of custom guards specified in config/auth.php to build multi auth system in Laravel.

### ISSUE THREAD

**Issue by amit-dalal** [laravel/jetstream#364]
In lot of projects we do have multiple user tables based on requirement, so, it is not feasible to have single user table in this scenario. Result is multiple tables in database storing credentials for different roles.

In this case till now we used to specify custom guard in config/auth.php in Laravel for each credential table and use them to build multi-auth system. However, Jetstream is using single guard specified in Fortify.php.

Request: Please **provide support for use of custom guards to be written in config/auth.php to create a multiauth system**.

**Comment by taylorotwell** [comment]
Probably won't be taking this on in the near future. Feel free to build into your own application. The more opinions we take on the more maintenance burden and complaints I have to deal with 😄

**Comment by taylorotwell** [comment]
You can already customize the auth process however you wish.
