### ISSUE TITLE
Adding data from component to Jetstream Modal

### ISSUE THREAD

**Issue by zenabus** [laravel/jetstream#369]
- Jetstream Version: 1.3
- Jetstream Stack: Livewire 2.2
- Laravel Version: Laravel 8.0
- PHP Version: 7.3
- Database Driver & Version: MySQL 8.0

### Description:
I'm not sure if this is a bug or it's just my code is wrong. What I'm trying to do is populate my <select></select> with data from my database every time I open the <x-jet-dialog-modal> via button click using Livewire component. My code works as I expected but when I try to close the modal an error occurs saying "trying to get property 'id' of non-object". I don't know where to find the cause of error and how to solve this on my own so I try asking here, I'm suspecting it's the modal close event trying to clear the data inside the modal. I'm new to Jetstream and Livewire and I'm starting to love it. Here are my codes:

#### users.blade.php
Button to open the modal:
`<x-jet-button class="mb-4" wire:click="toggleUserModal">
       Add New User
</x-jet-button>`

Jetstream Modal:
`<x-jet-dialog-modal wire:model="userModal" maxWidth="lg">
      <x-slot >
          Add New User
      </x-slot>`

      <x-slot name="content">
          <div class="mt-4"> 
              <x-jet-label for="" >Full Name</x-jet-label>
              <x-jet-input type="text" class="mt-1 block w-full" />
              <x-jet-input-error for="text" class="mt-2" />
          </div>
          <div class="mt-4">
              <x-jet-label for="" >Email Address</x-jet-label>
              <x-jet-input type="text" class="mt-1 block w-full" />
              <x-jet-input-error for="text" class="mt-2" />
          </div>
          <div class="mt-4">
              <x-jet-label for="" >Position</x-jet-label>
              <select name="" id="" class="form-select rounded-md shadow-sm mt-1 block w-full">
                @foreach($positions as $row)
                  <option value="{{ $row->id }}">{{ $row->position }}</option>
                @endforeach
              </select>
              <x-jet-input-error for="text" class="mt-2" />
          </div>
          <div class="mt-4">
              <x-jet-label for="" >Campus</x-jet-label>
              <x-jet-input type="text" class="mt-1 block w-full" />
              <x-jet-input-error for="text" class="mt-2" />
          </div>
      </x-slot>

      <x-slot name="footer">
          <x-jet-secondary-button wire:click="$toggle('userModal')" wire:loading.attr="disabled">
              {{ __('Nevermind') }}
          </x-jet-secondary-button>

          <x-jet-button class="ml-2" wire:click="addUser" wire:loading.attr="disabled">
              {{ __('Add User') }}
          </x-jet-button>
      </x-slot>
  `</x-jet-dialog-modal>`

#### users.php - Livewire component
`namespace App\Http\Livewire;

use Livewire\Component;
use Illuminate\Support\Facades\DB;

class Users extends Component {

  public $userModal = false;
  public $positions = [];

  public function toggleUserModal() {
    $this->userModal = true;
    $this->positions = DB::select('SELECT  * FROM positions');
  }

  public function render() {
    return view('livewire.users');
  }
}

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
