### ISSUE TITLE
Error when installing jetstream with livewire and teams, Error:  The process "composer require "livewire/livewire:"^^"2.0" "laravel/sanctum:"^^"2.6"" exceeded the timeout of 60 seconds."

### ISSUE THREAD

**Issue by jparradog** [laravel/jetstream#37]
- Jetstream Version: ^0.6.0
- Laravel Version: ^8.0
- PHP Version: ^7.3
- Database Driver & Version: mysql

### Description:
Command: php artisan jetstream: install livewire --teams
Error installing jetstream with livewire and teams, Error: The process "composer require" livewire / livewire: "^^" 2.0 "" laravel / sanctum: "^^" 2.6 "" exceeded the timeout of 60 seconds. ".

I already tried modifying composer config: composer config --global process-timeout 5000.

I already tried to install livewire and sanctum separately and they install correctly.

When I try to install "php artisan jetstream: install livewire" without "--teams", it works but it does not allow me to log in with an already predefined user or by registration, it returns me to the login.

### Steps To Reproduce:

laravel new blog --dev
cd blog
npm install
php artisan migrate
php artisan jetstream:install livewire --teams
[http://prntscr.com/ub2b1k](url)

**Comment by taylorotwell** [comment]
Fixed.
