### ISSUE TITLE
Change email address (verification)

### ISSUE THREAD

**Issue by Loots-it** [laravel/jetstream#370]
When someone changes their email address, the mail address immediately changes, without verifying the new mail address first. Afterwards, when the user wants to check his dashboard, he can't do this because his email address isn't verified. This of course only occurs when the verification feature is on. To me, it makes more sense that the mail address only changes after the mail address is verified. With the current functionality, if the user writes a typo in his new mail address, he can't verify his account and he can't change his mail address anymore because he no longer has access to his account. So his account will be lost. Or am I missing something here?

**Comment by devingray** [comment]
For me this would be a feature that I think you would need to implement on an APP specific basis, not all apps would have this requirement and the ability to display old emails until new emails are verified would be extra overhead on the maintainers. 

To do this, you can edit the `UpdateUserProfileInformation` action and implement this logic in there

```
      $user->forceFill([
            'name' => $input['name'],
            'email' => $input['email'], // Remove this line
            'email_verified_at' => null, // Remove this line
        ])->save();

       // Do what ever you need to store the second email and send the verification mail
```

**Comment by driesvints** [comment]
No plans for this sorry.

**Comment by Loots-it** [comment]
> For me this would be a feature that I think you would need to implement on an APP specific basis, not all apps would have this requirement and the ability to display old emails until new emails are verified would be extra overhead on the maintainers.
> 
> To do this, you can edit the `UpdateUserProfileInformation` action and implement this logic in there
> 
> ```
>       $user->forceFill([
>             'name' => $input['name'],
>             'email' => $input['email'], // Remove this line
>             'email_verified_at' => null, // Remove this line
>         ])->save();
> 
>        // Do what ever you need to store the second email and send the verification mail
> ```

Indeed, I was thinking about adding an extra column to the password_resets table and updating the emailadres once the user clicks on it. It shouldn't be that much work. However, I personally think every app with email verification should have this functionality. It doesn't make sense to create accounts that can no longer be accessed just because of a typo.

**Comment by Loots-it** [comment]
> No plans for this sorry.

What if I added the functionality myself and create a pull request?

**Comment by lsmith77** [comment]
see also https://github.com/laravel/fortify/issues/331

that being said if someone could make this either an installable extension or set of customization instructions, it would be awesome.

**Comment by jimmays** [comment]
Has anyone implemented this?
