### ISSUE TITLE
Copy to Clipboard Button for API Tokens and 2FA 

### ISSUE THREAD

**Issue by MHassanSaqib** [laravel/jetstream#375]
Hi, 

Copy to clipboard button will be very useful for end-users to copy the API tokens. Also, this button will be useful in copying 2FA recovery codes and the QR code string. 

Inspired from Github:
![image](https://user-images.githubusercontent.com/7033816/96803781-ac7b3300-1426-11eb-8083-30bcb6af003b.png)

**Comment by driesvints** [comment]
No plans for this sorry.
