### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by assisfery** [laravel/jetstream#38]
### Steps To Reproduce:
 composer require laravel/jetstream

### Description:
[InvalidArgumentException]
Package laravel/jetstream at version  has a PHP requirement incompatible with your PHP version (7.2.10)

**Comment by taylorotwell** [comment]
Error message sums up your issue.

**Comment by assisfery** [comment]
Right !!!!
Which version of PHP works?

**Comment by mikebronner** [comment]
Hi @assisfery, check the composer.json file: https://github.com/laravel/jetstream/blob/master/composer.json#L17

**Comment by assisfery** [comment]
Thank you ✌️
