### ISSUE TITLE
Feature proposal: SSO server/broker implementation

### ISSUE THREAD

**Issue by lbssousa** [laravel/jetstream#380]
I would like to suggest that Jetstream offers the option to be configured as a SSO server/broker out-of-box. There are some handy SSO implementations in PHP which could be used for that:

* Generic library: https://github.com/jasny/sso

  * Example of Laravel implementation: https://github.com/awnali/SSO-laravel-5

* Generic library: https://github.com/zefy/php-simple-sso

  * Examples of Laravel implementations: https://github.com/zefy/laravel-sso, https://github.com/mi-lopez/laravel-sso

**Comment by taylorotwell** [comment]
Probably won't be taking this on in the near future. Feel free to build into your own application. The more opinions we take on the more maintenance burden and complaints I have to deal with 😄
