### ISSUE TITLE
bug: Class 'Inertia\ServiceProvider' not found when using --no-dev composer flag

### ISSUE THREAD

**Issue by ibrunotome** [laravel/jetstream#381]
- Jetstream Version: v1.4.1
- Jetstream Stack: Inertia
- Laravel Version: v8.9.0
- PHP Version: 7.4.6

### Description:

I always deploy to production with `--prefer-dist --classmap-authoritative --no-dev` composer flags, but this seems not possible when using jetstream/inertia.

<img width="463" alt="Screen Shot 2020-10-22 at 17 34 14" src="https://user-images.githubusercontent.com/4256471/96927019-d109f600-148c-11eb-83a4-89fbbbfdf0c6.png">

### Steps To Reproduce:

Create a new project with jetstream/inertia, drop vendor folder and try a `composer install --prefer-dist --classmap-authoritative --no-dev`

(I tried without --no-dev flag and works normally)

**Comment by driesvints** [comment]
Couldn't reproduce with the above steps. Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
