### ISSUE TITLE
Teams not respecting custom route key or model resolution logic

### ISSUE THREAD

**Issue by brentarcane** [laravel/jetstream#382]
- Jetstream Version: 1.5.1
- Jetstream Stack: Livewire
- Laravel Version: 8.11.2
- PHP Version: 7.4.8
- Database Driver & Version: MySQL 8

### Description:

Team model resolution is not respecting any [custom route resolution methods](https://laravel.com/docs/8.x/routing#customizing-the-resolution-logic)`. Additionally, [customizing the default key name](https://laravel.com/docs/8.x/routing#customizing-the-default-key-name) has no effect. This appears to be caused by fixed model resolution in [TeamController](https://github.com/laravel/jetstream/blob/eb35206daaad412a3763885403ee506e7e2bf667/src/Http/Controllers/Livewire/TeamController.php#L21) rather than relying on route model binding.

This prevents us from using, for example, a team `slug` rather than team `id` without reimplementing the `TeamController`.

### Steps To Reproduce:

Customize the route key or route resolution logic as per the Laravel documentation. The team URL remains in the same format, for example `http://laravel.test/teams/1`

**Comment by driesvints** [comment]
This is indeed not possible atm and is by design. I'll leave it to @taylorotwell to decide if we want to provide customization for this.

**Comment by taylorotwell** [comment]
It's not possible to use route model binding because I don't know what namespace the team is even in (people could customize it).

**Comment by emmadesilva** [comment]
> It's not possible to use route model binding because I don't know what namespace the team is even in (people could customize it).

@taylorotwell Could we reopen this? I think utilizing route model binding would feel more like Laravel, and a default value could assume `\App\Models\Team` for the model namespace, but it could be configurable in the `JetstreamServiceProvider` like we do for registering actions?

This would also fix https://github.com/laravel/jetstream/issues/218 as not everyone wants to expose numerical IDs in their routes.

Edit: `Jetstream.php` already has a static property for the `$teamModel`. Should be usable right?
