### ISSUE TITLE
GET route on /api/user not accessible

### ISSUE THREAD

**Issue by marijnbent** [laravel/jetstream#386]
- Jetstream Version: 1.4.1
- Jetstream Stack: Inertia
- Laravel Version: 8.10.0
- PHP Version: 7.4.11

### Description:
The default /api/user route is not accessible. When logged out, the login page is shown. When logged in, you get redirected to the dashboard. When accessed using Insomnia with an Authorization header and valid API key present I get a  `"message": "Unauthenticated."`.

### Steps To Reproduce:
1. Register and create an account
2. Go to /api/user
3. You get redirected to /dashboard

**Comment by bonzai** [comment]
I can't confirm using the latest version of Jetstream (1.5.1) and Laravel (8.11.2):

```js
axios.get('/api/user').then(response => {
    console.log(response.data) // {"id":1,"name":"Test User"...}
})
```

It also works in Insomania using the `Authorization` header:

```
> GET /api/user HTTP/1.1
> User-Agent: insomnia/2020.3.3
> Authorization: Bearer MY_API_TOKEN
> […]

{"id":1,"name":"Test User"...}
```

Make sure you have added your domain to `stateful` option in the `config/sanctum.php` file.

- https://laravel.com/docs/8.x/sanctum#spa-configuration

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
