### ISSUE TITLE
Missing team

### ISSUE THREAD

**Issue by IgorDePaula** [laravel/jetstream#394]
- Jetstream Version: 1.5
- Jetstream Stack: Inertia 
- Laravel Version: 8.11
- PHP Version: 7.4.3
- Database Driver & Version: sqlite

### Description:
I disable creation team on user register, now on access dashboard, the jetstream search the user team, but the user not have, he will create one.

### Steps To Reproduce:
1. On app/ACtion/Fortify/CreateNewUser.php disable line 36: $this->createTeam($user); <- add commnet in this line
2. Register a new user on register form.

![Captura de tela de 2020-10-24 22-23-20](https://user-images.githubusercontent.com/2833993/97111210-4e677d80-16bc-11eb-9d73-d82bdd73e561.png)

**Comment by bonzai** [comment]
https://github.com/laravel/jetstream/issues/117#issuecomment-690263656

> I think it is better for a user to always have at least 1 team.

**Comment by IgorDePaula** [comment]
Yes, but is strange the user self register and login with team already. I prefer that he self create a team.

**Comment by IgorDePaula** [comment]
I make a little change, but the dashboard is total blank.

**Comment by driesvints** [comment]
You always need a team record, even when teams are disabled.
