### ISSUE TITLE
Warning about run jet stream on non-fresh applications. 

### ISSUE THREAD

**Issue by weogrim** [laravel/jetstream#398]
Firstly, sorry for opening Feature request, but it is not possible to open issue on suggested; https://github.com/laravel/jetstream-docs.

Please, give red visible warning for peoples, that Jetstream will overwrite your existing work, and it is meant to be install only on fresh installations. 

There is no visible information about it, neither here: https://jetstream.laravel.com/1.x/introduction.html, nor here: https://jetstream.laravel.com/1.x/installation.html. 

There is small info on official docs: https://laravel.com/docs/8.x/authentication, but it is very easy to miss, and it does not clearly state that you may lose your work. 

Personally, I found Jetstream without looking in official documentation, and... well, I think you guessed it already. 

A simple clear message will save people the trouble.

**Comment by driesvints** [comment]
If you think anything can be better in the docs you're free to send in a PR 👍 

Side note: Jetstream is mainly meant for new Laravel projects. If you're migrating an existing project then you'll run into these issues.

**Comment by weogrim** [comment]
Unfortunately, I don't know how to add new PR, but it seems to me that the information that your package can remove people's work is so important that you should mention it in the documentation.

Your side note is not explicitly mentioned anywhere. There is not a single mention in Jeststream's documentation that the package cannot be run on top of existing projects.

**Comment by driesvints** [comment]
https://jetstream.laravel.com/1.x/installation.html#installing-jetstream

>  you may use the --jet option to create **a new Jetstream powered Laravel application**

Think that's pretty explicit?

**Comment by weogrim** [comment]
I don't think it is understandable. Yes the documentation tells how to install Jetstream on top of a new Laraval installation, but it doesn't imply that installing on top of an existing project will erase your work.

I do not want to argue with you here, because you are probably right, if you read carefully and do a research on this topic, probably after a while you would find out that the package is intended only for new projects. But I think people, including me, can easily miss that.

I tried to add my PR to dosc, I hope it turned out well :). If not, I enclose a proposal below:

On https://jetstream.laravel.com/1.x/installation.html, after *Installing Jetstream* header 

```
:::danger Do not install Jetstream on an existing project

Jetstream is meant for new projects only. Attempting to install this package on an existing project will overwrite the files and may result in loss of your work. 
:::
```

```html
<div class="custom-block danger">
    <p class="custom-block-title">Do not install Jetstream on an existing project</p>
    <p>Jetstream is meant for new projects only. Attempting to install this package on an existing project will overwrite the files and may result in loss of your work. </p>
</div>
```

**Comment by nathanDoan** [comment]
same thing happened to me :(  Newb problems I suppose
