### ISSUE TITLE
Readme docs link is 404

### ISSUE THREAD

**Issue by fletch3555** [laravel/jetstream#4]
- Jetstream Version: N/A
- Laravel Version: N/A
- PHP Version: N/A
- Database Driver & Version: N/A

### Description:
Docs link in readme currently points to a 404'd page.  I'm guessing it's more likely that the docs are still in progress than that this was an oversight, so this is mostly an FYI in case you weren't already aware.

Might be worth at least putting a "coming soon" page just to prevent the onslaught of bug reports similar to this one.

Any ETA on when we could expect them?  Or just "with 8.0 in a week"?

### Steps To Reproduce:
Click the link

**Comment by driesvints** [comment]
The docs haven't been written yet

**Comment by fletch3555** [comment]
Super fast reply.  I figured as much.  Thanks!
