### ISSUE TITLE
Add check for macro in InstallCommand like UICommand in laravel/ui

### ISSUE THREAD

**Issue by Kamona-WD** [laravel/jetstream#407]
I would like to suggest to add checking for macro in install command this will make us be able to make packages
to add more stacks like in laravel ui we can make more presets
I mean some think like this in handle method in InstallCommand class

        if (static::hasMacro($this->argument('stack'))) {
            return call_user_func(static::$macros[$this->argument('stack')], $this);
        }

        // Install Stack...
        if ($this->argument('stack') === 'livewire') {
            $this->installLivewireStack();
        } elseif ($this->argument('stack') === 'inertia') {
            $this->installInertiaStack();
        }

And finally I'm sorry for my bad English

**Comment by bonzai** [comment]
See #26.
