### ISSUE TITLE
Target [Laravel\Fortify\Contracts\CreatesNewUsers] is not instantiable.

### ISSUE THREAD

**Issue by jparradog** [laravel/jetstream#41]
- Jetstream Version: 0.6.0
- Laravel Version: 8.x-dev
- PHP Version: 7.4.2
- Database Driver & Version:mysql

### Description:
After the clean installation of Laravel with jetstream and livewire, authentication and equipment, it does not allow registration.
context:
[https://flareapp.io/share/OmVLBR78](url)

### Steps To Reproduce:
laravel new blog --dev
cd blog
npm install
php artisan migrate
php artisan jetstream:install livewire --teams
register new user

**Comment by rajakhoury** [comment]
Did you register the `FortifyServiceProvider` and `JetstreamServiceProvider`  located in App\Providers ?

**Comment by Jubeki** [comment]
It seems like under windows it works with `\n` instead of `PHP_EOL`
Don't know why though.

so it could be:
```php
file_put_contents(config_path('app.php'), str_replace(
    "App\\Providers\\RouteServiceProvider::class,\n",
    "App\\Providers\\RouteServiceProvider::class,\n        App\Providers\FortifyServiceProvider::class,".PHP_EOL,
    $appConfig
));
```

**Comment by jparradog** [comment]
The installer did not auto-register the service providers, FortifyServiceProvider and JetstreamServiceProvider, I already did it manually and it works fine now.
config\app.php
`App\Providers\FortifyServiceProvider::class,
        App\Providers\JetstreamServiceProvider::class,`

**Comment by taylorotwell** [comment]
Can't recreate on a fresh app.

**Comment by Jubeki** [comment]
@taylorotwell it happens with Windows and Git.

Git replaces `\r\n` with `\n` but PHP_EOL is still `\r\n` so in the file `config/app.php` you have Line endings with `\n` but str_replace is looking for `\r\n` (PHP_EOL) so the replacing is not happening.
