### ISSUE TITLE
Update to latest inertia packages

### ISSUE THREAD

**Issue by t-itzel** [laravel/jetstream#411]
My setup:

`laravel/jetstream` => 1.5.3
`@inertiajs/inertia` => 0.6.0
`@inertiajs/inertia-vue` => 0.4.1

Jetstream profile view breaks because of wrong access of `$page` properties 

The access was changed in https://github.com/inertiajs/inertia/releases/tag/inertia-vue%40v0.3.0
> Updated the $page property to return the full page object, instead of just the page props.

Example ( InertiaForm.js - hasErrors() )
`this.inertiaPage().errorBags` should be `this.inertiaPage().props.errorBags`

**Comment by driesvints** [comment]
Will be coming in v2

**Comment by t-itzel** [comment]
and when will v2 be released?

**Comment by driesvints** [comment]
No eta I'm afraid.
