### ISSUE TITLE
Can not scan 2FA barcode with authenticator apps if it is styled dark mode.

### ISSUE THREAD

**Issue by underwood** [laravel/jetstream#415]
- Jetstream Version: 1.5
- Jetstream Stack: Livewire
- Laravel Version: 8.12
- PHP Version: 7.4

### Description:
When styling the Profile 2FA auth page as dark mode, background color #212121 adjacent to the barcode image it wouldn't scan with the Google Authenticator App or the Symantec VIP Access Authenticator App.

Adding a white border around the barcode image resolved the issue allowing both apps to scan the barcode as expected.

I opened a pull request to add a white border around the 2FA QR code image.
https://github.com/laravel/jetstream/pull/414

### Steps To Reproduce:
Change background around barcode image on Profile 2FA to #212121.

**Comment by driesvints** [comment]
Thanks for the PR 👍
