### ISSUE TITLE
Tailwind hidden - Pagination, Navigation etc.

### ISSUE THREAD

**Issue by cfreak** [laravel/jetstream#418]
- Jetstream Version: 1.5.3
- Jetstream Stack: Livewire
- Laravel Version: 8.12.3
- PHP Version: 7.4

### Description:
i don't know why, but when i log into a fresh installation of Laravel with Jetstream, i don't see the Dropdown Navigation in the right upper corner. If i look into the console, i see that it has a hidden class, also if i integrate pagination, it is not showing because the div has an hidden class. is there any bug, or what i'm doing wrong?

### Steps To Reproduce:
Make a freh installation :-)

**Comment by driesvints** [comment]
Works fine for me:

<img width="384" alt="Screenshot 2020-10-30 at 10 24 12" src="https://user-images.githubusercontent.com/594614/97688141-11273500-1a9a-11eb-8bcc-4b53be7844b5.png">

**Comment by cfreak** [comment]
What is the process behind? 

How the hidden attribute is normally removed?

What can cause the problem?

**Comment by cfreak** [comment]
I Don't get any error in the console, didn't modify anything. Just a plain installation.

**Comment by driesvints** [comment]
Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by cfreak** [comment]
I got it a little bit closer.

Seems only to appear in Chrome but not in Firefox

Chrome Version Tested: 86.0.4240.80

**Comment by driesvints** [comment]
Works fine for me in Chrome 86.0.4240.111

<img width="1904" alt="Screenshot 2020-10-30 at 11 21 29" src="https://user-images.githubusercontent.com/594614/97693902-20aa7c00-1aa2-11eb-9ab3-9b4c3be44b8e.png">
