### ISSUE TITLE
Users name gets transmitted to ui-avatars.com

### ISSUE THREAD

**Issue by mhenkel1** [laravel/jetstream#423]
- Jetstream Version: 1.5.3
- Jetstream Stack: Inertia
- Laravel Version: 8.0.2
- PHP Version: 7.3
- Database Driver & Version: --

### Description:
I have just seen that the users name gets transmitted to ui-avatars.com by default.
This should be removed from the framework, or it should be made an option.
I don't think its a good idea to send your users names to a different website / service by default.

### Steps To Reproduce:
Install Laravel, install Jetstream with Inertia preset.

**Comment by driesvints** [comment]
If you want to change anything here feel free to send in a PR.

**Comment by mhenkel1** [comment]
@driesvints Done ;)

**Comment by pzoechner** [comment]
Why not just truncate the user's name to its initials, instead of transmitting the full name? The outcome would be the same and privacy shouldn't be a concern anymore.
