### ISSUE TITLE
Teams change stack=livewire to inertia automatic!

### ISSUE THREAD

**Issue by KatiaSishost** [laravel/jetstream#426]
this happens with Laravel 8 version and the latest version of jetstream

with a clean install of laravel ... I add composer require laravel / jetstream

then...

php artisan jetstream: install livewire .... it works OK ..

this creates the jetstream.php file ... where in one part it says stack = "livewire" ...

But then if I want to add the Teams option with the command php artisan jetstream: install livewire --teams

after doing the above steps ...
the file jetstream.php change to 'stack' => 'inertia',

Why?

I tried several times in case I was wrong and used the php artisan jetstream command: install inertia --teams by mistake ... but no, I was not wrong.

Is something wrong in this case? or should i just change stack = inertia to stack = livewire again?

**Comment by driesvints** [comment]
You need to pick the teams option up front. You can't run the install command twice.
