### ISSUE TITLE
Feature request: add a default scaffold e2e tests with cypress and Inertia

### ISSUE THREAD

**Issue by IgorDePaula** [laravel/jetstream#428]
Is possible add a default scaffold e2e tests with cypress and Inertia?

**Comment by driesvints** [comment]
Probably not something we're gonna work on ourselves.

**Comment by IgorDePaula** [comment]
I don't understand. The VueJS scaffold, , the Quasar (VueJS framework) has, why not jetstream?

**Comment by driesvints** [comment]
If you want to feel free to release a package yourself with these.

**Comment by IgorDePaula** [comment]
Sorry, but the laravel team looks like robots repeating the same phrase: "feel free". If you don't want new proposals, close the issues for new requests. It simple.

**Comment by tcox-enrollfirst** [comment]
@IgorDePaula Think about how slippery that slope is for the Laravel development team.  And where does it stop?

e.g. 
Feature Request # 187,203
Add [some ridiculously specific component] for [pick your favorite ui library] in [livewire | inertia] stack...

**Comment by IgorDePaula** [comment]
@tcox-enrollfirst Ok, now I understand, more time, sorry. I only want contrib to a new and better tool for laravel.

**Comment by driesvints** [comment]
@IgorDePaula you can't expect us to merge and maintain every single feature request we get. This is open source. You're free to build it and maintain it yourself.
