### ISSUE TITLE
Default css classes on <x-jet-input> component

### ISSUE THREAD

**Issue by vayurobins** [laravel/jetstream#435]
Hi.
I wanted to use the ```<x-jet-input>``` for a checkbox input and while this is possible, there are a couple of default CSS classes on the component, that does not go well with the checkbox input, namely "form-input shadow-sm". Maybe we could have them removed or somehow overridable? Just an idea ;-)

```<input {{ $disabled ? 'disabled' : '' }} {!! $attributes->merge(['class' => 'form-input shadow-sm']) !!}>```

**Comment by GENL** [comment]
You may wrap in in a div or template tag then remove all the classes you don't want on the children,

**Comment by driesvints** [comment]
Think it's best that you use your own component in this case.
