### ISSUE TITLE
The Session Records Steel exists after delete the user from the database.

### ISSUE THREAD

**Issue by ousid** [laravel/jetstream#438]
- Jetstream Version: ^1.6
- Jetstream Stack: Livewire
- Laravel Version: ^8.12
- PHP Version: 7.4.10
- Database Driver & Version: MySQL 10.5.5

### Description:
After the account deleted successfully, the session belongs to the deleted user steel exists in the database except the `user_id` becomes `NULL`.

### Steps To Reproduce:
Delete User Account
after the deletion completed successfully look at the records at the sessions table.

**Comment by driesvints** [comment]
I don't really see how this is a problem tbh.
