### ISSUE TITLE
When removing 3 of 4 Jetstream permissions it should display things a bit differently

### ISSUE THREAD

**Issue by rotaercz** [laravel/jetstream#442]
- Jetstream Version: 8.13
- Jetstream Stack: Livewire
- Laravel Version: 8.13
- PHP Version: 7.3.32
- Database Driver & Version:

### Description:
In laravel\app\Providers\JetstreamServiceProvider.php when you comment out 3 of the Jetstream permissions it'll still leave 1 of the checkboxes available. Ideally it should display it in a clean way where the Create button is on the same row as the token name textfield and the single checkbox shouldn't even be visible.

### Steps To Reproduce:
Just comment out 3 of the permissions and take a look at the view.

**Comment by driesvints** [comment]
Feel free to send in a PR if you want 👍
