### ISSUE TITLE
Inertia Stack doesn't respect fortify config

### ISSUE THREAD

**Issue by ManojKiranA** [laravel/jetstream#445]
- Jetstream Version: 1.6.0
- Jetstream Stack: Inertia
- Laravel Version: 8.14.0
- PHP Version: 7.4.11
- Database Driver & Version:  --

### Description:
Even after disabling the following features it doesn't hiding from profile 

```
Features::updateProfileInformation(),
Features::updatePasswords(),
```

### Steps To Reproduce:

Just try disabling the above features and refresh the profile page

**Comment by driesvints** [comment]
Correct. I'll send in a PR to fix these. Thanks for reporting.
