### ISSUE TITLE
Soft deleted users throw an error when accessing their roles

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [laravel/jetstream#446]
https://github.com/laravel/jetstream/blob/8f6fd594b67573d45d2df72fcb1f4709a3e500ea/src/HasTeams.php#L132-L134

When viewing a user that has been soft deleted, it is not possible to view the roles that they had.

```
ErrorException
Trying to get property 'membership' of non-object
```

**Comment by joelbutcher** [comment]
The code snippet you've provided works as intended, with soft-deletes applied to the model, records of that model with `deleted_at` set, are filtered out. For them not to be, breaks the underlying logic the the `SoftDeletes` trait and associated global scope.

If you require the functionality to view the roles associated with users that have been soft-deleted, then I would suggest that this is use-case specific functionality you are asking for?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by ChrisThompsonTLDR** [comment]
@joelbutcher I think it's odd that we can access any other relationship on a soft deleted record, except for the one I mentioned in this issue.  Even a simple `optional()` wrapper on this would stop it from throwing an error and gracefully fail.

Another option, since the user_id was left in the role_user table, after the user was soft deleted, would be to not go through the team -> user relationship, but rather user ->whereHas(role).
