### ISSUE TITLE
(App\Models\User)->profile_photo_url is wrong path

### ISSUE THREAD

**Issue by nguyenthemanh2601** [laravel/jetstream#449]
- Jetstream Version: v1.6.0
- Jetstream Stack: Inertia
- Laravel Version: 8.14.0
- PHP Version: 7.4.11
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.3.24-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

### Description:
trait Laravel\Jetstream\HasProfilePhoto->getProfilePhotoUrlAttribute() return wrong url

### Steps To Reproduce:
1. Run project in custom port( in my case, i run this command: php artisan serve --port=888)
2. Create an user in Jetstream
3. Enable Features::profilePhotos() on config.jetstream.features
4. Go to user/profile and chose a phote ->click save.
5. Refresh page and we can see profile photo download failed
profile_photo_path has been saved. but profile_photo_url does not contain a port 888. so, profile_photo_url is wrong and profile photo download failed

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by curtisbelt** [comment]
I was having this same issue, but then I figured it out. The URL was correct, except that it was missing the port number.

In my `.env` file, I had set `APP_URL=http://localhost` -- but the URL should have been `http://localhost:8000`.

So if anyone else runs into this, I hope this helps.
