### ISSUE TITLE
ProcessTimedOutException on installing a stack

### ISSUE THREAD

**Issue by ManojKiranA** [laravel/jetstream#45]
- Jetstream Version: 0.6.0
- Laravel Version: 8.0
- PHP Version: 7.4.3
- Database Driver & Version:

### Description:

When i try to run this command its giving me 

` Symfony\Component\Process\Exception\ProcessTimedOutException`

![image](https://user-images.githubusercontent.com/30294553/92226830-f5047e80-eec2-11ea-89d8-f9d356d992a9.png)

So i have fixed this by passing INF as time value

https://github.com/laravel/jetstream/blob/master/src/Console/InstallCommand.php#L116

https://github.com/laravel/jetstream/blob/master/src/Console/InstallCommand.php#L123

```
// Install Livewire...
        (new Process(['composer', 'require', 'livewire/livewire:^2.0', 'laravel/sanctum:^2.6'], base_path(),null,null,INF))
                ->run(function ($type, $output) {
                    $this->output->write($output);
                });

        // Sanctum...
        (new Process(['php', 'artisan', 'vendor:publish', '--provider=Laravel\Sanctum\SanctumServiceProvider', '--force'], base_path(),null,null,INF))
                ->run(function ($type, $output) {
                    $this->output->write($output);
                });

```

**Comment by driesvints** [comment]
Feel free to PR.

**Comment by driesvints** [comment]
@ManojKiranA we're gonna tag a new version which should fix this.
