### ISSUE TITLE
Features::profilePhotos() doesn't work behind ngrok.io

### ISSUE THREAD

**Issue by sathio** [laravel/jetstream#452]
- Jetstream Version: 1.6.0
- Jetstream Stack: Livewire
- Laravel Version: 8.14.0
- PHP Version: 7.4
- Database Driver & Version:
mysql
### Description:
I can upload profile photos correctly using port 8000 but behind ngrok.io tunnel I get `The photo failed to upload.`

I have this, not sure if it matters:

     resolve(\Illuminate\Routing\UrlGenerator::class)->forceScheme('https');

the stacktrace is unintelligible

    {
        "message": "",
        "exception": "Symfony\\Component\\HttpKernel\\Exception\\HttpException",
        "file": "/blah/laravel/framework/src/Illuminate/Foundation/Application.php",
        "line": 1071,
        "trace": [
            {
                "file": "/blah/laravel/framework/src/Illuminate/Foundation/helpers.php",
                "line": 44,
                "function": "abort",
                "class": "Illuminate\\Foundation\\Application",
                "type": "->"
            },
            {
                "file": "/blah/laravel/framework/src/Illuminate/Foundation/helpers.php",
                "line": 85,
                "function": "abort"
            },
            {
                "file": "/blah/livewire/livewire/src/Controllers/FileUploadHandler.php",
                "line": 22,
                "function": "abort_unless"
            },

### Steps To Reproduce:
vanilla installation of jetstream, run behind ngrok.io

**Comment by driesvints** [comment]
Not sure if this is Jetstream related tbh. Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by joelbutcher** [comment]
I've come across issues like this in the past - try running Ngrok through just `http` instead of `https`. As this is just as testing-case and not an issue with live, I don't see the reason behind it being an "issue"

**Comment by sathio** [comment]
i'm sure it's a problem with Ngrok, nonetheless the exception raised doesn't really help understanding what's going on, and I think the application should work when proxied. I can't use http because i need https to do oauth stuff with third parties

**Comment by sathio** [comment]
if I comment this from FileUploadHandler.php it works, 

    public function handle()
    {
        //abort_unless(request()->hasValidSignature(), 401);

        $disk = FileUploadConfiguration::disk();

        $filePaths = $this->validateAndStore(request('files'), $disk);

        return ['paths' => $filePaths];
    }

so i suspect that it has to do with some signature :)

**Comment by nohumans** [comment]
I have the same problem with a clean installation, in an AWS Elastic Beanstalk environment, whith Auto Scaling and load balancer, and commenting out the same line of FileUploadHandler.php works fine.

**Comment by nohumans** [comment]
Hi!
My solution! store temp files on s3 bucket.

**Comment by N30** [comment]
He is right, in my case I was using Jetstream with livewire and I edited my config/livewire.php to:
```

    'temporary_file_upload' => [
        'disk' => 's3'
```
