### ISSUE TITLE
[BUG] Missing Feature Checks in Inertia Stack

### ISSUE THREAD

**Issue by joelbutcher** [laravel/jetstream#453]
- Jetstream Version: 1.6.0
- Jetstream Stack: Inertia
- Laravel Version: 8.4.1
- PHP Version: 7.4
- Database Driver & Version: MySQL 8

### Description:
In `profile/Show.vue`, the feature flags for update profile information and update passwords are missing. 

They are, however present in the livewire stack.

I've addressed the issue in an unrelated PR, but wanted to post a bug report here for people to refer to.

See my comment [here](https://github.com/laravel/jetstream/pull/444#issuecomment-726748919): #444

### Steps To Reproduce:

**Comment by driesvints** [comment]
This hasn't been released yet so I don't think the version number is correct here? I'll add them.

**Comment by driesvints** [comment]
https://github.com/laravel/jetstream/pull/454
