### ISSUE TITLE
After installing JetStream, Stack trace showing errors in cached php files, not in original blade.php views

### ISSUE THREAD

**Issue by almazdanilov** [laravel/jetstream#455]
- Jetstream Version: 1.6.0
- Jetstream Stack: Livewire --teams
- Laravel Version: 8.10.0
- PHP Version: 7.4.12
- Database Driver & Version: 10.4.15-MariaDB

### Description:
If we have error inside View, Laravel shows blade.php file in Stack trace.
But after installing Jetstream, Laravel shows cached php file in Stack trace.

### Steps To Reproduce:
Install Jetsream according to documentation:
```
composer require laravel/jetstream
php artisan jetstream:install livewire --teams
php artisan migrate
```
After that make little mistake in welcome.blade.php, f.e. put {{$unknownVariable}} at the beginning of the file. Open website and in Stack trace you will see **Illuminate\View\Engines\CompilerEngine::handleViewException** in cached php file located in storage/framework/views/. But before installing Jetstream, Laravel was showing **Illuminate\Foundation\Bootstrap\HandleExceptions::handleError** in welcome.blade.php. It's impossible to quickly trace errors when Stack trace shows them in cached files. Cached view files absolutely different than their source blade.php files.

**Comment by srdante** [comment]
This is not a Jetstream issue.

**Comment by almazdanilov** [comment]
Tried to install livewire to fresh new Laravel project and same problem appeared. So it's really not  Jetstream's but livewire's issue. Closing.
