### ISSUE TITLE
Switching to another teams opens response in modal window

### ISSUE THREAD

**Issue by ManojKiranA** [laravel/jetstream#46]
- Jetstream Version: 0.6.0
- Laravel Version: 8.0
- PHP Version: 7.4.3
- Database Driver & Version:

### Description:

After installing the team stack in Inertia Js when i try to create a new team or switching to new team open's the response in modal window

![image](https://user-images.githubusercontent.com/30294553/92229786-a6a5ae80-eec7-11ea-9240-402f02cefa59.png)

### Steps To Reproduce:

1. Install Jetstream.
2. Install Inertia Js stack with team features.
3. Try Creating a new team or Switching teams

**Comment by taylorotwell** [comment]
Can't recreate this. If you can send a PR with the fix.
