### ISSUE TITLE
Resend Verification Email on page email/verify should have a sensible rate limiting

### ISSUE THREAD

**Issue by alan-zhang-** [laravel/jetstream#462]
I think normally, 5 resend  emails in a hour is enough.

Jetsteam is great.

**Comment by driesvints** [comment]
No plans for this

**Comment by alan-zhang-** [comment]
Thanks for reply.  But the registered person can click the Resend Verification Email a hundred times which means 1 hundred same emails in a short time, so it's better to have rate limiting.

**Comment by alan-zhang-** [comment]
> No plans for this
Thanks for reply. But the registered person can click the Resend Verification Email a hundred times which means 1 hundred same emails in a short time, so it's better to have rate limiting.
