### ISSUE TITLE
Developer Menu: Horizon, Telescope & Nova

### ISSUE THREAD

**Issue by dillingham** [laravel/jetstream#465]
Just a thought, what if Jetstream had a "developer menu".

- Nova (if installed) /nova
- Telescope (if installed) /telescope
- Horizon (if installed) /horizon

Would be extra cohesive if horizon & telescope were embedded in the Jetstream layout.

Even more if [Nova's auth dropdown was Jetstreams](https://github.com/laravel/nova-issues/issues/2928) 😇

---

![download (10)](https://user-images.githubusercontent.com/29180903/99208080-8595ef80-278d-11eb-8c1b-ac9b8c8fb3fc.png)

**Comment by seshac** [comment]
I don't think so, Those all are optional features and not much needed because developers were already aware of the Horizon, Telescope, and Nova URLs.

**Comment by SketchNI** [comment]
> I don't think so, Those all are optional features and not much needed because developers were already aware of the Horizon, Telescope, and Nova URLs.

@seshac, while this is true it would be a "nice to have" in a jetstream app right from the start.

**Comment by seshac** [comment]
Agreed, sir, ..

**Comment by taylorotwell** [comment]
Add this to your own application.

**Comment by dillingham** [comment]
@taylorotwell cool, I can see how it would be bloaty.

Would make for a good package `dillingham/jetstream-dev-menu` :)

https://github.com/laravel/ideas/issues/2439

**Comment by dillingham** [comment]
@taylorotwell kinda cool how inertia loads in frames.
Could be cool to have a sys.app.com install of jetstream with nova, horizon & telescope 
---
![Laravel](https://user-images.githubusercontent.com/29180903/102104402-25ca4d00-3dfc-11eb-98a5-9df9677b8350.gif)

**Comment by driesvints** [comment]
@dillingham that's a bug actually and resolved in the next version.

**Comment by dillingham** [comment]
@driesvints ah good to know thanks! :)
