### ISSUE TITLE
Error installing after upgrading from laravel 7.16 to 8

### ISSUE THREAD

**Issue by techguydev** [laravel/jetstream#471]
- Jetstream Version: 1.6.0
- Jetstream Stack: Livewire
- Laravel Version: 8
- PHP Version:7.4
- Database Driver & Version: MySQL 

### Description:

I am getting this error when installing:
  Problem 1
    - Conclusion: don't install laravel/jetstream v1.6.0
    - Conclusion: remove bacon/bacon-qr-code 1.0.3
    - Installation request for laravel/jetstream ^1.6 -> satisfiable by laravel/jetstream[1.x-dev, v1.6.0].
    - Conclusion: don't install bacon/bacon-qr-code 1.0.3
    - laravel/jetstream 1.x-dev requires laravel/fortify ^1.0 -> satisfiable by laravel/fortify[1.x-dev, v1.0.0, v1.0.1, v1.1.0, v1.2.0, v1.2.1, v1.3.0, v1.3.1, v1.4.0, v1.4.1, v1.4.2, v1.4.3, v1.5.0, v1.6.0, v1.6.1, v1.6.2, v1.7.0, v1.7.1].
    - laravel/fortify 1.x-dev requires bacon/bacon-qr-code ^2.0 -> satisfiable by bacon/bacon-qr-code[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - laravel/fortify v1.0.0 requires bacon/bacon-qr-code ^2.0 -> satisfiable by bacon/bacon-qr-code[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - laravel/fortify v1.0.1 requires bacon/bacon-qr-code ^2.0 -> satisfiable by bacon/bacon-qr-code[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - laravel/fortify v1.1.0 requires bacon/bacon-qr-code ^2.0 -> satisfiable by bacon/bacon-qr-code[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - laravel/fortify v1.2.0 requires bacon/bacon-qr-code ^2.0 -> satisfiable by bacon/bacon-qr-code[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - laravel/fortify v1.2.1 requires bacon/bacon-qr-code ^2.0 -> satisfiable by bacon/bacon-qr-code[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - laravel/fortify v1.3.0 requires bacon/bacon-qr-code ^2.0 -> satisfiable by bacon/bacon-qr-code[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - laravel/fortify v1.3.1 requires bacon/bacon-qr-code ^2.0 -> satisfiable by bacon/bacon-qr-code[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - laravel/fortify v1.4.0 requires bacon/bacon-qr-code ^2.0 -> satisfiable by bacon/bacon-qr-code[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - laravel/fortify v1.4.1 requires bacon/bacon-qr-code ^2.0 -> satisfiable by bacon/bacon-qr-code[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - laravel/fortify v1.4.2 requires bacon/bacon-qr-code ^2.0 -> satisfiable by bacon/bacon-qr-code[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - laravel/fortify v1.4.3 requires bacon/bacon-qr-code ^2.0 -> satisfiable by bacon/bacon-qr-code[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - laravel/fortify v1.5.0 requires bacon/bacon-qr-code ^2.0 -> satisfiable by bacon/bacon-qr-code[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - laravel/fortify v1.6.0 requires bacon/bacon-qr-code ^2.0 -> satisfiable by bacon/bacon-qr-code[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - laravel/fortify v1.6.1 requires bacon/bacon-qr-code ^2.0 -> satisfiable by bacon/bacon-qr-code[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - laravel/fortify v1.6.2 requires bacon/bacon-qr-code ^2.0 -> satisfiable by bacon/bacon-qr-code[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - laravel/fortify v1.7.0 requires bacon/bacon-qr-code ^2.0 -> satisfiable by bacon/bacon-qr-code[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - laravel/fortify v1.7.1 requires bacon/bacon-qr-code ^2.0 -> satisfiable by bacon/bacon-qr-code[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - Can only install one of: bacon/bacon-qr-code[2.0.0, 1.0.3].
    - Can only install one of: bacon/bacon-qr-code[2.0.1, 1.0.3].
    - Can only install one of: bacon/bacon-qr-code[2.0.2, 1.0.3].
    - Can only install one of: bacon/bacon-qr-code[2.0.3, 1.0.3].
    - Installation request for bacon/bacon-qr-code (locked at 1.0.3) -> satisfiable by bacon/bacon-qr-code[1.0.3].

Installation failed, reverting ./composer.JSON to its original content.

### Steps To Reproduce:

composer require laravel/jetstream

**Comment by bonzai** [comment]
Your app is using `bacon/bacon-qr-code:1.0.3` where Fortify (used by Jetstream) requires `bacon/bacon-qr-code:^2.0`.

**Comment by driesvints** [comment]
Jetstream is meant for new laravel apps, not existing ones.
