### ISSUE TITLE
Fresh install of Laravel 8.0, then add in Jetstream causes dependency issue

### ISSUE THREAD

**Issue by d2inco** [laravel/jetstream#472]
- Jetstream Version: 1.6.0
- Jetstream Stack: livewire
- Laravel Version: 8.0
- PHP Version: 5.3
- Database Driver & Version: n/a

### Description:
From fresh system, fresh laravel install, new project, attempting to scaffold with Jetstream, I get dependency errors

### Steps To Reproduce:
New system, installed:
* `composer `(from web source)
* Laravel 8 via `composer global require laravel/installer`
* created a new project with `laravel new --dev PROJNAME` (tried it with `--dev --jet --stack=livewire --teams` also)
* in the project, execute `composer require laravel/jetstream` and it generates this error:
```
composer require laravel/jetstream
Using version ^1.6 for laravel/jetstream
./composer.json has been updated
Running composer update laravel/jetstream
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - laravel/jetstream[v1.6.0, ..., 1.x-dev] require illuminate/support ^8.0 -> found illuminate/support[v8.0.0, ..., 8.x-dev] but it conflicts with another require.
    - Root composer.json requires laravel/jetstream ^1.6 -> satisfiable by laravel/jetstream[v1.6.0, 1.x-dev].
Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

(I get the same error when I try to create the project with a `--jet --stack=livewire --teams`).  Seems like the composer requirements for jetstream are out of sync with what's available

**Comment by bonzai** [comment]
Run `laravel new PROJNAME` (without `--dev`).

**Comment by d2inco** [comment]
Thank you @bonzai, that did it.

Question, then: don't I want the dev packages in place when I'm doing development??

**Comment by bonzai** [comment]
No, because if you use the `--dev` option, installer will try to install the latest development release of the framework (which is incompatible with Jetstream).

**Comment by d2inco** [comment]
got it.  Thank you.

**Comment by bonzai** [comment]
Also, if you want to install the development version of Jetstream (2.0), then you can run `composer require laravel/jetstream:dev-master` inside your app folder.
