### ISSUE TITLE
User table generated with current_team_id when teams not enabled.

### ISSUE THREAD

**Issue by ChrisBrenton** [laravel/jetstream#473]
- Jetstream Version: 1.6.0
- Jetstream Stack: Livewire
- Laravel Version: 8.14.0
- PHP Version: 7.4.11
- Database Driver & Version: MySQL: 8.0.21

### Description:
When running the initial migration after creating a new project with the `--jet` argument and not using teams, the user table is generated with a `current_team_id` field.

### Steps To Reproduce:
Create a new Laravel project via the installer and pass the --jet argument. Opt out of teams.
Migrate the database.
Using the application database, `describe` the user table. Notice that there is a `current_team_id` field.

**Comment by driesvints** [comment]
A user always needs a personal team, even with teams disabled.
