### ISSUE TITLE
Laravel 8 Wepback API configuration problem

### ISSUE THREAD

**Issue by VCollins** [laravel/jetstream#475]
- Jetstream Version: 1.6
- Jetstream Stack: Livewire
- Laravel Version: 8.14
- PHP Version: 7.3.0
- Database Driver & Version: MySQL v8.0

### Description:
using "npm run dev" results in the error "Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema. configuration.module.rules[10] has an unknown property 'loaders' "

### Steps To Reproduce:
Environment: Vagrant VM with Linux 20.04, accessed through an elevated command prompt in Windows 10.
Navigate to directory hosting Laravel 8 project
Run command "rm -rf node_modules" and wait for the command to complete
Run command "rm package-lock.json"
Run command "npm cache clear --force"
Run command "sudo npm install --global npm"
Run command "sudo yarnpkg install"
Run command "sudo yarnpkg add babel@latest"
Run command "sudo yarnpkg add webpack@latest"
Run command "sudo yarnpkg add webpack-cli@latest"
Run command "sudo yarnpkg add vue-template-compiler --save-dev --production=false"
Run command "sudo yarnpkg add sass-loader@8.* sass --save-dev --production=false"
Run command "sudo npm install --global cross-env"
Run command "yarnpkg run dev"

### What is the expected behavior?
Npm compiles the necessary files and assets, based on dependencies and provides a success message.

### Other relevant information:
webpack version: 5.6.0
Node.js version: 10.19.0
Operating System: Windows 10, but VM is Vagrant build on Virtualbox manager

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
