### ISSUE TITLE
Updating to TailwindCSS v2.0 causes NPM or YARN to break

### ISSUE THREAD

**Issue by andcl** [laravel/jetstream#476]
- **Jetstream Version**: 1.6.1
- **Jetstream Stack**: Livewire
- **Laravel Version**: 8.14.0
- **PHP Version**: 7.3

**Description**:
When updating tailwind package to new `^2.*` version, which needs postCSS v8, `yarn run dev` breaks.

**Steps To Reproduce**:
Within a Fresh Laravel + Jetstream installation, change tailwind library version in `package.json` to the newer and update.
Then `yarn run dev`.

**Comment by taylorotwell** [comment]
Jetstream 1 is on Tailwind 1. It would be your job to update it to 2. Jetstream 2 will ship with Tailwind 2.

**Comment by andcl** [comment]
Thanks Taylor, then I will look for the Jetstream 2 release.

**Comment by gavinr** [comment]
@taylorotwell  Is there a rough schedule on when v2 would be released? Like within a few days? weeks? months? (it's ok if the answer is "no" too -- I'm simply unsure if this is published information from the team that I've missed) Thanks!

**Comment by driesvints** [comment]
@gavinr we don't have an ETA sorry.
