### ISSUE TITLE
Router not working right when not authenticated

### ISSUE THREAD

**Issue by iRealWorlds** [laravel/jetstream#480]
- Jetstream Version: 1.6 (I think. The latest, I just installed it)
- Jetstream Stack: Inertia
- Laravel Version: 8.15.10
- PHP Version: 7.4.10
- Database Driver & Version: MariaDB 10.4.14

### Description:
When using the `route()` function, in something like
```
<nav-link :href="route('login')" :active="route().current('login')">
    Login
</nav-link>
<nav-link :href="route('register')" :active="route().current('register')">
    Register
</nav-link>
```
everything works as expected when the user is authenticated.
But, when I log out, I get the following error in the console as soon as I click on a link:
![image](https://user-images.githubusercontent.com/28299559/99743965-742b4b00-2adf-11eb-95f4-abce55e9df57.png)

Also, there is another rather bizarre effect:
Instead of loading the page in the main body, a kind of modal is opened containing the page that the link is pointing to.
For example, when clicking on the login link, I get that error in the console and the following effect:
![image](https://user-images.githubusercontent.com/28299559/99744272-10ede880-2ae0-11eb-84ad-d4234b9d291f.png)

### Steps To Reproduce:
On a fresh Laravel installation with Jetstream, using the Inertia stack, just make the `welcome` route display the dashboard view and add the conditions required to hide all the parts of the layout that use `$page.user`.

**Comment by driesvints** [comment]
This will be fixed in the next Jetstream release. Please see https://github.com/laravel/jetstream/issues/128
