### ISSUE TITLE
Feature Request: Option to require 2FA

### ISSUE THREAD

**Issue by eorenstein1** [laravel/jetstream#483]
It would be great if there was an option to force 2FA. When the option is enabled through the Jetstream config, new users would be prompted to Enable 2FA upon signing in and wouldn't be able to access any authenticated routes until they enable 2FA.

**Comment by Geekgurus** [comment]
Yes @eorenstein1 that's true. 2FA is important.

**Comment by relaypilot** [comment]
Is there any famous app or website that does that? 
(I don't think I've ever came accross a mandatory 2FA upon registration.)
It feels like hassling your users in my opinion, but I could be mistaken.

**Comment by jonpage999** [comment]
> Is there any famous app or website that does that?
To join a GitHub team you may be required to enable 2FA first, so this website is at least a partial example. It isn't for the entire site, but it's clearly important enough that groups within the site consider it essential. It's not hard to imagine that other systems they implement would have the same requirement.

**Comment by christogonus** [comment]
> Is there any famous app or website that does that?
> (I don't think I've ever came accross a mandatory 2FA upon registration.)
> It feels like hassling your users in my opinion, but I could be mistaken.

Twilio.com now does that.

**Comment by taylorotwell** [comment]
You can build this into your own application.
