### ISSUE TITLE
how can we use tailwind 2.0 with jetstream ?

### ISSUE THREAD

**Issue by thomasdominic** [laravel/jetstream#486]
Do you plan this upgrade ?

**Comment by cufano** [comment]
As you can see in this repo comments history, it will be implemented in next Jetstream 2 version.

**Comment by driesvints** [comment]
Will be included in Jetstream v2.

**Comment by aligajani** [comment]
> Will be included in Jetstream v2.

thanks. will it be an easy upgrade for people already on jetstream 1?

**Comment by taylorotwell** [comment]
There is no upgrading Jetstream. It is an application starter kit. Once you install it that's it. You don't upgrade it ever. Even if a future release of Jetstream is released. It is impossible to upgrade it - your UI will have been modified. You may have customized it, etc. You simply start applications with whatever the latest release it and that's it. You can add your own features from there.
