### ISSUE TITLE
Deprecation Error on Inertia >0.3.0

### ISSUE THREAD

**Issue by vincenzoraco** [laravel/jetstream#495]
- Jetstream Version: 1.6.2
- Jetstream Stack: Inertia
- Laravel Version: 8.16.0
- PHP Version: 8.0.0-dev
- Database Driver & Version: Mysql 8

### Description:
As of v0.3.0, Inertia deprecated the promise that is returned from Inertia.visit().

**Comment by driesvints** [comment]
Inertia v0.3.0 has been the default version for over two months now and we haven't gotten any reports about this yet. Are you sure we're not missing anything here?

/cc @reinink
