### ISSUE TITLE
SESSION DOESN'T PERSIST UNTIL REMEMBER ME IS CHECKED

### ISSUE THREAD

**Issue by sirkenedy** [laravel/jetstream#498]
- Jetstream Version:1.6
- Jetstream Stack: Livewire
- Laravel Version: 8.12
- PHP Version: 7.3.1
- Database Driver & Version: Mysql 5.7.24

### Steps To Reproduce:
1. Install Laravel
2. Install Jetstream. 
3. php artisan jetstream:install livewire
4. npm install && npm run dev
5. php artisan migrate
6. php artisan vendor:publish --tag=jetstream-views
7. Register (after register, the user is not automatically logged in but redirected to login page)
8. Login(using invalid, an error response was returned)
9. Login without remember me being checked(using valid details, i was redirected to login page with no response)
10. Login with remember me being checked( then i was able to access dashboard)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
