### ISSUE TITLE
Jet option does not exist on current laravel installer

### ISSUE THREAD

**Issue by jpkontreras** [laravel/jetstream#50]
- Jetstream Version: #.#.#
- Laravel Version: v7.27.0
- PHP Version: v7.4.8
- Database Driver & Version: none

### Description:
 Jet option does not exist on current laravel installer

### Steps To Reproduce:
`laravel new project-name --jet`

#### Output

  The "--jet" option does not exist.

new [--dev] [--auth] [-f|--force] [--] [<name>]

**Comment by jparradog** [comment]
You must update the repository to Laravel version 8.0-dev so that you can install with --jet

**Comment by jpkontreras** [comment]
THX !
