### ISSUE TITLE
Feature request: Add a migration guide in the docs

### ISSUE THREAD

**Issue by Garanaw** [laravel/jetstream#501]
I have a couple of projects started back in Laravel 5.x or 6.x, where Laravel UI was used for Auth matters. We have been upgrading Laravel's version up to the latest (currently 8.16.1), however the Auth system remains unchanged. Probably most of the old projects will be in the same situation.

I have unsuccessfully tried to find a migration guide from the old stacks to Jetstream, and I reckon it should't be very difficult, but it would be nice to have a guide in the docs that cover all the points / required changes.

**Suggested stacks to cover:**
- Integrated Auth system (_Laravel 5.x_)
- Laravel/ui & Passport (_Laravel 6.x_)

**Comment by driesvints** [comment]
Hey @Garanaw. Jetstream is intended to work with Laravel 8 and nothing below. Further more, Jetstream is a scaffold tool for new Laravel apps. If you plan to migrate your own app you'll have to figure out that yourself as each app is different from another.
