### ISSUE TITLE
The logout feature does not work [BUG]

### ISSUE THREAD

**Issue by stephan0810** [laravel/jetstream#503]
- Jetstream Version: v1.6.2
- Jetstream Stack: Inertia
- Laravel Version: Laravel Framework 8.16.1
- PHP Version: 7.4.9
- Database Driver & Version: MySQL:5.7.26

### Description:

Previously, the logout feature worked fine using jetstream, but after upgrading the version, this behavior is no longer possible.
I haven't edited the code for jetstream logout, what kind of problem can I expect?

### Steps To Reproduce:

- install jetstream and choose inertiajs
- Register account and login
- Click the logout button in the header

**Comment by bistory** [comment]
Check your version of Ziggy, it should be 0.9.4 for Jetstream 1.6.x

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by amineCHATATE** [comment]
With Jetstream we can use this code :

`<form method="POST" action="{{ route('logout') }}">
       @csrf
       <x-jet-dropdown-link href="{{ route('logout') }}" onclick="event.preventDefault(); this.closest('form').submit();">
                <i class="fa fa-sign-out"></i>{{ __('Logout') }}
        </x-jet-dropdown-link>
</form>`

**Comment by amineCHATATE** [comment]
this this is used by jetstream by default

**Comment by YisusYaro** [comment]
You need to use a form with method POST. Here an example.

<pre><code>
&lt;form method="POST" name="logout" action="{{ route('logout') }}">
      @csrf
      &lt;a class="dropdown-item" href="javascript:document.logout.submit()">Salir&lt;/a>
&lt;/form>
</code></pre>

**Comment by geekfahim** [comment]
Here's the code for logout. I had added some conditions too. If anyone need feel free to use it.
```
        @if (auth()->id())
            <form method="POST" action="{{ route('logout') }}">
                @csrf
                <div class="nav-item">
                    <a class="nav-link" href="{{ route('logout') }}" onclick="event.preventDefault();
                                this.closest('form').submit(); " role="button">
                        <i class="fas fa-sign-out-alt"></i>

                        {{ __('Log Out') }}
                    </a>
                </div>
            </form>
        @else
            <li class="nav-item">
                <a class="nav-link" href="{{ route('login') }}" role="button">
                    <i class="fas fa-sign-in-alt"></i>
                    Login
                </a>
            </li>
        @endif
```

**Comment by Addd12** [comment]
where exactly should we add this code? in which file?
