### ISSUE TITLE
Easy scaffold new models with CRUD features

### ISSUE THREAD

**Issue by drsounds** [laravel/jetstream#51]
I want a feature that is a command that makes it easy to scaffold new model and CRUD-functionality on the dashboard like

````bash
php artisan jetstream:crud topic --fields=name:text
php artisan jetstream:crud article --fields=name:text,description:text,topic:topic_id
````

That automatically creates code for the App\Models, Controllers and pages with vue code and inertiajs/livewire code for CRUD. fields ending with _id will create an one to many relation or _ids create a many to many relationship, both with typeaheads on the frontend.

**Comment by taylorotwell** [comment]
This isn't a bug report so closing for now.
