### ISSUE TITLE
Unable to register a new user on fresh Jetstream installation.

### ISSUE THREAD

**Issue by vwmoose** [laravel/jetstream#516]
- Jetstream Version: 1.6
- Jetstream Stack: Livewire 2.0
- Laravel Version: 8.12
- PHP Version: 7.3.12
- Database Driver & Version: MySQL 5.7

### Description: 
Currently I'm unable to register a new user on a fresh Jetstream installation with Teams.  The following error occurs:-

ErrorException
Non-static method App\Models\User::create() should not be called statically

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
app/Actions/Fortify/CreateNewUser.php:31

### Steps To Reproduce:  
Install Laravel with Jetstream and Teams.
Click Register (top right)
Fill in registration form and submit.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by vwmoose** [comment]
@driesvints did you even look at this issue?  This is a problem that did not occur on v1.4 and now does on v1.6.  This is not my code and is an issue, I believe, with a file shipped with the library.

**Comment by joelbutcher** [comment]
@vwmoose Do you have any code references to backup this issue report? Just done a clean v1.6 install and not had an issue

**Comment by vwmoose** [comment]
I'm going to have to eat humble pie, seems as if it may be attributable to a trait applied on the User model by a package I'm developing!  Sorry for the inconvenience!
