### ISSUE TITLE
In InstallCommand.php line 197:    copy(C:\xampp\htdocs\ehmo1\resources\js/app.js): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by vcnwafor** [laravel/jetstream#517]
- Jetstream Version: #.#.#
- Jetstream Stack: Inertia / Livewire
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

### Description:
i installed the demo version of backpack and later installed jetstream and everything went well and after i ran the install, i got the error below
In InstallCommand.php line 197:

  copy(C:\xampp\htdocs\ehmo1\resources\js/app.js): failed to open stream: No such file or directory

**Comment by vcnwafor** [comment]
i simply went in, created the js folder and copied the app.js file over.

**Comment by w5m** [comment]
@vcnwafor to clarify, you copied the app.js file from the `.../resources/assets/js/` folder into the `.../resources/js/` folder you created?
