### ISSUE TITLE
Tracking: Update to latest version of Inertia.js

### ISSUE THREAD

**Issue by weaversam8** [laravel/jetstream#518]
Jetstream links directly to the documentation for Inertia.js, but we are running outdated version of both `@inertiajs/inertia` (0.3.0 vs. 0.7.0) and `@inertiajs/inertia-vue` (0.2.0 vs. 0.4.3). This isn't a major issue, but I've already stumbled upon issues trying to do something in the Inertia docs to find out it silently fails in Jetstream's default setup.

I updated my version of both of these plugins to the latest versions available today (listed above) and didn't encounter many issues on my relatively small project. I wanted to create this issue to track the issue(s) I did find so we know what updates are necessary when we update to a later version. 

* The `jetstream`, `user`, and `errorBags` properties on `$page` have been moved to the `$page.props` property, so all references to these properties will need to be updated. This includes:
  * Pages for profile updates and two factor authentication
  * The API token manager page
  * The `InteractsWithErrorBags` Mixin
  * The default generated `AppLayout` component
* Inertia provides a deprecation warning for how we register the Vue adapter. This is a simple change:
![image](https://user-images.githubusercontent.com/2546219/101588413-594c4800-39b4-11eb-94c9-13bd814f96e1.png)

According to Dries, these updates are slated for v2. I don't think we need to wait that long, as these are simple fixes, but obviously it's up to the maintainers. Happy to do a PR for this if updates before v2 are welcome.

See other related issues: #410, #411

**Comment by weaversam8** [comment]
cc @t-itzel re #411

**Comment by driesvints** [comment]
This will come in v2. Please be patient.
