### ISSUE TITLE
Interia progress indicator not compatible with Jetstream

### ISSUE THREAD

**Issue by markvesterskov** [laravel/jetstream#519]
- Jetstream Version: 1.6.4
- Jetstream Stack: Inertia
- Laravel Version: 8.18.1
- PHP Version: 7.4.10
- Database Driver & Version: Mysql 8.0.21

### Description:
I'm trying to add the default @inertiajs progress indicator to a fresh Jetstream installation but it results in the follow javascript error firing on `interia:progress` and `inertia:finish`:

`Uncaught TypeError: Cannot read property 'visit' of null`

It seems to be caused by the "detail" parameter of the Inertia event being null, because the progress bar is referencing `event.detail.visit.completed.` I cannot really decipher why the details parameter is null, as I'm new to Inertia.

### Steps To Reproduce:
Create a fresh Jetstream installation with Inertia stack
`npm install @inertiajs/progress`
Update app.js with 
`import { InertiaProgress } from '@inertiajs/progress'`
`InertiaProgress.init()`
Load a page slower than the default 250 ms progress indicator timeout
JS error occurs

**Comment by joelbutcher** [comment]
@markvesterskov Increase the default timeout for the progress indicator? I don't see the issue here - what do suggest should be done to address the page load speed?

**Comment by joelbutcher** [comment]
@markvesterskov What's the JS error?

**Comment by markvesterskov** [comment]
@joelbutcher I'm not bashing the page load speed - I'm only pointing to the fact that the default Inertia progress indicator, which is super nice to have, does not work with Jetstream. Increasing the default timeout changes nothing.

The JS error is, as written in my first post: `Uncaught TypeError: Cannot read property 'visit' of null` - the progress and finish event listeners try to reference `event.detail.visit` which is not set on the event; I'm guessing due to a Jetstream configuration somewhere.

**Comment by schmidfelix** [comment]
It seems that version ^0.2 of inertiajs/progress is not compatible with the Inertia version which gets installed when creating a fresh laravel application. (https://github.com/inertiajs/progress/issues/6). I think jetstream is using v0.3 of inertia, and the newest one is v0.7.

You have to use either v0.1 for the progress bar or upgrade your hole application. I think the second one is the better one, but more complex as I haven't found a correct upgrade guide? When doing the steps someone written in the linked issue (https://github.com/inertiajs/progress/issues/6#issuecomment-719073887), a other error occurs and for example the "Update Profile Information Form" does not get shown.

**Comment by joelbutcher** [comment]
@markvesterskov Okay. I've just taken a quick dive through the inertia source code for Jetstream and the Inertia Progress package. Seems to be that the version of Inertia Progress you're using isn't compatible with the version of InertiaJs currently used in Jetstream.

**Comment by markvesterskov** [comment]
Thanks guys, I thought i had searched high and low for an error like mine, except for in the Progress repo. I'll go with downgrading for now, and waiting for Jetstream to bump Inertia.

**Comment by joelbutcher** [comment]
@markvesterskov Happy to help, Jetstream v2 will bring a bump of Inertia. If you're feeling brave, you could checkout the master branch for your project - bit it's liable to change!
