### ISSUE TITLE
components under profile folder not working

### ISSUE THREAD

**Issue by Sanjay-Sahu-Bandla** [laravel/jetstream#522]
- Jetstream Version: 1.5
- Jetstream Stack: Livewire
- Laravel Version: 8.17.2
- PHP Version: 7.4.13
- Database Driver & Version: I'm working on local development with MySQL provided by Apache/2.4.41 (Ubuntu)

### Description:
Components under resources/views/profile are not working
```
Livewire\Exceptions\ComponentNotFoundException
Unable to find component: [profile.update-password-form]
```

It was working fine for a while but don't know what caused this bug. I tried by running `php artisan livewire:discover` and reverting the previous commits related to this issue, but no use. However the components under resources/views/auth are working fine from the beginning.

![Screenshot from 2020-12-09 20-23-59](https://user-images.githubusercontent.com/54032677/101645557-87856280-3a5c-11eb-9012-832e7d6d7caa.png)

**Comment by driesvints** [comment]
Works just fine for me on a fresh Jetstream Livewire install.

**Comment by s0nyc69** [comment]
@Sanjay-Sahu-Bandla 
did you managed to work it out? I have the exakt same problem right now and have not the slightest idea, what produces this error, tried to reproduce the livewire-components but still the same output...

**Comment by Sanjay-Sahu-Bandla** [comment]
> @Sanjay-Sahu-Bandla 
> did you managed to work it out? I have the exakt same problem right now and have not the slightest idea, what produces this error, tried to reproduce the livewire-components but still the same output...
> 
> @driesvints 
> Sorry to bother you, but I found out, that this error occurs after installing the blade-ui-kit...

No, I tried a lot. But nothing got worked which is why I had to disable 2FA and other functionalities of Jetstream inorder to make it work.
