### ISSUE TITLE
Incorrect interface given to Carbon\CarbonInterval::setLocalTranslator()

### ISSUE THREAD

**Issue by jameswagoner** [laravel/jetstream#523]
- Jetstream Version: 1.6.3
- Jetstream Stack: Inertia / Livewire
- Laravel Version: 8.17.2
- PHP Version: 7.3.23

### Description:
When I got to the user profile, I am greeted with `Argument 1 passed to Carbon\CarbonInterval::setLocalTranslator() must implement interface Symfony\Component\Translation\TranslatorInterface, instance of Carbon\Translator given`. Error happens in `resources/views/profile/logout-other-browser-sessions-form.blade.php` when `$sesson->last_active` is called.

### Steps To Reproduce:
Click `Profile` link from the user dropdown on the top right of the UI.

### More Info
I have seen this error come up in other issue trackers where Laravel is being used and relates to Symphony 5. While everyone notes PHP Version ^7.4 and making sure it is what your webserver is actually using, I have 7.3 on the server and cli.

Other "fix" was to delete vendor folder, clear composer cache, and composer install. That was done but no change. It sounded like others had older versions of Symphony cached. I verified composer did in fact install version 5.

**Comment by driesvints** [comment]
You've already found the correct solution by updating your dependencies 👍

**Comment by jameswagoner** [comment]
Not a solution when it had no effect there guy...

Only solution that moves my project forward is not using methods that involves localized strings being returned from Carbon. Ended up removing `$session->last_active` from the blade file.

**Comment by driesvints** [comment]
You said:

> Other "fix" was to delete vendor folder, clear composer cache, and composer install.

**Comment by jameswagoner** [comment]
Followed by:

> That was done but no change. It sounded like others had older versions of Symphony cached. I verified composer did in fact install version 5.

This issue is obviously my problem (more so a problem with Carbon) so not trying to be difficult. Spun up a local homestead environment and did not experience the errors. So I can narrow it to something on my web server.

If others have had a similar experience, would like to know what troubleshooting ideas they went through.

**Comment by driesvints** [comment]
Ah that wasn't very clear indeed. Definitely don't think you're being difficult, no problem. Since this is very specific to your use case I'd like to suggest that you try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.

**Comment by jameswagoner** [comment]
I'll take that route when I need to get human readable strings from Carbon. Thanks, Laracasts and SO are the only ones I have been to. I'll have to checkout Discord.

I was pretty bummed when an error hit right out of the box and fair amount researched solutions didn't work for me.

**Comment by NHuebnerWMG** [comment]
Bumping this thread. I had to completely empty out this file to get Jetstream to work.
