### ISSUE TITLE
Two Factor Auth published view not working with fortify prefixed routes

### ISSUE THREAD

**Issue by Caffe1neAdd1ct** [laravel/jetstream#525]
- Jetstream Version: 1.6
- Jetstream Stack: Livewire
- Laravel Version: 8.12
- PHP Version: 7.4
- Database Driver & Version: MariaDB 10.5

### Description:

Changing the fortify prefix allows prefixing the entire login pipeline routes from `/login` to `/admin/login` however currently breaks the two factor authentication process due to the published Jetstream Livewire view for 2FA containing a manual form url:

```
<form method="POST" action="/two-factor-challenge">
                @csrf
```

Changing to 

```
<form method="POST" action="{{ route('two-factor.login') }}">
                @csrf
```

Fixes for me.

**Comment by driesvints** [comment]
I've sent in a PR: https://github.com/laravel/jetstream/pull/528

**Comment by Caffe1neAdd1ct** [comment]
@driesvints Thanks very much for raising the pull request!
