### ISSUE TITLE
Unable to locate a class or view for component [guest-layout].

### ISSUE THREAD

**Issue by muhadnan2** [laravel/jetstream#527]
- Jetstream Version: ^1.6
- Jetstream Stack: InertiaJS
- Laravel Version: 8.12
- PHP Version: 7.4.13
- Database Driver & Version: MySQL

### Description:
Unable to locate a class or view for component [guest-layout].

### Steps To Reproduce:
after I did ``php artisan optimize:clear`` i was get some problem..
show error `Unable to locate a class or view for component [guest-layout].` 
I looked in the provider jetstream code, this component is not registered by default.

just add this to `AppServiceProvider` its normal again:
````
/**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Blade::component('guest-layout', GuestLayout::class);
    
}
```
thanks before.

**Comment by driesvints** [comment]
The GuestLayout component should be published to your `app/View/Components` directory after you run the install command.
