### ISSUE TITLE
Namespaced 'user' in inertia shared data

### ISSUE THREAD

**Issue by danilopinotti** [laravel/jetstream#530]
Hello!

I want to suggest using 'auth' namespace on 'user' that represents the current user on inertia shared data.

https://github.com/laravel/jetstream/blob/1.x/src/Http/Middleware/ShareInertiaData.php

```php
Inertia::share(array_filter([
    // ...
    'auth' => [
        'user' => function () use ($request) {
           //
        },
    ],
]));
```

The motivation is that 'user' is a very common model and, keeping this way, generates a lot of conflicts on a simple Users CRUD.

The first solution I tried was renaming the 'user' on the controller to 'model', but why would only 'user' have to be different from the whole system? In addition, other developers would probably waste time debugging to find out that the name 'user' is reserved by inertia.

I've solved this issue with container binding, replicating InertiaSharedData, and applying the modifications suggested in this issue.

I believe that may have other people with the same problem.

If this suggestion will be approved, I can made a PR with the updates

**Comment by bonzai** [comment]
#323

**Comment by driesvints** [comment]
Please see the above
