### ISSUE TITLE
React version PR questions

### ISSUE THREAD

**Issue by s1owjke** [laravel/jetstream#532]
Because Inertia also supports React and there were a lot of requests i created React version of Jetstream.
I tried to make the code close to vue version.

There are a number of things that are not ready yet, but most of the work is done.
All code is available in this repository https://github.com/s1owjke/laravel/tree/jetstream-react

I haves questions about pull request:
1. Is it worth create PR in this repo, or better separate them like https://github.com/laravel/breeze
I can also maintain the React version in the future.
2. If its better to create PR, then for which version i should prepare it for current 1.x or future 2.x?

**Comment by joelbutcher** [comment]
Nice work - quick question though - you're using classes over functional components in your repo. May I ask if you have a specific reason for this? I though as of react 1.16 developers were being encouraged to take a stateless approach via functional components as it reduces the size of the compiled JavaScript?

**Comment by s1owjke** [comment]
Thanks. Do you mean class components? But I don't use them at all, at this moment i know only one specific case for classes - ErrorBoundaries. Since version 16.8.0 (when hooks were added) there is no other reason to use class components.

**Comment by driesvints** [comment]
Thanks for creating this. However, we have no plans of adding a react version to Jetstream.

**Comment by joelbutcher** [comment]
@s1owjke my apologies - I wasn't reading the code well at all last night! I thought I saw a class declaration in one of your show.js files, but I clearly didn't!!


Perhaps I shouldn't be on GitHub that late in the night 😅

**Comment by e-hop** [comment]
> Thanks for creating this. However, we have no plans of adding a react version to Jetstream.

I read this anwers lot of times. A React version option is claimed everywhere.
