### ISSUE TITLE
Focus styles missing on all buttons since Tailwind 2 update

### ISSUE THREAD

**Issue by taylormaguire** [laravel/jetstream#534]
- Jetstream Version: master
- Jetstream Stack: Both
- Laravel Version: 8
- PHP Version: 7.4
- Database Driver & Version:

### Description:
In master, since the addition of Tailwind 2.0 and the removal of TailwindUI, all of the focus styles on every button have been removed. This includes the TeamMemberManager Role Buttons. This is an issue for accessibility. I believe Tailwind 2 now utilizes the focus:ring and focus:ring-color-000 format.

It appears the focus styles are working on inputs.

### Steps To Reproduce:
Install a new Laravel application and install the "dev-master" version of Jetstream.

**Comment by taylormaguire** [comment]
I should note, I would be willing to PR these changes, but will take me a few days to get to it. Let me know.

**Comment by driesvints** [comment]
Sure thing, feel free to PR. Thanks
