### ISSUE TITLE
Call to undefined method App\Models\User::getProfilePhotoUrlAttribute() 

### ISSUE THREAD

**Issue by Sanjay-Sahu-Bandla** [laravel/jetstream#536]
- Jetstream Version: 1.5
- Jetstream Stack: Livewire
- Laravel Version: 8.0
- PHP Version: 7.4.13
- Database Driver & Version: I'm working on local development with MySQL provided by apache

### Description:

I'm getting this error after removing the jetstream from my app. As there is no documentation on uninstalling the jetstream completely I just followed the below way

- composer remove laravel/jetstream
- php artisan config:clear
- php artisan cache:clear
- deleting the related files such as jestream.php, fortify.php and other files under app/actions

However, I'm still unable to get rid of this error

![Screenshot from 2020-12-15 12-49-26](https://user-images.githubusercontent.com/54032677/102183535-043c9480-3ed4-11eb-8edd-8e27f82484aa.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
