### ISSUE TITLE
How can I change the UI Avatars (Background and Text) Color?

### ISSUE THREAD

**Issue by devhoussam** [laravel/jetstream#552]
**jetstream** use the **[UI Avatars](https://ui-avatars.com/)** to create default user profile picture I want to customize the **Background and Text Color**

**Here is an example :** 

![](https://i.imgur.com/k9ewhzC.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by talelmishali** [comment]
The documentation provides you with the answer: [#Managing Profile Photos
](https://jetstream.laravel.com/1.x/features/profile-management.html#profile-photos)
The `App\Models\User` class using the `Laravel\Jetstream\HasProfilePhoto` trait, you can overwrite the `defaultProfilePhotoUrl ` method:

`protected function defaultProfilePhotoUrl()
    {
        return 'https://ui-avatars.com/api/?name=' . urlencode($this->name) . '&color=7F9CF5&background=EBF4FF';
    }`

**Comment by baldomerocho** [comment]
[talelmishali](https://github.com/talelmishali) Thanks bro
