### ISSUE TITLE
user.membership is undefined - TeamMemberManager.Vue

### ISSUE THREAD

**Issue by VincentMeert** [laravel/jetstream#556]
- Jetstream Version: 1.6.3
- Jetstream Stack: Inertia 
- Laravel Version: 8.17.2
- PHP Version: 7.4.9
- Database Driver & Version: phpmyadmin 5.0.2

### Description:
 in the file TeamMemberManager.vue the part under  does not appear because membership is undefined. 
![image](https://user-images.githubusercontent.com/8351497/102761773-a26aa780-4377-11eb-92ad-cfe66b8606b1.png)

If I replace this code : 
`                                <button class="ml-2 text-sm text-gray-400 underline"
                                           v-if="userPermissions.canAddTeamMembers && availableRoles.length"
                                           @click="manageRole(user)">
                                        {{  displayableRole(user.membership.role) }}
                                </button>
`
By
`                                <button class="ml-2 text-sm text-gray-400 underline"
                                           v-if="userPermissions.canAddTeamMembers && availableRoles.length"
                                           @click="manageRole(user)">
                                       {{ user }}
                                </button>`

I have all user information but nothing about membership and role : 

![image](https://user-images.githubusercontent.com/8351497/102762402-887d9480-4378-11eb-8124-15db910f1500.png)

The problem is not in the displayableRole method but with the membership relationship which is not send to the Vue component. (or in the $page variable ? )

How can I achieve this ? 

Thanks

### Steps To Reproduce:

Just a clean laravel installation >8.0 with jetstream (with teams and inertia stack)

**Comment by VincentMeert** [comment]
Forget it. sorry.
We added some method is the user and team model and so we added 
`use App\Models\User;` 
on the top of the class which make it all wrong because, I guess, some function makes reference to the wrong user class...

**Comment by mediabloke** [comment]
@VincentMeert Can you please clarify what you removed? I'm having this exact issue right now, and can't find anything beyond this post

**Comment by VincentMeert** [comment]
this was a long time ago.
But if I remember well, the default user class was moved into an other project as depedencie of the project I was working on. 
and so, the `use App\Models\User;` was not refering anymore at the good class. I had to remove it to have the default path or write something like use `SharedApp\SharedModels\User;` to get all the informations I was needed

**Comment by mediabloke** [comment]
@VincentMeert Thank you for responding. Posting my fix here in case anyone has this issue in the future. In my case, I had added a users relationship in my Team model like this    

```
public function users(): BelongsToMany
    {
        return $this->belongsToMany(User::class);
    }
```
This overrode the existing relationship and removed some important properties, including all membership options
