### ISSUE TITLE
Request: reconsider #323

### ISSUE THREAD

**Issue by drjdr** [laravel/jetstream#558]
- Jetstream Version: 1.x / master
- Jetstream Stack: Inertia 

### Description:
@taylorotwell @driesvints @reinink May I kindly ask to reconsider #323 ? 
Having to substitute `user` with `user_something` on every page to avoid interference with the `auth user` seems not right...

### Steps To Reproduce:
Create a profile inertia-page for a user, or any inertia-page that needs a user object different from the logged in user.
The user object passed as a prop to this page interferes with the `$page.props.user` which is also used for the logged in user.

**Comment by driesvints** [comment]
Probably not sorry.

**Comment by drjdr** [comment]
Hi @driesvints,
Thanks for this quick reply, any particular reason why you would not prefer this?

**Comment by driesvints** [comment]
It's not worth the breaking change.

**Comment by driesvints** [comment]
Looks like we'll be making the change after all: https://github.com/laravel/jetstream/pull/323#issuecomment-749510856

**Comment by drjdr** [comment]
Thanks a lot for the follow-up @driesvints, and my best wishes to the team
