### ISSUE TITLE
Possible Image Vunerability

### ISSUE THREAD

**Issue by srdante** [laravel/jetstream#564]
- Jetstream Version: 1.x
- Jetstream Stack: Inertia / Livewire
- Laravel Version: 8
- PHP Version: 7.4

### Description:
Jetstream uses laravel validation 'image' option. This option allow any user to send SVG files that can be malicious. Creating a script tag inside an svg file make it possible to create an XSS vulnerability.

In order to the script tag to be executed, the image needs to be opened in a new tab. The image being displayed only does not cause the script tag to be executed. A practical case  for this vulnerability, it would be a user to open the image of another user in order to check the full image or download it.

### Steps To Reproduce:

1. The photo upload option must be enabled.
2. Go to profile page and upload a svg image with <script> tag and click on save.
3. Right click on the image and click to open in a new tab.

### SVG Image Example:
```
<svg version="1.1" baseProfile="full" xmlns="http://www.w3.org/2000/svg">
   <polygon id="triangle" points="0,0 0,50 50,0" fill="#000" stroke="#000"/>
   <script type="text/javascript">
      alert(document.cookie);
   </script>
</svg>
```

**Comment by driesvints** [comment]
If you want to change the rule for this you're free to do so in your own app. The `UpdateUserProfileInformation` action is copied into your app by Jetstream so you can adjust it like you want.

As for the vulnerability I don't believe it should be the responsibility of the `UpdateUserProfileInformation` action or the `image` rule to check this. Feel free to work something out in your own app. We're also open to PR's if you want to contribute something to Jetstream or the framework. Thanks.
