### ISSUE TITLE
Fresh Install doesn't work on existing project using `App/` for models.

### ISSUE THREAD

**Issue by abr4xas** [laravel/jetstream#567]
- Jetstream Version: dev-master
- Jetstream Stack: Livewire
- Laravel Version: 8.20.1
- PHP Version: PHP 7.4.12
- Database Driver & Version: MySQL version: 5.7.29

### Description:

I'm having the same issue like #531 

### Steps To Reproduce:
- a fresh installation of laravel
- require jetstream
- instal livewire stack

PS: I know, I'm using a dev branch ;)

**Comment by abr4xas** [comment]
Fixed, cache issues.

**Comment by driesvints** [comment]
Fresh installs of laravel have `App\Models` as their default namespace. If you change your default namespace then you're responsible yourself for changing any stubs installed by Jetstream.

**Comment by joelbutcher** [comment]
@abr4xas unrelated but applicable side note: Jetstream a scaffold for *new* Laravel 8 projects. It's not designed to be used with existing projects...

If you really need auth scaffolding for your app, checkout Laravel Breeze

**Comment by abr4xas** [comment]
Hey @joelbutcher,  I was using a fresh laravel 8 installation and jetstream @ dev to test it ;)
