### ISSUE TITLE
Unable to recover account if email is not accessible on email address change

### ISSUE THREAD

**Issue by lawzava** [laravel/jetstream#568]
- Jetstream Version: 1.6.5
- Jetstream Stack: Livewire
- Laravel Version: 8.20
- PHP Version: 8.0
- Database Driver & Version: pgsql

### Description:
If a user attempts to change the current email and fails to access that new email address, it will be impossible to access the account anymore.

### Steps To Reproduce:
Create an account, "request to change" email address (send verification link), attempt to do something before verifying the new email address.

### Suggestion:
Do not change the email address of the user until the email is verified. Allow usage of the original email address until then.

**Comment by driesvints** [comment]
Please add the Jetstream version you're using.

**Comment by lawzava** [comment]
> Please add the Jetstream version you're using.

@driesvints added

**Comment by driesvints** [comment]
This has already been requested before and we're not planning on changing anything here sorry. A user should enter the correct email address.

**Comment by lawzava** [comment]
@driesvints just to clarify the reasoning behind it - is this avoided to not increase the complexity of the Jetstream or is there some other reason?

Since there are not many apps out there that would be this harsh on the users 😄

**Comment by driesvints** [comment]
The complexity yes
