### ISSUE TITLE
Passing 'user' as props in Inertia render messes up with auth user

### ISSUE THREAD

**Issue by raynirola** [laravel/jetstream#570]
- Jetstream Version: 1.6.5
- Jetstream Stack: Inertia
- Laravel Version: 8.20.1
- PHP Version: 8.0

#### Passing 'user' as props in Inertia render messes up with auth user:
```php
class UserController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param User $user
     * @return Response
     */
    public function show (User $user): Response
    {
        return Inertia::render('User/Show', ['user' => $user]);
    }
}
```

### Steps To Reproduce:

- Fresh laravel jetstream app
- Register 2 users
- Create a route for showing a user
   ```php
    Route::get('users/{user:id}', [UserController::class, 'show'])
           ->middleware(['auth:sanctum', 'verified'])
           ->name('user.show');
   ```
- Accept the props in User/Show Vue component.
   ```js
    props: {
        user: Object
    }
   ```
- Login with the first user
- Visit route `'/users/{user:id}'` with second user's id.
- Logged in user's name changes to {user}'s name

### Screenshots
<img width="686" alt="user one" src="https://user-images.githubusercontent.com/54945029/103351270-b4132400-4ac8-11eb-9d6d-3bbbbcbc170d.png">
<br/>
<img width="686" alt="user 2" src="https://user-images.githubusercontent.com/54945029/103351273-b6757e00-4ac8-11eb-8c10-7d970c1082c4.png">

**Comment by bonzai** [comment]
This is by design. See #323, #530.

Just change the `user` prop to something else.

**Comment by raynirola** [comment]
> This is by design. See #323, #530.
> 
> Just change the `user` prop to something else.

Thanks, looks like gotta live with my OCD triggered.

**Comment by peckanthony** [comment]
Had the same thing, problem is I didn't notice it at first, since it doesn't produce an error, it just changes the user prop.

**Comment by raynirola** [comment]
We can rename it to notAuthUser, 😄
