### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by hamiozturk** [laravel/jetstream#571]
- Jetstream Version: i try install latest version
- Jetstream Stack: Inertia / Livewire
- Laravel Version: 8
- PHP Version: 8.0.0
- Database Driver & Version:

### Description:

Hi, i try install jetstream with composer, i got this warning.  

I read this blog post you shared.
[https://blog.laravel.com/laravel-php-8-support](url)

When i run `composer require laravel/jetstream`

I got this warning.

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/jetstream[v1.6.0, ..., 1.x-dev] require illuminate/support ^8.0 -> found illuminate/support[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires laravel/jetstream ^1.6 -> satisfiable by laravel/jetstream[v1.6.0, ..., 1.x-dev].`

**Comment by joelbutcher** [comment]
Check your dependencies, it looks like Jetstream is clashing with another dependency you're using. 

Are you installing from fresh or into an existing project?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
