### ISSUE TITLE
Jetstream Inertia using deprecated promises

### ISSUE THREAD

**Issue by CryDeTaan** [laravel/jetstream#575]
- Jetstream Version: 1.6.6
- Jetstream Stack: Inertia
- Laravel Version: 8.20.1
- PHP Version: 7.4.9
- Database Driver & Version: MySQL 8

### Description:
This issue was mention in #495 but this is an attempt to provide additional information. 

Laravel Jetstream is making use of the Inertia [Form helper](https://inertiajs.com/forms#form-helper). This helper in Laravel Jetstream implements a promise that is returned from `Inertia.visit()` which Inertia deprecated as of v0.3.0 as can be seen from the [docs](https://inertiajs.com/manual-visits#promise-deprecation) which Laravel Jetstream is making use of.

### Steps To Reproduce:
Simplest way to find this error is to navigate to the Profile page of a fresh Laravel project and update the user/profile information and view the console to see the warning:

```
app.js:109 Inertia.js visit promises have been deprecated and will be removed in a future release. Please use the new visit event callbacks instead.

Learn more at https://inertiajs.com/manual-visits#promise-deprecation
```

![image](https://user-images.githubusercontent.com/11268952/103444814-6cc19a80-4c64-11eb-965f-1a88ae851bab.png)

HTH

^C

**Comment by bonzai** [comment]
#496

> Upcoming Jetstream 2.x releases updates all of this. If you want to upgrade your own application's Inertia stuff you can do so in your own application.

**Comment by CryDeTaan** [comment]
Ah, sorry for missing that. Any idea on ETA?
