### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Symfony\Component\Console\Cursor' not found in C:\Users\JosÃ© Rivas\AppData\Roaming\Composer\vendor\symfony\console\Helper\QuestionHelper.php:245

### ISSUE THREAD

**Issue by quierounapagina-com** [laravel/jetstream#577]
- Jetstream Version: #.#.#
- Jetstream Stack: Inertia / Livewire
- Laravel Installer Version: 4.1.1
- PHP Version: 7.3.21
- Database Driver & Version:

### Description: When I try to install Laravel with Jetstream using the command: "laravel new test-app --jet"

I get the options to choose between livewire and inertia, but it automatically shows the following fatal error:

Fatal error: Uncaught Error: Class 'Symfony\Component\Console\Cursor' not found in C:\Users\JosÃ© Rivas\AppData\Roaming\Composer\vendor\symfony\console\Helper\QuestionHelper.php:245
Stack trace:
#0 C:\Users\JosÃ© Rivas\AppData\Roaming\Composer\vendor\symfony\console\Helper\QuestionHelper.php(141): Symfony\Component\Console\Helper\QuestionHelper->autocomplete(Object(Symfony\Component\Console\Style\SymfonyStyle), Object(Symfony\Component\Console\Question\ChoiceQuestion), Resource id #1, Object(Closure))
#1 C:\Users\JosÃ© Rivas\AppData\Roaming\Composer\vendor\symfony\console\Helper\QuestionHelper.php(68): Symfony\Component\Console\Helper\QuestionHelper->doAsk(Object(Symfony\Component\Console\Style\SymfonyStyle), Object(Symfony\Component\Console\Question\ChoiceQuestion))
#2 C:\Users\JosÃ© Rivas\AppData\Roaming\Composer\vendor\symfony\console\Helper\QuestionHelper.php(469): Symfony\Component\Console\Helper\QuestionHelper->Symfony\Component\Console\Helper\{closure}()
#3 C:\Users\JosÃ© Rivas\AppData\Roaming\Composer\vendor\symfo in C:\Users\JosÃ© Rivas\AppData\Roaming\Composer\vendor\symfony\console\Helper\QuestionHelper.php on line 245

and the process ends

### Steps To Reproduce:

Open Windows 10 CMD

I am located in the folder where I will create the project

I use the command: laravel new test-app --jet

I get the error

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
