### ISSUE TITLE
Expired session not redirect to Login

### ISSUE THREAD

**Issue by lucaros97** [laravel/jetstream#578]
- Jetstream Version: 1.6.5
- Jetstream Stack: Inertia
- Laravel Version: 8.20.1
- PHP Version: 7.4.13
- Database Driver & Version: MySQL 8.0.17

### Description:
I've a problem when the session expire and didn't redirect to login page. In the log I see this error:
```
local.ERROR: Trying to get property 'headers' of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property 'headers' of non-object at /Users/lucarossi/code/domtracker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:191)
[stacktrace]
```

**Comment by lucaros97** [comment]
There are also this errors:
```
local.ERROR: Argument 1 passed to Illuminate\Session\Middleware\StartSession::addCookieToResponse() must be an instance of Symfony\Component\HttpFoundation\Response, null given
```

```
local.ERROR: Argument 1 passed to Illuminate\Cookie\Middleware\EncryptCookies::encrypt() must be an instance of Symfony\Component\HttpFoundation\Response, null given
```

**Comment by driesvints** [comment]
Since we didn't get any reports about this before and we're on the verge of releasing Jetstream v2 I'm going to close this. If we released Jetstream v2 and the problem persists please report back. Thanks.

**Comment by lucaros97** [comment]
I found the problem was due to a function inside the Handler Exception class.
I had a function called render where I was declaring a custom message for a specific exception and this causes this problem.
So it was rendering a blank page instead of redirecting to login page.
Didn't know why.

Anyway thank you!

**Comment by chandrasbt** [comment]
> I found the problem was due to a function inside the Handler Exception class.
> I had a function called `render `where I was declaring a custom message for a specific exception and this causes this problem.
> So it was rendering a blank page instead of redirecting to login page.
> Didn't know why.
> 
> Anyway thank you!

Awesome. Thanks! was breaking my head over it since past 2 months!
