### ISSUE TITLE
Problems installing Jetstram with Livewire

### ISSUE THREAD

**Issue by danielschweiger** [laravel/jetstream#579]
- Jetstream Version: 1.6.5
- Jetstream Stack: Livewire
- Laravel Version: 8.20.1
- PHP Version: 7.3

I have troubles when installing Jetstream. 

First:

    composer require laravel/jetstream

This works as expected.

Then:

    php artisan jetstream:install livewire

Output:

    Migration created successfully!

    ErrorException

    file_get_contents(/Users/xxxx/xxxx/xxxx/xxxx.net/.env.example): failed to open stream: No such file or directory

    at vendor/laravel/jetstream/src/Console/InstallCommand.php:516

Then I try to uninstall Jetstream:

    composer remove laravel/jetstream

The uninstaller runs, at the end I see this output:

    ...

    Generating optimized autoload files
    > Illuminate\Foundation\ComposerScripts::postAutoloadDump
    > @php artisan package:discover --ansi

    In fortify.php line 134:
                                              
    Class 'Laravel\Fortify\Features' not found  
                                              
    Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by driesvints** [comment]
Hi there, I can't reproduce this. Make sure you first install a fresh Laravel app before installing Jetstream:

```bash
laravel new your-app
```

Or use the Laravel installer to install Jetstream for you:

```bash
laravel new your-app --jet
```

**Comment by danielschweiger** [comment]
@driesvints thx for your hints, I tried to install jetstream into a laravel app which also is running nova. is there a way to use them both?

**Comment by driesvints** [comment]
@danielschweiger Jetstream is meant for new Laravel apps, not existing ones.

**Comment by mrpritchett** [comment]
I can reproduce this on a brand new app.

**Comment by mrpritchett** [comment]
I updated and reinstalled everything I could think of. No luck.

**Comment by driesvints** [comment]
@mrpritchett just tried it again myself and everything works as expected. I don't get that error.

**Comment by mrpritchett** [comment]
Any other information I could provide that might help reproduce on your end?

**Comment by driesvints** [comment]
No idea really... what PHP version are you running? Directory permissions? Are you just serving the website or using valet, docker, homestead?

**Comment by mrpritchett** [comment]
8.0.2. I'm using Valet. This is the first site that has ever had this problem in a long list of Valet sites. It is my first new site with Laravel 8 and PHP 8 (although I've upgraded sites to both of those locally in this setup before). 

Permissions:

![Screen Shot 2021-02-12 at 11 49 13 AM](https://user-images.githubusercontent.com/3329081/107796923-5826f680-6d28-11eb-8831-fea86b87d939.png)

**Comment by driesvints** [comment]
I think it's best that you try a support channel at this point because I'm out of ideas I'm afraid:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by mrpritchett** [comment]
Fair enough, thanks for trying.

**Comment by joelbutcher** [comment]
@mrpritchett I’ve ran into a few problems with nginx on Big Sur. Maybe try a different hosting method instead of Valet as a test and see if that solves this issue

**Comment by mrpritchett** [comment]
@joelbutcher Yeah, I've switched to Sail for now, which works fine.

**Comment by syslogic** [comment]
This comes from `config/jetstream.php` or `config/jetstream.php`, which may complain about "undefined namespace" at statements alike: `use Laravel\Jetstream\Features` or `use Laravel\Fortify\Features`... which will subsequently throw "class not found". `Laravel\Jetstream\Features` and `Laravel\Fortify\Features` both are loaded from the `vendor` directory (as I could see from the one that is being found, even if it is the other one in my case) ...so this probably should be where to look for them.

**Comment by khaledw62** [comment]
i've been in this ```jetstream``` installation for a couple of days 
after running 
```sh
composer global update 
```  
it worked fine i don't actually know what was happening

**Comment by psyfire25** [comment]
Hi there I have done a stupid thing cos im a newb! 

I thought I would play with jetstream on my laravel project so installed it! As im sure you are aware it broke it! How do i go about undoing the install and fixing the project?

**Comment by flexchar** [comment]
@psyfire25 just revert to the last working commit. Make sure you also delete `vendors` folder and do fresh `composer install`.
