### ISSUE TITLE
Cannot install Livewire without global Composer?

### ISSUE THREAD

**Issue by miclaus** [laravel/jetstream#584]
- Jetstream Version: latest
- Jetstream Stack: Livewire
- Laravel Version: ^8.12
- PHP Version: 7.3.1
- Database Driver & Version: -

### Description:
I'm trying to install Jetstream with Livewire as suggested by the Jetstream documentation, however it does not seem to work. It seems it's because I'm not using a gobally installed Composer.

I think this should also be possible with only a `composer.phar`.

### Steps To Reproduce:

1. Downloaded Composer v2.0.8 with the official Composer download script
2. Installed Laravel: `php composer.phar create-project laravel/laravel`
3. Require Sanctum: `php composer.phar require laravel/sanctum` 
    (A step which is not outline very well in the documentation.)
4. Require Jetsteam: `php composer.phar require laravel/jetstream`
5. Tried installing Livewire: `php artisan jetstream:install livewire`

Console output:

```
$ php artisan jetstream:install livewire
sh: line 0: exec: composer: not found
Copied Directory [/vendor/laravel/sanctum/database/migrations] To [/database/migrations]
Copied File [/vendor/laravel/sanctum/config/sanctum.php] To [/config/sanctum.php]
Publishing complete.
```

When ignoring the error and serving the Laravel app and then authenticating with a user, the Livewire Blade directives are shown in the Dashboard:

```
@livewireStyles
@livewire('navigation-dropdown')
...
@livewireScripts
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by miclaus** [comment]
see #588 for what i used as a quick fix.
