### ISSUE TITLE
If available use composer.phar for installing stacks

### ISSUE THREAD

**Issue by miclaus** [laravel/jetstream#586]
When running:
```
php artisan jetstream:install livewire
```

the console currently outputs in some cases:
```
sh: line 0: exec: composer: not found
```

This is probably because on some systems there is no globally installed composer.

In that case, it would be nice if the installation script could recognize and use `composer.phar` instead of using a (possibly missing) globally installed composer.

**Comment by driesvints** [comment]
Sure we can maybe add a flag to include a path to the composer binary. Feel free to send in a PR.

**Comment by miclaus** [comment]
@driesvints alright thanks for the idea! i tried simply replacing the `composer` command with `composer.phar`, however it was also not found, weirdly enough, but the paths seem to be correct:

```
sh: line 0: exec: composer.phar: not found
```

in the meantime, could you maybe please tell me what `php artisan jetstream:install livewire` does behind the scenes?

i looked a little bit into in myself and for me it seems to finally run `composer.phar require livewire/livewire:^2.0 laravel/sanctum:^2.6`. (this probably also explains why installing sanctum is not explicitly specified in the docs?) 

manually running `php composer.phar require livewire/livewire:^2.0 laravel/sanctum:^2.6` seems to have fixed the issue for me.

**Comment by miclaus** [comment]
@driesvints just created a PR #588 that helped fix my issue.
