### ISSUE TITLE
inertia-link  302

### ISSUE THREAD

**Issue by pucoder** [laravel/jetstream#591]
- Jetstream Version: master
- Jetstream Stack: Inertia
- Laravel Version: 8.12
- PHP Version: 7.4
- Database Driver & Version: MySQL

### Description:
File: NavLink.vue

```vue
<template>
<!--    <a :href="href" :class="classes">-->
<!--        <slot></slot>-->
<!--    </a>-->
    <inertia-link :href="href" :class="classes">
        <slot></slot>
    </inertia-link>
</template>
```
When I set up a link in the navigation that requires login, clicking on the link will not redirect the browser's address bar to the link, but will appear as a popover. I changed the code "inertia-link" tag into "a" tag and it was normal

**Comment by schmidfelix** [comment]
It looks like that the stub file (https://github.com/laravel/jetstream/blob/2.x/stubs/inertia/resources/js/Jetstream/NavLink.vue) is containing the correct inertia-link tag. I've created a project from the master brach too, and it works. So maybe it got already fixed.

**Comment by driesvints** [comment]
Please see the answer above.
