### ISSUE TITLE
(Inertia) Clicking a link causes full page reload

### ISSUE THREAD

**Issue by lucasvbeek** [laravel/jetstream#6]
- Jetstream Version: 0.0.3
- Laravel Version: 8.x-dev

### Description:
The NavLink, ResponsiveNavLink and DropdownLink components are using regular anchor tags instead of inertia-link, which results in unwanted full page reloads.

### Steps To Reproduce:
- Setup a Laravel 8 project with Jetstream (Inertia)
- Click any link

**Comment by taylorotwell** [comment]
Feel free to send PR.

**Comment by taylorotwell** [comment]
I should be able to get to it today if nobody else does.

**Comment by taylorotwell** [comment]
Got it taken care of on next patch.
