### ISSUE TITLE
[FEATURE] Ability to customise the Settings URL

### ISSUE THREAD

**Issue by Chazza** [laravel/jetstream#600]
Hi team,

Thanks for creating Jetstream, would you be able to allow us to customise the settings url, as I want to use /user/profile for something else.

Thanks.

**Comment by driesvints** [comment]
The routes are published after installation so edit them as you like.

**Comment by Chazza** [comment]
> The routes are published after installation so edit them as you like.

Thank you @driesvints, is this a new thing? As at time of me trying it, I had to manually publish the routes.

**Comment by brentarcane** [comment]
You still have to publish the routes using:

`php artisan vendor:publish --provider="Laravel\Jetstream\JetstreamServiceProvider" --tag=jetstream-routes`

Once you do this, you can edit Jetstream URLs in `routes/jetstream.php`

**Comment by Chazza** [comment]
> You still have to publish the routes using:
> 
> `php artisan vendor:publish --provider="Laravel\Jetstream\JetstreamServiceProvider" --tag=jetstream-routes`
> 
> Once you do this, you can edit Jetstream URLs in `routes/jetstream.php`

Thank you, I ended up doing this via:
> php artisan vendor:publish --tag=jetstream-routes

I wasn't sure if it automatically published when creating a new Jetstream app since.
