### ISSUE TITLE
Putting i18n support back to Inertia

### ISSUE THREAD

**Issue by bistory** [laravel/jetstream#601]
Hi 👋
I don't want to start a flame war but the removal of i18n support a few days before 2.0 release is regretful...

A lot of Laravel users are not english-speaking and they are probably developing websites in their native language.
Before Jetsteam, installing a Laravel project in a different locale was simple : create the project, add laravel/ui then add translations with the awesome laravel-lang/lang package.

Now we have to add translation to every Vue component. This adds a useless and time-consuming step.
Then when Jetstream is updated, we have to go across every file checking what have changed to update files manually...

Is there a chance you change your mind about i18n support for Inertia ?

Thanks !

**Comment by driesvints** [comment]
Heya. I'm sorry but we won't be reconsidering this, sorry.

**Comment by bistory** [comment]
Understood... sadly

**Comment by PhilippVujic** [comment]
Really sad it won't be reconsidered. Is there a way to implement this myself then?
