### ISSUE TITLE
Set a default team on registration

### ISSUE THREAD

**Issue by johnpaulmedina** [laravel/jetstream#603]
When using teams as an "organization" rather than arbitrarily creating a new team for every user within the application which allows them to invite to their team and so forth - it would be best to have a feature that allows a default team.

Example:

Using Jetstream as an enterprise web app. We want the ability to add all of the employees. Additionally, we want to have separate offices (teams). Where team_id 1 is the main organization and each other team is another office. At the top level we can assign a user to another office but they are always part of the default team as well. This allows for us to control the manager of each team and limit office specific items to their teams.

**Comment by dalehurley** [comment]
I recommend you look at the team policy and replicate that into an organisation policy implementing your specific use case.

**Comment by johnpaulmedina** [comment]
I agree for this specific use case of "Organizations".

In the above example I just used my use case to best describe the feature. In the current setup if I have 10 users on my team those ten can make their own team and invite others and so forth. Or if using permissions to control the creations of teams those 10 users will still have their own team. Having your own team is not a one size fits all use case and may complicate user experiences when interacting with an application.

If I had an application with thousands of users then I would also now have thousands of teams created upon registration. One can argue to disable the teams support but out of the box it does what most developers need structurally. 

Similar to how Team has an option for invitations it should allow to specify a default team_id & role to eliminate creating a user team each time a user registers.

It just makes the out-the-box features more powerful

**Comment by joelbutcher** [comment]
I highly doubt that an Organisational context will be added to Jetstream out-of-the-box. You would be better off writing a package with migrations and override the registration mechanics with a custom views /actions etc.

**Comment by driesvints** [comment]
We have no plans for this sorry.

**Comment by johnpaulmedina** [comment]
I wasn't asking for organizational context. I was referring to team functionality. But ok.

**Comment by dalehurley** [comment]
@johnpaulmedina I reread your post.

Again this is a specific use case.

I would recommend you look at modifying:

- app/Actions/Fortify/CreateNewUser.php
- app/Actions/Jetstream/AddTeamMember.php
- app/Actions/Jetstream/CreateTeam.php

You can modify the Actions to your use case.

**Comment by webcourse-ng** [comment]
A "default team" setting, instead a unique and individual one, is also an option I am looking for...
