### ISSUE TITLE
Switch user's current team when accepting an email invitation

### ISSUE THREAD

**Issue by relaypilot** [laravel/jetstream#605]
When a user receives an invitation email and clicks on the button to join the new team, it would make sense to automatically update his `current_team_id` to the new team ID.

At the moment, accepting an invitation from an email redirects to the dashboard but leaves the user's current team to its previous state (most likely his personal team ID) which can be confusing if the user was expecting to join the new team upon clicking the button.

**Comment by driesvints** [comment]
We're not going to be applying many changes to Jetstream going further, sorry.

**Comment by kjohnson** [comment]
For those looking to add this functionality, I was able to copy the Route definition and use a custom controller (same name, different namespace).

### routes/web.php
```php
Route::get('/team-invitations/{invitation}', [TeamInvitationController::class, 'accept'])
    ->middleware(['signed'])
    ->name('team-invitations.accept');
```
### app\Http\Controllers\TeamInvitationController.php
```php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Laravel\Jetstream\Contracts\AddsTeamMembers;
use Laravel\Jetstream\TeamInvitation;

class TeamInvitationController extends \Laravel\Jetstream\Http\Controllers\TeamInvitationController
{
    /**
     * @inheritDoc
     */
    public function accept(Request $request, TeamInvitation $invitation)
    {
        app(AddsTeamMembers::class)->add(
            $invitation->team->owner,
            $invitation->team,
            $invitation->email,
            $invitation->role
        );

        $invitation->delete();

        /**
         * Switch the user to the inviting team.
         */
        $request->user()->switchTeam( $invitation->team );

        return redirect(config('fortify.home'))->banner(
            __('Great! You have accepted the invitation to join the :team team.', ['team' => $invitation->team->name]),
        );
    }
}

```
