### ISSUE TITLE
Error when adding a second profile picture option

### ISSUE THREAD

**Issue by Chazza** [laravel/jetstream#608]
Hi Team,

Firstly, thanks for creating Jetstream, I'm still in my early stages yet with Laravel but Jetstream seems fantastic. I'm coming from Breeze, so apologies if this is 'self solvable'.

I'm adding in the ability for a user to be able to specify a profile banner, I've added in my HasProfileBanner trait (a duplicate of the existing HasProfilePhoto trait). I've copied this into the `update-profile-information-form` blade file, and when I go to upload an avatar I get the following error:
Property [$banner] not found on component: [laravel.jetstream.http.livewire.update-profile-information-form] 

When looking into this, the `UpdateProfileInformationForm` inside of the vendor folder, but there seems to be no way to publish this?

I'm using the newest version of Laravel (2.x) at time of this issue, with the Livewire stack integrated. This is basically stock Jetstream, minus adding the banners.

Please advise on this, as I'm not sure where to go.

**Comment by joelbutcher** [comment]
Hi @chazza if you want to "extend" the functionality of these components, then you're probably best of extending the class responsible for it and re-registering it in a service provider.

**Comment by Chazza** [comment]
> Hi @Chazza if you want to "extend" the functionality of these components, then you're probably best of extending the class responsible for it and re-registering it in a service provider.

Hi Joel, is there not a wait to publish those? I'm somewhat new to this still, so don't know how to do that aspect yet.  I dived into the above file and saw the information was there, and thought all I'd need to do is copy paste that.

**Comment by joelbutcher** [comment]
There's no way to publish the PHP classes responsible managing the components in Jetstream. You'll have to extend them yourself for added functionality. 

On the plus side, the actions that these component classes use are published, so you're easily able to update your validation etc. 

See `App\Actions\Jetstream`

**Comment by Chazza** [comment]
> There's no way to publish the PHP classes responsible managing the components in Jetstream. You'll have to extend them yourself for added functionality.
> 
> On the plus side, the actions that these component classes use are published, so you're easily able to update your validation etc.
> 
> See `App\Actions\Jetstream`

I did add in my validation for my `banner` but get the above error, I'm guessing due to the `UpdateProfileInformationForm` LiveWire component only having photo?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Chazza** [comment]
> Hi there,
> 
> Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:
> 
> * [Laracasts Forums](https://laracasts.com/discuss)
> * [Laravel.io Forums](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [Discord](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
> 
> However, this issue will not be locked and everyone is still free to discuss solutions to your problem!
> 
> Thanks.

Hi @driesvints, would this not be an issue as I cannot publish the file, and I'm stuck with this error.

**Comment by driesvints** [comment]
@Chazza if this is an issue then please file a bug report with the issue template filled in.

**Comment by Chazza** [comment]
@driesvints done #614
