### ISSUE TITLE
Validation errors not working with Inertia

### ISSUE THREAD

**Issue by lucaros97** [laravel/jetstream#612]
- Jetstream Version: 2.0.0
- Jetstream Stack: Inertia
- Laravel Version: 8.21.0
- PHP Version: 7.4.13
- Database Driver & Version: MySQL 8.0.17

Description:
I'm using a form with some fields that are required and I'm validating them. However when I submit the form, it throw the errors in the respective bags but I can't show them with the `form.error` method.

Steps To Reproduce:
Here is the code:

In the Vue component I have this:
```js
<form class="w-full text-left">
  <div class="w-full mt-2">
    <div class="col-span-6 sm:col-span-4">
      <jet-label for="name" value="Name" />
      <jet-input id="name" type="text" class="rounded-md mt-1 block w-full" v-model="form.name" autocomplete="name" />
      <jet-input-error :message="form.error('name')" class="mt-2" />
    </div>
  </div>
</form>


data() {
    return {
        form: this.$inertia.form({
            name: null,
        }, {
            bag: 'addNewDomain',
            resetOnSuccess: false,
       }
    }
}

methods: {
    addNewDomain() {
      this.form.post(route("domain.store"), this.form, {
        preserveScroll: true,
      });
    },
}
```

In the Controller I Validate with the default Laravel Validation Helper:
```php
public function store(Request $request)
{
    request()->validate([
        'name' => 'required|string',
    ]);
}
```

**Comment by lucaros97** [comment]
Here is the error props:
![image](https://user-images.githubusercontent.com/8333004/103999828-b0089580-519d-11eb-9957-3c0b273cdc26.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
