### ISSUE TITLE
Cannot create other user media types due to no vendor:publish option

### ISSUE THREAD

**Issue by Chazza** [laravel/jetstream#614]
- Jetstream Version: 2.x
- Jetstream Stack: Livewire
- Laravel Version: 8
- PHP Version: 7.4
- Database Driver & Version: MySQL

### Description:
There is currently no way to publish the Livewire component classes, meaning its impossible to be able to add other avatar options, such as a user banner. When looking, this code is listed inside of a Livewire Component class, which cannot be exported via vendor:publish currently.

### Steps To Reproduce:
 1. Copy the HasProfilePhoto trait, name it HasProfileBanner.
 2. Add a `profile_banner_path` to a User model.
 3. Copy the Profile Photo section inside of `update-user-information-form`.
 4. Change the name from `photo` to banner.
 5. Add the banner validation inside of the `UpdateUserInformation` class.
 6. You'll get a `Property [$banner] not found on component: [laravel.jetstream.http.livewire.update-profile-information-form]` error when submitting a new banner.

**Comment by driesvints** [comment]
Hey @Chazza. This isn't a bug but a feature request and one that has been denied already: https://github.com/laravel/jetstream/pull/308

Sorry but we're not reconsidering this at the time. You can still build your own Livewire components and use those if you want.

**Comment by Chazza** [comment]
> Hey @Chazza. This isn't a bug but a feature request and one that has been denied already: #308
> 
> Sorry but we're not reconsidering this at the time. You can still build your own Livewire components and use those if you want.

How comes we can’t get the Livewire components themselves if this is a starter kit?
