### ISSUE TITLE
Shared data to Inertia not working on Jetstream 2

### ISSUE THREAD

**Issue by lucaros97** [laravel/jetstream#617]
- Jetstream Version: 2.0.0
- Jetstream Stack: Inertia
- Laravel Version: 8.21.0
- PHP Version: 7.4.13
- Database Driver & Version: MySQL 8.0.17

### Description:
After upgrading Laravel Jetsream to v2, I updated @inertiajs/inertia to v0.8.2 and @inertiajs/inertia-vue to v0.5.4

Now when I login into the app it throw this errors:
```js
[Vue warn]: Error in render: "TypeError: undefined is not an object (evaluating '_vm.$page.user.profile_photo_url')"

found in

---> <AppLayout> at resources/js/Layouts/AppLayout.vue
       <Show> at resources/js/Pages/Domains/Show.vue
         <Inertia>
           <Root>
```

```js
TypeError: undefined is not an object (evaluating '_vm.$page.user.profile_photo_url')
```

**Comment by driesvints** [comment]
This is a manual task to do and not part of the upgrade process.
