### ISSUE TITLE
Jetstream 2.0 bombs on sail artisan migrate on clean install using MariaDB.

### ISSUE THREAD

**Issue by leradix** [laravel/jetstream#619]
- Jetstream Version: 2.0.3
- Jetstream Stack: Livewire
- Uses Teams: no
- Laravel Version: 8.5.7
- PHP Version: 8.0.0
- Database Driver & Version: mariadb 10.5

### Description:

Getting the following QueryException on artisan migrate when installing Jeststream on a clean install of Laravel via Docker/Sail. Only changes to .env was the root password and only change to docker.compose.yml was swapped out mysql for mariadb:latest. I had previously installed previous version of Jetstream ok (not 2.0) but ran into this error.

   Illuminate\Database\QueryException

  SQLSTATE[HY000] [1045] Access denied for user 'root'@'172.18.0.5' (using password: YES) (SQL: select * from information_schema.tables where table_schema = lastleaf and table_name = migrations and table_type = 'BASE TABLE')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:678
    674▕         // If an exception occurs when attempting to run a query, we'll format the error
    675▕         // message to include the bindings with SQL, which will make this exception a
    676▕         // lot more helpful to the developer instead of just the database's errors.
    677▕         catch (Exception $e) {
  ➜ 678▕             throw new QueryException(
    679▕                 $query, $this->prepareBindings($bindings), $e
    680▕             );
    681▕         }
    682▕

      +33 vendor frames
  34  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

### Steps To Reproduce:

Brand new install of Laravel project using instructions for Windows (WSL 2).

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
