### ISSUE TITLE
[Feature] Allow Exporting of Livewire Components (Classes)

### ISSUE THREAD

**Issue by Chazza** [laravel/jetstream#621]
#### Why?
Exporting of the components (code behind) would allow for extra user customisation that normally wouldn't be accessible otherwise. For example, currently its _impossible_ to have profile banners using Jetstream as the photo code is burried within the `UpdateUserProfileInformation` component class.

I know @calebporzio did a PR back in October which got rejected, but this would open up more options for customisation. As someone who has a site currently being developed under Breeze, I'd like to utilise Jetstreams scaffolding, and seeing as the sole purpose is to be a customisable and ready to go base.

Please please reconsider this option, currently I have it somewhat implemented, but the vendor providers make it impossible unless I manually comment out other code.

**Comment by driesvints** [comment]
I'm sorry but I've already explained to you in https://github.com/laravel/jetstream/issues/614 that we're note reconsidering this for the time being. If you really want to try again feel free to attempt a PR to see if Taylor would accept it but I doubt it.
