### ISSUE TITLE
User Verification Using Notification Channels

### ISSUE THREAD

**Issue by dillingham** [laravel/jetstream#626]
Would be pretty awesome if we could use a notification channel for verification.
Email (current) is default. But also sms, phone, etc.
Even address verification with a postcard (like nextdoor app) using lob notification channel 
Maybe even use same programming for 2FA with sms, email & phone codes like banks etc

**Comment by joelbutcher** [comment]
Whilst this would be cool, yhis isn't the responsibility of Jetstream. Laravel's user verification by default only uses the users email. 

Take a look at the `App\Actions\Fortify\CreateNewUser` action - this is where the logic is called for sending the verification email. If you want this specific functionality, your best to implement this in your own application, like everyone else. 

Alternatively, you could build a package that replaces the action.

**Comment by dillingham** [comment]
@joelbutcher Im aware that jetstream uses email to verify users. I'm saying if it instead used a email notification.. and a config option of which notification class.. and the schema was generic.. we could have this awesome functionality to opt into very easily. Or however a clean coder would implement it lol 

Thanks for your feedback though 😃

**Comment by dillingham** [comment]
It does seem more of an Illuminate topic. 
Just removing the word email from this class illustrates my pointt.
But I see what you mean.

```
<?php

namespace Illuminate\Auth\Listeners;

use Illuminate\Auth\Events\Registered;
use Illuminate\Contracts\Auth\MustVerifyEmail;

class SendVerificationNotification
{
    /**
     * Handle the event.
     *
     * @param  \Illuminate\Auth\Events\Registered  $event
     * @return void
     */
    public function handle(Registered $event)
    {
        if ($event->user instanceof MustVerify && ! $event->user->isVerified()) {
            $event->user->sendVerificationNotification();
        }
    }
}

```

**Comment by driesvints** [comment]
We have no plans for this atm sorry. Feel free to build this into your own app.
