### ISSUE TITLE
Syntax Error: Unexpected ')' in InstallCommand.php

### ISSUE THREAD

**Issue by PeteBishwhip** [laravel/jetstream#634]
- Jetstream Version: 2.1.0
- Jetstream Stack: Livewire
- Uses Teams: no
- Laravel Version: 8.x
- PHP Version: 7.3
- Database Driver & Version: MySQL

### Description:
Line 500 of InstallCommand.php has an extra comma at the end of some function arguments, causing an error.

I intend to push a fix immediately.

```
[devspace@cpanel1-fsn1-dc7 ragnar.spacefor.dev]$ composer install --ignore-platform-reqs
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   ParseError 

  syntax error, unexpected ')'

  at vendor/laravel/jetstream/src/Console/InstallCommand.php:501
    497â–•             $modifiedMiddlewareGroup = str_replace(
    498â–•                 $after.',',
    499â–•                 $after.','.PHP_EOL.'            '.$name.',',
    500â–•                 $middlewareGroup,
  âžœ 501â–•             );
    502â–• 
    503â–•             file_put_contents(app_path('Http/Kernel.php'), str_replace(
    504â–•                 $middlewareGroups,
    505â–•                 str_replace($middlewareGroup, $modifiedMiddlewareGroup, $middlewareGroups),

      +1 vendor frames 
  2   [internal]:0
      Composer\Autoload\ClassLoader::loadClass("Laravel\Jetstream\Console\InstallCommand")

  3   [internal]:0
      spl_autoload_call("Laravel\Jetstream\Console\InstallCommand")
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

### Steps To Reproduce:
Install laravel 8
Pull in JetStream via Composer

Run php artisan jetstream:install livewire

**Comment by driesvints** [comment]
Don't use `--ignore-platform-reqs`

**Comment by PeteBishwhip** [comment]
@driesvints - `--ignore-platform-reqs` is something I needed to use on my local development environment however, the issue remains.

I recommend re-opening this issue and reviewing the PR I have submitted. You'll see that JetStream in fact has a PHP Syntax Error.

**Comment by driesvints** [comment]
You're using a language feature that doesn't exists for the PHP version you're using. You're causing this by using that flag.
