### ISSUE TITLE
System Admin separate from team_roles

### ISSUE THREAD

**Issue by jbersamin** [laravel/jetstream#637]
Hi Guys,

My requirement is to have a single or two user to access the entire application and display all teams and they can switch to it and view the team data.

In the current jetstream team setup how I will do this?

_This is not an issue but a question. Please close this issue if I'm in the wrong place or point me where should I ask this question. Thanks_

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
