### ISSUE TITLE
Text on website is hidden behind sidebar

### ISSUE THREAD

**Issue by tobx** [laravel/jetstream#638]
### Description:
The main text on the website ([jetstream.laravel.com](https://jetstream.laravel.com)) is hidden behind the sidebar.

### Steps To Reproduce:
Set the browser resolution width to something between 960 and about 1150 (see screenshot).

I am using Firefox 84.0.2 on macOS 11.1.

![jetstream](https://user-images.githubusercontent.com/6427718/104711803-1ce1d980-5722-11eb-9e2b-9e9dad0bb92a.png)

**Comment by driesvints** [comment]
Thanks. I don't think this is a too big deal since you can just widen your browser. We'd be happy to accept a PR to fix this however.

**Comment by tobx** [comment]
I agree, but I did not just open this issue because I do not want to change my browser width. I thought this might be in your interest to fix, because I think 960 to 1150 is a quite common browser width and not every user will think of resizing their browser window if there is a design error. Furthermore it is a little annoying if every user who is used to this size has to resize its browser every time again when he needs to read something in the docs.

I can imagine there is more important issues to work on and this is really not a big deal, I am super happy with Jetstream in general, but I thought you might want to reconsider. If not, that is alright with me, I also have currently not enough time to analyze the CSS of this page.
