### ISSUE TITLE
"This user has already been invited to the team" error

### ISSUE THREAD

**Issue by wezcornell** [laravel/jetstream#643]
- Jetstream Version: 2.1.0
- Jetstream Stack: Livewire
- Uses Teams: yes
- Laravel Version: 8.22.1
- PHP Version: 7.4.13
- Database Driver & Version: MySQL

### Description:
Receiving "This user has already been invited to the team" when adding a team member's email that has been previously invited to another team.

### Steps To Reproduce:
1) Create two teams under the same user account. (I used my 'personal' team + setup another non-personal team)
2) In the FIRST team invite a@a.com (DO NOT accept invite via email)
3) In the SECOND team invite b@b.com (DO NOT accept invite via email)
4) Go back to the FIRST team, and try to add b@b.com, you'll receive "This user has already been invited to the team"

**Comment by driesvints** [comment]
I can confirm this. It seems that the user's account setup is still pending which doesn't allows invites to other teams at the same time.

Appreciating a PR for this, otherwise I'll take a look at this soon.

**Comment by taylorotwell** [comment]
Fixed in next patch release (sometime today).
