### ISSUE TITLE
What if the published Jetstream feature tests were put in their own folder?

### ISSUE THREAD

**Issue by exzachlyvv** [laravel/jetstream#644]
In all of my applications, I organize my unit tests into folders per feature or area. Otherwise, the top-level `test/Feature` folder gets too cumbersome. I'm wondering how we feel about doing something similar with Jetstream published tests? We could move them to `test/Feature/Jetstream` or something similar.

Love that they are published now btw.

**Comment by driesvints** [comment]
I don't think we have plans for that right now sorry.
