### ISSUE TITLE
Missing jetstream-options config

### ISSUE THREAD

**Issue by iantasker** [laravel/jetstream#646]
- Jetstream Version: All
- Jetstream Stack: All
- Uses Teams: Either

### Description:

The `Features` class references the config file `jetstream-options` in the `optionEnabled` method but this file is not created when jetstream is installed. 

Should the file be created during install or should it reference an `options` section within the existing `jetstream` config file?

**Comment by driesvints** [comment]
It's dynamic config at runtime. See https://github.com/laravel/jetstream/blob/c9913fbe0ec725b51f8c229c9d92eb4cca38146e/src/Features.php#L122
