### ISSUE TITLE
PHP7.4.13 Laravel 8 with team error on first load due to TeamInvitationController.php

### ISSUE THREAD

**Issue by elsodev** [laravel/jetstream#647]
- Jetstream Version: 2.1.1
- Jetstream Stack: Inertia 
- Uses Teams: yes 
- Laravel Version: 8.24.0
- PHP Version: 7.4.13
- Database Driver & Version: MySQL 5.7

### Description:
Flare error
https://flareapp.io/share/17WEyL3m

**File**
`vendor/laravel/jetstream/src/Http/Controllers/TeamInvitationController.php`
```
        return redirect(config('fortify.home'))->banner(

            __('Great! You have accepted the invitation to join the :team team.', ['team' => $invitation->team->name]),

        );

```

**Suggested fix, remove comma from end of first param**
```
        return redirect(config('fortify.home'))->banner(

            __('Great! You have accepted the invitation to join the :team team.', ['team' => $invitation->team->name])

        );

```

### Steps To Reproduce:
1. Fresh install of Laravel 8 with Jetstream Inertia with teams
2. Using Valet to run Laravel projects
3. Will run in this problem immediately on first load
4. Double confirmed Laravel is running on 7.4.13 using tinker `phpversion();` and composer is on PHP7.4.13 as well

**Comment by driesvints** [comment]
You don't seem to be running Laravel on 7.4. Most likely your CLI runs on a different version.
