### ISSUE TITLE
Prefetch Pagination Responses

### ISSUE THREAD

**Issue by johnpaulmedina** [laravel/jetstream#648]
Just shooting this out there. Might be more of a use-case implementation and I understand Jetstream was more of a starter-kit so I don't know if it is a feature that can be included by default.

When loading paginated data have a response intercepter that will prefetch the next page url of the Jetstream response.

I am currently implementing this on our application using the Cache engine to store responses. When `Jetstream::inertia()->render` response has a `prefetch` flag set then on the frontend I am prefetching the next_url which would save that response in Cache on the Laravel side so when/if the user clicks to the next page its almost instant.

The toss up is that each request basically makes 2 requests IF it was told to prefetch - but the user experience is improved drastically when handling large datasets.

**Comment by driesvints** [comment]
Feel free to attempt a PR to see if Taylor would accept it 👍
