### ISSUE TITLE
TeamMemberManager not using custom TeamInvitation model

### ISSUE THREAD

**Issue by asivaneswaran** [laravel/jetstream#649]
- Jetstream Version: 2.1.1
- Jetstream Stack: Livewire
- Uses Teams: yes
- Laravel Version: 8.24.0
- PHP Version: 8.0.0
- Database Driver & Version:

### Description:
The cancelTeamInvitation method does not use the custom Team Invitation model that was defined

### Steps To Reproduce:
1- Open TeamMemberManager.php
2- Scroll to line 128:
```   
 public function cancelTeamInvitation($invitationId)
    {
        if (! empty($invitationId)) {
            TeamInvitation::whereKey($invitationId)->delete();
        }

        $this->team = $this->team->fresh();
    }
```

**Comment by driesvints** [comment]
> Open TeamMemberManger.php

There's no such class in Jetstream v2.

**Comment by asivaneswaran** [comment]
@driesvints I realized all my tests are old files.... It's not showing up on my vendor either?

**Comment by driesvints** [comment]
@asivaneswaran there was a typo in your class name which is why I didn't find it :')

I've sent in a fix here: https://github.com/laravel/jetstream/pull/651. Thanks for reporting.

**Comment by asivaneswaran** [comment]
@driesvints  Oh yeah, you are absolutely right haha. I will edit it for future reference.
