### ISSUE TITLE
Problem to register a new users: Target [Laravel\Fortify\Contracts\CreatesNewUsers] is not instantiable.

### ISSUE THREAD

**Issue by danidoble** [laravel/jetstream#65]
- Jetstream Version: 0.6.4
- Laravel Version: 8.0
- PHP Version: 7.4.9
- Database Driver & Version: MySQL 5.7.24 

### Description:
`Illuminate\Contracts\Container\BindingResolutionException`
`Target [Laravel\Fortify\Contracts\CreatesNewUsers] is not instantiable.`

Here you can see the error
[https://flareapp.io/share/4m4lgpmM#F54](url)

### Steps To Reproduce:
I just install laravel 8, and install jetstream
`composer require laravel/jetstream`
And next I install livewire 
`php artisan jetstream:install livewire`
I compile the assets 
`npm install && npm run dev`
I Publish the views
`php artisan vendor:publish --tag=jetstream-views`
And I make the migration
Until here everything it's fine but, when i try to register a new user i have the error

This error also have when i use 
`laravel new project-name --jet`

**Comment by yasserbn97** [comment]
you must register `FortifyServiceProvider ` and `JetstreamServiceProvider` providers in `config/app.php`

```
        'providers' => [
		// [...]
                App\Providers\FortifyServiceProvider::class,
                App\Providers\JetstreamServiceProvider::class,
        ],

```
