### ISSUE TITLE
Impossible to edit email text

### ISSUE THREAD

**Issue by andreacivita** [laravel/jetstream#654]
# Description

Hi, i found impossible to edit or configure verification email text (i want to localize it italian). There is no way to edit text because i have no idea of where it is generated.

I published all tags, but i have only views populated by {{ $slot }}. Where I found this slot and how can i publish it to my src directory (since I can't edit vendor dir).

Thanks

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by andreacivita** [comment]
Hi man, 
No i think its a bug because \Illuminate\Auth\Notifications\VerifyEmail class is not published so i have no way to edit its content.
Is there a way to generate it with `php artisan vendor:publish` or i have to replace this file?

**Comment by andreacivita** [comment]
I solved the problem following this guide: https://laracasts.com/discuss/channels/laravel/how-to-publish-verifyemailphp-in-laravel-57.

**Comment by ndmgrphc** [comment]
It's not a bug it's just a major oversight and violation of the 80/20 opinionation rule.  What's more depressing than the dismissive response is that you had to reference a laravel 5.7 hack.  This happens in almost every framework's lifecycle.  Stubborn culture infects core contributor team and forks are born...  Just a matter of time.
