### ISSUE TITLE
Invite to team without new user creating their own team

### ISSUE THREAD

**Issue by ryanxedi** [laravel/jetstream#657]
Currently, when inviting a user to a team, the new user is required to register (if not already registered) and this generates the user their own team.  It would be helpful to have an option to NOT create a new team for invited users, and just add them to the invited team.  If you've been invited to use a new app, you wouldn't typically need to have your own team too.

Otheriwse, absolutely stunning work.....

**Comment by driesvints** [comment]
Jetstream requires each user to have their own personal team at all times, even with teams disabled.
