### ISSUE TITLE
Test Tests\Feature\EmailVerificationTest::test_email_verification_screen_can_be_rendered fails after installing it with Teams feature

### ISSUE THREAD

**Issue by erhansogut** [laravel/jetstream#660]
- Jetstream Version: 2.1
- Jetstream Stack: Inertia
- Uses Teams: yes
- Laravel Version: 8.12
- PHP Version: 8
- Database Driver & Version: MySql

### Description:
With a clean install of Laravel and Jetstream running the command 'php artisan test --parallel' 
all test passes except one test_email_verification_screen_can_be_rendered 

### Steps To Reproduce:
After installation and configuration of Laravel with Jetstream
Run 'php artisan test --parallel' 
Receive this error

```
 • Tests\Feature\EmailVerificationTest > email verification screen can be rendered
   ErrorException 

  Attempt to read property "user_id" on null

  at vendor/laravel/jetstream/src/HasTeams.php:107
    103▕      * @return bool
    104▕      */
    105▕     public function ownsTeam($team)
    106▕     {
  ➜ 107▕         return $this->id == $team->user_id;
    108▕     }
    109▕ 
    110▕     /**
    111▕      * Determine if the user belongs to the given team.

      +16 vendor frames 
  17  [internal]:0
      Inertia\Response::Inertia\{closure}()

      +49 vendor frames 
  67  tests/Feature/EmailVerificationTest.php:30
      Illuminate\Foundation\Testing\TestCase::get()
```

i got it working by adjusting the test to

    public function test_email_verification_screen_can_be_rendered()
    {
        $this->withoutExceptionHandling();

        if (! Features::enabled(Features::emailVerification())) {
            return $this->markTestSkipped('Email verification not enabled.');
        }

        $user = User::factory()->withPersonalTeam()->create([
            'email_verified_at' => null,
        ]);

        $response = $this->actingAs($user)->get('/email/verify');

        $response->assertStatus(200);
    }

**Comment by driesvints** [comment]
Hmm can't reproduce this. This works fine for me on a fresh Jetstream install.

**Comment by erhansogut** [comment]
Weird didn't do any changes its just a fresh install and then runned 'php artisan jetstream:install inertia --teams' after that i tried testing 'php artisan test --parallel' i'm running the latest Homestead, Laravel, Jetstream. It getting the error because Jetstream expects a default Personal team and with the test its not generating a team i think the error is generated because its trying to fetch the teams of the user.

**Comment by kapilashrami** [comment]
This worked for me 

```
 public function test_email_verification_screen_can_be_rendered()
    {
        if (! Features::enabled(Features::emailVerification())) {
            return $this->markTestSkipped('Email verification not enabled.');
        }

        $user = User::factory()
            ->withPersonalTeam() // <- Added this
            ->create([
                'email_verified_at' => null,
            ]);

        $response = $this->actingAs($user)->get('/email/verify');

        $response->assertStatus(200);
    }
```

**Comment by azurinspire** [comment]
I had same problem, adding `Team::factory()->create(['user_id' => $user->id,]);` to `test_email_verification_screen_can_be_rendered` solves the problem. Should check `Features::teams` of course in general Jetstreams installation.

**Comment by vincenzoraco** [comment]
> I had same problem, adding `Team::factory()->create(['user_id' => $user->id,]);` to `test_email_verification_screen_can_be_rendered` solves the problem. Should check `Features::teams` of course in general Jetstreams installation.

Or you can use the factory state manipulation method to add the team instead

```
$user = User::factory()->withPersonalTeam()->create([
    'email_verified_at' => null,
]);
```
