### ISSUE TITLE
Issues with Auth helper

### ISSUE THREAD

**Issue by ctschetter** [laravel/jetstream#664]
- Jetstream Version: 2.1.3
- Jetstream Stack: Livewire
- Uses Teams: no
- Laravel Version: 8.5.9
- PHP Version: 7.4.6
- Database Driver & Version: MySQL 5.7.22

### Description:
When using Laravel Jetstream, the Auth helper functions do not work.
E.G. Auth::loginUsingId($id);
Even with the Auth facade imported you will get:
"Method Illuminate\Auth\RequestGuard::loginUsingId does not exist."

### Steps To Reproduce:
Login as an existing user, then run Auth::loginUsingId($id);

**Comment by joelbutcher** [comment]
The exception is correct for the `RequestGuard`. You need to configure your application to use the `SessionGuard` if you want to utilise this specific method.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
