### ISSUE TITLE
Create Team disabled on Team Policy, but teams/create route not disabled. 

### ISSUE THREAD

**Issue by berkerbekman** [laravel/jetstream#665]
- Jetstream Version: Latest
- Jetstream Stack:  Livewire
- Uses Teams: yes
- Laravel Version: Latest
- PHP Version: Latest
- Database Driver & Version: sqlite

### Description:

I don't want the user to create more than one team. i disabled in team policy.

`    public function create(User $user)
    {
        return false;
    }`

but I can access the route. localhost/teams/create

when i press the create button, the unauthorized modal opens. the route itself needs to be unauthorized. teams/create.

### Steps To Reproduce:
<img width="1438" alt="Ekran Resmi 2021-02-07 22 58 27" src="https://user-images.githubusercontent.com/22637092/107157944-0aad3100-6998-11eb-8b17-6a293640efc4.png">

**Comment by driesvints** [comment]
Enabling or disabling teams needs to be done up front when creating an app and not afterwards.

**Comment by berkerbekman** [comment]
> Enabling or disabling teams needs to be done up front when creating an app and not afterwards.

I didn't understand exactly what to do. Can you explain more clearly?

**Comment by driesvints** [comment]
@berkerbekman when you first install Jetstream you're presented with the option to choose teams or not. If you choose teams upon install you cannot easily disable it afterwards as there's much tiny bits and pieces that can cause issues like the above. Try installing a fresh jetstream app and choose to not enable teams upon installation.

**Comment by berkerbekman** [comment]
> @berkerbekman when you first install Jetstream you're presented with the option to choose teams or not. If you choose teams upon install you cannot easily disable it afterwards as there's much tiny bits and pieces that can cause issues like the above. Try installing a fresh jetstream app and choose to not enable teams upon installation.

I did. but there is the same error. I think this is a bug that needs to be fixed.

laravel new project
composer require laravel/jetstream
php artisan jetstream:install livewire
php artisan jetstream:install livewire --teams

I did all the steps in order. The error is the same.

**Comment by driesvints** [comment]
You ran the install step two times. One time without the teams option and one time with the teams option. You can only run it one time.

**Comment by berkerbekman** [comment]
> You ran the install step two times. One time without the teams option and one time with the teams option. You can only run it one time.

I tried in two ways. the result is the same.

laravel new project
composer require laravel/jetstream
php artisan jetstream:install livewire --teams
and TeamsPolicy create function true to false.
php artisan migrate
php artisan serve

Should all the steps be like this? It doesn't work that way.

**Comment by driesvints** [comment]
I'm sorry, I totally misunderstood the issue. I can now see what you mean. I'll PR a fix. Thanks for reporting!

**Comment by driesvints** [comment]
@berkerbekman I'll keep this open until the PR is merged
