### ISSUE TITLE
Modify jetstream actions like fortify

### ISSUE THREAD

**Issue by GDanielRG** [laravel/jetstream#672]
I am trying to add a line of code to the logout-from-other-browser-sessions code, just to flash a notification message, but it appears that theres not a way to modify the actions like in fortify. Something like this would be useful.

**Comment by driesvints** [comment]
At the moment we don't support publishing Livewire components. See Taylor's answer here: https://github.com/laravel/jetstream/pull/308#issuecomment-707162659

However, we're welcoming PRs that allow to customize these views further if it's a valid use case. Thanks

**Comment by GDanielRG** [comment]
It's not something related to the views, what I am trying to accomplish is to just run a line of code on the backend when the 'destroy' method of the 'OtherBrowserSessionsController' executes. Just to flash some message. We are able to do this on the actions regarding fortify, but jetstream doesn't seem to allow a way to modify or extend this functionalities. Am I missing something?
