### ISSUE TITLE
Adding extra middleware

### ISSUE THREAD

**Issue by anishsarkar** [laravel/jetstream#675]
Is there any way to add a middleware to any of the routes? For  example, I would like to close registration when I reach a count of 10000 users. I was wondering if there is any way other than manually commenting out in the fortify config file the feature of registration.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by joelbutcher** [comment]
@anishsarkar You can add middleware to your fortify config file. Once you've written it, add it to your applications route middleware in `app/Http/Kernel.php` like so:

```php

    /**
     * The application's route middleware.
     *
     * These middleware may be assigned to groups or used individually.
     *
     * @var array
     */
    protected $routeMiddleware = [
        'foo' => \App\Http\Middleware\FooMiddleware::class,
    ];~~~~
```

then call it in `config/fortify.php` using:

```php
    // ...
    'middleware' => ['web', 'foo'],
    // ...
```
