### ISSUE TITLE
Suggestion: Pre-fill email on the registration form when inviting users

### ISSUE THREAD

**Issue by stancl** [laravel/jetstream#678]
It would be nice if the registration link in the team invitation email pre-filled the email address of the team member.

That way they can't accidentally sign up with a wrong email address — the accept invitation link wouldn't work with it.

The changes would probably be these:

https://github.com/laravel/jetstream/blob/9dbc974ab0a1757bd185c7461df01f6c1e33f27d/stubs/livewire/resources/views/auth/register.blade.php#L19

```diff
- <x-jet-input id="email" class="block mt-1 w-full" type="email" name="email" :value="old('email')" required />
+ <x-jet-input id="email" class="block mt-1 w-full" type="email" name="email" :value="old('email') ?? request('email')" required />
```

https://github.com/laravel/jetstream/blob/9dbc974ab0a1757bd185c7461df01f6c1e33f27d/resources/views/mail/team-invitation.blade.php#L6

```diff
- @component('mail::button', ['url' => route('register')])
+ @component('mail::button', ['url' => route('register', ['email' => $invitation->email)])
```

Just a suggestion, let me know if you'd like a PR for this.

**Comment by driesvints** [comment]
Yeah seems like a valid suggestion to me. Feel free to attempt a PR to see if Taylor would accept it 👍
