### ISSUE TITLE
Inertia authentication views

### ISSUE THREAD

**Issue by m1guelpf** [laravel/jetstream#68]
When playing around with Jetstream, I got confused as to why my changes to the Inertia components weren't applying to the authentication views until I realized those always use Blade components. To make it easier on myself and prevent confusion, I ported them to Inertia. Is there any interest on a PR to add this to Jetstream?

**Comment by taylorotwell** [comment]
Personally I want to keep these just plain Blade. That way they don't have to be duplicated for each stack.
