### ISSUE TITLE
Support for God Mode

### ISSUE THREAD

**Issue by maxkruger** [laravel/jetstream#682]
When dealing with user's support issues, we need the ability to view what their account looks like, so we can act on their behalf and help diagnose problems. 

Can we have the ability to: 
- Set a user role to `superuser` or similar
- The super user's available team list includes all teams
- The super users are able to switch to a team, and the current team variable reflects that team
- View all teams on an admin page

**Comment by ionasskopelitis** [comment]
I guess you could use something like:
```
Gate::after(function ($user, $ability) {
    return $user->is_superuser (or maybe check the usertype whatever floats your boat) && env('ENABLE_SUPERUSER', false);
});
```

**Comment by joelbutcher** [comment]
Whilst you will lack the "has all teams" trait of a superuser role. Check out [Laravel Impersonate](https://github.com/404labfr/laravel-impersonate)

**Comment by maxkruger** [comment]
This is just what I was after. Thanks!
