### ISSUE TITLE
Tests fail on fresh install of jetstream (minus teams support) if API feature enabled.

### ISSUE THREAD

**Issue by jonnywilliamson** [laravel/jetstream#684]
- Jetstream Version: 2.2.1
- Jetstream Stack: Inertia
- Uses Teams: no
- Laravel Version: 8.28.1
- PHP Version: 7.4.13
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.32

### Description:
On a fresh install of laravel, then jetstream (with NO team support) following the install commands in the docs, all tests in the features directory pass.

Then editing `jetstream.php` config and enabling `Features::api()` and re-runing the tests results in the 3 tests failing.

### Steps To Reproduce:

```
laravel new demo
cd demo
composer require laravel/jetstream
php artisan jetstream:install inertia
npm install && npm run dev
php artisan migrate
```

Run the tests. All green.

Edit `jetstream.php` config and enable `Features::api()`

Run the tests. 3 Fail.

I'm not sure if this is by design. But my proposed fix would be something like this:

https://github.com/laravel/jetstream/pull/683

**Comment by driesvints** [comment]
Adjust the tests to your setup.

**Comment by jonnywilliamson** [comment]
Hmm. 

My only point was that I have done NO setup. This is a fresh install. 

Just turning features on or off inside jetstream surely shouldn't make jetstreams tests fail?

**Comment by Raffi-001** [comment]
make sure APP_ENV is set to testing ins your .env file:
`APP_ENV=testing`
