### ISSUE TITLE
Laravel Jetstream email verification not working

### ISSUE THREAD

**Issue by lucaros97** [laravel/jetstream#686]
- Jetstream Version: 2.2.1
- Jetstream Stack: Inertia
- Uses Teams: yes
- Laravel Version: 8.28.1
- PHP Version: 7.4.13
- Database Driver & Version: MySQL 8.0.17

### Description:
I'm using the Inertia version of Laravel Jetstream. 
I have everything configured and working. I enabled the emailVerification entry in my `config/fortify.php` configuration file and I implemented the `MustVerifyEmail` to my User model. 
When I register a user, the app send me the email with the link, however the link seems not working. 
It redirects me to the login page and if I try to login it returns me a `419 Session Expired` error. 
In the user table the `email_verified_at` field it's still null.

Any hint? Thanks

**Comment by lucaros97** [comment]
Just tried also with a fresh new Jetstream app. Configured everything and still getting a 419 session expired when I click in the "verify email address" button and then try to login

**Comment by driesvints** [comment]
I can't reproduce this. I used all the steps from above with the same stack and it works just fine for me in Safari.

**Comment by ArneAnka** [comment]
I have the same problem...

- Jetstream Version: 2.7
- Jetstream Stack: Inertia
- Uses Teams: no
- Laravel Version: 9.10
- PHP Version: 8.1.5
- Database Driver & Version: MySQL 

Cannot figure this one out.

**Comment by benshawuk** [comment]
Same issue here with Jetstream 3.2
