### ISSUE TITLE
Laravel Jetstream - Passport

### ISSUE THREAD

**Issue by drjdr** [laravel/jetstream#690]
if using `passport` rather than `sanctum` we receive an accessToken.
so 
```
'token' => $token->accessToken,
```
instead of:
https://github.com/laravel/jetstream/blob/debf79d278ac7b2fddfc5ae949adcf2b740a4258/src/Http/Controllers/Inertia/ApiTokenController.php#L49

Can we make this compatible?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
