### ISSUE TITLE
Laravel\Jetstream\Http\Livewire\SetPasswordForm component doesn't exist

### ISSUE THREAD

**Issue by slaFFik** [laravel/jetstream#700]
- Jetstream Version: 2.2.3
- Jetstream Stack: Livewire
- Uses Teams: yes
- Laravel Version: 8.31.0
- PHP Version: 7.4.4
- Database Driver & Version: MySQL 5.7

### Steps To Reproduce:
1. install clean laravel and livewire
2. install and configure `laravel/socialite`
3. Your `users` table should have:
```php
$table->string('provider')->index();
$table->string('provider_id')->index();
```
4. Make sure you have `$table->string('password')->nullable();` - because I do not plan to use passwords right now
5. Create GH app, and define all required data in `.env` file
<details>

```php
    'github' => [
        'client_id' => env('GITHUB_CLIENT_ID'),
        'client_secret' => env('GITHUB_CLIENT_SECRET'),
        'redirect' => env('GITHUB_REDIRECT'),
    ],
```

</details>

6. Create `LoginController.php` with something like this:
<details>

```php
<?php

namespace App\Http\Controllers;

use App\Models\Team;
use App\Models\User;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Response;
use Illuminate\Routing\Redirector;
use Illuminate\Support\Str;
use Laravel\Socialite\Facades\Socialite;

class LoginController extends Controller
{
    /**
     * Send the user to auth via a Provider.
     *
     * @param $provider
     *
     * @return Response
     */
    public function redirectToProvider($provider)
    {
        return Socialite::driver($provider)
            ->setScopes(['read:user', 'repo'])
            ->redirect();
    }

    /**
     * Obtain user information from the Provider API.
     *
     * @param  string  $provider  Either github, gitlab, or bitbucket.
     *
     * @return Application|RedirectResponse|Redirector
     */
    public function handleProviderCallback($provider)
    {
        $providerUser = Socialite::driver($provider)->user();
        ray($providerUser);

        $userEmail = $providerUser->getEmail() ?: $this->getGeneratedEmailByProvider($providerUser, $provider);

        // Create user if it doesn't exist.
        $user = User::firstOrCreate(
            [
                'provider' => $provider,
                'provider_id' => $providerUser->getId(),
            ],
            [
                'email' => $userEmail,
                'name' => $providerUser->getName(),
            ]
        );

        /*
         * Every new user needs a team for dashboard/jetstream to work.
         * Create a personal team for the user.
         */
        if ($user->wasRecentlyCreated) {
            $team = Team::forceCreate([
                'user_id' => $user->id,
                'name' => 'Personal Team',
                'personal_team' => true,
            ]);
            $team->save();

            // Assign the user to a newly created team.
            $user->current_team_id = $team->id;
            $user->save();
        }

        auth()->login($user, true);

        return redirect('dashboard');
    }

    private function getGeneratedEmailByProvider($providerUser, $provider): string
    {
        switch ($provider) {
            case 'github':
                return "{$providerUser->getNickname()}@users.noreply.github.com";
            case 'gitlab':
                return "{$providerUser->getId()}-{$providerUser->getNickname()}@users.noreply.gitlab.com";
            case 'bitbucket':
                return "{$providerUser->getNickname()}@users.noreply.bitbucket.org";

            default:
                return Str::random().'@example.com';
        }
    }
}
```
</details>

7. Your `routes/web.php` should have:
<details>

```php
Route::get('/login/{provider}', [LoginController::class, 'redirectToProvider']);
Route::get('/login/{provider}/callback', [LoginController::class, 'handleProviderCallback']);
```

</details>

8. Go through the login process on a site using `/login/github` URL.
9. After confirmation on GH site you are redirected to your site, user/team created, dashboard is working fine.
10. Open `user/profile` URL, and you will see:
<details>

![image](https://user-images.githubusercontent.com/282234/110221511-54286780-7ed5-11eb-9e20-a20540ced405.png)

</details>

11. As I've created a user via provider, the password is null.
12. In `resources/views/profile/show.blade.php` there is a `! is_null($user->password)` check that leads to `@livewire('profile.set-password-form')` being called because the password is null.
13. There is `\Laravel\Jetstream\Http\Livewire\UpdatePasswordForm`, but there is NO `\Laravel\Jetstream\Http\Livewire\SetPasswordForm` component inside the latest jetstream.
14. I guess this is why Jetstream is freaking out.

**Comment by driesvints** [comment]
Hey @slaFFik. I can't find `set-password-form` anywhere in Jetstream. Can you point out with a line to the code where it is?

**Comment by slaFFik** [comment]
I see it in `resources/views/profile/show.blade.php` file after I published a bit more than a week ago the jetstream views, but right now I can't find that in Jetstream repo, even with `git log -Sset-password-form --all`.
I definitely haven't written that from scratch by myself and there are no other packages that implement that for me.
Here is how it looked like:
![image](https://user-images.githubusercontent.com/282234/110384350-2f172e80-8066-11eb-8d0b-2ba313fa795e.png)

Anyway, it's not relevant anymore, because the current Jetstream version doesn't have that code ^.
