### ISSUE TITLE
Using bootstrap instead of tailwind CSS in vue.js welcome component

### ISSUE THREAD

**Issue by orhanerday** [laravel/jetstream#702]
I install jetstream+inertia.js into my laravel project and everything is working perfectly but I need to use bootstrap 5 in only welcome. vue component so how can I handle it?

My app.js file;

```
require('./bootstrap');

// Import modules...
import {createApp, h} from 'vue';
import {App as InertiaApp, plugin as InertiaPlugin} from '@inertiajs/inertia-vue3';
import 'animate.css';
import Toaster from '@meforma/vue-toaster';
import 'alpinejs';



const el = document.getElementById('app');

createApp({
    render: () =>
        h(InertiaApp, {
            initialPage: JSON.parse(el.dataset.page),
            resolveComponent: (name) => require(`./Pages/${name}`).default,
        }),
})
    .mixin({methods: {route}})
    .use(InertiaPlugin)
    .use(Toaster)
    .mount(el);
```
My app.css file:

```
@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';
```

**Comment by driesvints** [comment]
We have no plans to support Bootstrap, sorry.

**Comment by orhanerday** [comment]
I already use Tailwind CSS in auth, but I just want to only one component but I can't.  I asked this question on StackOverflow and attracted attention. https://stackoverflow.com/questions/66494398/how-can-i-use-bootstrap-instead-of-tailwind-css-in-vue-js-welcome-component
