### ISSUE TITLE
The error for 2FA is returned with key "email"

### ISSUE THREAD

**Issue by mokhosh** [laravel/jetstream#704]
I had this issue with Fortify which I reported here https://github.com/laravel/fortify/issues/236 and @driesvints suggested I should make a PR.

So, I added this PR to Fortify https://github.com/laravel/fortify/pull/238 to make validation exception key more consistent.

I'm not sure what parts of Jetstream should be updated other than its composer dependencies to make the relevant PR for Jetstream though.

**Comment by driesvints** [comment]
Actually I think this might be okay after all. It seems errors are just looped over and the key is never used directly in Jetstream: https://github.com/laravel/jetstream/blob/2.x/resources/views/components/validation-errors.blade.php

**Comment by mokhosh** [comment]
amazing @driesvints thanks
