### ISSUE TITLE
Membership incrementing id

### ISSUE THREAD

**Issue by louisgab** [laravel/jetstream#706]
- Jetstream Version: last
- Jetstream Stack: both
- Uses Teams: yes

### Description:
I just noticed there is no override of the `$incrementing` attribute inside the Membership model (which defaults to false in Pivot):
`public $incrementing = true;`
while inside the migration there is a autoincrementing id:
`$table->id()`

I would prefer a combined primary key without id, but it's personal choice, so let's add the incrementing attribute ?

I can PR it

**Comment by driesvints** [comment]
No plans for this sorry.
