### ISSUE TITLE
Foreign key index

### ISSUE THREAD

**Issue by louisgab** [laravel/jetstream#707]
- Jetstream Version: last
- Jetstream Stack: both
- Uses Teams: yes

### Description:
Not realy a bug, but some index are missing on foreign keys inside migrations:

CreateUsersTable:
`$table->foreignId('current_team_id')->nullable();`

CreateTeamuserTable:
`$table->foreignId('team_id');`
`$table->foreignId('user_id');`

CreateTeamInvitationsTable:
`$table->foreignId('team_id')->constrained()->cascadeOnDelete();`

I can PR it if you would

**Comment by driesvints** [comment]
You can add them in your own app 👍

**Comment by fcolecumberri** [comment]
> Not realy a bug, but some index are missing on foreign keys inside migrations:

Actually this DO seems to be a bug, there is no reason not to make the database check the relationship using the foreign keys.
