### ISSUE TITLE
Trying to get property 'name' of non-object after registration (on dashboard view)

### ISSUE THREAD

**Issue by vgavrilovikj** [laravel/jetstream#710]
I just installed jetstreams had no issues with the installation - that works fine - the login, registration.. what doesn't work is after I login to the platform, I am redirected to /dashboard, when I go to the dashboard - I get the following error: "Trying to get property 'name' of non-object " in the file "navigation-menu.blade.php"...

Here's my DB users table:
![image](https://user-images.githubusercontent.com/29601489/111541822-3d093580-8771-11eb-9b5c-96cd2fd82ba3.png)

And also teams table:
![image](https://user-images.githubusercontent.com/29601489/111541883-4befe800-8771-11eb-9796-25810f326306.png)

The problem is in the navigation-menu.blade.php file.. I tried to find what's causing the issue, and it looks like that the function `currentTeam()` in `HasTeams.php` returns null instead of the team..

When I run the following line of code in the navigation-menu.blade.php `@php
        dd(Auth::user()->currentTeam);
    @endphp`

In the dashboard view I get the following (null):
![image](https://user-images.githubusercontent.com/29601489/111542159-a5581700-8771-11eb-958b-c18965c006ed.png)

and when I run the following line of code `@php
        dd(Auth::user()->current_team_id);
    @endphp`

I get (2):
![image](https://user-images.githubusercontent.com/29601489/111542253-c456a900-8771-11eb-9c59-24cb85fc4375.png)

Which if you take a look and see in the table is the actual id of the team...

Any idea how to solve the issue?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by traubisoda** [comment]
I have a very similar issue after a fresh install with Intertia and teams.
It seems like the user's current team is not set on login (or at least not passed to Intertia), the weird thing is if I dd the team in the router, it fixes the issue for the current session.
```
Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    dd(request()->user()->currentTeam);
    return Inertia::render('Dashboard');
})->name('dashboard');
```
After logging out and in again, the issue appears again.
