### ISSUE TITLE
Trait "RedirectsActions" in Livewire/Inertia - Allow redirects for all Actions.

### ISSUE THREAD

**Issue by camya** [laravel/jetstream#717]
It's possible to set an own redirect path within the "CreateTeam" and "DeleteTeam" actions  by implementing a `redirectTo()` method which returns the redirect URL as string. Useful to redirect to the Team detail page after creating a new one.

// app/Actions/Jetstream/CreateTeam.php
```
class CreateTeam implements CreatesTeams
{
  public $team;
 
  public function create($user, array $input)
  {
    // ...
    $this->team = $team;
    return $team;
  }
 
  // Called magically from vendor/laravel/jetstream/src/Http/ - see RedirectsActions trait.
  public function redirectTo()
  {
    return '/teams/' . $this->team->id;
 }
}
```

This is possible, because some Jetstream Controller use the `trait RedirectsActions` and call the $this->redirectPath() method to get the user configured redirect url.

// Example: vendor/laravel/jetstream/src/Http/Livewire/CreateTeamForm.php
`return $this->redirectPath($creator);`

Unfortunately this is only implemented for store() and destroy() of Teams yet. For me the most important one is a chance to redirect the user to a special Team Dashboard URL after switching the teams.

Hopefully the RedirectsActions trait can be implemented in all methods, where a redirect is possible.

Please implement the trait "RedirectsActions" for:

- Switch Team (Most important)
- Update Team
- Add Team Member
- Cancel invitation
- Remove Team Member
- Team Member leaves Team
- Delete User
- Update Password
- Update profile
- ...

If there is a better way to implement redirects after these actions, I'm really interested.

**Comment by driesvints** [comment]
If you want to propose something feel free to send in a PR so we can look at actual code 👍

**Comment by camya** [comment]
@driesvints Sorry, but I have to ask. Was this a real request for a PR, or just a automatically applied "text block" answer? "Propose something" sounds a bit vague. ;)

If it's really a request to invest time in a PR, why do you closed the issue immediately without any specific feedback or chance for a short discussion?

So, my question. Should I or somebody else invest time in a PR, or will the PR also rejected and closed probably with a one-line because the feature is just not needed/required/wanted in Jetstream?
