### ISSUE TITLE
Problem with Livewire and registrering a user.

### ISSUE THREAD

**Issue by FoksVHox** [laravel/jetstream#73]
- Jetstream Version: 0.6.4
- Laravel Version: 8.x-dev
- PHP Version: 7.2.5
- Database Driver & Version: MariaDB, 5.7.24

### Description:
So I just installed Laravel 7 and then upgraded it toLaravel 8 following the [upgrading guide](https://laravel.com/docs/8.x/upgrade). But now when I try to create a user, I'm getting an error:
![image](https://user-images.githubusercontent.com/37844753/92325641-86ebc300-f04c-11ea-8615-4eee4a8e34e4.png)

### Steps To Reproduce:

1. Install Laravel 7
2. Upgrade Laravel following the [upgrading guide](https://laravel.com/docs/8.x/upgrade)
3. Remove the `UserFactory`
4. Move the User Model into `app/Models`
5. Rename the namespace to the new location.
6. Update the auth config to use the new namespace for the user model
7. Install JetStream via composer
8. Run `php artisan jetstream:install livewire --teams`
9. Run the migrations
10. Try and sign up for an account
11. See the error

**Comment by schmeits** [comment]
I fixed it by adding 

App\Providers\FortifyServiceProvider::class,
to your config/app.php

There is a PR fixing this issue

**Comment by FoksVHox** [comment]
> I fixed it by adding
> 
> App\Providers\FortifyServiceProvider::class,
> to your config/app.php
> 
> There is a PR fixing this issue

Which PR is it? 

And I've tried to add the `App\Providers\FortifyServiceProvider::class,`  in my `config/app.php`,
but it gave me this error:
![image](https://user-images.githubusercontent.com/37844753/92326684-3e380800-f054-11ea-8083-3abb3454949a.png)

**Comment by schmeits** [comment]
Checkout these:

https://github.com/laravel/jetstream/pull/55
https://github.com/laravel/jetstream/issues/65

**Comment by FoksVHox** [comment]
> Checkout these:
> 
> #55
> #65

Fixed it, thank you.
