### ISSUE TITLE
Recreating an account after account deletion doesn't work properly

### ISSUE THREAD

**Issue by Loots-it** [laravel/jetstream#730]
- Jetstream Version:2.2.4
- Jetstream Stack: Livewire
- Uses Teams: no
- Laravel Version: 8.34
- PHP Version: 8.0
- Database Driver & Version: MariaDB 10.3
- Forge provisioned server

### Description:
When testing my application I found a small bug, nothing serious, mostly annoying when testing/debugging. If you create an account and delete it, there is a small bug when you try to recreate the same account (although I think it will also happen if you try to create another account). When you register, you won't be logged in immediately, but you will be redirected to the login page. I am pretty sure this is because the login cookie of the old account isn't deleted yet. If I delete all the cookies from the site before I try to recreate the account, everything works fine.

### Steps To Reproduce:
1. register a new account
1.1. as expected, you are now logged in
2. go to profile and delete this new account
3. try to recreate the account you just deleted
3.1. this time, you are not logged in directly, but are redirected to the login page -> bug

**Comment by driesvints** [comment]
I can confirm this. I'll pick this up internally to see what the best solution would be.

**Comment by driesvints** [comment]
We'd appreciate a PR for this, otherwise we'll pick this up eventually.

**Comment by driesvints** [comment]
I'm going to mark this as an enhancement since nothing is really broken here.

**Comment by Loots-it** [comment]
If I find some time, I will look into it! It shouldn't be too difficult I think/hope.

**Comment by driesvints** [comment]
I think the latter and I think the 2.x branch is fine. The first one re-uses too much a bit there I believe.

**Comment by Loots-it** [comment]
Inertia has the same bug. And ok, I will use the second approach, I personally think the first one is better though. We just want to destroy the authenticated session. With the second approach, this code will be duplicated across 3 places (logout, inertia delete account, livewire delete account). I will implement the fix today or tomorrow.
