### ISSUE TITLE
Localize Inertia stack

### ISSUE THREAD

**Issue by amiranagram** [laravel/jetstream#731]
It would be a good thing if all the strings in Inertia are translatable.

Since all the strings are loaded from JSON files (as far as I know) we don't have to do anything fancy here, we can just import the correct JSON file in JS and replace the value.

I have already written [a post about this](https://www.amirrami.com/use-laravels-default-translation-strings-in-javascript) few months back. Here's a snippet so you don't have to read the whole post:

```javascript
import forEach from 'lodash/forEach';

const __ = (key, replace) => {
    let locale = document.documentElement.getAttribute('lang');
    let translation = key;

    import(`__/${locale}.json`).then(translations => {
        translation = translations[key]
            ? translations[key]
            : key
    }).catch(error => {
        console.error(`${locale}.json is missing from your lang folder!`)
    });

    forEach(replace, (value, key) => {
        translation = translation.replace(`:${key}`, value)
    });

    return translation;
}
```

I'm willing to code this (and go through all the strings and wrap them with the given function).

**Comment by driesvints** [comment]
We had this before but it over complicated the code base. We're not reconsidering this atm, sorry.

**Comment by robclancy** [comment]
lmao wtf
