### ISSUE TITLE
User Model replacement

### ISSUE THREAD

**Issue by kieferjs** [laravel/jetstream#738]
Our project uses a different model than 'Users' for the web authorization.  Everything works for Jetstream except the Teams because it is looking for the user columns on our protected pivot table called 'team_agent' which is in our project's Membership model file.  The jetstream.php file was altered in my local environment to use the Agent model but the AWS remote server files are using the User model.  Is there a way to close the loop here in this one area so it can use a different user model for Teams?  Our User model is used on the API side for mobile app customers that will not be authenticated users into our web app.

/**
     * The user model that should be used by Jetstream.
     *
     * @var string
     */
    public static $userModel = 'App\\Models\\Agent';

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
