### ISSUE TITLE
QR image wrong

### ISSUE THREAD

**Issue by yashiroiori** [laravel/jetstream#743]
- Jetstream Version: ^2.3
- Jetstream Stack: Inertia
- Uses Teams: no
- Laravel Version: ^8.12
- PHP Version: 7.4.16
- Database Driver & Version: mariadb 10.5.9

### Description:
Into profile page when enable Two Factor Authentication the QR code it's bad render and the same case it's only use Fortify

![image](https://user-images.githubusercontent.com/17031855/113345112-39d48480-92ef-11eb-9bdd-aee89e906e60.png)

**Comment by driesvints** [comment]
Works fine for me:

![Screenshot 2021-04-02 at 11 56 38](https://user-images.githubusercontent.com/594614/113405679-7f09bc80-93aa-11eb-8c4b-890cabf53cb8.jpg)

**Comment by yashiroiori** [comment]
Finally found the problem

The line 31 with: setlocale(LC_ALL,"es_ES@euro","es_ES","esp"); return QR code wrong, when comment that line work fine

![image](https://user-images.githubusercontent.com/17031855/113553202-03cc2480-95bd-11eb-8329-03060ebf85dd.png)

**Comment by yashiroiori** [comment]
> Works fine for me:
> 
> ![Screenshot 2021-04-02 at 11 56 38](https://user-images.githubusercontent.com/594614/113405679-7f09bc80-93aa-11eb-8c4b-890cabf53cb8.jpg)

Finally found the problem

The line 31 with: setlocale(LC_ALL,"es_ES@euro","es_ES","esp"); return QR code wrong, when comment that line work fine

But why setlocale make that problem with QR code??
![image](https://user-images.githubusercontent.com/17031855/113553356-45f56600-95bd-11eb-94b9-20938636a5e8.png)
