### ISSUE TITLE
TeamFactory fails on unique name with faker_locale => en_GB (possibly others)

### ISSUE THREAD

**Issue by jayenne** [laravel/jetstream#745]
- Jetstream Version: latest
- Jetstream Stack: Livewire
- Uses Teams: yes
- Laravel Version: latest
- PHP Version: 8.0
- Database Driver: MySQL & Version: 8

### Description:
Jetstream seeding fail generating company name whilst `config app faker_locale => 'en_GB'` but works fine with `en_US` 
unfortunately is also fails to generate `county` as `en_US` but works fine as `en_GB`.
As i need en_GB for county and en_US for company name i'm in a pickle.

Can I dynamically set the `faker_locale` for each factory? - i'd be happy with that. or maybe pass the `faker_locale` as a value with ->hasSomething('en_US')->hasSomethingElse('en_GB') ?

### Steps To Reproduce:
set the config app `facker_locale` to `en_GB` 
create a user seeder:
```
User::factory()
            ->count(200)
            ->withPersonalTeam()
            ->create();
```
wait for fail: `Maximum retries of 10000 reached without finding a unique value`

thank you.

**Comment by driesvints** [comment]
This seems like an issue with Faker. Please open an issue on their repo.
