### ISSUE TITLE
Default phpunit tests do not pass Fortify registration feature is disabled

### ISSUE THREAD

**Issue by isometriq** [laravel/jetstream#747]
- Jetstream Version: 2.2
- Jetstream Stack: Livewire
- Uses Teams: no
- Laravel Version: 8.12
- PHP Version: 7.4

### Description:
The test should check if feature is not enabled instead of failing, like so:
```
if (! Features::enabled(Features::registration())) {
    return $this->markTestSkipped('Registration not enabled.');
}
```
This is what other features do, like email verification.

### Steps To Reproduce:
- Disable (comment) the registration feature in `/config/fortify.php`
- Run phpunit tests (ie: `sail test` or `php artisan test`)

**Comment by driesvints** [comment]
Remove tests that you don't need.
