### ISSUE TITLE
Delete Account Test is Failing in Livewire Stubs

### ISSUE THREAD

**Issue by inmanturbo** [laravel/jetstream#748]
https://github.com/laravel/jetstream/blob/39d50ec0dda28ae2077baf9df307509a09307d75/stubs/tests/livewire/DeleteAccountTest.php#L24
https://github.com/laravel/jetstream/blob/39d50ec0dda28ae2077baf9df307509a09307d75/src/Http/Livewire/DeleteUserForm.php#L67
https://github.com/laravel/jetstream/pull/742

<pre><font color="#4E9A06">PHPUnit Pretty Result Printer 0.30.1 by Codedungeon and contributors.</font>
<font color="#C4A000">==&gt; Configuration: ~/Projects/dev-menus/phpunit-printer.yml</font>

PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

<font color="#34E2E2"><b> ==&gt; ExampleTest                </b></font><font color="#4E9A06">✔  </font>
<font color="#34E2E2"><b> ==&gt; ApiTokenPermissionsTest    </b></font><font color="#4E9A06">✔  </font>
<font color="#34E2E2"><b> ==&gt; AuthenticationTest         </b></font><font color="#4E9A06">✔  ✔  ✔  </font>
<font color="#34E2E2"><b> ==&gt; BrowserSessionsTest        </b></font><font color="#4E9A06">✔  </font>
<font color="#34E2E2"><b> ==&gt; CreateApiTokenTest         </b></font><font color="#4E9A06">✔  </font>
<font color="#34E2E2"><b> ==&gt; DeleteAccountTest          </b></font><font color="#EF2929"><b>⚈  </b></font><font color="#4E9A06">✔  </font>
<font color="#34E2E2"><b> ==&gt; DeleteApiTokenTest         </b></font><font color="#4E9A06">✔  </font>
<font color="#34E2E2"><b> ==&gt; EmailVerificationTest      </b></font><font color="#FCE94F"><b>⇢  ⇢  ⇢  </b></font>
<font color="#34E2E2"><b> ==&gt; ExampleTest                </b></font><font color="#4E9A06">✔  </font>
<font color="#34E2E2"><b> ==&gt; PasswordConfirmationTest   </b></font><font color="#4E9A06">✔  ✔  ✔  </font>
<font color="#34E2E2"><b> ==&gt; PasswordResetTest          </b></font><font color="#4E9A06">✔  ✔  ✔  ✔  </font>
<font color="#34E2E2"><b> ==&gt; ProfileInformationTest     </b></font><font color="#4E9A06">✔  ✔  </font>
<font color="#34E2E2"><b> ==&gt; RegistrationTest           </b></font><font color="#4E9A06">✔  ✔  </font>
<font color="#34E2E2"><b> ==&gt; ...nticationSettingsTest   </b></font><font color="#4E9A06">✔  ✔  ✔  </font>
<font color="#34E2E2"><b> ==&gt; UpdatePasswordTest         </b></font><font color="#4E9A06">✔  ✔  ✔  </font>

Time: 00:01.551, Memory: 50.50 MB

<font color="#EF2929"><b>✖ There was 1 error:</b></font>

1) Tests\Feature\DeleteAccountTest::test_user_accounts_can_be_deleted
  RuntimeException: Session store not set on request.

/.../jetstream-dem/vendor/laravel/framework/src/Illuminate/Http/Request.php:483
/.../jetstream-demo/vendor/laravel/jetstream/src/Http/Livewire/DeleteUserForm.php:67
/.../jetstream-demo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
/.../jetstream-demo/vendor/laravel/framework/src/Illuminate/Container/Util.php:40
/.../jetstream-demo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
/.../jetsream-demo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37
/.../jetsream-demo/vendor/livewire/livewire/src/ComponentConcerns/HandlesActions.php:149
/.../jetstream-demo/vendor/livewire/livewire/src/HydrationMiddleware/PerformActionCalls.php:35
/.../jetstream-demo/vendor/livewire/livewire/src/LifecycleManager.php:82
/.../jetstream-demo/vendor/livewire/livewire/src/Connection/ConnectionHandler.php:12
/.../jetstream-demo/vendor/livewire/livewire/src/Controllers/HttpConnectionHandler.php:20
/.../jetstream-demo/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:48
/.../jetstream-demo/vendor/laravel/framework/src/Illuminate/Routing/Route.php:254
/.../jetstream-demo/vendor/laravel/framework/src/Illuminate/Routing/Route.php:197
/.../jetstream-demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php:695
/.../jetstream-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128
/.../jetstream-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103
/.../jetstream-demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php:697
/.../jetstream-demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php:672
/.../jetstream-demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php:636
/.../jetstream-demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php:625
/.../jetstream-demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:166
/.../jetstream-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128
/.../jetstream-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103
/.../jetstream-demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:141
/.../jetstream-demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:110
/.../jetstream-demo/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:508
/.../jetstream-demo/vendor/livewire/livewire/src/Testing/TestableLivewire.php:190
/.../jetstream-demo/vendor/livewire/livewire/src/Testing/MakesHttpRequestsWrapper.php:29
/...jetstream-demo/vendor/livewire/livewire/src/Testing/TestableLivewire.php:191
/...jetstream-demo/vendor/livewire/livewire/src/Testing/TestableLivewire.php:175
/.../jetstream-demo/vendor/livewire/livewire/src/Testing/Concerns/MakesCallsToComponent.php:134
/.../jetstream-demo/vendor/livewire/livewire/src/Testing/Concerns/MakesCallsToComponent.php:36
/...jetstream-demo/vendor/livewire/livewire/src/Testing/Concerns/MakesCallsToComponent.php:30
/.../jetstream-demo/tests/Feature/DeleteAccountTest.php:26

<span style="background-color:#CC0000"><font color="#D3D7CF">ERRORS!</font></span>
<span style="background-color:#CC0000"><font color="#D3D7CF">Errors: 1, Skipped: 3.</font></span>
</pre>

**Comment by driesvints** [comment]
Resubmit this with a filled out issue template.

**Comment by inmanturbo** [comment]
> Resubmit this with a filled out issue template.

Sorry about that, I created from selecting "mention in issue" from a line number in source code, and it skipped the issue templates. Thanks for the help.
