### ISSUE TITLE
DeleteAccountTest error after composer update

### ISSUE THREAD

**Issue by kcop4uk** [laravel/jetstream#753]
- Jetstream Version: 2.3.1
- Jetstream Stack:  Livewire
- Uses Teams: no
- Laravel Version: 8.36.2
- PHP Version: 8.0.3
- Database Driver & Version:  sqlite/memory

### Description:
DeleteAccountTest::test_user_accounts_can_be_deleted  gives an error after the "composer update"

### Steps To Reproduce:
=== Right before the update:
$ phpunit
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.
.......................S....S..SSSS........................       59 / 59 (100%)

=== Update:
$ composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 11 updates, 0 removals
  - Upgrading barryvdh/laravel-debugbar (v3.5.2 => v3.5.5)
  - Upgrading facade/flare-client-php (1.4.0 => 1.6.1)
  - Upgrading facade/ignition (2.6.0 => 2.8.2)
  - Upgrading fakerphp/faker (v1.14.0 => v1.14.1)
  - Upgrading filp/whoops (2.11.0 => 2.12.0)
  - Upgrading laravel/fortify (v1.7.8 => v1.7.9)
  - Upgrading laravel/framework (v8.34.0 => v8.36.2)
  - Upgrading laravel/jetstream (v2.2.5 => v2.3.1)
  - Upgrading laravel/sail (v1.4.9 => v1.4.11)
  - Upgrading laravel/sanctum (v2.9.2 => v2.9.4)
  - Upgrading livewire/livewire (v2.4.1 => v2.4.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 11 updates, 0 removals
  - Downloading laravel/framework (v8.36.2)
  - Downloading barryvdh/laravel-debugbar (v3.5.5)
  - Downloading filp/whoops (2.12.0)
  - Downloading facade/flare-client-php (1.6.1)
  - Downloading facade/ignition (2.8.2)
  - Downloading fakerphp/faker (v1.14.1)
  - Downloading laravel/fortify (v1.7.9)
  - Downloading laravel/jetstream (v2.3.1)
  - Downloading laravel/sail (v1.4.11)
  - Downloading laravel/sanctum (v2.9.4)
  - Downloading livewire/livewire (v2.4.2)
  - Upgrading laravel/framework (v8.34.0 => v8.36.2): Extracting archive
  - Upgrading barryvdh/laravel-debugbar (v3.5.2 => v3.5.5): Extracting archive
  - Upgrading filp/whoops (2.11.0 => 2.12.0): Extracting archive
  - Upgrading facade/flare-client-php (1.4.0 => 1.6.1): Extracting archive
  - Upgrading facade/ignition (2.6.0 => 2.8.2): Extracting archive
  - Upgrading fakerphp/faker (v1.14.0 => v1.14.1): Extracting archive
  - Upgrading laravel/fortify (v1.7.8 => v1.7.9): Extracting archive
  - Upgrading laravel/jetstream (v2.2.5 => v2.3.1): Extracting archive
  - Upgrading laravel/sail (v1.4.9 => v1.4.11): Extracting archive
  - Upgrading laravel/sanctum (v2.9.2 => v2.9.4): Extracting archive
  - Upgrading livewire/livewire (v2.4.1 => v2.4.2): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: jenssegers/agent
Discovered Package: laravel/fortify
Discovered Package: laravel/jetstream
Discovered Package: laravel/sail
Discovered Package: laravel/sanctum
Discovered Package: laravel/tinker
Discovered Package: livewire/livewire
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.

=== Right after the update:
$ phpunit
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.
.......................S....SE.SSSS........................       59 / 59 (100%)

Time: 00:10.091, Memory: 50.50 MB

There was 1 error:

1) Tests\Feature\LaravelProvided\DeleteAccountTest::test_user_accounts_can_be_deleted
RuntimeException: Session store not set on request.

**Comment by inmanturbo** [comment]
@kcop4uk This was fixed in #750. You can get the patch by upgrading Jetstream to 2.x-dev.
