### ISSUE TITLE
special character encoding in reset password url

### ISSUE THREAD

**Issue by thomasrd1** [laravel/jetstream#756]
- Jetstream Version: 2.3.1
- Jetstream Stack: Livewire
- Uses Teams: No
- Laravel Version: 8.36.2
- PHP Version: 8.0
- Database Driver & Version: MySQL

### Description:

A user is unable to reset their password if it contains a special character "+". When the user goes to reset their email address using the reset password form, the email address is not correctly displayed in the form fields. The + is removed and replaced by a space. 

eg Reset link is...

https://sitename/reset-password/10d8fe6eeb6ea142ddf27b50c4230013039be5e1c872c6e026f6afd44006fefb?email=thomas+test2@thomas.com

![image](https://user-images.githubusercontent.com/48821914/114542185-fab51480-9c9a-11eb-9218-66a92f67f12b.png)

### Steps To Reproduce:

Create a user with a + in their email address
Request reset password
Click on link in the email
See if the special character is displayed in the form field.

**Comment by ZeProf2Code** [comment]
It works correctly for me, the + is correctly encoded.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
