### ISSUE TITLE
Jetstream::inertia()->whenRendering('Auth/Register', function(){...}) has no effect

### ISSUE THREAD

**Issue by plakhin** [laravel/jetstream#759]
- Jetstream Version: 2.3.1
- Jetstream Stack: Inertia
- Uses Teams: no
- Laravel Version: 8.36.2
- PHP Version: 8.0.3

### Description:
adding `Jetstream::inertia()->whenRendering('Auth/Register', function(){...})` to `boot()` method of `JetstreamServiceProvider` gives no effect at all. The same with `Auth/Login` page. Though this works for `Profile/Show` as suggested in docs.

### Steps To Reproduce:
add
```php
Jetstream::inertia()->whenRendering(
    'Auth/Register',
    function (Request $request, array $data) {
        dd('callback');
    }
);
```
to `boot()` method of `JetstreamServiceProvider`. then open `/register` page. Default registration page will be displayed instead of `dd()` output.

**Comment by driesvints** [comment]
![Screenshot 2021-04-19 at 12 35 47](https://user-images.githubusercontent.com/594614/115223155-c8c50780-a10b-11eb-815b-69e3c12f4728.jpg)

https://jetstream.laravel.com/2.x/features/authentication.html#customizing-inertia-authentication-views
