### ISSUE TITLE
Adding more info about normal ajax calls in the documentation

### ISSUE THREAD

**Issue by Benoit1980** [laravel/jetstream#760]
Hello,

Would it be possible to add in your documentation more information about a simple ajax call in Jetstream away from Intertia.

ie, when you try something basis like:
```
axios.get('/testing')
     .then(response => {
     this.TestingConnection = response.data;
     console.log(response);
     });
```

Controller
```
  return response()->json($data);
```

You receive something else in the front end:
```
{"cookies":{},"transferStats":{}}
```

What causes this in Jetstream please as my controller outputs something completely different(using the logger()).
It looks like something interfere with the basic laravel json output when not using inertia in your installation.

Thank you.

**Comment by driesvints** [comment]
We're welcoming PR's.

**Comment by Benoit1980** [comment]
Thank you for the reply.
Not sure I understand your request, do you mean that it is actually not possible to send an axio request through Jetstream and need someone to add the feature?
How did all the other developers use Jetstream in the past without axios? As some may use Intertia but in many cases, Axios basic request is needed(ie: third party APIs communication).

**Comment by rohanmax360** [comment]
even though i am getting the same response after using third-party API, is there any solution for this?

**Comment by Benoit1980** [comment]
> even though i am getting the same response after using third-party API, is there any solution for this?

I hope it it helps you but the only way I could find was to create an event like this:

#Create a livewire component
#Component
```
<button wire:click="$emit('generateRandomId')" class="button button-success">
<i class="mr-1 icon ion-md-at"></i>
@lang('crud.common.generate_id')
</button>
```


#Place your component in your blade file
```
`@livewire('generate-id')` //Needs to match the class name
```


#Create an event class
```
GenerateId.php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Livewire\Component;

class GenerateId extends Component
{

    public $randomId;

    protected $listeners = ['generateRandomId' => 'randomId'];

    public function render()
    {
        return view('livewire.generate-email');
    }


    public function randomId()
    {
        $this->dispatchBrowserEvent('random-id', ['id' => User::latest()->first()->id;]);
    }
}
```


Listen to it on your blade file
```
@push('scripts')
<script>
    window.addEventListener('random-id', event => {
        document.getElementById('id').value = event.detail.id;
    })
</script>
@endpush
```


I will be honest with you, the more I use Livewire, the more I hate it, so many steps to produce a basic axios "kind of" call. I prefer vue with basic axios calls.
