### ISSUE TITLE
Install with vue js 2

### ISSUE THREAD

**Issue by azam1** [laravel/jetstream#761]
Is it possible to install jetstream with VueJS2? I tried to install them separately but as soon as I add jetstream Vue version gets updated to 3.

**Comment by azam1** [comment]
edit composer.json "laravel/jetstream": "^2.1", then run composer install; php artisan jetstream:install inertia on terminal. And finally run npm install; npm run dev; php artisan migrate on terminal.

**Comment by blite** [comment]
the fact that vue 3 is forced this early, makes me think this project doesn't know what it is doing.

**Comment by dillingham** [comment]
@blite the fact that you don't realize this is optional makes me think you don't know what you're doing.

**Comment by blite** [comment]
@dillingham https://inertiajs.com/client-side-setup which one does it default to? Vue 3 or Vue 2?  I have it working with vue2 just fine, but it still force installs inertia-vue3 which I have to remove and install inertia-vue.  Also on https://jetstream.laravel.com/2.x/introduction.html it doesn't even mention which version of vue it uses on https://jetstream.laravel.com/2.x/introduction.html or on https://jetstream.laravel.com/2.x/stacks/inertia.html

This probably won't even matter in a year, but right now it does.

Large UI frameworks that don't have full Vue 3 Support yet:

* https://github.com/bootstrap-vue/bootstrap-vue/issues/5196
* https://github.com/vuetifyjs/vuetify/issues/11162
* https://next.quasar.dev/start/upgrade-guide (in beta)
* https://github.com/coreui/coreui-vue/issues/126

not exhaustive but I think it really shows where vue 3 support is right now.

sorry for the flippant comment

**Comment by dillingham** [comment]
@blite no worries :) that was constructive.. thanks.

**Comment by adeyinkakoya** [comment]
Hi Guys. I have issues setting up Jetstream Inertia with Vue 2. I tried the steps mentioned:
Setup laravel 8
composer required Jetstream
Edited ecomposer.json "laravel/jetstream": "^2.1", 
Ran composer install and then php artisan jetstream:install inertia

No changes were made.

Kindly help me through the setup. Thank you

**Comment by gijsbeijer** [comment]
Hi all,

Following the steps mentioned above, it still installs everything with inertia-vue3 and vue3 formatted views.

Any guide on how to get Jetstream to work with vue2 (and Vuetify)?

**Comment by fahmiegerton** [comment]
I need help too! It still forces to install vue 3. I tried with fixed version "2.1.4" but got error with Laravel dependencies unmatched. I need vue2 so bad right now and I don't know how :'(

**Comment by gijsbeijer** [comment]
i was able to install it with vue 2 only on creating a new project. Tried downgrading several packages before I gave up and tried a fresh install.

**Comment by tgbamaq** [comment]
> i was able to install it with vue 2 only on creating a new project. Tried downgrading several packages before I gave up and tried a fresh install.

you need to add "-w" flag to update dependencies.
Try this: "composer require laravel/jetstream:2.1.4 -w".
its running for me.
