### ISSUE TITLE
Add a way to only install the backend gears of the jetstream engine without the frontend gears.

### ISSUE THREAD

**Issue by fcolecumberri** [laravel/jetstream#763]
Jetstream has a lot of backend development (specially the `teams` development) that could be used on several projects that don't need all the frontend development (like RESTfull APIs) I have just listed several classes/traits that could be implemented on a frontend agnostic auth backend:

```
- class Laravel\Jetstream\TeamInvitation
- abstract class Laravel\Jetstream\Team
- class Laravel\Jetstream\Role
- trait Laravel\Jetstream\RedirectsActions
- class Laravel\Jetstream\OwnerRole
- abstract class Laravel\Jetstream\Membership
- trait Laravel\Jetstream\HasTeams
- trait Laravel\Jetstream\HasProfilePhoto
- class Laravel\Jetstream\Actions\UpdateTeamMemberRole
- class Laravel\Jetstream\Actions\ValidateTeamDeletion
- model App\Models\*
- class App\Policies\TeamPolicy
- maybe some (maybe all) of App\Providers\*
- the non inetia/livewire of Tests\Feature\*
- class Laravel\Jetstream\Mail\TeamInvitation
- class Laravel\Jetstream\Rules\Role
- (maybe more)
```

I am not sure which could be the best way to do this, maybe a flag on the installation step to only install the backend, maybe split the package in 2 (like fortify which is the common engine for jetstream and breeze) or maybe add the `team` feature to fortify.

Thanks.

**Comment by driesvints** [comment]
Hey @fcolecumberri, we don't have plans for this sorry. Feel free to work on a package for these yourself if you like 👍
