### ISSUE TITLE
after login user not redirect to dashboard

### ISSUE THREAD

**Issue by mirdoraghi** [laravel/jetstream#768]
- Jetstream Version: 2.3
- Jetstream Stack: Inertia 
- Uses Teams: no
- Laravel Version: 8.37.0
- PHP Version: 7.4.11
- Database Driver & Version: PostgreSQL 13
- Dashboard templete: https://keenthemes.com/metronic/
- Dashboard route: /admin/dashboard

### Description:

After login dashboard opens in a modal instead of redirecting to a full-page dashboard view.

![image](https://user-images.githubusercontent.com/44964722/115684242-7171a200-a36c-11eb-987d-2df82f043e7f.png)

### Steps To Reproduce:
Login with any user
A modal(iframe) should appear with dashboard view

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by mirdoraghi** [comment]
this not is a question. this is a bug!
