### ISSUE TITLE
[2.x] Sanctum stateful requests middleware is not installed by default

### ISSUE THREAD

**Issue by rennokki** [laravel/jetstream#773]
Duplicate issue: https://github.com/laravel/jetstream/issues/386

It seems like out of the box, Jetstream is not adding the Sanctum's `\Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class` middleware in `api` group in `Http/Kernel.php` like so:

```php
    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        ...

        'api' => [
            \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
            'throttle:api',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
    ];
```

I think it should be added, even commented if it shouldn't be enabled by default, or at least to be documented somewhere because I've been debugging a few tens of minutes to find out why I cannot statefully send requests to API from the Inertia-served pages, only finding out the middleware was not added.

**Comment by driesvints** [comment]
Please upgrade to the latest issue to see if the issue persists (the issue linked is Jetstream v1. And please fill out the issue template next time.

**Comment by pmochine** [comment]
@driesvints yes it's still a problem !

**Comment by s17-git** [comment]
I did it but i can stil not consume my api protected by auth:sanctum from inertia/laravel.
