### ISSUE TITLE
Config view name

### ISSUE THREAD

**Issue by crrack** [laravel/jetstream#779]
Hi i get an idea to add view name in Controllers with config option like this:

![Snímek obrazovky 2021-05-06 v 9 15 24](https://user-images.githubusercontent.com/23639276/117257197-eaccc280-ae4b-11eb-8137-616176b74f72.png)

 and config:

![Snímek obrazovky 2021-05-06 v 9 15 35](https://user-images.githubusercontent.com/23639276/117257287-02a44680-ae4c-11eb-8eaf-1086cffbb5a7.png)

What do you think about this idea? Using folders structure in Jetstream is not ideal for me so i think people can be happy with this config option and people who dont care can use default option.

**Comment by driesvints** [comment]
The views are already published to your app so you can do whatever you want with them.
