### ISSUE TITLE
Inertia - Validate "canCreateTeams" in the responsive-nav-link

### ISSUE THREAD

**Issue by iBet7o** [laravel/jetstream#784]
In the responsive-nav-link to create a team, "canCreateTeams" is not validated. So if teams are enabled, the link to create a team will always be visible for responsive design.

https://github.com/laravel/jetstream/blob/9663d7eb4e58ec86f105efb07f712fb81e6c92f2/stubs/inertia/resources/js/Layouts/AppLayout.vue#L190

**Comment by driesvints** [comment]
Feel free to send in a PR, thanks 👍
