### ISSUE TITLE
Reconsider the text type for the profile colmn with a more limited type

### ISSUE THREAD

**Issue by rabin-io** [laravel/jetstream#789]
https://github.com/laravel/jetstream/blob/7ed0cadd8d0c1cfe03dffa8553c8807f4c4fa92f/database/migrations/2014_10_12_000000_create_users_table.php#L24

After reading about this a bit, I see that this column type is overkill for this use case, on MySQL, MSSQL and PostgresSQL this type can hold up to 2GB/4GB of data

DB | Column Type | Length
--- | --------------- | -------
PostgreSQL | TEXT, VARCHAR | variable unlimited length. https://www.postgresql.org/docs/current/datatype-character.html
MSSQL | text  | Variable-length non-Unicode data in the code page of the server and with a maximum string length of 2^31-1 (2,147,483,647). When the server code page uses double-byte characters, the storage is still 2,147,483,647 bytes. Depending on the character string, the storage size may be less than 2,147,483,647 bytes. https://docs.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql?view=sql-server-ver15
MySQL | TEXT | 64K https://www.mysqltutorial.org/mysql-text/

**Comment by driesvints** [comment]
Feel free to attempt a PR 👍
