### ISSUE TITLE
Two factor authentication can not be enabled

### ISSUE THREAD

**Issue by JustRostin** [laravel/jetstream#790]
- Jetstream Version: 2.3.6
- Jetstream Stack: Livewire
- Uses Teams:  no
- Laravel Version: 8.42.1
- PHP Version: 7.3
- Database Driver & Version:

### Description:
When you want to activate the two factor authentication it does not giva the QR code. in the console you get the following message:
```
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at index.js:58 
```

### Steps To Reproduce:
Activate two factor authentication in profile

**Comment by driesvints** [comment]
Hey @JustRostin. Seems to be working fine for me:

![Screenshot 2021-05-25 at 12 55 18](https://user-images.githubusercontent.com/594614/119486375-786b4600-bd58-11eb-80bb-5376cc61a667.jpg)

Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
