### ISSUE TITLE
Idea: InteractsWithTeams trait for team's resources

### ISSUE THREAD

**Issue by pakogn** [laravel/jetstream#791]
It's a really simple idea, but would be great to have a Trait that you can use in your models that are related to the Team. This may solve common use cases when dealing with Team's resources, like scopes, relationships, etc. In this way can serve as a boost when working in a project when the team has related resources.

Example.

Contact::currentTeam()->get();

**Comment by driesvints** [comment]
You can already do `$user->currentTeam`

https://jetstream.laravel.com/2.x/features/teams.html#inspecting-user-teams
