### ISSUE TITLE
How to use customize the prop names of jetstream shared intertia data?

### ISSUE THREAD

**Issue by msonowal** [laravel/jetstream#805]
First of all, thanks @taylorotwell  for the awesome starter kit which is pretty extensive.

Just need some small light on it
How to use customize the prop names of jetstream shared inertia data?

Basically if we want to add additional properties and remove some of the properties completly in the shared data or rename the jetstream all together from customization point of view, I don't seem to find any best way, Would anyone provide a light on it. It would be great.

I thought of overriding the middleware but the application always register its own middleware in the provider if we can have some kind of opportunity to handle that part would be great.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by pmochine** [comment]
@msonowal any news?
