### ISSUE TITLE
Back Button On browser

### ISSUE THREAD

**Issue by loreberti89** [laravel/jetstream#806]
- Jetstream Version: ^2.3
- Jetstream Stack: Inertia
- Uses Teams: no
- Laravel Version: 8.35.1
- PHP Version: 8.0.5

With stack inertia, If I make a Logout or compile form and then return back with browser button, I see always old data.
When is a form could not be a problem because with remember :false of inertia i can "clean" the form, but when I make a logout, and I click on back button I can see all old data in previous screen that was only for the user logged.

**Comment by driesvints** [comment]
Can you provide a video of the behavior?

**Comment by driesvints** [comment]
Also which browser are you experiencing this?

**Comment by driesvints** [comment]
We can't provide support for that here I'm afraid. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
