### ISSUE TITLE
Fix x-transition opacity duration in action-messages with alpine js

### ISSUE THREAD

**Issue by kastriotkastrati** [laravel/jetstream#807]
The new Alpine js update has changed the way x-transition and opacity work, which is something used on action-messages. Upon updating livewire and alpine js I encountered multiple errors. 
I solved this by modifying the x-transition opacity like this:

```

x-transition.opacity
x-transition:leave.duration.1500ms

```

**Comment by driesvints** [comment]
Re open this with a filled out issue template
