### ISSUE TITLE
Vue transitions on persisted inertia layout slots not working with "out-in" mode

### ISSUE THREAD

**Issue by Bronco84** [laravel/jetstream#811]
- Jetstream Version: 2.3
- Jetstream Stack: Inertia
- Uses Teams: no
- Laravel Version: 8.40
- PHP Version: 8.0
- Vue 3.0.5
- IntertiaJs 0.9.2

**Description:** 
I am having a difficult time pinpointing the reason, and I'm not sure if this is an inertia issue, or jetstream, but when I define a persistent layout in my app.js file with a slot for pages wrapped in a vue transition with "out-in" mode, it is only loading the component on the initial page load.

**Things I've noticed:** 
- The transition between pages works fine when I am not logged in for whatever reason, even when I use custom, non-jetstream components. 
- The transition works without "out-in" mode enabled. 
- The inertia request is correctly fetching the page and related user data as expected when navigation occurs, and fires the related events. 
- The vue transition events are no longer fired after the initial page load. It's as though inertia can't find the slot once an initial transition (on page load) has occurred.
- I can get the transition to work by changing a variable with a setTimeout function triggered by an inertia navigation event using v-if to show and hide the slot. 

**Steps To Reproduce:**
- Use default jetstream/inertia/vue setup with fortify authentication scaffolding. 
- Setup a persistent layout in app.js inertia initialization with a vue transition element wrapping a slot component. 
- Log into the app and try navigating to various pages. 
- After initial load, the navigated page component is not being pulled into the layout.

Thank you!

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Bronco84** [comment]
Understood, thank you for the info!
