### ISSUE TITLE
Could not parse DateTime::__construct(): Failed to parse time string

### ISSUE THREAD

**Issue by diegorodrigo90** [laravel/jetstream#815]
- Jetstream Version: 2.3
- Jetstream Stack: Inertia 
- Uses Teams:  no
- Laravel Version: 8.40
- PHP Version: 8.0.7
- Database Driver & Version: PostgreSQL 13

### Description:

When i install Jetstream with Inertia stack at laravel 8 and try to access the API Tokens page, get the error:

```
Carbon\Exceptions\InvalidFormatException
Could not parse 'Thu 24 Jun 16:46:15 2021': DateTime::__construct(): Failed to parse time string (Thu 24 Jun 16:46:15 2021) at position 13 (:): Unexpected character

```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by diegorodrigo90** [comment]
Happens with a fresh laravel installation, when i install JetStream Inertia stack and create an API Token this error appears on got to the '/user/api-tokens' route
