### ISSUE TITLE
Potential race condition in fresh install of jetstream with livewire

### ISSUE THREAD

**Issue by kevinohashi** [laravel/jetstream#816]
- Jetstream Version: 2.3.11
- Jetstream Stack: Livewire
- Uses Teams: no
- Laravel Version: 8.48.1
- PHP Version: 7.4.3
- Database Driver & Version: mysql 

### Description:

I receive the following error on a fresh install of Jetstream.
app.js:2792 Uncaught ReferenceError: data is not defined
    at app.js:2792
    at Function.<anonymous> (app.js:1881)
    at flushHandlers (app.js:1651)
    at stopDeferring (app.js:1655)
    at deferHandlingDirectives (app.js:1658)
    at initTree (app.js:1842)
    at app.js:1813
    at Array.forEach (<anonymous>)
    at Object.start (app.js:1812)
    at Module../resources/js/app.js (app.js:4903)

If I set a breakpoint on line 2792 and execute the actual line from the console

`data = evaluate(el, expression, {scope: dataProviderContext});`

and resume execution, the error never shows up and everything loads fine. Data gets defined and it steps through without issue.

I am thinking it's executing before everything is fully loaded causing this error but unsure how to fix this.

The block of code surrounding the problematic line is posted here
// packages/alpinejs/src/directives/x-data.js

addRootSelector(() => `[${prefix("data")}]`);

directive("data", skipDuringClone((el, {expression}, {cleanup}) => {

  expression = expression === "" ? "{}" : expression;

  let magicContext = {};

  injectMagics(magicContext, el);

  let dataProviderContext = {};

  injectDataProviders(dataProviderContext, magicContext);

  data = evaluate(el, expression, {scope: dataProviderContext});

  injectMagics(data, el);

  let reactiveData = reactive(data);

  initInterceptors(reactiveData);

  let undo = addScopeToNode(el, reactiveData);

  if (reactiveData["init"])

    reactiveData["init"]();

  cleanup(() => {

    undo();

    reactiveData["destroy"] && reactiveData["destroy"]();

  });

}));

### Steps To Reproduce:
laravel new jetstream --jet --git
cd jetstream
npm install & npm run dev
php artisan serve
load the site, register and on the /dashboard is where I get this error.

**Comment by sintierra** [comment]
It's an alpinejs error. Update alpine with npm update, the release from 2 days ago fix the issue in my enviroment, which is almost the same as yours.
https://github.com/alpinejs/alpine/releases/tag/v3.2.1

**Comment by driesvints** [comment]
See the above.

**Comment by kevinohashi** [comment]
updating alpine to 3.2.1 fixed the issue, thank you.
