### ISSUE TITLE
Blank dashboard screen on fresh installation

### ISSUE THREAD

**Issue by Stetzon** [laravel/jetstream#818]
- Jetstream Version: 2.3.11
- Jetstream Stack: Inertia
- Uses Teams: yes 
- Laravel Version: 8.49.0
- PHP Version: 8.0.7
- Database Driver & Version: mysql v8.0.24

### Description:
After a fresh installation of laravel and jetstream, running the app and logging in will redirect to a blank dashboard screen. Checking the browser console there is a javascript error and multiple warnings.

### Steps To Reproduce:
1. create new laravel project
2. follow jetstream installation instructions for inertia + teams.  Npm i, run dev + migrate
3. create sample user, run the app, login
4. Will now see blank dashboard page

or use below repo:
1. Clone
2. update env
3. composer install / npm i
4. migrate, seed user
5. run app + login

https://github.com/Stetzon/jetstream-inertia

**Comment by driesvints** [comment]
Works fine for me:

![Screen Shot 2021-07-01 at 09 37 03](https://user-images.githubusercontent.com/594614/124085034-e689e380-da4f-11eb-9647-5191793e4079.jpg)

**Comment by Stetzon** [comment]
Hi @driesvints , thanks for taking the time to look into this.  Looking at the console in chrome I am seeing this error

![image](https://user-images.githubusercontent.com/2012640/124131357-b80b0900-da4d-11eb-9199-32c7bcd5650b.png)

which led me to create a new project _without_ teams, which then did work.  Are you sure your scaffolding included teams?

**Comment by driesvints** [comment]
Thanks. Yes I did. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by Stetzon** [comment]
I was able to narrow it down whether or not the user has an associated team. It looks like the app may expect the authenticated user to always have a team (when using teams). Logging in as a basic user created via `User::factory()->create()` will cause the error after logging in, but adding the `withPersonalTeam()` state will resolve it and the app behaves as expected.

**Comment by RichardDern** [comment]
I confirm that the problem is linked to user's creation, either from a factory or directly with `User::create` : neither creates a *personal_team*, which seems to be required when using Jetstream.

I create my first user through a Seeder.

```php
public function run()
    {
        $name     = env('FIRST_USER_NAME');
        $email    = env('FIRST_USER_EMAIL');
        $password = env('FIRST_USER_PASSWORD');

        if (empty($name) || empty($email) || empty($password)) {
            return;
        }

        if (User::where('email', '=', $email)->exists()) {
            return;
        }

        $user = new User([
            'name'              => $name,
            'email'             => $email,
            'password'          => Hash::make($password),
            'email_verified_at' => now()
        ]);

        $user->save();
    }
```

But to make it work, I need to add the team creation. The code was found in the _app/Actions/Fortify/CreateNewUser.php_ file :

```php
public function run()
    {
        $name     = env('FIRST_USER_NAME');
        $email    = env('FIRST_USER_EMAIL');
        $password = env('FIRST_USER_PASSWORD');

        if (empty($name) || empty($email) || empty($password)) {
            return;
        }

        if (User::where('email', '=', $email)->exists()) {
            return;
        }

        $user = new User([
            'name'              => $name,
            'email'             => $email,
            'password'          => Hash::make($password),
            'email_verified_at' => now()
        ]);

        $user->save();

        $user->ownedTeams()->save(Team::forceCreate([
            'user_id'       => $user->id,
            'name'          => explode(' ', $user->name, 2)[0] . "'s Team",
            'personal_team' => true,
        ]));
    }
```

This could (should?) be done in the `created` hook of the `User` model, because right now, it looks like Jetstream assumes all users to be created through the register form.

**Comment by chissevo** [comment]
In my case i execute this command: artisan optimize:clear.
