### ISSUE TITLE
Vue SPA version of Jetstream

### ISSUE THREAD

**Issue by codepotato** [laravel/jetstream#819]
Hey awesome folk at Laravel, I was wondering if there's anything planned in the pipeline to release a full SPA version of Jetstream using Vue? 

I know you have the inertiaJS variant but for our projects at Codepotato we prefer a "proper" SPA (no disrespect to inertia, it's great!) and wondered if there's any appetite or plans to release this? 

If not, would it be okay if we submitted a PR with the necessary code to offer this?

**Comment by driesvints** [comment]
We don't have any plans for this atm, sorry.

**Comment by codepotato** [comment]
Good to know, thanks @driesvints 👍
