### ISSUE TITLE
Enable profile photo upload

### ISSUE THREAD

**Issue by TolyanDimov** [laravel/jetstream#824]
- Jetstream Version: "laravel/jetstream": "^2.3"
- Jetstream Stack: "livewire/livewire": "^2.5"
- Uses Teams: no
- Laravel Version: "laravel/framework": "^8.40"
- PHP Version: "php": "^7.3|^8.0"

### Description:
Friends, tell a newbie.
After a clean install of Laravel + Jetstream, I decided to display the avatar in profile.
![2021-07-08_163052](https://user-images.githubusercontent.com/54508375/124933357-7f9a9a80-e00c-11eb-9414-4fb64fdaf190.png)

### Steps To Reproduce:
The image is displayed after loading.
When I press the save button, the photo is not displayed (see picture).

Sorry for my english.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
