### ISSUE TITLE
http://localhost:3000/browser-sync/browser-sync-client.js - net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by lotestudio** [laravel/jetstream#827]
- Jetstream Version: 2.3.11
- Jetstream Stack: Inertia 
- Uses Teams:  no
- Laravel Version: 8.49.2
- PHP Version: 7.4.2
- Database Driver & Version:

OS - MacOs Catalina
Local server: using Valet latest

### Description:
http://localhost:3000/browser-sync/browser-sync-client.js  
return
net::ERR_CONNECTION_REFUSED

Hot reload not working. Maybe it's not a jetstream issue, but I'm glad if someone points me in the right direction...
Thanks in advance

### Steps To Reproduce:
Fresh installation on laravel and jetstream with inertiajs.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
