### ISSUE TITLE
Target [Laravel\Fortify\Contracts\CreatesNewUsers] is not instantiable.

### ISSUE THREAD

**Issue by Avvernio** [laravel/jetstream#83]
- Jetstream Version: 0.7.0
- Laravel Version: 8.0
- PHP Version: 7.4.9
- Database Driver & Version: MariaDB 10.4.14

Running on latest Xampp build (windows) using Vhost

### Description:
On a new laravel 8 dev environment upon trying to registering and submitting the form the "<strong>Target [Laravel\Fortify\Contracts\CreatesNewUsers] is not instantiable.</strong>" error appears

### Steps To Reproduce:

composer create-project --prefer-dist laravel/laravel laravel8 dev-develop
composer require laravel/jetstream
php artisan jetstream:install livewire
npm install && npm run dev
php artisan migrate

**Comment by Avvernio** [comment]
just to be sure i made another clean copy, same result

stack trace: https://flareapp.io/share/A7EQNg7r#F51

**Comment by andersondeoliveiramachado** [comment]
https://flareapp.io/share/Bm0LRemx#F54

**Comment by andersondeoliveiramachado** [comment]
> just to be sure i made another clean copy, same result
> 
> stack trace: https://flareapp.io/share/A7EQNg7r#F51

SOLVED !

https://github.com/laravel/fortify/issues/7

**Comment by Avvernio** [comment]
Thanks @andersondeoliveiramachado solution was the correct one for me as well.

**Comment by abdessamadelhamdany** [comment]
Well it looks like if you don't use fortify with jetstream (or in this case not registering jetstream views)
you need to register your own views, in my case was:

```
Fortify::loginView(function () {
    return view('auth.login');
});

Fortify::registerView(function () {
    return view('auth.register');
});
```

**Comment by king-team-du-net** [comment]
Hi,

On a new laravel 8 development environment, when trying to change the password

Illuminate\Contracts\Container\BindingResolutionException
Target [Laravel\Fortify\Contracts\RequestPasswordResetLinkViewResponse] is not instantiable.

Thanks

**Comment by bedus-creation** [comment]
One thing that I am missing over here while using fortify without jetstream is to forget registration of FortifyServiceProvider.

```php
// app.php
App\Providers\FortifyServiceProvider::class,
```
