### ISSUE TITLE
Latest InertiaJS updates break Jetstream stubs

### ISSUE THREAD

**Issue by wattsie** [laravel/jetstream#830]
Just an FYI for others that have an issue (broke my little app, and this fixed it for me)
`[Vue warn]: Failed to resolve component: inertia-link `

When upgrading the the following, pages fail to load as they are no longer able to find "inertia-link"

```
"@inertiajs/inertia": "^0.10.0",
"@inertiajs/inertia-vue3": "^0.5.1",
```

As a result of this update (https://github.com/inertiajs/inertia/pull/765) Head and Link are no longer globally registered.

A quick fix is in app.ts import "Link" and register the component.
```
import {App as InertiaApp, plugin as InertiaPlugin, Link} from '@inertiajs/inertia-vue3'
app.component('InertiaLink', Link)
```

Complete way, would be to modify all related stubs to include:
```
<script>
import { Head, Link } from '@inertiajs/inertia-vue3' // Vue 3
export default {
  components: {
    Head,
    Link,
  }
}
</script>
```

**Comment by driesvints** [comment]
Ping @reinink

**Comment by dillingham** [comment]
Was part of the 0.7 Vue release 

https://inertiajs.com/releases/inertia-vue-0.7.0-2021-07-13

Was initially surprised it wasn't included in the 1.0 release but it was a tiny fix

**Comment by driesvints** [comment]
@claudiodekker provided a fix for this. Thanks for reporting.

**Comment by reinink** [comment]
Thanks @claudiodekker 👏
