### ISSUE TITLE
Install fails with fresh, bone-stock Laravel instance.

### ISSUE THREAD

**Issue by unrivaledcreations** [laravel/jetstream#838]
- Jetstream Version: `^1.3|^2.0` (via `composer.json`)
- Jetstream Stack: Inertia / (N/A)
- Uses Teams: yes / no (N/A)
- Laravel Version: 8.51.0
- PHP Version: 8.0.8
- Database Driver & Version: (N/A)

### Description:

Getting a Composer error on install, using the command `composer require laravel/jetstream`:

```
Problem 1
    - laravel/jetstream[v2.3.0, ..., 2.x-dev] require league/commonmark ^1.3 -> found league/commonmark[1.3.0, ..., 1.6.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires laravel/jetstream ^2.3 -> satisfiable by laravel/jetstream[v2.3.0, ..., 2.x-dev].
```

The bone-stock Laravel installation uses Jetstream v2 because `vendor/laravel/framework/src/Illuminate/Mail/composer.json` contains `"league/commonmark": "^1.3|^2.0"`. However, Jetstream's `composer.json` requires `"league/commonmark"` `"^1.3"`. This breaks the installation process because the core Laravel framework already installed v2.x when Jetstream seems to insist on v1.3 (of the `league/commonmark` dependency).

### Steps To Reproduce:

```sh
laravel new test
cd test
composer require laravel/jetstream
```

The single command, `laravel new --jet --stack=inertia test`, also fails for the same reason.

### Workaround:

Manually adding `"league/commonmark": "^1.3",` to the root `composer.json` project file before `composer require laravel/jetstream` seems to work around the problem.

**Comment by jonorozcoc** [comment]
I confirm the issue with

- PHP: 8.0.6
- Stack: Livewire

It happens on fresh install and the workaround mentioned by @unrivaledcreations works

**Comment by zamarproject** [comment]
I had the same issue.
I tried your suggestion but didn´t work.
I placed "league/commonmark": "^1.3" in the root composer.json project file:

    "require": {
        "php": "^7.3|^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "league/commonmark": "^1.3",   <-- right there...        
        "laravel/framework": "^8.40",
        "laravel/tinker": "^2.5"
    },
    
    Then, I launched "composer require laravel/jetstream" and also I tried with "laravel new --jet --stack=inertia test"
    and the same error message.
    Any suggestion?
    :(

**Comment by daffigusti** [comment]
after you put
`"league/commonmark": "^1.3"`
on `composer.json`
You must delete `composer.lock` before you run `composer require laravel/jetstream`.

It works for me.

**Comment by juanjo1307** [comment]
same issue with inertia
Problem 1
    - laravel/jetstream[v2.3.0, ..., 2.x-dev] require league/commonmark ^1.3 -> found league/commonmark[1.3.0, ..., 1.6.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires laravel/jetstream ^2.3 -> satisfiable by laravel/jetstream[v2.3.0, ..., 2.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by zamarproject** [comment]
Oh Thank you so much, I´ll take a look right now!

**Comment by zamarproject** [comment]
Great !
It worked for me too!
I found also, another way to resolve it:

After place"league/commonmark": "^1.3", I installed, in the root of the
project:

composer require league/commonmark:^1.3

and it worked for me too!

**Comment by driesvints** [comment]
Tagged v2.3.12 with a fix. Thanks everyone for reporting.

**Comment by RomanSarvarov** [comment]
Guys, do you still have this problem as me?
[Currently](https://github.com/laravel/jetstream/blob/2.x/src/Http/Controllers/Inertia/TermsOfServiceController.php) Jetstream is calling this class:
`use League\CommonMark\Environment;`

I'm using CommonMark ver 2.0 and this package does not contain this class.
It [have](https://github.com/thephpleague/commonmark/blob/main/src/Environment/Environment.php) League\CommonMark\Environment\Environment (not League\CommonMark\Environment)

**Comment by pwncraft** [comment]
@RomanSarvarov commonmark 2.0 deprecates and changes quite a few things. This breaks the implementation that jetstream is using for the Terms/Privacy Policy feature. 

You can work around by updating the Controllers in the vendor folder with the new way to use the GithubFlavoredMarkdownConverter. 

TermsOfServiceController:
`<?php

namespace Laravel\Jetstream\Http\Controllers\Livewire;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Laravel\Jetstream\Jetstream;
use League\CommonMark\GithubFlavoredMarkdownConverter;

class TermsOfServiceController extends Controller
{
    /**
     * Show the terms of service for the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\View\View
     */
    public function show(Request $request)
    {
        $termsFile = Jetstream::localizedMarkdownPath('terms.md');

        return view('terms', [
            'terms' => (new GithubFlavoredMarkdownConverter())->convertToHtml(file_get_contents($termsFile)),
        ]);
    }
}
`
PrivacyPolicyController:
`<?php

namespace Laravel\Jetstream\Http\Controllers\Livewire;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Laravel\Jetstream\Jetstream;
use League\CommonMark\GithubFlavoredMarkdownConverter;

class PrivacyPolicyController extends Controller
{
    /**
     * Show the privacy policy for the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\View\View
     */
    public function show(Request $request)
    {
        $policyFile = Jetstream::localizedMarkdownPath('policy.md');

        return view('policy', [
            'policy' => (new GithubFlavoredMarkdownConverter())->convertToHtml(file_get_contents($policyFile)),
        ]);
    }
}
`

**Comment by driesvints** [comment]
Tagged v2.3.14 with a fix.
