### ISSUE TITLE
Laravel Passport integration

### ISSUE THREAD

**Issue by willishq** [laravel/jetstream#84]
I am creating a platform which requires an Oauth flow (it is a billing platform to manage subscriptions to multiple seperate services) and while it is easy enough to integrate, I wonder if it would be of benefit to have such functionality available in Jetstream?

If this is something that you would be looking to add I am more than happy to implement the functionality myself and submit a pull request, if not I'll obviously just add it to my project.

**Comment by driesvints** [comment]
I doubt we'll be implementing this natively into jetstream, sorry.

**Comment by siarheipashkevich** [comment]
@willishq did you implement the integration between passport and jetstream?

**Comment by martindilling** [comment]
> I am creating a platform which requires an Oauth flow (it is a billing platform to manage subscriptions to multiple seperate services) and while it is easy enough to integrate, I wonder if it would be of benefit to have such functionality available in Jetstream?
> 
> If this is something that you would be looking to add I am more than happy to implement the functionality myself and submit a pull request, if not I'll obviously just add it to my project.

If you implemented Passport, did you get it working reusing some of the existing things from Jetstream, or did you just roll your own thing?

**Comment by alia007me** [comment]
For website authentication which is better? passport or jetstream.
