### ISSUE TITLE
Undefined array key "permission"

### ISSUE THREAD

**Issue by potsky** [laravel/jetstream#841]
- Jetstream Version: v2.3.12
- Jetstream Stack: Livewire
- Uses Teams: yes
- Laravel Version: 8.51.0
- PHP Version: 8
- Database Driver & Version: PGSQL

### Description:

Since composer update from 2.3.11 to 2.3.12, when I run `sail php unit`, I have 8 failed tests with the same error :

```
  • Tests\Feature\InviteTeamMemberTest > team members can be invited to team
   Facade\Ignition\Exceptions\ViewException

  Undefined array key "permission" (View: /var/www/html/resources/views/teams/team-member-manager.blade.php)

  at [internal]:0
      1▕

  1   resources/views/teams/team-member-manager.blade.php:83
      Livewire\Component::__get()

      +5 vendor frames
  7   [internal]:0
      Laravel\Jetstream\Http\Livewire\TeamMemberManager::Laravel\Jetstream\Http\Livewire\{closure}()
```

### Steps To Reproduce:

Run tests on an updated JetStream install.

**Comment by hamza-masoud** [comment]
I have the same error I don't know what I should do

**Comment by ismailcaakir** [comment]
I have the same error.

**Comment by aberkanimed** [comment]
I have the same error

**Comment by driesvints** [comment]
tagged v2.3.13 with a fix. Thanks

**Comment by hamza-masoud** [comment]
thanks ❤❤ alot
