### ISSUE TITLE
Typo in $data array key

### ISSUE THREAD

**Issue by daniel-zahariev** [laravel/jetstream#842]
There's a typo on this line:
https://github.com/laravel/jetstream/blob/ed624ff095952a0c61750ccad5aa67e6d2ff2c44/src/Http/Livewire/TeamMemberManager.php#L260
it should read: `$data['permissions'],`

**Comment by driesvints** [comment]
tagged v2.3.13 with a fix. Thanks

**Comment by driesvints** [comment]
Btw, feel free to just PR that next time
