### ISSUE TITLE
Class "League\CommonMark\Environment" not found

### ISSUE THREAD

**Issue by caiokawasaki** [laravel/jetstream#844]
- Jetstream Version: 2.3.13
- Jetstream Stack: Livewire
- Uses Teams: no
- Laravel Version: 8.52.0
- PHP Version: 8.0.8 (Using Sail)
- Database Driver & Version: None

### Description:

Yesterday I decided to run away from the Laravel/Vue stack and test Livewire, I just created a simple CRUD, and after making some changes, I noticed that on the registration screen the `Terms of Service` and `Privacy Policy` pages weren't rendering. I even tried it with a clean install...

On both pages the following error is displayed: [https://flareapp.io/share/87ng2Z05#F48](https://flareapp.io/share/87ng2Z05#F48)

### Steps To Reproduce:

```sh
curl -s https://laravel.build/example-app | bash
```

```sh
sail composer require laravel/jetstream
sail artisan jetstream:install livewire
sail npm install
sail npm run dev
sail artisan migrate
```

Then enable `Features::termsAndPrivacyPolicy()` inside `config/jetstream.php`.

Both pages displays the error:

- [http://localhost/terms-of-service](http://localhost/terms-of-service)
- [http://localhost/privacy-policy](http://localhost/privacy-policy)

### Edit

Looks like a `PR` related to this issue is open: https://github.com/laravel/jetstream/pull/843

**Comment by driesvints** [comment]
Tagged v2.3.14 with a fix.
