### ISSUE TITLE
Tailwind purges styles in /resources/views

### ISSUE THREAD

**Issue by he11yeah** [laravel/jetstream#859]
- Jetstream Version: v2.3.14
- Jetstream Stack: Livewire
- Uses Teams: no
- Laravel Version: v8.55.0
- PHP Version: v7.3.29
- Database Driver & Version:

### Description:
Tailwind purges styles in /resources/views leading to missing css classes styling for:

- dashboard.blade.php
- navigation-menu.blade.php
- policy.blade.php
- terms.blade.php

`'./resources/views/**/*.blade.php',` is targeting all blade files in all subdirectories, but not the parent directory itself.

### Steps To Reproduce:

1. laravel new laravel
2. cd laravel
3. composer require laravel/jetstream
4. php artisan jetstream:install livewire
5. npm install && npm run dev

## I have been fixing this in my projects by adding the following line after line 9 in tailwind.config.js
`'./resources/views/*.blade.php',`

**Comment by driesvints** [comment]
Seems to work fine for me.
