### ISSUE TITLE
[FR] Route for /teams that goes to the users first team settings

### ISSUE THREAD

**Issue by raisonon** [laravel/jetstream#861]
I'm looking to create a link that directs to the team settings. 

Ie. Invite another user to your team

Only a POST route for /teams

Is there a good process to direct someone to their teams settings already or would it be good to create a PR which:

* Adds a get route for /teams
*  adds a showDefault() to TeamController and gets the first team associated to the user

Cheers

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
