### ISSUE TITLE
Team::allUsers() and Team::users() have different return types

### ISSUE THREAD

**Issue by dominikkukacka** [laravel/jetstream#868]
- Jetstream Version: 2.3.10
- Jetstream Stack: Inertia
- Uses Teams: yes
- Laravel Version: 8.48.2
- PHP Version: 8.0.10

### Description:
I noticed that the Team functions users() and allUsers() have different return types:

users() -> Illuminate\Database\Eloquent\Relations\BelongsToMany
allUsers() -> Method Illuminate\\Database\\Eloquent\\Collection::paginate does not exist.

This means we can't do something like: ->allUsers()->paginate()
Is there any way around that? I tried producing a fix but could not come up with a nice solution.

**Comment by driesvints** [comment]
Feel free to add something to your own app.
