### ISSUE TITLE
Is there any way to choose between inertia-vue2 and inertia-vue3?

### ISSUE THREAD

**Issue by fahmiegerton** [laravel/jetstream#870]
Hello, I just get to the point. Is there any way to pick between inertia-vue2 and inertia-vue3? If there is (or would be), that would be awesome. So much feature on vue environment are in vue2. I tried use inertia-vue3 with so many vue2-ish plugins, but none of them are working. I don't want to use react because I don't understand reactjs yet. That would be great if in anyway we can choose version of inertia-vue (and because I really need it, that much). Thank you!

**Comment by driesvints** [comment]
I'm afraid not. Jetstream uses Vue3 atm.

**Comment by fahmiegerton** [comment]
> I'm afraid not. Jetstream uses Vue3 atm.

Is there any way to trick it? downgrading makes a lot of compatibility issues, force to edit package.json to use vue2 instead vue3 doesn't work either, any clues I could force to use vue2? if not, i think i'm screwed.
