### ISSUE TITLE
Bug: Cannot create record in team_user table

### ISSUE THREAD

**Issue by nguyentranchung** [laravel/jetstream#876]
- Jetstream Version: Latest
- Jetstream Stack: Inertia / Livewire
- Uses Teams: yes
- Laravel Version: 8.58
- PHP Version: 8.0.9
- Database Driver & Version: MySQL 8

### Description:

after creating the account, a row in the users table is created, a row in the teams table is created, but not a row in the user_table table is created.

### Steps To Reproduce:

Just create a new account

![laraveljetstream1 drawio](https://user-images.githubusercontent.com/9611224/132442172-305f421a-7bf5-4a7e-86ba-8869d9845ced.png)

Seee PR: https://github.com/laravel/jetstream/pull/874

**Comment by driesvints** [comment]
Your personal team doesn't have a pivot record.
