### ISSUE TITLE
Translations not available in Inertia stack

### ISSUE THREAD

**Issue by devinfd** [laravel/jetstream#877]
- Jetstream Version: 2.3.16
- Jetstream Stack: Inertia
- Uses Teams: Yes
- Laravel Version: 8.59.0
- PHP Version: 8.0

### Description:
Translations not available in Inertia stack. I see this as a bug and not a feature request because translations work in the Livewire stack but not Inertia.

**Comment by driesvints** [comment]
Yes that's intended. We removed them because we don't want the maintenance burden.
