### ISSUE TITLE
Allow a different middleware group for Inertia data binding

### ISSUE THREAD

**Issue by LeoColomb** [laravel/jetstream#880]
In `JetsreamServiceProvider`, the `web` middleware group is hard written.

https://github.com/laravel/jetstream/blob/a24cddce5e158c743723cc04f9b8d3194f62aab3/src/JetstreamServiceProvider.php#L234

This complicates the configuration on where Inertia and Jetstream are expected to be used.
The request is to allow changing this middleware group.

---

The configuration includes a `middleware` field, which is used to specify which middleware to apply on Jetstream routes.
I find it a bit confusing why there is no link between this configuration field and the above request.

**Comment by driesvints** [comment]
We currently have no plans for this, sorry.
