### ISSUE TITLE
Laravel Bootstrap fan.

### ISSUE THREAD

**Issue by netaccount-tarik** [laravel/jetstream#884]
Hi to all just to mention that I am laravel passion fan, and want to say that I am also BOOTSTRAP 4 FAN, and JQUERY, and will always stick with that, so please have support for bootstrap and jquery in future as well.  Because nothing can change bootstrap + Laravel. Thanks!

**Comment by FoksVHox** [comment]
See #702, #219 & #179

**Comment by netaccount-tarik** [comment]
danke.
