### ISSUE TITLE
 create sequence laravelteam_invitations minvalue 1  start with 1 increment by 1 ) in pdo_oci8

### ISSUE THREAD

**Issue by cadentic** [laravel/jetstream#885]
- Jetstream Version: #.#.#
- Jetstream Stack: Inertia / Livewire
- Uses Teams: yes / no
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

jetstream inertia 
team yes
php 7.4
laravel 8.xx
database 19c oracle autonomous databse , pdo_oci8 , yajra/laravel packages 
### Description:
php artisan --version
Laravel Framework 8.61.0

### Steps To Reproduce:

php artisan migrate 
fails with an error 

` Error Code    : 955
Error Message : ORA-00955: name is already used by an existing object
Position      : 16
Statement     : create sequence laravelteam_invitations minvalue 1  start with 1 increment by 1
Bindings      : []
 (SQL: create sequence laravelteam_invitations minvalue 1  start with 1 increment by 1 )
`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
