### ISSUE TITLE
ValidateTeamDeletion ValidationException not handled.

### ISSUE THREAD

**Issue by lhdev** [laravel/jetstream#889]
- Jetstream Version: 2.4.0
- Jetstream Stack: Livewire
- Uses Teams: yes
- Laravel Version: 8.61.0
- PHP Version: 7.4.19
- Database Driver & Version

### Description:
When deleting a team that fails validation, the validation logic produces a ValidationException in ValidateTeamDeletion.php that isn't caught and displayed.

### Steps To Reproduce:
Edit: views/teams/show.blade.php to force a situation where deleting a team will fail.

```php
@if (Gate::check('delete', $team))
                <x-jet-section-border />

                <div class="mt-10 sm:mt-0">
                    @livewire('teams.delete-team-form', ['team' => $team])
                </div>
@endif
```

Once you submit the Delete Team form, no error gets displayed.
Chrome Dev Tools confirms from the network tab:

```json
{
    "errors": {
        "team": [
            "You may not delete your personal team."
        ]
    },
}
```

I've confirmed this on two separate Laravel sites, one that is just a vanilla install with Jetstream, the other is a full blown project.

**Comment by driesvints** [comment]
You can't ever delete your personal team. It's always required.

**Comment by lhdev** [comment]
That’s not the point, that’s an easy way to reproduce.  You can just as easily add a new validation exception if another condition is met which is what I’m actually doing.  This issue still exists.
