### ISSUE TITLE
HasTeams Trait with BelongToMany Pivot withTimestamp not follow Model definition

### ISSUE THREAD

**Issue by xicond** [laravel/jetstream#891]
- Jetstream Version: 2.3.16
- Jetstream Stack: Inertia
- Uses Teams: yes
- Laravel Version: v8.58.0
- PHP Version: 7.4.22
- Database Driver & Version: 10.5.8-MariaDB-log
- Doctrine/dbal: 2.13.2

### Description:
Pivot withTimestamp not follow Model definition
I have legacy user table definition that too many dependency, so I need to adapt the timestamp fieldname.
When I modified timestamp field for User.php, calling Auth::user()->teams causing errors
The error indicated, the timestamp field changed is in team_user, instead of team_user follow default fieldname as team_user.created_at

```
Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'team_user.create_at' in 'field list' in /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:79
Stack trace:
#0 /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(79): PDO->prepare('select teams....', Array)
#1 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(352): Doctrine\DBAL\Driver\PDOConnection->prepare('select teams....')
#2 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(685): Illuminate\Database\Connection->Illuminate\Database\{closure}('select teams....', Array)
```

### Steps To Reproduce:

app\Models\User.php
```
    const CREATED_AT = 'create_at';
    const UPDATED_AT = 'last_modified_at';
```

~~My workaround is just disabled the withTimestamp :~~
```
// originally
public function teams()
    {
        return $this->belongsToMany(Jetstream::teamModel(), Jetstream::membershipModel())
                        ->withPivot('role')
                        ->withTimestamps()
                        ->as('membership');
    }
```

```
// become
public function teams()
    {
        return $this->belongsToMany(Jetstream::teamModel(), Jetstream::membershipModel())
                        ->withPivot('role')
                        ->as('membership');
    }
````

@derekmd suggested another better workaround on [laravel/framework #38820](https://github.com/laravel/framework/issues/38820#issuecomment-922384748)

**Comment by driesvints** [comment]
Hey @xicond since this is a question about customizing Jetstream's default scaffolding it's best to ask this on a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
