### ISSUE TITLE
ValidateTeamDeletion ValidationException not handled.

### ISSUE THREAD

**Issue by lhdev** [laravel/jetstream#894]
- Jetstream Version: 2.4.0
- Jetstream Stack: Livewire
- Uses Teams: yes
- Laravel Version: 8.61.0
- PHP Version: 7.4.19
- Database Driver & Version

### Description:
When deleting a team that fails validation, the validation logic produces a ValidationException in ValidateTeamDeletion.php that isn't caught and displayed.  I'm adding to the Team Deletion logic and throwing an exception if the Team is deleted when specific conditions are met.

### Steps To Reproduce:
To simulate this easily, just do below,  the last issue was closed because this wasn't taken as a step to reproduce, clearly we don't want to delete our personal team, the issue of the exception not being handled still exists!!!

Edit: views/teams/show.blade.php to force a situation where deleting a team will fail.

```php
@if (Gate::check('delete', $team))
                <x-jet-section-border />

                <div class="mt-10 sm:mt-0">
                    @livewire('teams.delete-team-form', ['team' => $team])
                </div>
@endif
```

Once you submit the Delete Team form, no error gets displayed.
Chrome Dev Tools confirms from the network tab:

```json
{
    "errors": {
        "team": [
            "You may not delete your personal team."
        ]
    },
}
```

I've confirmed this on two separate Laravel sites, one that is just a vanilla install with Jetstream, the other is a full blown project.

**Comment by driesvints** [comment]
As I said in the previous issue, you cannot delete your personal theme. If you really believe this is a bug please provide a repo that reproduces the issue with:

```bash
laravel new bug-report --github="--public"
```

**Comment by lhdev** [comment]
Why are you being such a pain?  I literally said that I am trying to throw a different exception.

**Comment by lhdev** [comment]
@driesvints The example above is to prove a point.  I have extracted controllers, livewire components and actions to my own namespace for customization.  Doing so in a bug-report repo is a lot of extra work.  This can be easily simplified and mocked up by just using the example above.

I DO NOT WANT TO DELETE A PERSONAL TEAM!!!  I am simply using that as an example to trigger the exception so you can see that it is not properly handled.  It will take you 2 minutes to confirm this instead of asking me to spend much longer than that publishing a bug-report repo.

Please re-evaluate this bug request and stop dismissing it.

**Comment by driesvints** [comment]
> Doing so in a bug-report repo is a lot of extra work.

It's also more work for me. Either provide me a repo that reproduces the problem with a non-personal theme or stop opening new issues.

**Comment by lhdev** [comment]
It's fine, I've said my piece and reported a valid issue, if you choose to not accept it and call it a feature, that's on you.
I can work around it, maybe someone else will encounter it later and be more willing to take the time to give you a demo.

But honestly, why throw a validation exception for the personal team deletion if you're not going to even catch and handle it / display the error to the user?  It puts them in a situation where there's ZERO feedback and they will think the app is broken.
