### ISSUE TITLE
Translations with quotation marks are shown encoded in the livewire component `label`

### ISSUE THREAD

**Issue by luisprmat** [laravel/jetstream#899]
- Jetstream Version: 2.4.2
- Jetstream Stack: Livewire
- Uses Teams: yes
- Laravel Version: 8.62.0
- PHP Version: 8.0.3
- Database Driver & Version: MySQL 5.7.24

### Description:
If i use **French translations** (locale `fr`) and they contain quotes, these are shown encoded with the `&#039;` code.
![bugJetstream](https://user-images.githubusercontent.com/9275870/135954727-13766426-ad1d-4a99-ba33-6b8dbb12c441.PNG)
For this example i'm using `'locale' => 'fr',`  in `config('app')` and the translations file `resources/lang/fr.json` (taked from [Laravel-Lang](https://github.com/Laravel-Lang/lang/blob/master/locales/fr/fr.json#L558-L559)) contains
```json
{
    ...
    "Team Name": "Nom de l'équipe",
    "Team Owner": "Propriétaire de l'équipe",
    ...
}
```
The problem occurs when the translation is passed through the `value` property of the `label` component using double curly syntax, such as in [Line 13](https://github.com/laravel/jetstream/blob/2.x/stubs/livewire/resources/views/teams/update-team-name-form.blade.php#L13) and [Line 27](https://github.com/laravel/jetstream/blob/2.x/stubs/livewire/resources/views/teams/update-team-name-form.blade.php#L27) of the [`resources/views/teams/update-team-name-form.blade.php`](https://github.com/laravel/jetstream/blob/2.x/stubs/livewire/resources/views/teams/update-team-name-form.blade.php) template.

This issue *can be avoided* if you replace the line 13
```php
<x-jet-label value="{{ __('Team Owner') }}" />
```
by 
```php
<x-jet-label :value="__('Team Owner')" />
```
i.e using the colon syntax or passing translation inside the slot
```php
<x-jet-label>{{ __('Team Owner') }}</x-jet-label>
```
(The same for the line 27)

### Steps To Reproduce:
- Install a Laravel fresh app with jetstream + livewire + teams.
- Set database, install and run javascript dependencies.
- Register a user.
- Set locale to `fr` and copy [`fr.json`](https://github.com/Laravel-Lang/lang/blob/master/locales/fr/fr.json) to `resources/lang/fr.json`.
- Go to *url* `teams/1`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
