### ISSUE TITLE
(Inertia) Cannot login, session does not seem to persist.

### ISSUE THREAD

**Issue by filipac** [laravel/jetstream#9]
- Jetstream Version: 0.0.4
- Laravel Version: 8.x-dev
- PHP Version: 7.4.5
- Database Driver & Version: Mysql 8

### Description:
After registering, when trying to login it fail silently and I am returned to the login page again. I can see the session in sessions table in MySQL but I cannot sucessfuly login. If I enter a wrong email or password, it returns with an error.

### Steps To Reproduce:
Install Jetstream.
php artisan jetstream:install inertia
php artisan migrate
Register
Try to login (i think after registering you should also be logged in automatically).

**Comment by ibourgeois** [comment]
The login route appears to be part of laravel/fortify

**Comment by ibourgeois** [comment]
also `composer update` fixed it for me ;)

**Comment by sirkenedy** [comment]
> * Jetstream Version: 0.0.4
> * Laravel Version: 8.x-dev
> * PHP Version: 7.4.5
> * Database Driver & Version: Mysql 8
> 
> ### Description:
> After registering, when trying to login it fail silently and I am returned to the login page again. I can see the session in sessions table in MySQL but I cannot sucessfuly login. If I enter a wrong email or password, it returns with an error.
> 
> ### Steps To Reproduce:
> Install Jetstream.
> php artisan jetstream:install inertia
> php artisan migrate
> Register
> Try to login (i think after registering you should also be logged in automatically).

were you able to get it fixed

**Comment by CleoCTech** [comment]
I'm also facing the exact same issue, i runned `composer updated`,  the problem wouldn't be fixed

**Comment by illusive-ch** [comment]
I am also getting this error on a fresh install of inertia/jetstream any thoughts on what could be the issue?

**Comment by jessarcher** [comment]
I am unable to replicate this issue by doing the following:

* `laravel new --jet` and selecting Inertia
* Configure an SQLite database
* Migrate
* Register
* Log out
* Log in

**Comment by laraben** [comment]
i faced the same issue because i changed the user id to uuid.
And the session table was linked to user id.
once i changed the migration of session to uuid it was working fine
