### ISSUE TITLE
Delete Account doesn't require Password Verification

### ISSUE THREAD

**Issue by SeanBourke** [laravel/jetstream#90]
- Jetstream Version: 0.6.4
- Laravel Version: 8.0 (dev)
- PHP Version: 7.94

### Description:
Jetstream will not request a user to reverify their password when deleting account, however this is required when logging out other sessions.

**Comment by Wulfheart** [comment]
This would be a nice enhancement indeed.

**Comment by SeanBourke** [comment]
I've completed and tested a change for Inertia, just working through Livewire now. Will have a PR up shortly.

**Comment by FoksVHox** [comment]
> I've completed and tested a change for Inertia, just working through Livewire now. Will have a PR up shortly.

Sounds lovely

**Comment by driesvints** [comment]
Feel free to PR

**Comment by BeerGrizzly** [comment]
I've implemented an OAuth login with Jetstream and it's really awesome 👍
Just one small factor thats limiting me at the moment is, that i can't delete a user account without it's password. The logic for that is now baked into the Livewire Component DeleteUserForm. Hence users that didn't login traditionally with a password won't be able to delete their accounts, without me editing vendor files atm. I do think that #91 is a suboptimal solution for everyone not only using password authentication. It would be great if there would be an option in the config but maybe that's overkill as well. Would love to hear your opinions on that.
