### ISSUE TITLE
User authentication status remains there if I use [users: POST] route.

### ISSUE THREAD

**Issue by brainlet-ali** [laravel/jetstream#900]
- Jetstream Version: 2.4.2
- Jetstream Stack: Inertia
- Uses Teams: no
- Laravel Version: 8.62.0
- PHP Version: 8.0
- Database Driver & Version: Sqlite

### Description:
When I try to use '/users' (POST) route and then try to logout in my test, I got the old user and not null.

I've to use 'users' (POST) route to store other sub-users for which the parent user is the current user (just a use case). Both of the tests in AuthenticationTest.php need to pass.

### Steps To Reproduce:
https://github.com/brainlet-ali/intertia_test

**Comment by driesvints** [comment]
Don't use multiple HTTP calls in a single test. That's not a real-life scenario that's possible.

**Comment by brainlet-ali** [comment]
Then why this test has multiple HTTP calls; the multiple HTTP calls may not be supported but it is very much real life scenario, you cannot write infinite seeders to satisfy every test.

test_two_factor_authentication_can_be_disabled()
{
        $this->actingAs($user = User::factory()->create());

        $this->withSession(['auth.password_confirmed_at' => time()]);

        $this->post('/user/two-factor-authentication');

        $this->assertNotNull($user->fresh()->two_factor_secret);

        $this->delete('/user/two-factor-authentication');

        $this->assertNull($user->fresh()->two_factor_secret);
    }
