### ISSUE TITLE
Password Confirmation - 401 Handling

### ISSUE THREAD

**Issue by DeanWhitehouse** [laravel/jetstream#903]
- Jetstream Version: 2.4.3
- Jetstream Stack: Inertia
- Uses Teams:  no
- Laravel Version: 8.64.0
- PHP Version: 8.0.9
- Database Driver & Version: MySQL 8.0.20

### Description:
When using the modal approach for confirming passwords, as detailed here https://jetstream.laravel.com/2.x/features/password-confirmation.html, if the user is logged out we simply get a console error rather than the expected redirect (expected from the auth middleware) or an error message

Looking into the route `/user/confirmed-password-status` we appear to get a JSON response from the Auth guard. 

We could add processing to`ConfirmsPassword.vue` file to check if a 401 error is returned and redirect to the login screen manually or by calling `$inertia.reload()`, however we can't show the user a message saying why they were redirected as we don't get anything in the flash or error props nor can we manually add this.

I believe this is a bug as it's inconsistent with the behaviour of the framework overal, if you reload the page the 401 is handled and redirected. 

As an extension of this I'd suggest an error message is sent with the redirect to allow for a message to be shown utilising banners https://jetstream.laravel.com/2.x/building-your-app.html#banner-alerts

### Steps To Reproduce:
* On a clean install of Laravel with Jetstream Inertia, add a new the `ConfirmsPassword.vue` element with a button in it to a password page. 
* Login to the site, then open a new tab and navigate to the newly created page.
* In the initial tab log out of the site
* Then return to the other tab and click the button
* Nothing will happen, just a console error

**Comment by driesvints** [comment]
@DeanWhitehouse you can always attempt a PR 👍
