### ISSUE TITLE
The invitation link is not checking the currently logged-in user is authorized to accept the invitation or not. 

### ISSUE THREAD

**Issue by sachinkumar121** [laravel/jetstream#907]
- Jetstream Version: 2.3
- Jetstream Stack: Inertia
- Uses Teams: yes
- Laravel Version: 8.40
- PHP Version: 8.0.11
- Database Driver & Version: 8.0.25 - MySQL Community Server

### Description:
It simply accepts the invitation and adds the member to the team without checking whether the currently logged-in user's email is matched with the invitation link or not.

### Steps To Reproduce:

1. Install the Laravel/jetstream with teams feature.
2. add a member to the team using his email address.
3. open that invitation link to any logged-in user's session(even from the owner session).
4. The invitation is accepted successfully.

### Real Use case example.
1. User A(whose email address is abc@example.com) adds a team member B(whose email address is def@example.com).
2. User C(whose email address is xyz@example.com) is logged in to another browser and opens that invitation link, the user B is added to the team.
3. It should check before accepting the invitation because user C has no right to accept the invitation of another team member.
4. Or you can say it should work the same as the Laravel default verification process. If you verified another user by opening their link to your account then the concerned user will never be verified. He has to log in to their account and accept the verification process then the user will be verified.

**Comment by driesvints** [comment]
That's intended.

**Comment by sachinkumar121** [comment]
I don't understand why? Is there is any specific reason or are you working on it?
