### ISSUE TITLE
Issue with encoding two times localizable strings

### ISSUE THREAD

**Issue by ZeProf2Code** [laravel/jetstream#908]
- Jetstream Version: 2.4.4
- Jetstream Stack: Livewire
- Uses Teams: yes
- Laravel Version: 8.73.0
- PHP Version: 8.0.13
- Database Driver & Version: PGSQL 8.0.13

### Description:
For example, if you translate "Team Owner" to french: "Propriétaire de l'équipe" it contains the ' character and therefore is encoded as `&#039;` by the e function here: https://github.com/laravel/jetstream/blob/2.x/stubs/livewire/resources/views/teams/create-team-form.blade.php#L12 but then when passed to the component, it is encoded one more time by the e function here:  https://github.com/laravel/jetstream/blob/2.x/resources/views/components/label.blade.php#L4 and results in the ' character being `&amp;#039;` which obviously, doesn't output correctly in the browser.

### Steps To Reproduce:

- Create a simple Laravel Jetstream instance.
- Translate one string that is encoded two times e.g. "Team Owner" so it contains the ' character.
- See the problem in your browser.

**Comment by driesvints** [comment]
Hey @ZeProf2Code. You own the team form file so feel free to update that as you wish. Otherwise we'd appreciate a PR.
