### ISSUE TITLE
browsersync bug

### ISSUE THREAD

**Issue by xushulang** [laravel/jetstream#913]
- Jetstream Version: 2.4
- Jetstream Stack: Inertia
- Uses Teams: yes
- Laravel Version: 8.6.6
- PHP Version: 8.0.12
- Database Driver & Version:

### Description:
when I click link,
![image](https://user-images.githubusercontent.com/52433214/144166681-2eb5abe0-6a29-4720-9861-8b37ed553c48.png)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
