### ISSUE TITLE
Jetstream 404 Error when use a Route with 3 Parameters

### ISSUE THREAD

**Issue by frankjosef** [laravel/jetstream#914]
- Jetstream Version: 2.4
- Jetstream Stack: Livewire
- Uses Teams: yes
- Laravel Version: 8.0
- PHP Version: 7.4
- Database Driver & Version: mysql

### Description:

We use a redirect route (public function) where we pass 3 parameters.
`Route::get('{ad}/{user_name}/{link_name}'`

But now I get a 404 error with the jetstream links. If I add one more parameter, the Jetstream components work as expected. Does anyone know a way to solve the problem?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
