### ISSUE TITLE
Request confirmation before changing profile email

### ISSUE THREAD

**Issue by lsmith77** [laravel/jetstream#916]
Related to https://github.com/laravel/fortify/issues/331 there is currently no protection to prevent users from locking themselves out of their account.

In this spirit it would be nice to ask users to confirm before overwriting their current email with a new one.

**Comment by driesvints** [comment]
I'm afraid I'm going to have to give you the same answer as on the fortify issue. It's probably best that you attempt a PR. Thanks.
