### ISSUE TITLE
Cannot invite team members with existing invitation

### ISSUE THREAD

**Issue by LarryBarker** [laravel/jetstream#917]
- Jetstream Version: 2.1
- Jetstream Stack: Livewire
- Uses Teams: yes 
- Laravel Version: 8.x
- PHP Version: 8.0
- Database Driver & Version: MySQL 5.7

### Description:

When attempting to invite a member to more than one team, there is an error that the user is already invited to the team. This happens when the user has been invited to a team, but not accepted the invitation, and you try to invite them to another team. 

![image](https://user-images.githubusercontent.com/28734844/145272686-dd7cc07a-858a-4c8c-be85-8ecb2dfbb7cd.png)
![image](https://user-images.githubusercontent.com/28734844/145272730-b3f29980-36b1-441f-9489-0103fc5cb874.png)

I attempted to modify the `InviteTeamMember` action to check for uniqueness on both the `team_id` and `email` columns. However, the `email` column on the `team_invitations` table has a unique index. This means that users can only have 1 invite pending at a time. 

```
protected function rules($team, string $email)
    {
        return array_filter([
            'email' => [
                'required',
                'email',
                Rule::unique('team_invitations')->where(function ($query) use ($team, $email) {
                    $query->where('team_id', $team->id)->where('email', $email);
                })
            ],
            'role' => Jetstream::hasRoles()
                            ? ['required', 'string', new Role]
                            : null,
        ]);
    }
```

### Steps To Reproduce:

1. Create two teams
2. Register a new user to be invited to both teams
3. Invite the user to the first team
4. Do not accept the invite
5. Attempt to invite the user to the second team
6. Notice the error that the user is already invited to the team

**Comment by driesvints** [comment]
I can't reproduce this. I can invite the same email address to two different teams. The unique index is on both the [team_id and email address](https://github.com/laravel/jetstream/blob/382723f6ec45394d8af80ab434414b4ffb5f69cd/database/migrations/2020_05_21_300000_create_team_invitations_table.php#L23), not on just the email address.

**Comment by LarryBarker** [comment]
Thanks Dries. Looks like v2.1 did not have the updated unique index on this table. I'll try updating.
