### ISSUE TITLE
[discussion] Customizing the brand color without modifying the components too much

### ISSUE THREAD

**Issue by rennokki** [laravel/jetstream#921]
Currently, changing the color schema is a bit of manual work to look after components that have hardcoded `*-gray-*` or `*-indigo-*` classes to be used as colors. I was thinking about how components can implement a boilerplate for color schemes, so that with minimum configuration, Jetstream can support color schemes without modifying components directly.

Would it be a great idea for Jetstream to ship by default custom colors (like `brand` variant or something like that) via extended color variants in Tailwind, so that the colors would be changed easier by the Tailwind configuration instead of finding and replacing those classes to change their respective colors?

Replacing the `*-indigo-*` classes within the Tailwind config would be a bit nasty, as I'd rather have a new color for the components instead of hard-coding one (like indigo).

**Comment by driesvints** [comment]
Hey @rennokki, I don't think we'll be working on this ourselves. We intended Jetstream to either be used out of the box as-is or have devs replace the default UI with their own one. Sorry. If you still want this you can always try a PR.
