### ISSUE TITLE
Multi Login

### ISSUE THREAD

**Issue by pouyaprs** [laravel/jetstream#922]
hello and have a nice day . 
how we could able to make multi Login on JetStream ?
we have 2 rules => User (on route site.com/user) and Admin (site.com/admin)

i'v tried a lot like making new guard but doesn't work . any example ? (i mean full example)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
