### ISSUE TITLE
Errors after installing jetstream with teams

### ISSUE THREAD

**Issue by miguelangelss4** [laravel/jetstream#923]
- Jetstream Version: 2.4.4 (commit 24d90e998a97636871d1d0f6a2f32cc8f954666d)
- Jetstream Stack: Livewire
- Uses Teams: yes 
- Laravel Version: Laravel Framework 8.74.0
- PHP Version: 8.0.13
- Database Driver & Version: MariaDB, libmysql - mysqlnd 8.0.13

### Description:
After a fresh installation of laravel and jetstream teams, I'm having issues. I generate Users with the default database seeder, but they have not teams associated. When I loggin with them, I have the error:
ErrorException
Attempt to read property "name" on null (View: C:\xampp\htdocs\ourplaces\resources\views\navigation-menu.blade.php)

because my current user have no team, and the view try to acces Auth::user()->currentTeam->name and Auth::user()->currentTeam->id

After solving it in that blade file, I got:
ErrorException
Undefined variable $trigger (View: C:\xampp\htdocs\ourplaces\resources\views\vendor\jetstream\components\dropdown.blade.php)

I have no idea why is that. I think jetstream views must work with all users, having or not teams created.

### Steps To Reproduce:

```
composer create-project laravel/laravel example-app
database\seeders\DatabaseSeeder.php file, uncomment: \App\Models\User::factory(10)->create();
cd example-app
composer require laravel/jetstream
php artisan jetstream:install livewire --teams
npm install
npm run dev
php artisan migrate --seed
php artisan vendor:publish --tag=jetstream-views
```

sorry about my English.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by miguelangelss4** [comment]
Hello
@driesvints was right, it was my mistake.

For anyone with this fail, in DatabaseSeeder.php I updated:
`\App\Models\User::factory(10)->create();`
to:
`\App\Models\User::factory(10)->withPersonalTeam()->create();`
