### ISSUE TITLE
Static analysis breaks on Jetstream 1.x applications

### ISSUE THREAD

**Issue by geisi** [laravel/jetstream#924]
- Jetstream Version: 1.6.6
- Jetstream Stack: Livewire
- Uses Teams: yes
- Laravel Version: 8.75.0
- PHP Version: all
- Database Driver & Version:
MySQL 8.x
### Description:
Hello I'm not sure if the 1.x branch is supported anymore so I'm opening an issue first. If this problem should be fixed I can open a PR for this.

When using jasonmccreary's awesome Laravel Shift Workbench on a Jetstream 1.x project there were occurring some errors and the build process failed.

```PHP
Cannot declare class Illuminate\Support\Collection, because the name is already in use
```

When digging deeper into this problem it seems that all common static analysis tools(PHPstan / Larastan) fail with this error on Jetstream 1.x applications with teams enabled. Sadly this breaks the whole static analysis build process.

The reason for this error is wrongly written phpDoc in the hasTeams trait:

```PHP
    /**
     * Get all of the teams the user owns or belongs to.
     *
     * @return \Illuminate\Collections\Collection
     */
    public function allTeams()
    {
        return $this->ownedTeams->merge($this->teams)->sortBy('name');
    }
```

When correcting the PHPDoc with the right *Illuminate\Support\Collection* class the static analysis runs fine.

### Steps To Reproduce:

Install fresh Laravel Installation.
Install Laravel Jestream 1.x with Teams

run static Analysis

Please contact me if I should open a PR for this.

**Comment by jasonmccreary** [comment]
Underneath this [Workbench task](https://laravelshift.com/workbench) uses Rector which uses PHPStan. So the incorrect PHP DocBlock reference is probably breaking any static analysis tool.

**Comment by driesvints** [comment]
I'm sorry but Jetstream 1.x isn't maintained anymore and we don't optimise specifically for static analysis. If you wish to change anything, we're welcoming PR's to the current stable branch: 2.x, thanks.

**Comment by jasonmccreary** [comment]
@driesvints, no problem. I'll check 2.x. For those encountering this issue, is it practical for me to ask them to upgrade to JetStream 2.x? I'm not as familiar with these packages as I should be.

**Comment by geisi** [comment]
@driesvints 
Thank you for your fast reply
If anyone has the same problem and does not want to migrate to Jetstream 2.x you can fix it with overloading the the allTeams() method in your User model:

````PHP
    /**
     * Get all of the teams the user owns or belongs to.
     *
     * @return \Illuminate\Support\Collection
     */
    public function allTeams()
    {
        return $this->ownedTeams->merge($this->teams)->sortBy('name');
    }
````

**Comment by driesvints** [comment]
@jasonmccreary Jetstream is a scaffold really so there isn't really an upgrade path for this package.

**Comment by jasonmccreary** [comment]
That's what I figured. This is corrected in 2.x.

**Comment by taylorotwell** [comment]
@driesvints  FYI - We will likely want to attempt to make all efforts to let Jetstream 1.x run on Laravel 9 as well.
