### ISSUE TITLE
Jetstream Delete Team Bug

### ISSUE THREAD

**Issue by bobimicroweber** [laravel/jetstream#928]
- Jetstream Version: 2.5
- Jetstream Stack:  Livewire
- Uses Teams: yes 
- Laravel Version: 8
- PHP Version: 7.4
- Database Driver & Version:

### Description:

ErrorException
Trying to get property 'id' of non-object (View: /home/mysite/code/resources/views/vendor/jetstream/components/switchable-team.blade.php)
https://mysite.com/dashboard 

### Steps To Reproduce:
When i delete the team of my user, i receive this error .

**Comment by driesvints** [comment]
You can't delete the personal team of your user.
