### ISSUE TITLE
Error on composer require the package

### ISSUE THREAD

**Issue by AEK-BKF** [laravel/jetstream#93]
- Jetstream Version: 1.0.0
- Laravel Version: 8.x
- PHP Version:7.4.9
- Database Driver & Version:

### Description:
![Screenshot from 2020-09-08 21-40-16](https://user-images.githubusercontent.com/16412739/92515426-45117700-f21c-11ea-8a8a-d903740e1579.png)

### Steps To Reproduce:
On : composer require laravel/jetstream

**Comment by mohmedr10** [comment]
edit JetstreamServiceProvider.php line 172  as in photo
then 
run composer update again 

![Screenshot_1](https://user-images.githubusercontent.com/38137819/92556771-05be4700-f26b-11ea-9936-51a8483d4a8f.png)

**Comment by mohmedr10** [comment]
edit JetstreamServiceProvider.php line 172 as in photo
then
run composer update again
![Screenshot_1](https://user-images.githubusercontent.com/38137819/92558746-7bc4ad00-f26f-11ea-82f3-e29f109983c3.png)

**Comment by driesvints** [comment]
Please uncache your routes before installing.

**Comment by AEK-BKF** [comment]
Thanks for replying,
I delete Bootstrap config cache file and every thing is fine !
