### ISSUE TITLE
Jetstream avatar customization issue

### ISSUE THREAD

**Issue by hoodpear** [laravel/jetstream#938]
- Jetstream Version: #.#.#
- Jetstream Stack: Livewire
- Uses Teams: no
- Laravel Version: 8.78.1
- PHP Version: 8.1.1
- Database Driver & Version: mysql

### Hi, devs!
I came today with something great in Jetstream which is photo feature it's great, but something I didn't understand:
Jetstream scaffolding automatically contains users names `$user->name` which [https://ui-avatars.com/](https://ui-avatars.com/) use the name in vendor folder. but wait, I want to change users `name` into `first_name` and `last_name`. The question is how can I edit the avatar placeholder variable:

## from:
`protected function defaultProfilePhotoUrl()
    {
        return 'https://ui-avatars.com/api/?name='.urlencode($this->name).'&color=7F9CF5&background=EBF4FF';
    }`
## To:
`protected function defaultProfilePhotoUrl()
    {
        return 'https://ui-avatars.com/api/?name='.urlencode($this->first_name).'&color=7F9CF5&background=EBF4FF';
    }`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
