### ISSUE TITLE
Change static colors to dynamic branding colors

### ISSUE THREAD

**Issue by titonova** [laravel/jetstream#942]
What I wish to add. Rather than making the colors of the components in Jetstream, static/fixed colors like `bg-indigo-500` etc to dynamic colors like `bg-primary-color`, `bg-primary-color-hover`, `bg-secondary-color`, because most, if not all Jetstream users would not want to use the default colors and manually changing the colors in each component can be a very tedious task.

I'd have made a pull request, but I wanted to be sure my idea was accepted so, I won't waste my time lol. 

Thanks, for youur consideration

**Comment by driesvints** [comment]
Hey there. At the moment we're not considering this. After installing, you're free to customise Jetstream however you like.
