### ISSUE TITLE
Multiple roles in team

### ISSUE THREAD

**Issue by gkakosouris** [laravel/jetstream#944]
Currently, Jetstream only allows for a user to have one role in a team.

Do you have any plans to allow users to have multiple roles in a team? 
Would you be open to a pull-request from the community that would add support for this?

**Comment by driesvints** [comment]
At the moment we have no plans for this, sorry.

**Comment by GeoSot** [comment]
@driesvints we can imagine your difficult position there, and that you may doesn't have any plans on this feature.

As this feature is very important for many developers (most business logics demand it), and jetstream tries to play an important role on authorization functionality, could you please give it a chance, reconsidering & answering the second question too?

It's too pity for many people to try to adapt on this official package and have to do workarounds to achieve this feature
