### ISSUE TITLE
'Attempt to read property "role" on null' when using teams

### ISSUE THREAD

**Issue by devstevehowe** [laravel/jetstream#947]
- Jetstream Version: 2.5.1
- Jetstream Stack: Livewire
- Uses Teams: yes
- Laravel Version: 8.6.10
- PHP Version: 8.1.1
- Database Driver & Version: MySQL 8

### Description:

When I invite team members to the project I am presented with the following error

Attempt to read property "role" on null (View: /home/forge/site.com/resources/views/teams/team-member-manager.blade.php)

I have dd the following
$user - Presents user object 
$user->membership - Presents a null object
$user->membership->role - Presents a null object

Individual teams works as it should, organizational teams do not

Error produced in the following code:

 @if (Gate::check('addTeamMember', $team) && Laravel\Jetstream\Jetstream::hasRoles())
                                        <button class="ml-2 text-sm text-gray-400 underline" wire:click="manageRole('{{ $user->id }}')">
                                            {{ Laravel\Jetstream\Jetstream::findRole($user->membership->role)->name }}
                                        </button>
                                    @elseif (Laravel\Jetstream\Jetstream::hasRoles())
                                        <div class="ml-2 text-sm text-gray-400">
                                            {{ Laravel\Jetstream\Jetstream::findRole($user->membership->role)->name }}
                                        </div>
                                    @endif

This is a relatively fresh install on a new site. No customizations done to Jetstream files either views or within the controllers

### Steps To Reproduce:

Invite members
Have them join team
Click on "team settings"

Attempt to read property "role" on null (View: /resources/views/teams/team-member-manager.blade.php)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by lucasdcrk** [comment]
Same issue here when trying to check if user has team permission on a team he doesn't own but is a member of.
<img width="810" alt="Screenshot 2022-02-07 at 10 40 45" src="https://user-images.githubusercontent.com/17224437/152763397-db2d5078-13a1-48ad-a9b7-1b04b0f4d12f.png">

Anyone solved this?

**Comment by khanakia** [comment]
laravel jetstream new registration not adding the user as owner in the team_user table so i am getting the same error
