### ISSUE TITLE
php artisan jetstream:install livewire/inertia did not completely scaffold Auth

### ISSUE THREAD

**Issue by jimgwhit** [laravel/jetstream#95]
Laravel v 8:

Also tried
 ```
php artisan jetstream:install livewire
```

Also tried
```
php artisan jetstream:install inertia
```
> A HomeController will also be generated to handle post-login requests to your application's dashboard.

Wasn't created.  Also no Login controller was created.  Where is the login controller?

I also use the authenticated method from the trait, but where is this trait now, no UI any more?

Is the UI still okay with version 8 (and future versions if I don't want jetstream), or is the UI deprecated, do you have to use jetstream.  Not anything in docs about the laravel ui for Auth.

And I thought jetstream was optional, where is the AuthenticatesUsers.php trait now located.

The docs are leaving out so much it seems.  The docs says there should be controller and trait:

> Authenticating

> Now that you have routes and views setup for the included `authentication controllers`, you are ready to register and authenticate new users for your application! You may access your application in a browser since the authentication controllers already contain the logic `(via their traits)` to authenticate existing users and store new users in the database.

**Comment by prof-anis** [comment]
I am facing the same issue here. I am looking for where my login and register views are so I can replace them with my HTML codes.

**Comment by driesvints** [comment]
Please reopen with a filled out issue template
