### ISSUE TITLE
Target class [App\Http\Middleware\HandleInertiaRequests] does not exist. LARAVEL 9 & JETSTREAM 2.6

### ISSUE THREAD

**Issue by andreysagot** [laravel/jetstream#953]
- Jetstream Version: 2.6
- Jetstream Stack: Inertia
- Uses Teams: yes
- Laravel Version: 9.0
- PHP Version: 8.1.1
- Database Driver & Version:mysql

### Description:

After installing the inertia stack, this class mentioned in the provider and middleware is not created. Laravel 9 & Jetstream 2.6
![error](https://user-images.githubusercontent.com/87910117/149358261-bfffd2ec-f1bc-40b0-bcbe-afd28e22462c.png)

**Comment by driesvints** [comment]
Thanks for testing. I just did a new release that should fix this.

Try: `laravel new test-jetstream --jet --dev`
