### ISSUE TITLE
Route group Sanctum guard

### ISSUE THREAD

**Issue by mxm1070** [laravel/jetstream#956]
- Jetstream Version: 2.6.1
- Jetstream Stack: Livewire (but probably both)
- Uses Teams: Yes
- Laravel Version: 8.79.0
- PHP Version: 8.0.12
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.36, for osx10.16 (x86_64) using  EditLine wrapper

### Description:

I'm working on a saas frontend using Jetstream. I've configured a new auth guard called customer in auth config, sanctum config, and fortify config. I'm able to login, register, and view the dashboard using this guard. However, I can't visit the profile page, because I get redirected to the login page, and then back to the dashboard, because I'm already logged in. I believe the problem is with the Livewire and Inertia route definitions both having:

`    
Route::group(['middleware' => ['auth', 'verified']], function () {
`

if I change the auth middleware to:

`    
Route::group(['middleware' => ['auth:sanctum', 'verified']], function () {
`

everything works fine. 

Is this a bug or a configuration problem on my end? If it's a configuration problem, how do I fix it?

I also took a look at fortify and it defines routes with a slightly more complicated auth middleware so maybe that could work here:

`
config('fortify.auth_middleware', 'auth').':'.config('fortify.guard')
`

Thanks!

### Steps To Reproduce:

1. Create a new project and install Jetstream with Livewire (or Inertia).
2. Create a new auth guard. 
3. Add the new auth guard to sanctum.guard.
4. Change fortify.guard to use the new auth guard.
5. Register on the site.
6. Try to visit the profile page.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by mxm1070** [comment]
@driesvints this isn't a support request. I believe this is a legitimate oversight in the routes definitions and I've addressed it in my pull request #957, please take a look.
