### ISSUE TITLE
CORS error on file upload when using BrowserSync

### ISSUE THREAD

**Issue by danielh-official** [laravel/jetstream#963]
- Jetstream Version: 2.6
- Jetstream Stack: Inertia / **Livewire**
- Uses Teams: yes / **no**
- Laravel Version: 8- PHP Version: 8.75
- Database Driver & Version: MySQL

### Description:

I'm using BrowserSync, which means that I need to access the app through localhost:3000 rather than 127.0.0.1:8000 in order to take advantage of the automatic refresh feature. I'm also using profile image upload.

On 127.0.0.1:8000, I have no problems uploading a profile image.

However, on localhost:3000, I get a CORS error. After inspecting the network, I notice that the image upload URL uses 127.0.0.1:8000 by default, and I have yet to find any way of changing it.

I'd like to be able to hand file uploads on any URL by using a custom .env variable (i.e., FRONTEND_URL), but I don't know how it's being handled. Do I need to `vender:publish` some files?

Below is my mix file:

```
const mix = require("laravel-mix");

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js("resources/js/app.js", "public/js")
    .sourceMaps()
    .postCss("resources/css/app.css", "public/css", [
        require("postcss-import"),
        require("tailwindcss"),
    ]);

if (mix.inProduction()) {
    mix.version();
}

mix.browserSync({
    proxy: process.env.APP_URL,
    notify: false,
});
```

### Steps To Reproduce:

1. Setup Laravel 8 with Jetstream and enable photo upload like you normally would.
2. Set up Mix with BrowserSync.
3. Run `php artisan serve` and `npm run watch` and attempt to upload a photo to the user profile in localhost:3000 or whatever is generated by BrowserSync on `npm run watch`.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
