### ISSUE TITLE
PHP8.1 support

### ISSUE THREAD

**Issue by ronfuller** [laravel/jetstream#968]
- Jetstream Version: 2.6.3
- Jetstream Stack: Inertia
- Uses Teams: yes / no
- Laravel Version: 8.80.0
- PHP Version: 8.1.2
- Database Driver & Version:

### Description:
The following error is logged every 1-2 seconds

Return type of Laravel\Jetstream\Role::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/jetstream/src/Role.php on line 70

### Steps To Reproduce:

Laravel Sail PHP 8.1 image
Login to the application

**Comment by driesvints** [comment]
I sent in a fix for this, thanks for reporting!
