### ISSUE TITLE
Allow to change naming convention for personal teams

### ISSUE THREAD

**Issue by rtrudel** [laravel/jetstream#974]
I understand the opinionated concept of having a default personal team with new registered users. But from there, it can raise some problems such as: `Firstname's Team` is hardcoded, so for multi-locale website, it suits only English.

I suggest to add a config to allow to change this naming by a variable, so, internationalizable, but also useful for some corner cases where the "Team" wording may be incorrect.

Ex:

```php
//Jetstream config:
'personal_team_name' => __("{name}'s Team"),

//Action
 protected function createTeam(User $user)
    {
       $name = explode(' ', $user->name, 2)[0];
    
        $user->ownedTeams()->save(Team::forceCreate([
            'user_id' => $user->id,
            'name' => str_replace('{name}', $name, config('jetstream.personal_team_name'), "{name}'s Team"),
            'personal_team' => true,
        ]));
    }
```
or even more dynamic way using Team model (which extends JetstreamTeam)

Reference: https://github.com/laravel/jetstream/blob/9663d7eb4e58ec86f105efb07f712fb81e6c92f2/stubs/app/Actions/Fortify/CreateNewUserWithTeams.php#L49

**Comment by driesvints** [comment]
You can update the name of the team after registering the user using, for example, the `Registered` event.
