### ISSUE TITLE
Language switcher

### ISSUE THREAD

**Issue by rtrudel** [laravel/jetstream#975]
I've had to implement a language switcher in my Jetstream project, but as it can be redundent for several projects, I think it could be a good improvement to have it right in the starter pack, disabled by default, as some other options.

![image](https://user-images.githubusercontent.com/18495095/152699443-3a47e7a2-2404-4231-802a-1bed4ff6c3f7.png)

**Comment by driesvints** [comment]
Heya thanks but we have no plans for this.
