### ISSUE TITLE
switch validation rules to priorize 'accepted'

### ISSUE THREAD

**Issue by simonbuehler** [laravel/jetstream#979]
hi,

minor issue but it would be better to switch the `accepted` and  `required` rules so the default message is something along 'Terms need to be _accepted_'

https://github.com/laravel/jetstream/blob/2bd67c5352e8d23e2a6350326de6888d5dc512b0/stubs/app/Actions/Fortify/CreateNewUser.php#L27

**Comment by driesvints** [comment]
Feel free to attempt a pr
