### ISSUE TITLE
Inertia SSR does not work with jetstream

### ISSUE THREAD

**Issue by DelaneyArkICT** [laravel/jetstream#987]
Jetstream does not work with SSR enabled when using inertia.

**Comment by driesvints** [comment]
Atm, we have no plans for this. If you want, you can attempt a PR.

**Comment by ObjectAssign** [comment]
@driesvints bump, its been a year has anything changed? :)

**Comment by jessarcher** [comment]
@ObjectAssign I've just spun up a Jetstream Inertia app with SSR enabled and have confirmed that it's working fine.

```sh
php artisan jetstream:install inertia --ssr
npm run build
node bootstrap/ssr/ssr.mjs
```

If you can identify an issue with SSR support on a fresh install of the latest version of Jetstream, then please feel free to open an issue with minimal reproduction steps.
