### ISSUE TITLE
"Log Out Other Browser Sessions Button" logs out current user when pressed twice

### ISSUE THREAD

**Issue by CodeAdminDe** [laravel/jetstream#993]
- Jetstream Version: 2.6.7
- Jetstream Stack: Livewire
- Uses Teams: no
- Laravel Version: 9.4.1
- PHP Version: 8.1.2
- Database Driver & Version: mysql (mariadb:10)
- Laravel Sail: yes

### Description:
I've ran into a bug the same way as https://github.com/laravel/framework/issues/41428 did (https://github.com/laravel/jetstream/issues/985 appeared => happily found the note that a bug fix is already there (https://github.com/laravel/framework/commit/50b46db563e11ba52a53e3046c23e92878aed395) => upgraded to the latest Laravel release).

The problem I am experiencing:
 * The first time a user pressed the "Log Out Other Browser Sessions" button, it works like expected 
   * => Other sessions are logged out ; own session is still usable
* The second time a user pressed the same button
  * => Own session get destroyed.

For illustration a short screenrecord: 

https://imgur.com/a/EJiPN0R

### Steps To Reproduce:

The issue occurs even with a completely fresh installation and can therefore be reproduced locally as follows:

* Install a new project (BTW: Thanks for this easy way to start new Laravel projects! Love it! :heart: ): `curl https://laravel.build/bugreport\?with\=mariadb | /bin/bash`
* Install Jetstream: `cd bugreport && sail up -d && sail composer require laravel/jetstream && sail artisan jetstream:install livewire`
* Run NPM and migration: `sail npm install && sail npm run dev && sail artisan migrate`
* Optional: Install Debugbar: `sail composer require barryvdh/laravel-debugbar --dev`

Happy to help with further investigation if needed! :smiley:

**Comment by driesvints** [comment]
Thank you. We'll investigate this one.

**Comment by taylorotwell** [comment]
PRs welcome.

**Comment by driesvints** [comment]
@CodeAdminDe is this still an issue on Laravel v9.5.1?

**Comment by CodeAdminDe** [comment]
> @CodeAdminDe is this still an issue on Laravel v9.5.1?

Yes, also in v9.5.1 the issue can be triggered as described initially. Just tested with a fresh installation.

I don't know how far it is related, but what i noticed is the "new" option of the Jetstream guard which is configured to `sanctum` by default (`config/jetstream.php`) and the fact that the value `password_hash_sanctum` instead of `password_hash_web` updates in the session (assuming an unchanged config). 
In Laravel version 8.77.1 with Jetstream 2.5.0 (and Fortify 1.8.6) the value of `password_hash_web` was updated by default and the issue does not occur.

**Comment by relaypilot** [comment]
@CodeAdminDe Can you check if commenting out this line resolves the issue?

`\Laravel\Jetstream\Http\Middleware\AuthenticateSession::class,`

in `app/Http/Kernel.php`:


```
protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
           // \Laravel\Jetstream\Http\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
],
```

If it doesn't change anything, can you try to revert the changes made by this commit: https://github.com/laravel/framework/commit/50b46db563e11ba52a53e3046c23e92878aed395

More specifically in `Illuminate\Foundation\Http\Kernel.php`, by replacing the following line:

`\Illuminate\Contracts\Session\Middleware\AuthenticatesSessions::class,`

with this one: 

`\Illuminate\Session\Middleware\AuthenticateSession::class,`

**Comment by CodeAdminDe** [comment]
@relaypilot Quickly tested within the fresh installation ... commenting out the line `\Laravel\Jetstream\Http\Middleware\AuthenticateSession::class,` in `app/Http/Kernel.php` would solve the issue.

**Comment by driesvints** [comment]
This one will be fixed on Tuesday, albeit with some needed changes to your app.
